### PR TITLE
sdb usage cleanup within rz_bin

### LINKED ISSUE #2307: Two small memory leaks
Each of the attached files (when un-gzipped) produce memory leaks, one example:

```sh
$ ./binrz/rizin/rizin -Aq ~/Downloads/id\ 000009\,sig\ 06\,src\ 012103+009495\,time\ 506124955\,op\ splice\,rep\ 8
Undefined type in free_object (0)
Undefined type in get_object (0x7d)
Undefined type in get_object (0x0)
Undefined type in get_object (0x0)
Undefined type in get_object (0x1b)
Undefined type in get_object (0x0)
Undefined type in get_object (0x0)
Undefined type in get_object (0x1b)
Undefined type in get_object (0x1b)
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Undefined type in get_object (0x2)
WARNING: No calling convention defined for this file, analysis may be inaccurate.

=================================================================
==4170383==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbd0c in get_code_object ../librz/bin/format/pyc/marshal.c:866

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6ebf7890 in rz_list_new ../librz/util/list.c:236

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbcf0 in get_code_object ../librz/bin/format/pyc/marshal.c:865

Indirect leak of 240 byte(s) in 2 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbd0c in get_code_object ../librz/bin/format/pyc/marshal.c:866

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7faa6ee8ed37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7faa6ebf793e in rz_list_append ../librz/util/list.c:293

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6ebf7890 in rz_list_new ../librz/util/list.c:236

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbcf0 in get_code_object ../librz/bin/format/pyc/marshal.c:865

SUMMARY: AddressSanitizer: 504 byte(s) leaked in 9 allocation(s).
```

### Expected behavior

Memory shouldn't be leaked.

### Actual behavior

A small amount of memory is leaked.

[id 000009,sig 06,src 012103+009495,time 506124955,op splice,rep 8.gz](https://github.com/rizinorg/rizin/files/8054346/id.000009.sig.06.src.012103%2B009495.time.506124955.op.splice.rep.8.gz)

[id 000740,sig 06,src 006653,time 64579299,op havoc,rep 2.gz](https://github.com/rizinorg/rizin/files/8054345/id.000740.sig.06.src.006653.time.64579299.op.havoc.rep.2.gz)

### LINKED ISSUE #2540: 12kb memory leak via non-freed sdb object
Make sure you are testing using the latest git version of rizin before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo amd64
| File format of the file you reverse (mandatory)      | MS-DOS executable, NE (unknown OS 30) (EXE)
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64
commit: eaaa2c9a6eb35a60477d86cd4982b3015a8c068b, build: 2022-04-13__12:52:24

### Expected behavior

Rizin shouldn't leak.

### Steps to reproduce the behavior
Build rizin with debug symbols and ASAN, something like `CFLAGS='-ggdb -fsanitize=address' meson --reconfigure ..  && ninja -j8`. Then using the attached POC file (when unzipped), [poc.zip](https://github.com/rizinorg/rizin/files/8481674/poc.zip), rizin has a relatively large leak via `sdb_new`:

```
~/git/rizin/build $ ./binrz/rizin/rizin -qAAA ~/Downloads/poc

=================================================================
==3153921==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11504 byte(s) in 1 object(s) allocated from:
    #0 0x7f0c5e23df17 in __interceptor_calloc /usr/src/debug/sys-devel/gcc-11.2.1_p20220115/gcc-11-20220115/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f0c5e03cdc4 in sdb_new ../subprojects/sdb/src/sdb.c:56
```

Valgrind gives a bit more information (once recompiled without ASAN):

```
~/git/rizin/build $ valgrind --leak-check=full ./binrz/rizin/rizin -qAAA ~/Downloads/poc
==3222398== Memcheck, a memory error detector
==3222398== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3222398== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==3222398== Command: ./binrz/rizin/rizin -qAAA /home/jake/Downloads/poc
==3222398==
--3222398-- WARNING: unhandled amd64-linux syscall: 334
--3222398-- You may be able to write your own handler.
--3222398-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--3222398-- Nevertheless we consider this a bug.  Please report
--3222398-- it at http://valgrind.org/support/bug_reports.html.
==3222398==
==3222398== HEAP SUMMARY:
==3222398==     in use at exit: 12,476 bytes in 22 blocks
==3222398==   total heap usage: 57,616 allocs, 57,594 frees, 30,220,119 bytes allocated
[snip other tiny leaks]
==3222398== 11,688 (11,504 direct, 184 indirect) bytes in 1 blocks are definitely lost in loss record 22 of 22
==3222398==    at 0x4849C0F: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3222398==    by 0x48F3FF4: sdb_new (sdb.c:56)
==3222398==    by 0x5BFBD42: rz_bin_file_new (bfile.c:224)
==3222398==    by 0x5BFC001: rz_bin_file_new_from_buffer (bfile.c:326)
==3222398==    by 0x5BF2CB6: rz_bin_open_buf (bin.c:302)
==3222398==    by 0x5BF3017: rz_bin_open_io (bin.c:360)
==3222398==    by 0x5E04A3B: core_file_do_load_for_io_plugin (cfile.c:692)
==3222398==    by 0x5E04A3B: rz_core_bin_load (cfile.c:938)
==3222398==    by 0x49660A8: rz_main_rizin (rizin.c:1145)
==3222398==    by 0x49D5349: (below main) (libc_start_call_main.h:58)
```

At first glance this seems to be caused by an incongruence in [rz_bin_file_new](https://github.com/rizinorg/rizin/blob/dev/librz/bin/bfile.c#L208) and [rz_bin_file_free](https://github.com/rizinorg/rizin/blob/dev/librz/bin/bfile.c#L229): _new creates bf->sdb, and _free doesn't free it.

Naively freeing bf->sdb in the _free function unfortunately results in a UAF elsewhere, so not sure what the right solution is.

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Tries to resolve some issues related to pointer moving from place to place.

- Fix #2307 
- Fix #2540

### CODE REVIEW

File: librz/core/cbin.c [hunk 1]
```diff
@@ -4159,16 +4158,16 @@ static void bin_pe_versioninfo(RzCore *r, PJ *pj, int mode) {
 }
 
 static void bin_elf_versioninfo_versym(RzCore *r, PJ *pj, int mode) {
```
Comment (XVilka) [inline librz/core/cbin.c:4173]: Can you also convert the mode into RzOutputMode enum?

File: librz/core/cbin.c [hunk 2]
```diff
@@ -4212,16 +4211,16 @@ static void bin_elf_versioninfo_versym(RzCore *r, PJ *pj, int mode) {
 }
 
 static void bin_elf_versioninfo_verneed(RzCore *r, PJ *pj, int mode) {
```
Comment (XVilka) [inline librz/core/cbin.c:4226]: Can you also convert the mode into the RzOutputMode enum?

**Review by XVilka — CHANGES_REQUESTED** [review]
Always good to see a cleanup.

File: librz/core/cbin.c (hunk 1 above)
Comment (ret2libc) [reply librz/core/cbin.c:4173]: no please, this PR has a very different purpose and it's already quite clean as is

File: librz/core/cbin.c (hunk 2 above)
Comment (ret2libc) [reply librz/core/cbin.c:4226]: no please, this PR has a very different purpose and it's already quite clean as is

**Review by ret2libc — APPROVED** [review]
<3

**Comment by ret2libc** [comment]
Does it also fix https://github.com/rizinorg/rizin/issues/2540 ?

**Comment by wargio** [comment]
> Does it also fix #2540 ?

it is possible. i'll check it tonight

**Comment by wargio** [comment]
@ret2libc yes it does.

**Review by ret2libc — CHANGES_REQUESTED** [review]
Going to review

File: librz/core/core.c [hunk 3]
```diff
@@ -2647,68 +2647,59 @@ RZ_API void rz_core_fini(RzCore *c) {
...
-	rz_list_free(c->cmd_descriptors);
-	c->analysis = rz_analysis_free(c->analysis);
-	rz_asm_free(c->rasm);
-	c->rasm = NULL;
-	c->print = rz_print_free(c->print);
-	c->bin = (rz_bin_free(c->bin), NULL);
-	c->lang = (rz_lang_free(c->lang), NULL);
-	c->dbg = (rz_debug_free(c->dbg), NULL);
-	rz_config_free(c->config);
+	RZ_FREE2(c->rcmd, rz_cmd_free);
```
Comment (ret2libc) [inline librz/core/core.c]: I like the idea of the macro, but I'm not sure my mind can easily map RZ_FREE2 == custom free+set-null. Maybe calling it `RZ_FREE_CUSTOM`?

File: test/db/cmd/cmd_i [hunk 4]
```diff
@@ -4515,7 +4515,7 @@ RUN
 
 NAME=ik-relro
 FILE=bins/elf/analysis/x86-helloworld-gcc
-CMDS=ik info/elf.relro
+CMDS=ik elf.relro
```
Comment (ret2libc) [inline test/db/cmd/cmd_i:4518]: why this change?

File: librz/core/core.c (hunk 3 above)
Comment (wargio) [reply librz/core/core.c]: yes, sure.

File: test/db/cmd/cmd_i (hunk 4 above)
Comment (wargio) [reply test/db/cmd/cmd_i:4518]: because before the `info` path was added by `rz_bin_object_new` in the following way:
```c
bin_obj->kv = plugin->get_sdb(); // pointer ownership is of the plugin
sdb_ns_set(bf->sdb, "info", bin_obj->kv);
bin_obj->kv = bf->sdb;
```
since that was one of the main causes of the un-freed pointers, then i decided to remove it since the usability is the same with the same errors.

Comment (ret2libc) [reply test/db/cmd/cmd_i:4518]: Ok. Not fully convincend though :D

But I don't care too much for SDB tbh and I hope it will go away one day.

**Comment by ret2libc** [comment]
Recreate with `asan` in branch name please.

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Comment by XVilka** [comment]
```

[XX] db/formats/mach0/mach0 osx mach0 ik
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc ik~uuid bins/mach0/ls-osx-x86_64
-- stdout
--- expected
+++ actual
@@ -1,0 +1,4 @@
+mach0_cmd_8.cmd=uuid
+mach0_cmd_8.format=mach0_uuid_command
+mach0_uuid_command.format=[4]Ed[16]b (mach0_load_command_type)cmd cmdsize uuid
+uuid.0=ff4d6c2e1dc0369d98d0d3040a8049e8
```
