### PR TITLE
Fix for ic* and pf* by a alternate commands ica and pfa

### LINKED ISSUE #5560: Replace `.pf*` with C equivalent and fix `tc` tests.
Due the changes in #5540 several tests in `test/db/cmd/cmd_tc` have been marked as broken due `pf` not producing anymore valid commands to apply flags at a given offset.

Before that PR, you could call `pf*` to generate all the needed commands to define the structure manually and with the help of `.` (i.e. eval) you could do `.pf* foo @ 0x1234` to define the structure `foo` at address `0x1234`.

The idea is a similar command from the `pf` command group to define the structure at the current offset, so the user could do `pf<new cmd> @ 0x1234` to achieve the same thing.

See `librz/type/format.c` code for more details.

### PR DESCRIPTION
**Pull request by Farhan-25**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

- `pfa <name> [addr]` - Apply a named format/structure at a given offset
- `ica <classname> [addr]` - Apply class method flags at a given offset
- `ict` - Generate `td` commands from binary classes to register them as types in the type database.(Replacement for ic*)

**Test plan**

I have added test for `ica`, `pfa` and fixed broken test in tc by `ict` command.

**Closing issues**

closes #5560

### CODE REVIEW

**Comment by Farhan-25** [comment]
The failed tests are unrelated.

File: librz/core/cbin.c [hunk 1]
```diff
@@ -4109,6 +4109,97 @@ RZ_API bool rz_core_bin_class_methods_print(RZ_NONNULL RzCore *core, RZ_NONNULL
...
+	rz_pvector_foreach (classes, iter) {
+		c = *iter;
+		if (!c || !c->name || !c->name[0]) {
+			continue;
+		}
+		RzStrBuf *sb = rz_strbuf_new(NULL);
+		if (!sb) {
+			return false;
+		}
+		rz_strbuf_appendf(sb, "td \"struct %s {", c->name);
```
Comment (wargio) [inline librz/core/cbin.c]: this is incorrect. you are generating again the commands that creates the classes.

**Review by wargio — CHANGES_REQUESTED** [review]
the test should not call `.` (eval) but instead it should just apply the struct via the C api. you have ported back what i have deleted.

Also all the tests are still marked as `BROKEN=1`

**Comment by notxvilka** [comment]
It looks like AI-generated to me, even the naming resembles the old code.

**Comment by Farhan-25** [comment]
> the test should not call `.` (eval) but instead it should just apply the struct via the C api. you have ported back what i have deleted.
> 
> Also all the tests are still marked as `BROKEN=1`

Oh okay i didnt got it last time i will fix that, but `pfa` is correct right?

**Comment by Farhan-25** [comment]
> It looks like AI-generated to me, even the naming resembles the old code.

Sir you can check it here i just fixed what this dude did wrong https://github.com/rizinorg/rizin/pull/5574/changes, I am not using AI.

**Comment by Farhan-25** [comment]
> > It looks like AI-generated to me, even the naming resembles the old code.
> 
> Sir you can check it here i just fixed what this dude did wrong https://github.com/rizinorg/rizin/pull/5574/changes, I am not using AI.

It was told that not to use rz_core_cmd0 so i thought by implementing this i would fix it thats why.

File: librz/core/cmd_descs/cmd_info.yaml [hunk 2]
```diff
@@ -46,6 +46,15 @@ commands:
...
         args: []
+      - name: ica
+        summary: Apply class flags at given address
+        cname: cmd_info_class_apply
+        args:
+        - name: class name
+          type: RZ_CMD_ARG_TYPE_STRING
+        - name: address
+          type: RZ_CMD_ARG_TYPE_RZNUM
+          optional: true
```
Comment (wargio) [inline librz/core/cmd_descs/cmd_info.yaml]: not sure if `address` should be part of it but maybe @notxvilka will disagree

File: librz/core/cmd_descs/cmd_info.yaml [hunk 3]
```diff
@@ -81,6 +90,10 @@ commands:
           - name: class name
             type: RZ_CMD_ARG_TYPE_STRING
             optional: true
+      - name: ict
```
Comment (wargio) [inline librz/core/cmd_descs/cmd_info.yaml]: rename this to `ics` (classes as C struct), as `ict` is the table method of `ic`

File: test/db/cmd/cmd_pf [hunk 4]
```diff
@@ -1089,3 +1089,17 @@ EXPECT=<<EOF
 ]
 EOF
 RUN
+
+NAME=Apply named format at current offset
+FILE=malloc://1024
+CMDS=<<EOF
```
Comment (wargio) [inline test/db/cmd/cmd_pf]: merge this test with the one before.

File: librz/core/cmd_descs/cmd_info.yaml (hunk 2 above)
Comment (notxvilka) [reply librz/core/cmd_descs/cmd_info.yaml]: Right, we usually define address by current offset and use `@ 0xXXXXX` construction instead.

**Review by wargio — APPROVED** [review]
LGTM, @notxvilka

**Comment by notxvilka** [comment]
@Farhan-25 in the future, please don't forget addressed feedback as "Resolved" to reduce the maintainer workload.

**Review by notxvilka — APPROVED** [review]

**Comment by Farhan-25** [comment]
> @Farhan-25 in the future, please don't forget addressed feedback as "Resolved" to reduce the maintainer workload.

Sure would keep that in mind
