### PR TITLE
Fix(fC): show correct comment when flags overlap

### LINKED ISSUE #5316: `fC` not working properly
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali x86_64
| File format of the file you reverse (mandatory)      | NONE
| Architecture/bits of the file (mandatory)            | NONE
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.9.0 @ linux-x86-64 commit: 17d10b91e043bdc40f9ba0a77ceda52cdc9c6829

`fC` shows the comment for the wrong flag if two flags are defined by the user on the same offset

### Expected behavior

`fC` should show the comment of first flag

### Actual behavior

`fC` shows the comment of second flag

### Steps to reproduce the behavior
* `f one 0x10 first` (`f+` also leads to the same result) 
* `f+ two 0x10 second`
* `fC one`

running `fC one` will show the comment of the second flag, i.e: `second`, instead of `first`

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

### PR DESCRIPTION
**Pull request by PremadeS**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

`fC` was showing comment of wrong flag if two flags existed at the same offset. See issue #5316  
...

**Test plan**

run test the provided test
OR, start rizin:
```bash
f foo 0x10 first
f+ bar 0x20 second
fC foo
``` 
the output will now be `first` instead of `second`, (the latter being incorrect)
...

**Closing issues**

closes #5316 
...

### CODE REVIEW

File: librz/core/cmd/cmd_flag.c [hunk 1]
```diff
@@ -881,12 +881,12 @@ RZ_IPI RzCmdStatus rz_flag_comment_handler(RzCore *core, int argc, const char **
...
-		if (item && item->comment) {
-			rz_cons_println(item->comment);
-		} else {
+		item = rz_flag_get(core->flags, argv[1]);
+		if (!item) {
 			RZ_LOG_ERROR("Cannot find the flag\n");
 			return RZ_CMD_STATUS_ERROR;
+		} else if (item->comment) {
+			rz_cons_println(item->comment);
 		}
```
Comment (Rot127) [inline librz/core/cmd/cmd_flag.c:890]: Wouldn't we want to print the flag even if it doesn't have a comment?

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: librz/core/cmd/cmd_flag.c (hunk 1 above)
Comment (PremadeS) [reply librz/core/cmd/cmd_flag.c:890]: > print the flag if the doesn't have a comment

Could you please elaborate on this?

The previous `fC` command always printed “Cannot find the flag” even when the flag actually existed but just didn’t have a comment. That was misleading since the flag was there, just missing a comment

The updated code now only shows the error if the flag truly isn’t found, and only prints the comment if one exists for that flag.
Otherwise nothing is printed
@Rot127

Comment (Rot127) [reply librz/core/cmd/cmd_flag.c:890]: Never mind. It makes sense this way.

**Review by Rot127 — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]
