### PR TITLE
RzCmd: Improve suggestions when wrong command/args is used

### LINKED ISSUE #2059: Wrong message / Command 'P' does not exist.
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint x86_64
| rizin 0.4.0-git @ linux-x86-64 commit: 98e4816b036214e1c3514aaa2e0e38c85f329e1d

### Expected behavior
prints `Usage: P<so?>   # Project management...`

### Actual behavior
prints `Command 'P' does not exist.`

### Steps to reproduce the behavior
- run rizin 
- run `P`

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

image

**Test plan**

...

**Closing issues**

Closes #2059

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
```

[XX] db/cmd/cmd_w w_escape
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -ecfg.oldshell=false -Qc 'wv8\@10
' =
-- stderr
--- expected
+++ actual
@@ --1,3 +-1,13 @@
 Command 'wv8@10' does not exist.
+Displaying the help of command 'wv8'.
+
+Usage: wv8 <value>   # Write value of 8 byte
+
+Write the number passed as argument at the current offset as 8 - bytes, respecting the cfg.bigendian variable
+
+Examples:
+| wv 0xdeadbeef # Write the value 0xdeadbeef at current offset
+| wv2 0xdead    # Write the word 0xdead at current offset
+| wv1 0xde      # Write the byte 0xde at current offset
```

File: librz/core/cmd/cmd.c [hunk 1]
```diff
@@ -3989,32 +4011,21 @@ DEFINE_HANDLE_TS_FCN_AND_SYMBOL(arged_stmt) {
...
-			char *help_msg = rz_cmd_get_help(state->core->rcmd, help_pra, use_color);
-			if (!help_msg) {
-				goto help_pra_err;
-			}
-			eprintf("%s", help_msg);
-			free(help_msg);
-		help_pra_err:
-			rz_cmd_parsed_args_free(help_pra);
-		}
+		eprintf("Wrong number of arguments passed to `%s`, see its help with `%s?`\n\n", cmdname, cmdname);
```
Comment (wargio) [inline librz/core/cmd/cmd.c:4014]: do we really want to use eprintf ?

Comment (ret2libc) [reply librz/core/cmd/cmd.c:4014]: For now, I think yes because it is used in other places here as well.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]
