### PR TITLE
rz-ar: add archive extraction utility

### LINKED ISSUE #4866: New utility `rz-ar` to unpack `.a` and `.lib` files
When you try to unpack windows built static libraries (`.a` and `.lib`)  with `ar x file.a` it will fail due the path not being available.

Moreover there are "valid" and "invalid" libraries built by the windows sdk which can and cannot have object files.

`rz-ar` should be able create the needed subfolder and unpack the object files in the working directory (unless an output dir is specified).

This new utility will be beneficial for creating signatures and more.

Example:

```
$ rizin -qc 'ol' ar://valid-BufferOverflow.lib 
 3 * r-x 0x0000424a ar://valid-BufferOverflow.lib//d_/8180.public.fre/internal/minwin/priv_sdk/lib/amd64/loadcfg.obj
 4 - r-x 0x00004249 ar://valid-BufferOverflow.lib//d_/8180.public.fre/internal/minwin/priv_sdk/lib/amd64/guard_support.obj
 5 - r-x 0x0000d645 ar://valid-BufferOverflow.lib//e_/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/gs_dllmain.obj
 6 - r-x 0x0000fc91 ar://valid-BufferOverflow.lib//e_/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/gs_support.obj
 7 - r-x 0x00000658 ar://valid-BufferOverflow.lib//e_/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/amdsecgs.obj
$ ar tv valid-BufferOverflow.lib 
r--r--r-- 100444/100444  16970 Feb 27 07:34 2015 d:/8180.public.fre/internal/minwin/priv_sdk/lib/amd64/loadcfg.obj
r--r--r-- 100444/100444  16969 Feb 27 07:34 2015 d:/8180.public.fre/internal/minwin/priv_sdk/lib/amd64/guard_support.obj
rw-rw-rw- 100666/100666  54853 Feb 27 07:36 2015 e:/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/gs_dllmain.obj
rw-rw-rw- 100666/100666  64657 Feb 27 07:36 2015 e:/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/gs_support.obj
rw-rw-rw- 100666/100666   1624 Feb 27 07:36 2015 e:/8180.obj.amd64fre/minkernel/tools/gs_support/ntdll/objfre/amd64/amdsecgs.obj
$ ar tv invalid-audioeng.lib 
--------- 0/0    498 Aug 22 16:03 2013 audioeng.dll
--------- 0/0    251 Aug 22 16:03 2013 audioeng.dll
--------- 0/0    288 Aug 22 16:03 2013 audioeng.dll
--------- 0/0     47 Aug 22 16:03 2013 audioeng.dll
--------- 0/0     43 Aug 22 16:03 2013 audioeng.dll
$ rizin -qc 'ol' ar://invalid-audioeng.lib 
ERROR: Cannot open 'ar://invalid-audioeng.lib'
```

[examples.zip](https://github.com/user-attachments/files/18568316/examples.zip)

### PR DESCRIPTION
**Pull request by IndAlok**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes. *(only `rz_main_rz_ar` was added, no new public structs.)*
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information. *(not needed here)*
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

This PR introduces a new `rz-ar` utility to list and extract members from static archives (`.a` / `.lib`) and resolves the Windows SDK path issue described in #4866.

### Problem
Windows-built archives can contain member names with absolute/path-like prefixes (for example `d:/.../file.obj`). Traditional extraction fails when parent directories do not exist or paths are not normalized.

### What this PR changes
- Adds a new `rz-ar` binary and main callback integration.
- Supports:
  - `-l` list matching members
  - `-o <dir>` extract to output directory
  - `-q` quiet mode
  - `-v` version
- Normalizes member paths safely:
  - `\` → `/`
  - strips/normalizes `.` and `..`
  - sanitizes non-printable / `:` characters
- Creates required subdirectories before extraction.
- Handles duplicate output names with suffixing (`.1`, `.2`, ...).
- Returns failure on invalid archives / no matching extractable members.
- Adds manpage and build-system wiring for the new tool.
- Adds regression tests under rz_ar.

**Test plan**

1. Configure and build:
- `meson setup build --buildtype=debug`
- `meson compile -C build`

2. Run tool regression tests:
- `cd test`
- `.rz-test.exe -j 1 db/tools/rz_ar` (Windows)
- `../build/binrz/rz-test/rz-test -j 1 db/tools/rz_ar` (Linux/macOS)

3. Manual validation with issue samples (which were provided in examples archive in issue):
- List:
  - `rz-ar -l examples/valid-BufferOverflow.lib`
- Extract to cwd:
  - `rz-ar examples/valid-BufferOverflow.lib`
- Extract to output dir:
  - `rz-ar -o out examples/valid-BufferOverflow.lib`
- Invalid archive behavior:
  - `rz-ar -l examples/invalid-audioeng.lib` (expected failure)

4. CI sanity:
- Verify `clang`/`gcc` builds pass for rz-ar.c (no implicit declarations).

**Closing issues**

closes #4866

### CODE REVIEW

File: librz/main/rz-ar.c [hunk 1]
```diff
@@ -0,0 +1,290 @@
...
+		"-o",
+		"dir",
+		"Set output directory (default .)",
+		"-q",
+		"",
+		"Quiet mode",
+		"-v",
+		"",
+		"Show version information",
+	};
```
Comment (wargio) [inline librz/main/rz-ar.c:28]: fix the formatting here. you can add `// clang-format off` and `// clang-format on` to prevent clang format from fucking up the code.

File: test/db/tools/rz_ar [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+RUN
+
+NAME=rz-ar -v
+FILE==
+REGEXP_FILTER_OUT=(commit:)
+CMDS=!rz-ar -v
+EXPECT=<<EOF
+commit:
+EOF
+RUN
```
Comment (wargio) [inline test/db/tools/rz_ar]: delete this as the `-v` arg is called by rz-test to test the tool availability.

**Review by wargio — CHANGES_REQUESTED** [review]
besides the test & formatting, looks almost perfect.

File: test/db/tools/rz_ar [hunk 3]
```diff
@@ -0,0 +1,67 @@
+NAME=rz-ar -h
+FILE==
+REGEXP_FILTER_OUT=(Usage:)
+CMDS=!rz-ar -h
+EXPECT=<<EOF
+Usage:
+EOF
+RUN
```
Comment (wargio) [inline test/db/tools/rz_ar]: use `TOOL` here and dump the whole help

File: librz/main/rz-ar.c (hunk 1 above)
Comment (IndAlok) [reply librz/main/rz-ar.c:28]: thanks for this, will keep in mind :)

File: librz/main/rz-ar.c [hunk 4]
```diff
@@ -0,0 +1,282 @@
...
+	}
+}
+
+static bool rz_ar_extract_member(RzArFp *member, const char *dst_path) {
+	rz_return_val_if_fail(member && dst_path, false);
+	const ut64 size = member->end - member->start;
+	if (size == 0) {
+		return rz_file_dump(dst_path, NULL, 0, false);
+	}
+	ut8 *buf = malloc(0x10000);
```
Comment (notxvilka) [inline librz/main/rz-ar.c]: What is this magic value?

Comment (notxvilka) [reply librz/main/rz-ar.c]: Make it define at least

File: librz/main/rz-ar.c [hunk 5]
```diff
@@ -0,0 +1,282 @@
...
+		"-l", "", "List matching members",
+		"-o", "dir", "Set output directory (default .)",
+		"-q", "", "Quiet mode",
+		"-v", "", "Show version information",
+	};
+	// clang-format on
+	rz_print_colored_help(options, RZ_ARRAY_SIZE(options), false);
+}
+
+static char *rz_ar_normalize_member_path(const char *name) {
```
Comment (notxvilka) [inline librz/main/rz-ar.c:33]: I think we had a function for that.

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: librz/main/rz-ar.c (hunk 5 above)
Comment (IndAlok) [reply librz/main/rz-ar.c:33]: I saw in file.c:
```
RZ_API char *rz_file_path_local_to_unix(const char *path) {
	char *r = rz_str_dup(path);
	if (!r) {
		return NULL;
	}
#if __WINDOWS__
	rz_str_replace(r, RZ_SYS_DIR, "/", true);
#endif
	return r;
}
```
and replaced just strdup, with it... but did you mean there already a helper that does ./.. collapsing and character sanitization required here completely?

File: librz/main/rz-ar.c (hunk 4 above)
Comment (IndAlok) [reply librz/main/rz-ar.c]: my bad, defined to extract chunk size, will keep in mind to do so ahead

File: librz/main/rz-ar.c (hunk 5 above)
Comment (notxvilka) [reply librz/main/rz-ar.c:33]: I think so, just forgot exactly where I saw it.

**Review by notxvilka — CHANGES_REQUESTED** [review]
Please fix the `mandoc` warnings:
```
mandoc: rz-ar.1:35:34: WARNING: new sentence, new line
mandoc: rz-ar.1:46:85: STYLE: input text line longer than 80 bytes: Invalid arguments, a...
mandoc: rz-ar.1:1:5: STYLE: normalizing date format to: Dd March 14, 2026
mandoc: rz-ar.1:65:2: WARNING: missing section argument: Xr rizin(1)
mandoc: rz-ar.1:66:2: WARNING: missing section argument: Xr rz-bin(1)
mandoc: rz-ar.1:67:2: WARNING: missing section argument: Xr rz-hash(1)
mandoc: rz-ar.1:64:2: WARNING: skipping paragraph macro: Pp after Sh
mandoc: rz-ar.1: WARNING: missing Os macro, using ""
```

**Review by notxvilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]
