### PR TITLE
Fix signature in JSON mode in MachO and check for NULL signature

### LINKED ISSUE #458: iCj prints invalid json
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS arm 64 + rosetta 
| File format of the file you reverse (mandatory)      | machO
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0 25663 @ darwin-x86-64 git.0.2.0 commit: 26e8490e363ded87e2bf4970c678b78925c3d2d6 build: 2021-01-25__22:41:55

### Expected behavior

`iCj` outputs valid JSON

### Actual behavior

```json
{"signature":No entitlement found}
```

### Steps to reproduce the behavior
- `rizin tests/bins/test/bins/mach0/ls-osx-x86_64`
- `iCJ`

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The MachO plugin was not considering JSON mode. This fixes it both for MachO and QNX.

**Test plan**

...

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/458

### CODE REVIEW

File: librz/bin/p/bin_mach0.c [hunk 1]
```diff
@@ -35,7 +35,14 @@ static Sdb *get_sdb(RzBinFile *bf) {
 static char *entitlements(RzBinFile *bf, bool json) {
 	rz_return_val_if_fail(bf && bf->o && bf->o->bin_obj, NULL);
 	struct MACH0_(obj_t) *bin = bf->o->bin_obj;
-	return rz_str_dup(NULL, (const char *)bin->signature);
+	if (!bin->signature) {
+		return NULL;
+	}
+	if (json) {
+		return rz_str_newf("\"%s\"", (const char *)bin->signature);
```
Comment (thestr4ng3r) [inline librz/bin/p/bin_mach0.c]: Use `rz_str_escape_utf8_for_json()`, or maybe even `PJ` with just a single `pj_s()` if that works.

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]

File: librz/bin/p/bin_mach0.c (hunk 1 above)
Comment (ret2libc) [reply librz/bin/p/bin_mach0.c]: good suggestion, i'll try

**Review by thestr4ng3r — APPROVED** [review]
