### PR TITLE
Fix arm64 analysis to fix regression on ARM64 switch tables.

### LINKED ISSUE #3093: Wrong switch-case analysis on MacOS M1 ARM
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 12.6 M1 Max
| File format of the file you reverse (mandatory)      | MachO
| Architecture/bits of the file (mandatory)            | M1 Max
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 @ darwin-arm-64 commit: b81d9225fc411c976502fd1c110c2feac0b17c9b

### Expected behavior
```
0x100003c44 0x100003c64 00:0000 32 s 0x100003c64 s 0x1000040f8 s 0x100003ec4 s 0x100003ed4 s [...]
```
In general, the value from the table at `0x100004638` should be added to `0x100003c58`.

### Actual behavior
```
0x100003c44 0x100003c64 00:0000 32 s 0x0000000c s 0x000004a0 s 0x0000026c s 0x0000027c s [...]
```

### Steps to reproduce the behavior
```
$ rizin -A /bin/ls
> s. 3c44
> afbi
```

### Additional Logs, screenshots, source code,  configuration dump, ...

Standard /bin/ls from MacOS [binls.zip](https://github.com/rizinorg/rizin/files/9772378/binls.zip)

```
> pdb @ 0x100003c44
│           0x100003c44      cmp   x16, 0x5b
│           0x100003c48      csel  x16, x16, xzr, ls
│           0x100003c4c      adr   x17, sym.func.100004638             ; 0x100004638
│           0x100003c50      nop
│           0x100003c54      ldrsw x16, [x17, x16, lsl 2]
│           0x100003c58      adr   x17, 0x100003c58
│           0x100003c5c      add   x16, x17, x16
│           ;-- switch
│           0x100003c60      br    x16                                 ; switch table (92 cases) at 0x100004638
```

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Capstone 6 brought a bug in `adr` and also now some instructions are not detected correctly in the Analysis code for Arm64.

### CODE REVIEW

File: librz/analysis/p/analysis_arm_cs.c [hunk 1]
```diff
@@ -991,8 +991,43 @@ static void anop64(ArmCSContext *ctx, RzAnalysisOp *op, cs_insn *insn) {
...
 	case CS_AARCH64(_INS_TST):
 #endif
+		if (ISIMM64(1)) {
+			op->val = IMM64(1);
+		}
 		op->type = RZ_ANALYSIS_OP_TYPE_CMP;
 		break;
+#if CS_NEXT_VERSION >= 6
+	case CS_AARCH64(_INS_ADDS):
+		if (insn->alias_id == AArch64_INS_ALIAS_CMN) {
```
Comment (Rot127) [inline librz/analysis/p/analysis_arm_cs.c]: Maybe it is worth to add an `inline` function which does:

```c
static inline bool is_alias(cs_insn insn, AArch64Alias alias_id) {
   return insn->is_alias && (insn->alias_id == alias_id);
}
```

Simply because this pattern gets more and more common.

Comment (wargio) [reply librz/analysis/p/analysis_arm_cs.c]: definetely

**Review by XVilka — APPROVED** [review]
