### PR TITLE
Pyc plugin segment fault fix and add tests

### LINKED ISSUE #803: rz-asm crashed when parsing python bytecode
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux
| File format of the file you reverse (mandatory)      | pyc
| Architecture/bits of the file (mandatory)            | pyc
| `rizin -v` full output, **not truncated** (mandatory)  | rz_asm 0.2.0-git @ linux-x86-64 commit: 27408a26cbc75f9bde3e0bcd8e537bc3a5c9cb36, build: 2021-03-08__20:34:55

### Expected behavior
Parse `0x0000006a` to an opcode with arguments

### Actual behavior
crashed with the following output:
```
 WARNING: rz_list_get_n: assertion 'list' failed (line 447)
 WARNING: rz_list_get_n: assertion 'list' failed (line 447)
 [1]    32414 segmentation fault (core dumped)  ./rz-asm -a pyc -d 0x0000006a
```

### Steps to reproduce the behavior
`rz-asm -a pyc -d  0x0000006a`

### Additional Info

- Everything works fine when using rizin `pd`.

- In `librz/asm/p/asm_pyc.c : line 22` Var `shared` is fetched from `bin->cur->o->obj`. It is used to get `cobjs` and `interned_table` (required by `rz_pyc_disasm`), but there is no NULL pointer check for it.
```
	RzBinPlugin *plugin = bin && bin->cur && bin->cur->o ? bin->cur->o->plugin : NULL;

	if (plugin) {
		if (!strcmp(plugin->name, "pyc")) {
			shared = bin->cur->o->bin_obj;
		}
	}
	RzList *cobjs = rz_list_get_n(shared, 0);
	RzList *interned_table = rz_list_get_n(shared, 1);
```

### PR DESCRIPTION
**Pull request by Heersin**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr may close issue#803. The pyc asm plugin requires version info from `RzAsm a->cpu` (which is set in its bin plugin bin_pyc.c), but rz-asm don't have the concept about rz-bin's info, this value will be a NULL pointer. So this pr patches `get_opcode_by_version` and `get_opcodes_equal` in `asm/arch/pyc/opcode.c` to prevent segment fault.

Also, I added some command tests for pyc plugin

**Test plan**

No crash when run `rz-asm -a pyc -d 0x0000006a`

**Closing issues**

closes #803 #805 

**Addtional Info**
Originally I wanted to set a default version to solve this problem. But due to `rz_pyc_disasm` requires more than just version info from other plugins. I just simply put a NULL pointer check and error message there. The similar problem may occur in other formats whose opcodes are different from various versions. Maybe `rz-asm` can add a command line option to specify version in the future ?

### CODE REVIEW

**Comment by XVilka** [comment]
Regarding version we might use `rz-asm -c` (`e asm.cpu`) for this, since it's efficiently a "CPU" for the Python bytecode VM. Same logic can be applied to Lua and Java VMs too.

**Comment by Heersin** [comment]
> Regarding version we might use `rz-asm -c` (`e asm.cpu`) for this, since it's efficiently a "CPU" for the Python bytecode VM. Same logic can be applied to Lua and Java VMs too.

I get it now. Thank you for your quick reply .

**Comment by XVilka** [comment]
I am not sure why GitHub didn't update rizin-testbins even if the files were merged. Maybe you could close this PR and open a new one?
https://github.com/rizinorg/rizin/pull/822/checks?check_run_id=2110073493#step:16:392

**Review by ret2libc — APPROVED** [review]

**Comment by Heersin** [comment]
> I am not sure why GitHub didn't update rizin-testbins even if the files were merged. Maybe you could close this PR and open a new one?
> https://github.com/rizinorg/rizin/pull/822/checks?check_run_id=2110073493#step:16:392

Oops it's my fault. The test-bins are put in a different path in my local machine. Sorry for the noise. I will update and push it later.

**Comment by XVilka** [comment]
```
 -- stderr
Undefined type in free_object (0)
```
https://github.com/rizinorg/rizin/pull/822/checks?check_run_id=2112395189#step:16:392

**Comment by Heersin** [comment]
CI can find these files, but seems no output there. It pass all tests in my environment. May be I should filter the stderr message ?
```
Running from /home/heersin/Workspace/mine/rizin/test
Loaded 12 tests.
[12/12]                    12 OK         0 BR        0 XX        0 FX
Finished in 0 seconds.
```

**Comment by Heersin** [comment]
> ```
>  -- stderr
> Undefined type in free_object (0)
> ```
> 
> https://github.com/rizinorg/rizin/pull/822/checks?check_run_id=2112395189#step:16:392

I see this error message. I think there might be a logic bug in parsing pyc object type.

**Comment by Heersin** [comment]
> > ```
> >  -- stderr
> > Undefined type in free_object (0)
> > ```
> > 
> > 
> > https://github.com/rizinorg/rizin/pull/822/checks?check_run_id=2112395189#step:16:392
> 
> I see this error message. I think there might be a logic bug in parsing pyc object type.

But despite this, the command should still have the correct output.

**Review by wargio — COMMENTED** [review]
Nice catch

**Comment by Maijin** [comment]
If it's indeed a valuable information to have when using the pyc plugin, then the message should be like the following: https://github.com/rizinorg/rizin/blob/dev/librz/bin/p/bin_write_mach0.c#L63


`eprintf("Warning: Undefined type in free_object (0)\n");`

Thoughts?

**Comment by Heersin** [comment]
I rebuilt rizin and located a segment fault in pyc's asm plugin.finit. In `librz/analysis/analysis.c : 206` [commit](https://github.com/rizinorg/rizin/commit/09082667580cb3e9fcbc4ba841e3e9943e1f1333#diff-d2dbca5a3ac262f4cbbd53ec765bdc06e7c4656527a689eb9c0bddeebdb1a617), there is a `plugin_fini(analysis)` after finding the corresponding plugin name for current arch.
```C

	if (analysis) {
		rz_list_foreach (analysis->plugins, it, h) {
			if (!h->name || strcmp(h->name, name)) {
				continue;
			}
			plugin_fini(analysis);
			analysis->cur = h;
			if (h && h->init && !h->init(&analysis->plugin_data)) {
				RZ_LOG_ERROR("analysis plugin '%s' failed to initialize.\n", h->name);
				return false;
			}
			rz_analysis_set_reg_profile(analysis);
			return true;
		}
	}
	return false;
```

 Then `free_opcode` defined in pyc plugin will try to free a non-allocated object, which causes this segmentfault. Comment the `plugin_fini` can solve this segmentfault. I think it should be a init routine.

```C
			// plugin_fini(analysis);
			analysis->cur = h;
```

btw, may I ask what's the meaning of `finit`?  It's `finish` or `final init` ?

**Comment by XVilka** [comment]
@Heersin it means "finish". @wargio did this refactoring for the Java PR, probably can help you here.

**Comment by Heersin** [comment]
I chose to patch the pyc plugin `free_opcode` and `finish` to prevent segment fault : )

File: librz/analysis/analysis.c [hunk 1]
```diff
@@ -144,8 +144,13 @@ RZ_API RzAnalysis *rz_analysis_new(void) {
 
 RZ_API void plugin_fini(RzAnalysis *analysis) {
 	RzAnalysisPlugin *p = analysis->cur;
-	if (p && p->fini && !p->fini(analysis->plugin_data)) {
-		RZ_LOG_ERROR("analysis plugin '%s' failed to terminate.\n", p->name);
+	if (p && p->fini) {
```
Comment (wargio) [inline librz/analysis/analysis.c]: actually it's easier to have there directly `analysis->plugin_data = NULL;` after the if.
no need to change that if.
Ps: be sure to run `./sys/clang-format.py`

File: librz/analysis/p/analysis_pyc.c [hunk 2]
```diff
@@ -128,7 +128,9 @@ static int pyc_op(RzAnalysis *a, RzAnalysisOp *op, ut64 addr, const ut8 *data, i
 }
 
 static bool finish(void *user) {
-	rz_return_val_if_fail(user, false);
+	if (user == NULL) {
+		return true;
+	}
```
Comment (wargio) [inline librz/analysis/p/analysis_pyc.c]: You can remove this if and just check for null pointer into `free_opcode()`

**Review by wargio — CHANGES_REQUESTED** [review]

File: librz/analysis/analysis.c (hunk 1 above)
Comment (Heersin) [reply librz/analysis/analysis.c]: Understand ~. Originally I though we can't set it to NULL if this plugin_data wasn't finished correctly.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
