### PR TITLE
Fix #3647

### LINKED ISSUE #3647: Some default panels broken
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 6.4.1-arch2-1 x86_64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ linux-x86-64 (not printed: commit 83e40b0c0cc76fc344dd778ec89c5eb43a2eaa8a)

### Expected behavior

The default panels in visual panels mode should work.

### Actual behavior

"Stack" and any other panels using `px` commands are broken for some reason. The default command for "Stack" is `pxq 256@r:SP` which runs fine on its own but not in the panel. Changing the command (using the `"` key) to `pxq 256@r:SP` again makes the window say `pxq 256@r:SP (xc 256@r:SP)` which seems to work fine but also prints the results of `xc`, not `pxq`. Changing the command to `xc 256@r:SP` works as intended.

The "Registers" command is out of date and should be ``%== true `e cfg.debug`; %! dr; %% ar``. Changing it to this works fine.

### Steps to reproduce the behavior

Open anything with `-d` and check `V!`

### Additional Logs, screenshots, source code,  configuration dump, ...

image

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Fix #3647

### CODE REVIEW

File: librz/core/tui/panels.c [hunk 1]
```diff
@@ -28,8 +28,8 @@
 
 #define PANEL_CMD_SYMBOLS       "isq"
 #define PANEL_CMD_XREFS         "axl"
-#define PANEL_CMD_STACK         "px"
-#define PANEL_CMD_REGISTERS     "?== true `e cfg.debug`; ?! dr; ?? ar" // select dr or ar depending on cfg.debug
+#define PANEL_CMD_STACK         "xc"
+#define PANEL_CMD_REGISTERS     "drt:value/cols/name/role"
```
Comment (ret2libc) [inline librz/core/tui/panels.c]: doesn't this work in debug mode only?

Comment (wargio) [reply librz/core/tui/panels.c]: no also esil

**Review by XVilka — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

File: librz/core/tui/panels.c (hunk 1 above)
Comment (ret2libc) [reply librz/core/tui/panels.c]: then why is there that hack later with "if the command starts with 'drt', replace it with 'art'"?

Comment (wargio) [reply librz/core/tui/panels.c]: because the user made me notice that drt does not output anything if not in debug/emu mode

Comment (ret2libc) [reply librz/core/tui/panels.c]: Then it was just ok to do as before, I think:
```
%== true `e cfg.debug` ; %! dr; %% ar
```

Comment (wargio) [reply librz/core/tui/panels.c]: no it is not because there is a function that cuts by ` ` (white space) and splits the command in tokens.
That function breaks some stuff. the whole panel code needs to be refactored to use the C api. this is a huge mess of commands and weird ways of swapping how commands are executed.

Comment (ret2libc) [reply librz/core/tui/panels.c]: Are you sure? It seems the user opening the issue has tried it and it worked. I also tried it briefly and it seems to work fine even in panels.

Comment (wargio) [reply librz/core/tui/panels.c]: doesn't work for me. only for debug mode

Comment (wargio) [reply librz/core/tui/panels.c]: seems that my not-working issue was caused by a broken layout
