### PR TITLE
Fix #2218: `.bf` extension identifies file as bf if contents are not recognized

### LINKED ISSUE #2218: `.bf` extension should identify file as bf if contents are not recognized
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64 20.04
| File format of the file you reverse (mandatory)      | bf
| Architecture/bits of the file (mandatory)            | bf
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 20777b6e0b06a35d10f43a89801e187c9daae77d, build: 2022-01-17__19:31:36

### Expected behavior

```sh
$ rizin -2 -c 'i~format' -q 2+5.bf
format   bf
```

### Actual behavior

```sh
$ rizin -2 -c 'i~format' -q 2+5.bf
format  any
```
Expected behavior can be obtained using `-F bf` but that shouldn't be necessary.

### Steps to reproduce the behavior

[2+5.bf.zip](https://github.com/rizinorg/rizin/files/7882025/2%2B5.bf.zip) (from Wikipedia)

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr makes rizin identify a file as `bf` by the `.bf` extension if its contents are not recognized, by allowing `bin` plugins to check the filename.

**Test plan**

All builds are green.

**Closing issues**

Closes #2218.

### CODE REVIEW

File: librz/bin/p/bin_bf.c [hunk 1]
```diff
@@ -93,6 +93,10 @@ static bool check_buffer(RzBuffer *buf) {
 	return true;
 }
 
+static bool check_filename(const char *filename) {
+	return rz_str_endswith(filename, ".bf");
```
Comment (thestr4ng3r) [inline librz/bin/p/bin_bf.c]: What about making it case-insensitive?

File: test/2+5.bf [hunk 2]
```diff
@@ -0,0 +1,20 @@
+++       Cell c0 = 2
```
Comment (thestr4ng3r) [inline test/2+5.bf]: Better put these files in the testbins repo.

**Review by thestr4ng3r — COMMENTED** [review]
I think it's debatable whether or not we want detection based on filenames at all, but If we do, then this is the right way to implement it imo :-)

File: test/2+5.bf (hunk 2 above)
Comment (thestr4ng3r) [reply test/2+5.bf]: I mean https://github.com/rizinorg/rizin-testbins, not the db dir.

Comment (kazarmy) [reply test/2+5.bf]: okay rizinorg/rizin-testbins#61 ... the db dir commit was just to test whether putting the files there would work, just in case this pr is not approved

File: librz/bin/p/bin_bf.c (hunk 1 above)
Comment (kazarmy) [reply librz/bin/p/bin_bf.c]: okay d2313fd66d69dc3f6b2b5cd5123f41adb767ca4e

**Review by wargio — APPROVED** [review]

**Review by thestr4ng3r — APPROVED** [review]
