### PR TITLE
Fix #3952

### LINKED ISSUE #3952: Crash on running `pdf` on ARMv7 file with DWARF
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 14.1 ARM64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARMv7
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/753f9c23672f994d2769b84c0e8876997dce7f80

### Expected behavior

No crash

### Actual behavior
```
rizin -e asm.cpu=cortexm -e asm.flags.real=true test_app2.elf
[0x00008080]> aaa
[0x00008080]> pdf @ sym.__do_global_dtors_aux
zsh: segmentation fault  rizin -e asm.cpu=cortexm test_app2.elf
```

Note, that crash happens only if `asm.flags.real` is set to `true`, otherwise it doesn't happen!

### Steps to reproduce the behavior
- Open rizin-testbins/elf/test_app2.elf
- Analyze
- Run `pdf`

Originally reported in https://github.com/rizinorg/rizin/issues/3929

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #3952

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]

File: librz/parse/filter.c [hunk 1]
```diff
@@ -310,7 +310,7 @@ static bool filter(RzParse *p, ut64 addr, RzFlag *f, RzAnalysisHint *hint, char
 					if (label) {
 						flagname = rz_str_newf(".%s", label);
 					} else {
-						flagname = strdup(f->realnames ? flag->realname : flag->name);
+						flagname = rz_str_new(flag->realname ? flag->realname : flag->name);
 					}
 					int maxflagname = p->maxflagnamelen;
 					if (maxflagname > 0 && strlen(flagname) > maxflagname) {
```
Comment (wargio) [inline librz/parse/filter.c]: theoretically `flagname` can be `NULL` and this check will make the process crash due a null deref because `strlen` does not check for NULL.

**Review by XVilka — APPROVED** [review]
