### PR TITLE
Improve dm= command: unified colors, unicode support, and alignment fix

### LINKED ISSUE #5251: Improve colors and unicode in `dm=` output
For example, currently it looks like:
```
map  16K - 0x00000002b9280000 |----------------------------------------------------------------------------------------------------------------------------| 0x00000002b9284000 r-- 89_copy_1
map   1G - 0x0000000fc0000000 |###################################################################################-----------------------------------------| 0x0000001000000000 --- 8a_copy
map 384G - 0x0000001000000000 |----------------------------------------------------------------------------------##########################################| 0x0000007000000000 --- 8b_copy
map 512M - 0x0000600000000000 |############################################################################################################################| 0x0000600020000000 rw- 8c_copy_userrwx
[0x10275d098]>
```

Or, with colors:

Image

- First, when `scr.utf8` is set to `true`, it could use Unicode characters (block and long horizontal ones) like in other places.
- Second, coloring could be improved to not only colorize addresses but other items as well. Maybe bars themselves could use different color as well. What is best is better to determine by trial and error
- Third, notice the misalignment because of the different width of the size column, should be fixed

### PR DESCRIPTION
**Pull request by Ayushd785**
## Summary
This PR enhances the `dm=` command output to provide a more consistent and visually appealing experience for memory map visualization.

## Changes Made
- **Unicode Support**: The command now uses Unicode block characters (█) and horizontal lines (─) when `scr.utf8` is enabled, falling back to ASCII characters (# and -) when disabled
- **Unified Color Scheme**: All elements (addresses, bars, vertical separators, and permission text) now use the same color for each memory map based on its permissions
- **Alignment Fix**: Fixed the size column formatting from `%4.8s` to `%5s` to ensure consistent alignment across different size values
- **Enhanced Visual Design**: Permission text and vertical separators are now colored to create a cohesive visual connection

## Screenshots-

before- 
image

After- 
image

## Color Mapping
- **RED** (`ai.exec`) for executable memory regions (`r-x`, `--x`)
- **BLUE** (`ai.write`) for writable memory regions (`rw-`)
- **GREEN** (`ai.read`) for read-only memory regions (`r--`)
- **BRIGHT RED** (`widget_sel`) for dangerous memory regions with both write and execute permissions (`rwx`)

Fixes #5251

### CODE REVIEW

**Comment by Ayushd785** [comment]
## AI declaration 

I have used GitHub Copilot for any syntax issues and Gemini for drafting and discussions. There is no line of code written by an AI in this pull request. Most of the code is just reused from other implementations .
like - Unicode Character pattern 

`const char *block = opts->unicode ? UTF_BLOCK : "#";`

for color palette usage-

`if (type & RZ_ANALYSIS_ADDR_TYPE_EXEC) {
    return core->cons->context->pal.ai_exec; // Color_RED;
}
if (type & RZ_ANALYSIS_ADDR_TYPE_WRITE) {
    return core->cons->context->pal.ai_write; // Color_BLUE;
}
if (type & RZ_ANALYSIS_ADDR_TYPE_READ) {
    return core->cons->context->pal.ai_read; // Color_GREEN;
}`

**Comment by Ayushd785** [comment]
Tested with larger memory maps using Rizin’s Cutter and Firefox to trigger them.
Cutter-
Screenshot From 2025-10-23 12-40-56
Firefox-
Screenshot From 2025-10-23 12-44-49

**Comment by Ayushd785** [comment]
@notxvilka As per the suggestion, the tests for the `dm=` command have been completely removed because the `~ `command does not work as expected for output filtering with dm=, and the visual output varies across environments, making it unsuitable for automated testing.

File: librz/core/cdebug.c [hunk 1]
```diff
@@ -668,29 +678,45 @@ static void print_debug_maps_ascii_art(RzDebug *dbg, RzList /*<RzDebugMap *>*/ *
...
 				(addr >= map->addr &&
 					addr < map->addr_end)
 					? '*'
 					: '-',
-				color_prefix, map->addr, color_suffix); // * indicates map is within our current sought offset
+				color_prefix, map->addr, color_suffix,
+				colors && bar_color[0] ? bar_color : "",
+				colors && bar_color[0] ? Color_RESET : ""); // * indicates map is within our current sought offset
 			int col;
-			for (col = 0; col < width; col++) { // Iterate over the available width/columns for bar graph
```
Comment (notxvilka) [inline librz/core/cdebug.c:680]: Please do not remove old comments. Apart from that LGTM

File: test/db/archos/linux-x64/dbg_maps [hunk 2]
```diff
@@ -9,6 +9,7 @@ EXPECT=<<EOF
 EOF
 RUN
 
+
```
Comment (notxvilka) [inline test/db/archos/linux-x64/dbg_maps]: Unnecessary change

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: librz/core/cdebug.c (hunk 1 above)
Comment (Ayushd785) [reply librz/core/cdebug.c:680]: i have restored the old comments some of them didn't made any sense for the new code so i added new ones for them

File: test/db/archos/linux-x64/dbg_maps (hunk 2 above)
Comment (Ayushd785) [reply test/db/archos/linux-x64/dbg_maps]: i have removed the extra line of change and kept only one line of space between those two to keep the test structure consistent as it was

**Comment by Ayushd785** [comment]
I sincerely apologize for the extra force-pushes. I was stuck with some Git synchronization issues where changes weren't being properly reflected in commits, even though they appeared correctly in my working directory. I had removed the extra line from dbg_maps, but it wasn't showing up in the committed changes. There was something I was missing, but I've fixed it now.

File: librz/core/cdebug.c [hunk 3]
```diff
@@ -644,20 +647,27 @@ static void print_debug_maps_ascii_art(RzDebug *dbg, RzList /*<RzDebugMap *>*/ *
 		const char *color_suffix = ""; // Color escape code appended to end of string
 		const char *fmtstr;
 		char humansz[8]; // Holds the human formatted size string [124K]
-		int skip = 0; // Number of maps to skip when re-calculating the minmax
+		int skip = 0;  // Number of maps to skip when re-calculating the minmax
```
Comment (notxvilka) [inline librz/core/cdebug.c]: One unnecessary space character here

**Review by notxvilka — CHANGES_REQUESTED** [review]
Just one little thing left

File: librz/core/cdebug.c (hunk 3 above)
Comment (Ayushd785) [reply librz/core/cdebug.c]: Yes sorry for that, Its fixed now

**Review by notxvilka — APPROVED** [review]
