### PR TITLE
Fix: asn and asr command #3885

### LINKED ISSUE #3885: read syscall on x86-64 Linux
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ linux-x86-64; commit: 729edc8919adb0227bc5fba67ffcef514cb4cf84

### Expected behavior

I expect

    asr 0 ===> read
    asn read ===> 0

### Actual behavior

    asr 0 ===> ERROR: Cannot resolve syscall: 0
    asn read ===> 128

### PR DESCRIPTION
**Pull request by Sl4y3r-07**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

I have fixed the issue with `asr` and `asn` commands related to `read` syscall. 
Issue:
```
asr 0 ===> ERROR: Cannot resolve syscall: 0
asn read ===> 128
```

Here I have modified this if block -> instead of `(num<1)` , I have done `num<0` in both the functions 
1.  rz_analysis_syscall_name_handler()
2. rz_analysis_syscall_number_handler()

```
if (num < 0) {
		RZ_LOG_ERROR("Cannot resolve syscall: %s\n", argv[1]);
		return RZ_CMD_STATUS_ERROR;
	}
```

Apart from this, I have also modified the function `sdb_array_get_num()`. Added an `error parameter` and if invalid entry is found, it returns `-1` instead of `0`.
...

Fix #3885

### CODE REVIEW

File: librz/util/sdb/src/array.c [hunk 1]
```diff
@@ -60,16 +60,21 @@ static inline int int_cmp(const void *a, const void *b) {
 	return 0;
 }
 
-RZ_API ut64 sdb_array_get_num(Sdb *s, const char *key, int idx) {
+RZ_API ut64 sdb_array_get_num(Sdb *s, const char *key, int idx, int* err) {
```
Comment (wargio) [inline librz/util/sdb/src/array.c]: instead of doing this, return `bool`.

```suggestion
RZ_API bool sdb_array_get_num(Sdb *s, const char *key, int idx, ut64* out_number) {
```

Comment (wargio) [reply librz/util/sdb/src/array.c]: in this way you can know if the function errored or not.

Comment (Sl4y3r-07) [reply librz/util/sdb/src/array.c]: okay, I'll fix this.

**Comment by wargio** [comment]
no you need to implement the code changes.

**Comment by Sl4y3r-07** [comment]
> no you need to implement the code changes.

Yes, I have done the changes. Please check.

**Review by Rot127 — CHANGES_REQUESTED** [review]
It breaks this test:
```diff
 [XX]   1 secs db/esil/arm_16 arm s110 syscalls asl ascii
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -aarm -b16 -easm.os=s110 -qc 'asn sd_evt_get' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-81
+0
```

Besides, please read our new AI guidelines: https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md#usage-of-ai-tools

**Comment by Sl4y3r-07** [comment]
> It breaks this test:
> 
> ```diff
>  [XX]   1 secs db/esil/arm_16 arm s110 syscalls asl ascii
> RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -aarm -b16 -easm.os=s110 -qc 'asn sd_evt_get' =
> -- stdout
> --- expected
> +++ actual
> @@ -1,1 +1,1 @@
> -81
> +0
> ```
> 
> Besides, please read our new AI guidelines: https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md#usage-of-ai-tools

I should have checked these tests, I am sorry for this part. I will take care of this in future contributions.

**Comment by Sl4y3r-07** [comment]
@Rot127 
I have a doubt here. 
In `linux-x86-64.sdb.txt`
```
_=0x80
read=0x80,0,3,ipi
write=0x80,1,3,izi
open=0x80,2,3,zxx
close=0x80,3,1,i
stat=0x80,4,2,
fstat=0x80,5,2,
lstat=0x80,6,2,
poll=0x80,7,3,
lseek=0x80,8,3,
mmap=0x80,9,6,
mprotect=0x80,10,3,
munmap=0x80,11,1,
brk=0x80,12,1,
rt_sigaction=0x80,13,3,
```
Syscall numbers are at index 1 and no of arguments at index 2. [Similarly for windows, openbsdm netbsd, ios, darwin]

But in case of `s110-arm-16.sdb.txt` 
```
_=-1
application_0=0,0
application_1=1,0
application_2=2,0
application_3=3,0
application_4=4,0
application_5=5,0
application_6=6,0
application_7=7,7
application_8=8,0
application_9=9,0
application_10=10,0
application_11=11,0
application_12=12,0
application_13=13,0
application_14=14,0
application_15=15,0
sd_softdevice_enable=0x10,0
sd_softdevice_disable=0x11,0
sd_softdevice_is_enabled=0x12,0,1
sd_softdevice_vector_table_base_set=0x13,0,1
sd_mbr_command=0x14,0,1
```
Syscall numbers are at idx 0

So, my doubt is, whether the fomrat for s110 is correct or need to be changed ? Cause I made the changes assuming the same pattern in the db files.

File: librz/util/sdb/src/query.c [hunk 2]
```diff
@@ -395,7 +395,10 @@ RZ_API char *sdb_querys(Sdb *r, char *buf, size_t len, const char *_cmd) {
 			int idx = sdb_atoi(cmd + 2);
 			/* +[idx]key=n */
 			/* -[idx]key=n */
-			ut64 curnum = sdb_array_get_num(s, eb + 1, idx);
+			ut64 curnum = 0;
+			if(!sdb_array_get_num(s, eb + 1, idx, &curnum)){
+              eprintf("Invalid syscall\n");
```
Comment (wargio) [inline librz/util/sdb/src/query.c]: remove the eprintf since this error is totally unrelated with the sdb code

Comment (wargio) [reply librz/util/sdb/src/query.c]: Just replace it with `goto fail;`

File: librz/syscall/syscall.c [hunk 3]
```diff
@@ -378,15 +378,15 @@ RZ_API RzSyscallItem *rz_syscall_get(RzSyscall *s, int num, int swi) {
...
 	}
-	int sn = (int)sdb_array_get_num(s->db, str, 1);
-	if (sn == 0) {
-		return (int)sdb_array_get_num(s->db, str, 0);
-	}
-	return sn;
+	ut64 sn = 0;																																																																																																																		
+	if (!sdb_array_get_num(s->db, str, 1, &sn)) {
+		return -1;																																																																																																			
+    }
```
Comment (wargio) [inline librz/syscall/syscall.c]: ?

File: librz/syscall/syscall.c [hunk 4]
```diff
@@ -378,15 +378,15 @@ RZ_API RzSyscallItem *rz_syscall_get(RzSyscall *s, int num, int swi) {
 }
 
 RZ_API int rz_syscall_get_num(RzSyscall *s, const char *str) {
```
Comment (wargio) [inline librz/syscall/syscall.c]: convert this api to return also bool and the syscall number in the args.

**Review by notxvilka — CHANGES_REQUESTED** [review]
it requires a test.

File: librz/syscall/syscall.c (hunk 3 above)
Comment (Rot127) [reply librz/syscall/syscall.c]: @Sl4y3r-07 Due to these lines I'd like to ask, if you used AI tools for coding?
You would need to disclose this according to our contributing guidelines:
https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md#usage-of-ai-tools

Comment (Sl4y3r-07) [reply librz/syscall/syscall.c]: Hi @Rot127 , I have gone through these contributing guidelines. I would like to clarify this change, I haven't used AI tools here, I have just changed the return type here from `int` to `bool`, and modified the `if block`

This was the initial code. It was first fetching the syscall number from index 1 and if 0 is returned then it fetches from the index 0. I looked the sdb files and found the syscall numbers are at index 1 only, I didn't understand why 0 idx is being returned ->  `return (int)sdb_array_get_num(s->db, str, 0);`  
```
int sn = (int)sdb_array_get_num(s->db, str, 1);
	if (sn == 0) {
		return (int)sdb_array_get_num(s->db, str, 0);
	}
	return sn;
```

That's why I made this change:
```
ut64 sn = 0;														
	if (!sdb_array_get_num(s->db, str, 1, &sn)) {
		return -1;																						
    }
   ```
   
   Since you have told about the failure of the testcase, in `s110` db: syscalls numbers are at index 0. I have mentioned about this also. 
   
   If you have any issue or doubt regarding this, please let me know. Sorry for the delayed reply, I am currently travelling.

File: librz/syscall/syscall.c (hunk 4 above)
Comment (Sl4y3r-07) [reply librz/syscall/syscall.c]: Okay, thanks. Just need a few hours to fix it since I am currently travelling. Sorry for the delay.

File: librz/syscall/syscall.c (hunk 3 above)
Comment (Rot127) [reply librz/syscall/syscall.c]: The issue is not with returning `-1`. It is because it adds a huge amount spaces at the end of the line.

**Comment by Sl4y3r-07** [comment]
> it requires a test.

I'll add for it.

File: librz/syscall/syscall.c (hunk 3 above)
Comment (Sl4y3r-07) [reply librz/syscall/syscall.c]: Ohh, it's because I have another testing repo for rizin, so at the time of making PR, I just take the final changes and push in the separate branch to the forked repo.

I will take care of this.

**Comment by Sl4y3r-07** [comment]
> @Rot127 I have a doubt here. In `linux-x86-64.sdb.txt`
> 
> ```
> _=0x80
> read=0x80,0,3,ipi
> write=0x80,1,3,izi
> open=0x80,2,3,zxx
> close=0x80,3,1,i
> stat=0x80,4,2,
> fstat=0x80,5,2,
> lstat=0x80,6,2,
> poll=0x80,7,3,
> lseek=0x80,8,3,
> mmap=0x80,9,6,
> mprotect=0x80,10,3,
> munmap=0x80,11,1,
> brk=0x80,12,1,
> rt_sigaction=0x80,13,3,
> ```
> 
> Syscall numbers are at index 1 and no of arguments at index 2. [Similarly for windows, openbsdm netbsd, ios, darwin]
> 
> But in case of `s110-arm-16.sdb.txt`
> 
> ```
> _=-1
> application_0=0,0
> application_1=1,0
> application_2=2,0
> application_3=3,0
> application_4=4,0
> application_5=5,0
> application_6=6,0
> application_7=7,7
> application_8=8,0
> application_9=9,0
> application_10=10,0
> application_11=11,0
> application_12=12,0
> application_13=13,0
> application_14=14,0
> application_15=15,0
> sd_softdevice_enable=0x10,0
> sd_softdevice_disable=0x11,0
> sd_softdevice_is_enabled=0x12,0,1
> sd_softdevice_vector_table_base_set=0x13,0,1
> sd_mbr_command=0x14,0,1
> ```
> 
> Syscall numbers are at idx 0
> 
> So, my doubt is, whether the fomrat for s110 is correct or need to be changed ? Cause I made the changes assuming the same pattern in the db files.

@Rot127 can you please look into it ? Rest all the suggested changes have been done.

**Comment by wargio** [comment]
the syscall format is different for each arch. on x86 you call `int 0x80` so at index 1 you find the actual syscall number, but on arm you just call `svc`, therefore the syscall number is at index 0

As you see in the sdb files, for x86 we define `_=0x80` meanwhile for arm `_=-1`, this means that for x86 we skip the 0x80 and just use the next value as syscall number, meanwhile in arm `-1` is an invalid value to let the code know to use directly the first value

**Comment by Sl4y3r-07** [comment]
> the syscall format is different for each arch. on x86 you call `int 0x80` so at index 1 you find the actual syscall number, but on arm you just call `svc`, therefore the syscall number is at index 0
> 
> As you see in the sdb files, for x86 we define `_=0x80` meanwhile for arm `_=-1`, this means that for x86 we skip the 0x80 and just use the next value as syscall number, meanwhile in arm `-1` is an invalid value to let the code know to use directly the first value

Yeah, right. 
So initially. here it is looking at both the indexes 1 and then 0: 
```
int sn = (int)sdb_array_get_num(s->db, str, 1);
	if (sn == 0) {
		return (int)sdb_array_get_num(s->db, str, 0);
	}
```

So, I thought if we could use this info `_=0x80` ,`_=-1`  to read the syscalls at the right index, but `windows-x86` dbs do not contain this info. 

I did this change (I thought syscalls are at only index 1) but some testcases will fail eventually (when syscalls are at index 0) 
```
int err = 0;
	int sn = (int)sdb_array_get_num(s->db, str, 1, &err);
	if (err) {
		return -1;
    }
```

Can we add similar info like (`_=0x2e`) in `windows-x86` sdb files ?? Or what do  you suggest ?

**Comment by wargio** [comment]
> but `windows-x86` dbs do not contain this info.

probably the default value is `-1`

**Comment by Sl4y3r-07** [comment]
> > but `windows-x86` dbs do not contain this info.
> 
> probably the default value is `-1`

Okay, I will confirm it and if not set, can i add `_=0x2e` this ?

**Comment by wargio** [comment]
> > > but `windows-x86` dbs do not contain this info.
> > 
> > 
> > probably the default value is `-1`
> 
> Okay, I will confirm it and if not set, can i add `_=0x2e` this ?

yes, if it matches how the windows syscall works. (tbh, i don't know, but i'm sure google will tell you)

**Comment by Sl4y3r-07** [comment]
> yes, if it matches how the windows syscall works. (tbh, i don't know, but i'm sure google will tell you)

Thanks a lot.

**Comment by Sl4y3r-07** [comment]
> yes, if it matches how the windows syscall works. (tbh, i don't know, but i'm sure google will tell you)

@wargio Kindly have a look at this please.
```
RZ_API bool rz_syscall_get_num(RzSyscall *s, const char *str, int* num) {
	rz_return_val_if_fail(s && str && num, false);																																																																
	if (!s->db) {
		return false;
	}
    st64 base = sdb_num_get2(s->db, "_");
	int idx = (base == -1) ? 0 : 1;
	ut64 sn = 0;
	if (!sdb_array_get_num(s->db, str, idx, &sn)) {
		return false;
    }
	*num = (int)sn;
	return true;
}
```

Here, I have added these two lines 
```
st64 base = sdb_num_get2(s->db, "_");
	int idx = (base == -1) ? 0 : 1;
```
For this I have created another func `sdb_num_get2` with `(signed) long long` return type since original func is of unsigned type.

The reason for this:
In `linux-arm-64` value is `_=0x0`. If I use `sdb_num_get()` it will return `0` and then because of (base==0) -> it will go for idx 0. This allows  to distinguish `valid 0x0` from “invalid” -1 (which sdb_num_get() couldn’t, since it returned unsigned).

For this I had these options:
1. Creating another similar function with return type st64
2. Change the return value of original function from 0 to -1.  
3. Modifying the func with return type bool and passing the arg to collect the result. [As you suggested for other functions]

Last two options need changes in many files.. that's why I opted for first.

what do you suggest?

**Comment by wargio** [comment]
ok for me

**Comment by wargio** [comment]
please just do `int idx = (base < 0) ? 0 : 1;`

**Comment by wargio** [comment]
please run clang format. see the developer.md file.

File: librz/syscall/syscall.c [hunk 5]
```diff
@@ -377,16 +377,19 @@ RZ_API RzSyscallItem *rz_syscall_get(RzSyscall *s, int num, int swi) {
 	return rz_syscall_item_new_from_string(ret, ret2);
 }
 
-RZ_API int rz_syscall_get_num(RzSyscall *s, const char *str) {
-	rz_return_val_if_fail(s && str, -1);
+RZ_API bool rz_syscall_get_num(RzSyscall *s, const char *str, int *num) {
```
Comment (Rot127) [inline librz/syscall/syscall.c]:
```suggestion
RZ_API bool rz_syscall_get_num(RZ_NONNULL RZ_BORROW RzSyscall *s, RZ_NONNULL const char *str, int *num) {
```

Comment (Rot127) [reply librz/syscall/syscall.c]: Please document the function as well. Since you know now how it works and what it does.

File: librz/util/sdb/src/array.c [hunk 6]
```diff
@@ -60,22 +60,26 @@ static inline int int_cmp(const void *a, const void *b) {
 	return 0;
 }
 
-RZ_API ut64 sdb_array_get_num(Sdb *s, const char *key, int idx) {
+RZ_API bool sdb_array_get_num(Sdb *s, const char *key, int idx, ut64 *out_number) {
```
Comment (Rot127) [inline librz/util/sdb/src/array.c]:
```suggestion
RZ_API bool sdb_array_get_num(RZ_NONNULL RZ_BORROW Sdb *s, RZ_NONNULL const char *key, int idx, RZ_OUT RZ_NONNULL ut64 *out_number) {
```

Also add the `rz_return_val_if_fail()` assert for the pointer arguments. And document it.

File: librz/util/sdb/src/num.c [hunk 7]
```diff
@@ -15,6 +15,11 @@ RZ_API ut64 sdb_num_get(Sdb *s, const char *key) {
 	return (!v || *v == '-') ? 0LL : sdb_atoi(v);
 }
 
+RZ_API st64 sdb_num_get2(Sdb *s, const char *key) {
```
Comment (Rot127) [inline librz/util/sdb/src/num.c]:
```suggestion
RZ_API st64 sdb_num_get2(RZ_NONNULL RZ_BORROW Sdb *s, RZ_NONNULL const char *key) {
```

And add assert

File: librz/util/sdb/src/sdb.h [hunk 8]
```diff
@@ -170,6 +170,7 @@ RZ_API void sdbkv_free(RZ_NULLABLE SdbKv *kv);
 RZ_API bool sdb_num_exists(Sdb *, const char *key);
 RZ_API int sdb_num_base(const char *s);
 RZ_API ut64 sdb_num_get(Sdb *s, const char *key);
+RZ_API st64 sdb_num_get2(Sdb *s, const char *key);
```
Comment (Rot127) [inline librz/util/sdb/src/sdb.h]:
```suggestion
RZ_API st64 sdb_num_get2(RZ_NONNULL RZ_BORROW Sdb *s, RZ_NONNULL const char *key);
```

File: librz/util/sdb/src/sdb.h [hunk 9]
```diff
@@ -233,7 +234,7 @@ RZ_API bool sdb_array_append_num(Sdb *s, const char *key, ut64 val);
 RZ_API bool sdb_array_prepend(Sdb *s, const char *key, const char *val);
 RZ_API bool sdb_array_prepend_num(Sdb *s, const char *key, ut64 val);
 RZ_API char *sdb_array_get(Sdb *s, const char *key, int idx);
-RZ_API ut64 sdb_array_get_num(Sdb *s, const char *key, int idx);
+RZ_API bool sdb_array_get_num(Sdb *s, const char *key, int idx, ut64 *out_number);
```
Comment (Rot127) [inline librz/util/sdb/src/sdb.h]:
```suggestion
RZ_API bool sdb_array_get_num(RZ_NONNULL RZ_BORROW Sdb *s, RZ_NONNULL const char *key, int idx, RZ_OUT RZ_NONNULL ut64 *out_number);
```

**Review by Rot127 — CHANGES_REQUESTED** [review]
Generally looks good. Please also add a test though.

File: librz/syscall/syscall.c (hunk 5 above)
Comment (wargio) [reply librz/syscall/syscall.c]: nice catch

**Comment by Sl4y3r-07** [comment]
@wargio @Rot127 I have added a unit test (`test_syscall.c`). So do I need to provide some copyright or license related information ?

File: librz/include/rz_syscall.h [hunk 10]
```diff
@@ -77,7 +77,7 @@ RZ_API void rz_syscall_free(RzSyscall *ctx);
 RZ_API RzSyscall *rz_syscall_ref(RzSyscall *sc);
 RZ_API bool rz_syscall_setup(RzSyscall *s, RZ_BORROW RZ_NONNULL RzPath *sys_path, const char *arch, int bits, const char *cpu, const char *os);
 RZ_API RzSyscallItem *rz_syscall_get(RzSyscall *ctx, int num, int swi);
-RZ_API int rz_syscall_get_num(RzSyscall *ctx, const char *str);
+RZ_API bool rz_syscall_get_num(RZ_NONNULL RZ_BORROW RzSyscall *s, RZ_NONNULL const char *str, int *num);
```
Comment (Rot127) [inline librz/include/rz_syscall.h]: Type annotation for `num` is missing. Please add it.

File: librz/syscall/syscall.c [hunk 11]
```diff
@@ -377,16 +377,28 @@ RZ_API RzSyscallItem *rz_syscall_get(RzSyscall *s, int num, int swi) {
...
-	rz_return_val_if_fail(s && str, -1);
+/**
+ * \brief Retrieves the syscall number for a given syscall name
+ *
+ * \param s Reference to RzSyscall instance containing the syscall database
+ * \param str Syscall name whose number should be retrieved
+ * \param num Reference where the resolved syscall number will be stored
+ *
+ * \return True, if syscall number is successfully fetched from the db, false otherwise
+ */
```
Comment (Rot127) [inline librz/syscall/syscall.c:388]:
```suggestion
/**
 * \brief Retrieves the syscall number for a given syscall name.
 *
 * \param s Reference to RzSyscall instance containing the syscall database.
 * \param str Syscall name whose number should be retrieved.
 * \param num Reference where the resolved syscall number will be stored.
 *
 * \return True, if syscall number is successfully fetched from the db, false otherwise.
 */
```

File: librz/util/sdb/src/array.c [hunk 12]
```diff
@@ -60,22 +60,34 @@ static inline int int_cmp(const void *a, const void *b) {
 	return 0;
 }
 
-RZ_API ut64 sdb_array_get_num(Sdb *s, const char *key, int idx) {
-	int i;
+/**
+ * \brief Retrieves a numeric value from an array entry stored in the Sdb database
+ *
+ * \param s Reference to SDB instance
+ * \param key Syscall name whose number should be retrieved
```
Comment (Rot127) [inline librz/util/sdb/src/array.c]: This is not correct. It is the key name. Not the syscall name.

File: librz/util/sdb/src/array.c [hunk 13]
```diff
@@ -60,22 +60,34 @@ static inline int int_cmp(const void *a, const void *b) {
...
+ * \param idx Index (zero-based) of the value to retrieve from the array
```
Comment (Rot127) [inline librz/util/sdb/src/array.c]:
```suggestion
 * \param idx Index of the value to retrieve from the array
```

File: librz/util/sdb/src/array.c [hunk 14]
```diff
@@ -60,22 +60,34 @@ static inline int int_cmp(const void *a, const void *b) {
...
+ * \param out_number Reference where the resolved syscall number will be stored
+ *
+ * \return True, if syscall number is successfully fetched, false otherwise
```
Comment (Rot127) [inline librz/util/sdb/src/array.c]: syscall

File: librz/util/sdb/src/num.c [hunk 15]
```diff
@@ -15,6 +15,20 @@ RZ_API ut64 sdb_num_get(Sdb *s, const char *key) {
...
 
+/**
+ * \brief Retrieves a number stored as a string in the database
+ *
+ * \param s The Sdb database handle
+ * \param key The key whose value should be retrieved
+ *
+ * \return The numeric value associated with the key, or -1 if not found or negative numeric value or non-numeric value
+ */
+RZ_API st64 sdb_num_get2(RZ_NONNULL RZ_BORROW Sdb *s, RZ_NONNULL const char *key) {
```
Comment (Rot127) [inline librz/util/sdb/src/num.c]: Just recognized that this function is only used once?
Please use `sdb_array_get_num` instead of adding a new function.

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: librz/util/sdb/src/num.c (hunk 15 above)
Comment (Sl4y3r-07) [reply librz/util/sdb/src/num.c]: Hi, the reason for adding new function was `sdb_num_get` return type is ut64 and  I needed it to return -1 that's why I used this.

I didn't get how can I use `sdb_array_get_num`

The code is 
```
RZ_API bool rz_syscall_get_num(RZ_NONNULL RZ_BORROW RzSyscall *s, RZ_NONNULL const char *str, int *num) {
	rz_return_val_if_fail(s && str && num, false);
	if (!s->db) {
		return -1;
	}
	st64 base = sdb_num_get2(s->db, "_");
	int idx = (base < 0) ? 0 : 1;
	ut64 sn = 0;
	if (!sdb_array_get_num(s->db, str, idx, &sn)) {
		return false;
	}
	*num = (int)sn;
	return true;
}
```

`sdb_num_get2` decides which index is need to be passed to `sdb_array_get_num`

File: librz/syscall/syscall.c (hunk 11 above)
Comment (Sl4y3r-07) [reply librz/syscall/syscall.c:388]: Should I add `.` in other documentations too?

File: librz/util/sdb/src/num.c (hunk 15 above)
Comment (Rot127) [reply librz/util/sdb/src/num.c]: Why do you need to return -1? `sdb_array_get_num` fails already if it can't find a numerical value for `key`.

**Review by Rot127 — APPROVED** [review]

File: test/db/esil/x86_32 [hunk 16]
```diff
@@ -2457,3 +2457,21 @@ EXPECT=<<EOF
 0x00178014 0x00001337 oeax+4919
 EOF
 RUN
+
+NAME=x86 openbsd syscalls asl ascii
+FILE==
+ARGS=-ax86 -b32 -easm.os=openbsd
+CMDS=asn read
```
Comment (wargio) [inline test/db/esil/x86_32]: does asn really require esil? why not under the cmd tests?

File: test/unit/test_syscall.c [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+
+	int num = 0;
+	bool ok = rz_syscall_get_num(&s, "foo", &num);
+	mu_assert_true(ok, "rz_syscall_get_num should return true");
+	mu_assert_eq(num, 7, "Expected syscall number 7");
+
+	sdb_free(db);
+	mu_end;
+}
+int all_tests() {
```
Comment (wargio) [inline test/unit/test_syscall.c:45]:
```suggestion
}

int all_tests() {
```

File: test/db/esil/x86_32 (hunk 16 above)
Comment (Sl4y3r-07) [reply test/db/esil/x86_32]: Some of the asn tests were already under the esil, that's why I thought to keep under the same. If you want, I can move these tests under cmd.

Comment (wargio) [reply test/db/esil/x86_32]: tbh, i don't see any reason for being under esil. move them under `db/cmd/cmd_as` or `db/cmd/syscall` (create the files if they do not exists.

Comment (Sl4y3r-07) [reply test/db/esil/x86_32]:
```
NAME=arm s110 syscalls asl ascii
FILE==
ARGS=-aarm -b16 -easm.os=s110
CMDS=asn sd_evt_get
EXPECT=<<EOF
81
EOF
RUN

NAME=arm s110 syscalls asl num
FILE==
ARGS=-aarm -b16 -easm.os=s110
CMDS=asr 0x51
EXPECT=<<EOF
sd_evt_get
EOF
RUN

```

Can I move these two tests also under cmd? They are in currently under `esil/arm16`

File: test/unit/test_syscall.c (hunk 17 above)
Comment (Sl4y3r-07) [reply test/unit/test_syscall.c:45]: All the changes have been done and I have squashed all the other commits into one.

File: test/db/esil/x86_32 (hunk 16 above)
Comment (wargio) [reply test/db/esil/x86_32]: yes, all the tests which are related to the `as` command

**Review by wargio — APPROVED** [review]
LGTM
