### PR TITLE
Show even sections with 0 size/vsize

### LINKED ISSUE #3551: .reloc section not listed with iS command
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | MS-DOS executable PE32 executable (DLL) (EFI boot service driver) Intel 80386, for MS Windows
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.2 @ linux-x86-64, package: 0.5.2 (RizinOrg)

### Expected behavior

rizin lists all the sections, including the `.reloc` one, as `objdump -x` does:
```
Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         0000099a  ffffee58  ffffee58  00000260  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 _TEXT_RE      0000006e  fffff7f8  fffff7f8  00000c00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 _TEXT_PR      0000072c  fffff878  fffff878  00000c80  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  3 .reloc        00000000  ffffffb8  ffffffb8  000013c0  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
SYMBOL TABLE:
no symbols
```

### Actual behavior

rizin misses .reloc:
```
[0xfffff7f8]> iS
paddr      size  vaddr      vsize align perm name    type flags
---------------------------------------------------------------------------------
0x00000260 0x9a0 0xffffee58 0x9a0 0x0   -r-x .text        CNT_CODE,MEM_NOT_PAGED
0x00000c00 0x80  0xfffff7f8 0x80  0x0   -r-x TEXT_RE      CNT_CODE,MEM_NOT_PAGED
0x00000c80 0x740 0xfffff878 0x740 0x0   -r-x TEXT_PR      CNT_CODE,MEM_NOT_PAGED
```

### Steps to reproduce the behavior

Can't share the binaries where this problem occurs. Please let me know what information (header fields, etc.) I can provide to help the fix.

```
[0xfffff7f8]> ih
paddr      name                                    vaddr      comment
-------------------------------------------------------------------------
0x000000c0 Signature                               0x000000c0 0x00004550
0x000000c4 Machine                                 0x000000c4 0x0000014c
0x000000c6 NumberOfSections                        0x000000c6 0x00000004
0x000000c8 TimeDateStamp                           0x000000c8 0x00000000
0x000000cc PointerToSymbolTable                    0x000000cc 0x00000000
0x000000d0 NumberOfSymbols                         0x000000d0 0x00000000
0x000000d4 SizeOfOptionalHeader                    0x000000d4 0x000000e0
0x000000d6 Characteristics                         0x000000d6 0x00002103
0x000000d8 Magic                                   0x000000d8 0x0000010b
0x000000da MajorLinkerVersion                      0x000000da 0x00000009
0x000000db MinorLinkerVersion                      0x000000db 0x00000000
0x000000dc SizeOfCode                              0x000000dc 0x00001160
0x000000e0 SizeOfInitializedData                   0x000000e0 0x00000000
0x000000e4 SizeOfUninitializedData                 0x000000e4 0x00000000
0x000000e8 AddressOfEntryPoint                     0x000000e8 0x00000c00
0x000000ec BaseOfCode                              0x000000ec 0x00000260
0x000000f0 BaseOfData                              0x000000f0 0x000013c0
0x000000f4 ImageBase                               0x000000f4 0xffffebf8
0x000000f8 SectionAlignment                        0x000000f8 0x00000020
0x000000fc FileAlignment                           0x000000fc 0x00000020
0x00000100 MajorOperatingSystemVersion             0x00000100 0x00000000
0x00000102 MinorOperatingSystemVersion             0x00000102 0x00000000
0x00000104 MajorImageVersion                       0x00000104 0x00000000
0x00000106 MinorImageVersion                       0x00000106 0x00000000
0x00000108 MajorSubsystemVersion                   0x00000108 0x00000000
0x0000010a MinorSubsystemVersion                   0x0000010a 0x00000000
0x0000010c Win32VersionValue                       0x0000010c 0x00000000
0x00000110 SizeOfImage                             0x00000110 0x000013c0
0x00000114 SizeOfHeaders                           0x00000114 0x00000260
0x00000118 CheckSum                                0x00000118 0x00000000
0x0000011c Subsystem                               0x0000011c 0x0000000b
0x0000011e DllCharacteristics                      0x0000011e 0x00000000
0x00000120 SizeOfStackReserve                      0x00000120 0x00000000
0x00000124 SizeOfStackCommit                       0x00000124 0x00000000
0x00000128 SizeOfHeapReserve                       0x00000128 0x00000000
0x0000012c SizeOfHeapCommit                        0x0000012c 0x00000000
0x00000130 LoaderFlags                             0x00000130 0x00000000
0x00000134 NumberOfRvaAndSizes                     0x00000134 0x00000010
0x00000140 IMAGE_DIRECTORY_ENTRY_IMPORT            0x00000140 0x00000000
0x00000144 SIZE_IMAGE_DIRECTORY_ENTRY_IMPORT       0x00000144 0x0000ffff
0x000001a0 IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT      0x000001a0 0x00000000
0x000001a4 SIZE_IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT 0x000001a4 0x0000ffff
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Some sections in PE may have both 0 raw size and 0 vsize, however, let's show them anyway to stick to what described in the file.

**Test plan**

See commit for test and also the related issue.

**Closing issues**

Closes #3551

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
One test needs updating:
```
[XX] db/formats/pe/virtsectblXP PE: corkami virtsectblXP.exe - sections
RZ_NOPLUGINS=1 /private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-1287038090/rizinorg/rizin/prefix/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc iSt:vaddr/cols/vsize/name bins/pe/virtsectblXP.exe
-- stdout
--- expected
+++ actual
@@ -1,4 +1,4 @@
-vaddr      vsize name
+vaddr      vsize name    
 -------------------------
 0x00400000 0x0   sect_0
 0x00400000 0x0   sect_1
```

BTW, have you considered making this optional? Via some `bin.zeroszsection` or something like that?

**Comment by ret2libc** [comment]
I haven't as this is likely not a very common scenario and it can probably be hidden with some table magic command. Also, it would require me to pass the env variable down into the PE plugin (that's where the filtering was done), so for now I don't think it's worth the effort.

File: librz/bin/format/pe/pe_section.c [hunk 1]
```diff
@@ -243,28 +243,19 @@ void PE_(write_image_section_header)(RzBuffer *b, ut64 addr, PE_(image_section_h
 struct rz_bin_pe_section_t *PE_(rz_bin_pe_get_sections)(RzBinPEObj *bin) {
 	struct rz_bin_pe_section_t *sections = NULL;
 	PE_(image_section_header) * shdr;
-	int i, j, section_count = 0;
+	int i, j;
 	char sec_name[PE_IMAGE_SIZEOF_SHORT_NAME + 1];
 
 	if (!bin || !bin->nt_headers) {
 		return NULL;
 	}
```
Comment (wargio) [inline librz/bin/format/pe/pe_section.c:251]: add a check if `bin->num_sections +1 == 0`

Comment (ret2libc) [reply librz/bin/format/pe/pe_section.c:251]: I think it can't ever be, because `num_sections` is initialized with `	bin->num_sections = bin->nt_headers->file_header.NumberOfSections;` in `bin_pe_init_sections` and `NumberOfSections` is a ut16, while `num_sections` is a int. Thus there will never be the value `0xffffffff` in there.

**Comment by wargio** [comment]
> I haven't as this is likely not a very common scenario and it can probably be hidden with some table magic command. Also, it would require me to pass the env variable down into the PE plugin (that's where the filtering was done), so for now I don't think it's worth the effort.

not really. just when printing in core.

**Comment by XVilka** [comment]
> > I haven't as this is likely not a very common scenario and it can probably be hidden with some table magic command. Also, it would require me to pass the env variable down into the PE plugin (that's where the filtering was done), so for now I don't think it's worth the effort.
> 
> not really. just when printing in core.

Agree, that would be a viable solution.

**Comment by ret2libc** [comment]
I think that can be avoided for now, I'm not sure how useful that would be or if it would break other use cases for other file formats.

**Comment by wargio** [comment]
i guess we can have more table examples on how to do this without implementing it.

**Comment by XVilka** [comment]
LGTM to merge then

**Review by wargio — APPROVED** [review]
