### PR TITLE
Split very large basic blocks

### LINKED ISSUE #5086: Unexpected scrolling behavior in file containing mostly 0
**Environment information**
* Operating System: Linux
* Cutter version: 2.3.4
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: raw binary

**Describe the bug**

Trying to scroll up while view is positioned near the end of 200kB file, causes it to jump up to ~0xfa00 .

Scrubbing through the file using navbar also result in occasional stuttering. Sometimes up to few second UI freezing.

This only happens for the attached file which contains mostly 0x00, and little bit of 0x90  at the start. Repeating the same using file that contains only 0x90 doesn't produce such problems. 

**To Reproduce**

1. Open attached file
2. Drag the mouse back and forth across navbar. Observe occasional freeze.
3. Jump to roughly the end of file using navbar
4. scroll up using scrollwheel
5. observe that the view jumped up from ~0x2f000 to 0xfa00 . 

Tested on x86_64. If you are testing on an arm computer might be necessary to manually switch architecture in advanced settings while opening the file.

**Expected behavior**

View scrolls up by ~3 lines for each wheel tick. All navigation is smooth just like with file containing only 0x90.

**Screenshots**

**Additional context**

I am guessing some kind of edge case in disassembler or rizin interpreting disassembler output.  Or maybe some kind of logic repeatedly attempting to skip all the 0x00 for some reason.

### PR DESCRIPTION
**Pull request by karliss**
Ensure instruction offset fits in uint16.

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [x] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed). rizinorg/book#140

**Detailed description**

Basic block instruction offsets are stored in 16bit integers. Artificially split basic blocks during analysis to ensure the technical limit isn't broken.

Slightly changes meaning of `analysis.bb.maxsize`. Previously setting it to:
* <64k split blocks into disconnected chunks
* 64k-256k split into chunks but incorrectly stored instruction positions causing all kind of bugs
* \>256k does nothing since MAX_FCN_SIZE check would return error first

Previous default was 512k making it useless. After the changes split blocks are connected using jump field.

Introduce `analysis.fnc_max_size` as a replacement limit in case when executable contains something weird or the function analysis fails to stop for some other reason. Currently using `ninstr` since it was the beast easily available size metric. Linear size could potentially be much bigger (especially if function does something like hot/cold code split), and the other size function iterates through all the basic blocks to add up size.

Rest of the changes

read_ahead limit in fcn.c `bytes_read = sizeof(buf);` . The old limit was purely a sanity check so no need to do exact limit when reading bytes for instruction. Reading as much max potential instruction size ensures that it reads whole intstruction and doesn't try to parse partial instruction bytes near the boundary of block split.

canalysis.c next refactoring,  the code adding new item was inside

```
do {
    if (fcnlen == fcnlen == RZ_ANALYSIS_RET_END) {
       ...
        addNext(...);
    }
} while (fcnlen != RZ_ANALYSIS_RET_END);
```
So it would never have more than single entry. Simplify by replacing custom dynamic array code with single variable for single address. That and rest of changes in `__core_analysis_fcn` is from when I attempted to get it working the way `analysis.bb.maxsize` resumed analysis previously.

**Test plan**

Beside the the added test.

* open ~300K file containing 0 (as raw x64 binary)
* `aaa`
* `s 0x23000`
* visual mode
* try to move up

**Closing issues**

Closes #5086

### CODE REVIEW

**Comment by karliss** [comment]
Need to rethink this. As this makes other existing limits ineffective.

**Comment by karliss** [comment]
Summary of situation:

`analysis.bb.maxsize` by default is set to 512k way above 2^16 .
MAX_FCN_SIZE is hardcoded to 256*1024 making `analysis.bb.maxsize` useless, it causes functiona analysis to stop with error when single basic block size exceeds it. 

Clamping `analysis.bb.maxsize` to UINT16_MAX or lower causes it to split larger basic blocks, so it wasn't necessary for me to introduce additional mechanism for it.  But it makes `MAX_FCN_SIZE` ineffective and there doesn't seem to be any other limiter (beside binary size) preventing  function growing infinitely when analysis goes wrong or attempting to analyze memory which isn't actually a proper function.

My proposal is:
* clamp analysis.bb.maxsize to ~UINT16_MAX - 256. Due to implementation details it needs to be at least single instruction under the real limit.
* Introduce a new config variable `analysis.max_fcn_size` and replace existing MAX_FCN_SIZE check with it. Use it to check the total function size not basic block size. Use whatever function size metric is conveniently available. Seems like it might need to be `RzAnalysisFunction::ninstr` since it's the only one directly tracked and stored, size in bytes is dynamically calculated from basic blocks that's not something you want to repeatedly recalculate during analysis of each instruction.
* In the basic block merge functions add check for bb.maxsize

**Comment by karliss** [comment]
Small correction existing analysis.bb.max_size logic splits the block, but doesn't chain them.

File: librz/arch/block.c [hunk 1]
```diff
@@ -336,6 +336,10 @@ RZ_API bool rz_analysis_block_merge(RzAnalysisBlock *a, RzAnalysisBlock *b) {
 		}
 	}
 
+	if (a->size + b->size > a->analysis->opt.bb_max_size) {
+		return false;
```
Comment (Rot127) [inline librz/arch/block.c:340]: Print an error message.

File: librz/core/canalysis.c [hunk 2]
```diff
@@ -1005,25 +984,19 @@ static int __core_analysis_fcn(RzCore *core, ut64 at, ut64 from, int reftype, in
...
+			if (has_next) {
+				ut64 newaddr = rz_analysis_function_max_addr(fcn);
+				RzIOMap *map = rz_io_map_get(core->io, newaddr);
+				if (!map || (map && (map->perm & RZ_PERM_X))) {
+					next = newaddr;
+					rz_core_analysis_fcn(core, next, next, 0, depth - 1);
 				}
-				free(next);
+			}
+			if (core->analysis->cur && core->analysis->cur->arch && !strcmp(core->analysis->cur->arch, "x86")) {
```
Comment (Rot127) [inline librz/core/canalysis.c:995]:
```suggestion
			if (core->analysis->cur && core->analysis->cur->arch && RZ_STR_EQ(core->analysis->cur->arch, "x86")) {
```

File: test/integration/test_analysis_fcn.c [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+		if (block->jump != UT64_MAX) {
+			mu_assert_eq(block->jump, block->addr + block->size, "blocks aren't chained");
+			block = rz_analysis_fcn_bbget_at(core->analysis, f, block->jump);
+		} else {
+			block = NULL;
+		}
+	}
+	mu_assert_eq(end, 240000, "Blocks don't cover whole function");
+
+	rz_core_free(core);
```
Comment (Rot127) [inline test/integration/test_analysis_fcn.c:45]: `f` and `cf` need to be freed?

**Review by Rot127 — APPROVED** [review]
I just have those nitpicks. Although, I struggle to understand the changes in the context of the functions they are in. Because they are so much spaghetti.
But your argument makes sense and since it is tested it lgtm.

Please be aware that we will re-implement the whole analysis loop in the next few months (based on RzIL). So don't spent too much brain power on it in the future.

File: librz/core/canalysis.c (hunk 2 above)
Comment (karliss) [reply librz/core/canalysis.c:995]: I Haven't touched that line of code except moving it few lines up inside the big `if (fcn)`

File: test/integration/test_analysis_fcn.c (hunk 3 above)
Comment (karliss) [reply test/integration/test_analysis_fcn.c:45]: Are the functions not owned by analysis and transitively the core?

 And I would hope that the file is by the io system although I am less sure about that one.    From a quick glance none of the io unit tests do any manual freeing of individual files beside the io subsystem itself.

Comment (Rot127) [reply test/integration/test_analysis_fcn.c:45]: Didn't check, but it's just optimal. If a dev builds and tests with ASAN, running these integration tests becomes annoying if they leak, because they spam the terminal output.

File: librz/arch/block.c (hunk 1 above)
Comment (karliss) [reply librz/arch/block.c:340]: There are 3 other error conditions already none of which print any error messages.  I am hesitant to adding error message in place like this unless it's an optional debug log printed at highest verbosity level, that's what the error return code is for. Deep low level functions are not the place for any user output. Especially in situation like this where failure is normal, requirements for merging two blocks weren't met nothing bad happens function remains in a valid state. As long as caller doesn't ignore return code and doesn't act with assumption that merging always succeeds it should be fine. Looking at how it's used by automerge, it just tries merging more or less everything which could potentially be merged leaving verification of finer requirements to `rz_analysis_block_merge`,  printing an error here would likely result in large amount of useless noise.

Comment (wargio) [reply librz/arch/block.c:340]: no need to put an error here. this is called recursively.

File: librz/arch/fcn.c [hunk 4]
```diff
@@ -698,11 +694,12 @@ static RzAnalysisBBEndCause run_basic_block_analysis(RzAnalysisTaskItem *item, R
 		}
 	}
 	if ((maxlen - (addrbytes * idx)) > MAX_SCAN_SIZE) {
+		// XXX idx is always 0 here, and maxlen comes from amalysis.bb.maxsize. This makes no sense.
 		RZ_LOG_DEBUG("Skipping large memory region during basic block analysis.\n");
 		maxlen = 0;
 	}
```
Comment (wargio) [inline librz/arch/fcn.c:700]: this looks like remnants of old code. maybe it could be deleted?

**Review by wargio — APPROVED** [review]

File: librz/arch/fcn.c (hunk 4 above)
Comment (karliss) [reply librz/arch/fcn.c:700]: As pointed out by Rot127 whole thing is going to be rewritten soon. And there are definitely  a bunch of weird stuff. Can't fix it all in this PR. 

The focus this time was on parts that have direct negative effect by producing bad instruction positions which breaks navigation.

**Comment by karliss** [comment]
What's the state of this? Anything left to do? Can be merged to dev?

**Review by Rot127 — APPROVED** [review]
Go ahead I'd say. @wargio @notxvilka

File: test/integration/test_analysis_fcn.c [hunk 5]
```diff
@@ -0,0 +1,54 @@
+// SPDX-FileCopyrightText: 2024 KarlisS <karlis3p70l1ij@gmail.com>
```
Comment (notxvilka) [inline test/integration/test_analysis_fcn.c]: 2025

**Review by notxvilka — APPROVED** [review]
LGTM with one small nitpick

**Review by notxvilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]
