### PR TITLE
Fix quit confirmation during debuggin session.

### LINKED ISSUE #3818: Asking for quit confirmation twice when debugging remotely
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArcoLinux, kernel 6.4.12
| File format of the file you reverse (mandatory)      | Remote qemu debugging (`gdb://localhost:1234`)
| Architecture/bits of the file (mandatory)            | 32 bits
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.1 @ linux-x86-64, commit: d9af48b56e47afadd1a77e74c12099efd5e8e19e

### Expected behavior

When debugging remotely with `scr.confirmquit` enabled, ask to confirm exit and then ask if the user wants to kill the process (or vice versa).

### Actual behavior

After executing `q`, it asks the user if he wants to quit twice:
```
[0x0000f15b]> q
Do you want to quit? (Y/n) y
Do you want to kill the process? (Y/n) y
Do you want to quit? (Y/n) y
```

### Steps to reproduce the behavior
After running `rizin -d dbg://localhost:1234`:

>**Edit:** Asciinema removed the video, just see output in [actual behavior](#actual-behavior).

I was debugging a 32 bit kernel in qemu (`qemu -s`).

### PR DESCRIPTION
**Pull request by vanshjangir**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

In `librz/main/rizin.c` , when in debugger session the program ask for quit confirmation independent of `scr.confirmquit` true or false. 
So the quit confirmation when in debug session is removed, and the code for debug session is pasted below the general quit confirm message, Now if user wants to quit then only program will ask to kill the process otherwise the program will just continue

**Test plan**

...

**Closing issues**

Closes #3818

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
What if we move the `if (debug)` code below the 
```
			if (rz_config_get_i(r->config, "scr.confirmquit")) {
				if (!rz_cons_yesno('n', "Do you want to quit? (Y/n)")) {
					continue;
				}
			}
```
? 

It would need some adjustments, but I think it would make more sense. There's some duplicated code here.

File: librz/main/rizin.c [hunk 1]
```diff
@@ -1495,6 +1477,21 @@ RZ_API int rz_main_rizin(int argc, const char **argv) {
...
+			if (debug) {
+				if (no_question_debug) {
+					if (rz_config_get_i(r->config, "dbg.exitkills") && y_kill_debug) {
+						rz_debug_kill(r->dbg, r->dbg->pid, r->dbg->tid, 9); // KILL
+					}
+				} else {
+					if (rz_config_get_i(r->config, "dbg.exitkills") &&
+						rz_debug_can_kill(r->dbg) &&
+						rz_cons_yesno('y', "Do you want to kill the process? (Y/n)")) {
+						rz_config_set_i(r->config, "scr.confirmquit", false);
```
Comment (ret2libc) [inline librz/main/rizin.c]: this is not needed anymore?!

**Review by ret2libc — CHANGES_REQUESTED** [review]

File: librz/main/rizin.c (hunk 1 above)
Comment (vanshjangir) [reply librz/main/rizin.c]: I understood, here is my approach

What I have done here is 
if `scr.confirmquit` is true, then the program will ask for quit confirmation and continue if n is returned.
if y is returned then the program will ask for to kill the process is and will not continue to the loop in any case.

**Review by ret2libc — APPROVED** [review]

File: librz/main/rizin.c [hunk 2]
```diff
@@ -1495,6 +1477,20 @@ RZ_API int rz_main_rizin(int argc, const char **argv) {
...
 				}
 			}
+
+			if (debug) {
+				if (no_question_debug) {
+					if (rz_config_get_i(r->config, "dbg.exitkills") && y_kill_debug) {
+						rz_debug_kill(r->dbg, r->dbg->pid, r->dbg->tid, 9); // KILL
+					}
+				} else {
+					if (rz_config_get_i(r->config, "dbg.exitkills") &&
```
Comment (wargio) [inline librz/main/rizin.c]: merge this.

**Comment by 8dcc** [comment]
(Closes #3818)

File: librz/main/rizin.c (hunk 2 above)
Comment (ret2libc) [reply librz/main/rizin.c]: what do you mean @wargio ?

**Comment by ret2libc** [comment]
IMO the PR is in good shape. @wargio ?

File: librz/main/rizin.c (hunk 2 above)
Comment (wargio) [reply librz/main/rizin.c]: just make this `else` an `else if` directly and avoid that double indentation.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
Thank you <3
