### PR TITLE
X86 Fix bad immediate operand value

### LINKED ISSUE #5279: x86 aoj -> opex.operands[].value Negative Imm with latest Rizin
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.9.0 @ linux-x86-64 commit: c009cb739ca4fd289e634c2bea432d1e7bcd3676

### Expected behavior

Disassembling the instruction at `0x1a68871c073` of the binary using `pd` should correctly disassemble the instruction and provide the immediate `0xd6`.

```
[0x1a68871c073]> pd
            0x1a68871c073      mov   byte [rsp+0x28], 0xd6
```

### Actual behavior

In our tools, we want to obtain an object representation of the instruction, so we use the `aoj` command to disassemble it. Although the string representation of the instruction remains correct, the value under the `opex.operands[1].value` property is negative: It's `-42` (`0xffffffffffffffd6`) instead of `0xd6`.

```json
    {
        "opcode": "mov byte [rsp+0x28], 0xd6",
        "disasm": "mov byte [rsp+0x28], 0xd6",
        (...)
        "sign": false,
        "opex": {
            "operands": [
                {
                    "size": 1,
                    "rw": 2,
                    "type": "mem",
                    "segment": "ss",
                    "base": "rsp",
                    "scale": 0,
                    "disp": 40
                },
                {
                    "size": 1,
                    "rw": 1,
                    "type": "imm",
                    "value": -42  <--
                }
            ],
       (...)
```

### Steps to reproduce the behavior

[binary on vt](https://www.virustotal.com/gui/file/013a92ea6df2995a8cdef11527dc4bda0b4a2e8dc642f7461c1cedb42297cadb)

```
s 0x1a68871c073
aoj
```

### Possible Fix

After investigation, we found that Zydis considers the `mov` instruction as having a signed immediate. Therefore, it casts the `u8` to `i8` and then promotes it to `i64`, thus extending the sign. I asked the author, and this is considered normal behavior.

Image

The problem is that Rizin does not consider the immediate size in the `get_imm_reg_value` function, so it retrieves the full 64-bit representation of the value, including the sign extension.

```C
static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);

	if (bitness == 32) {
		value &= 0xFFFFFFFF;
	} else if (bitness == 16) {
		value &= 0xFFFF;
	}
	return value;
}
```
I quickly fixed this behavior by adding a line that masks the value according to the immediate size.

```C
static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);

	value &= (1 << zydeop->size * 8) - 1; // <--

	if (bitness == 32) {
		value &= 0xFFFFFFFF;
	} else if (bitness == 16) {
		value &= 0xFFFF;
	}
	return value;
}
```

### PR DESCRIPTION
**Pull request by cyril-t-f**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Zydis, by default, generates signed immediate values that are sign-extended to 64 bits. This behavior results in incorrect immediate values from Rizin as it doesn't take into account the operand size. This pull request resolves this issue by ensuring Rizin correctly accounts for the operand size.

**Test plan**

```
e io.va=true
e asm.arch=x86
e asm.bits=64
wx "c6442428d6"
aoj
```

For each mov instruction, `opex.operands[1].value` must match the disassembly and not be negative.

```
[0x00000000]> aoj~{[0].opex.operands[1].value}
214
```

**Closing issues**

closes #5279 

https://github.com/rizinorg/rizin-testbins/pull/198

### CODE REVIEW

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 1]
```diff
@@ -55,6 +55,7 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
+	value &= (1 << zydeop->size * 8) - 1;
```
Comment (wargio) [inline librz/arch/p/analysis/analysis_x86_zydis.c]: isn't this doing the same as the if below? maybe we could remove the ifs below?

**Review by notxvilka — CHANGES_REQUESTED** [review]
Instead of using 25 bytes long test binary, you could just use `wx ...` command to write them directly in the test.
Also, you could use `~{}` "json grep" to check only one partricular field:
```
[0x100000964]> aoj~{[0].opex}
{"operands":[{"type":"reg","value":"x28"},{"type":"reg","value":"x27"},{"type":"mem","base":"sp","disp":-96}],"writeback":true}
[0x100000964]> aoj~{[0].opex.operands}
[{"type":"reg","value":"x28"},{"type":"reg","value":"x27"},{"type":"mem","base":"sp","disp":-96}]
[0x100000964]> aoj~{[0].opex.operands[0]}
{"type":"reg","value":"x28"}
[0x100000964]> aoj~{[0].opex.operands[2].disp}
-96
[0x100000964]>
```

File: librz/arch/p/analysis/analysis_x86_zydis.c (hunk 1 above)
Comment (cyril-t-f) [reply librz/arch/p/analysis/analysis_x86_zydis.c]: Well as far as i'm aware of the codebase (very little) I think yes, at least logic-wise. The bitness information should already be encoded in the operand structure, unless there's a scenario where it would be out of sync with how the decoder is initialized.

Let me know if you want me to do more modifications.

Comment (wargio) [reply librz/arch/p/analysis/analysis_x86_zydis.c]: just remove the if after your changes.

**Review by wargio — APPROVED** [review]

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 2]
```diff
@@ -55,12 +55,7 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
-	if (bitness == 32) {
-		value &= 0xFFFFFFFF;
-	} else if (bitness == 16) {
-		value &= 0xFFFF;
-	}
-	return value;
+	return value & ((1 << zydeop->size * 8) - 1);
```
Comment (wargio) [inline librz/arch/p/analysis/analysis_x86_zydis.c]:
```suggestion
	return value & ((1ull << zydeop->size * 8) - 1);
```

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 3]
```diff
@@ -55,12 +55,7 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
-	if (bitness == 32) {
-		value &= 0xFFFFFFFF;
-	} else if (bitness == 16) {
-		value &= 0xFFFF;
-	}
-	return value;
+	return value & ((1ull << zydeop->size * 8) - 1);
```
Comment (notxvilka) [inline librz/arch/p/analysis/analysis_x86_zydis.c]:
```
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
../librz/arch/p/analysis/analysis_x86_zydis.c:58:24: runtime error: shift exponent 64 is too large for 64-bit type 'long long unsigned int'
    #0 0x7fa4ff61ad9a in get_imm_reg_value ../librz/arch/p/analysis/analysis_x86_zydis.c:58
    #1 0x7fa4ff61ad9a in op0_memimmhandle ../librz/arch/p/analysis/analysis_x86_zydis.c:2098
    #2 0x7fa4ffebe03a in anop ../librz/arch/p/analysis/analysis_x86_zydis.c:2462
    #3 0x7fa4ffedf1b5 in analyze_op ../librz/arch/p/analysis/analysis_x86_zydis.c:3238
    #4 0x7fa50000f79b in rz_analysis_op ../librz/arch/op.c:128
    #5 0x55e079f28939 in setup_rop_hitasm ../test/unit/test_rop.c:26
    #6 0x55e079f2af39 in setup_rop_hitlist ../test/unit/test_rop.c:54
    #7 0x55e079f2af39 in test_rz_direct_solver ../test/unit/test_rop.c:128
    #8 0x55e079f2bd09 in all_tests ../test/unit/test_rop.c:144
    #9 0x55e079f2871e in main ../test/unit/test_rop.c:148
    #10 0x7fa4fb42a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
    #11 0x7fa4fb42a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
    #12 0x55e079f28784 in _start (/home/runner/work/rizin/rizin/build/test/unit/test_rop+0x5784) (BuildId: 94e8c6b33db4ea6c3cec45e9ac2057976c3ebee3)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../librz/arch/p/analysis/analysis_x86_zydis.c:58:24 in 
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```
See CI logs for full error: https://github.com/rizinorg/rizin/actions/runs/16470966436/job/46560577809?pr=5285#step:15:162

**Review by notxvilka — CHANGES_REQUESTED** [review]
Please fix tests

File: librz/arch/p/analysis/analysis_x86_zydis.c (hunk 3 above)
Comment (wargio) [reply librz/arch/p/analysis/analysis_x86_zydis.c]: Maybe add an if checking the size. If 64 bit, don't do anything

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 4]
```diff
@@ -55,10 +55,9 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
-	if (bitness == 32) {
-		value &= 0xFFFFFFFF;
-	} else if (bitness == 16) {
-		value &= 0xFFFF;
+	ut32 exponent = zydeop->size * 8;
+	if (exponent < 64){
+		value &= ((1ull << exponent) - 1);
```
Comment (notxvilka) [inline librz/arch/p/analysis/analysis_x86_zydis.c:60]: Some tests are failing:
```
[XX]   2 secs C:\projects\rizin\test\db\cmd\cmd_ahi ahi 10 and 10u imm (x86_64)
ANSICON=1 RZ_NOPLUGINS=1 C:\projects\rizin\rizin-vs2022_64-v0.9.0\bin\rizin.exe -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -a x86 -b 64 -qc 'e asm.bytes=false
wa "cmp eax, -1"
pd 1
ahi 10
pd 1
ahi 10u
pd 1
echo
ah-
wa "cmp rax, -1"
pd 1
ahi 10
pd 1
ahi 10u
pd 1
' =
-- stdout
--- expected
+++ actual
@@ -1,6 +1,6 @@
-            0x00000000      cmp   eax, 0xffffffff
-            0x00000000      cmp   eax, -1
-            0x00000000      cmp   eax, 4294967295
+            0x00000000      cmp   eax, 0xffffffff                      ; -1
+            0x00000000      cmp   eax, -1                              ; 0xffffffff ; -1
+            0x00000000      cmp   eax, 4294967295                      ; 0xffffffff ; -1
 
             0x00000000      cmp   rax, 0xffffffffffffffff
             0x00000000      cmp   rax, -1
```
https://ci.appveyor.com/project/rizinorg/rizin/builds/52456434/job/h6qvjupiei0gpwgg
https://github.com/rizinorg/rizin/actions/runs/16496963177/job/46657031282?pr=5285

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 5]
```diff
@@ -55,10 +55,9 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
-	if (bitness == 32) {
-		value &= 0xFFFFFFFF;
-	} else if (bitness == 16) {
-		value &= 0xFFFF;
+	ut32 exponent = zydeop->size * 8;
+	if (exponent < 64){
```
Comment (notxvilka) [inline librz/arch/p/analysis/analysis_x86_zydis.c]: Missing space:
```
Formatting [821/1875] librz/arch/p/analysis/analysis_x86_zydis.c
librz/arch/p/analysis/analysis_x86_zydis.c:59:20: error: code should be clang-formatted [-Wclang-format-violations]
        if (exponent < 64){
                          ^
```

**Review by notxvilka — CHANGES_REQUESTED** [review]
Just couple minor things left

File: librz/arch/p/analysis/analysis_x86_zydis.c [hunk 6]
```diff
@@ -55,7 +55,11 @@ struct Getarg {
 
 static inline ut64 get_imm_reg_value(ZydisDecodedOperand *zydeop, ut64 addr, ut64 op_size, int bitness) {
 	ut64 value = (zydeop->imm.is_relative ? (zydeop->imm.value.s + addr + op_size) : zydeop->imm.value.u);
-	return value & ((1ull << zydeop->size * 8) - 1);
+	ut32 exponent = zydeop->size * 8;
+	if (exponent < 64){
```
Comment (wargio) [inline librz/arch/p/analysis/analysis_x86_zydis.c]:
```suggestion
	if (exponent < 64) {
```

File: librz/arch/p/analysis/analysis_x86_zydis.c (hunk 4 above)
Comment (cyril-t-f) [reply librz/arch/p/analysis/analysis_x86_zydis.c:60]: I fixed tests directly related to the issue. @notxvilka Please confirm if you want me to fix the other ones reported by AppVeyor as well.

Comment (notxvilka) [reply librz/arch/p/analysis/analysis_x86_zydis.c:60]: @cyril-t-f it's not related to AppVeyor in particular - they fail also on other CI jobs as well: https://github.com/rizinorg/rizin/actions/runs/16519843399/job/46737036803?pr=5285

**Review by wargio — APPROVED** [review]
