### PR TITLE
Fixes `aav` search in mips and others

### LINKED ISSUE #4942: aav breaks output of MIPS
When you run `aav` (also via `-A` or `aaa`) on some mips binaries, it breaks the output.

```
$ rizin -qc 'aa; pdf @ main' test/bins/elf/analysis/mipsbe-ip
[.... outputs normal ....]
│     ╎│    0x00402c18      lui   a1, 0x42
│     ╎│    0x00402c1c      move  a0, a2
│     ╎│    0x00402c20      sw    a2, (var_2ch)
│     ╎│    0x00402c24      jalr  t9
│     ╎│    0x00402c28      addiu a1, a1, -0xfc4                       ; argv
│     ╎│    0x00402c2c      lw    gp, (var_40h)
│     ╎│    0x00402c30      lw    a2, (var_2ch)
│     └───< 0x00402c34      beqz  v0, 0x402a2c
│      │    0x00402c38      nop
│      │    0x00402c3c      lw    v0, -0x7efc(gp)                      ; [0x4351e4:4]=0
│      │    0x00402c40      lui   a1, 0x42
│      │    0x00402c44      lw    t9, -sym.imp.fprintf(gp)             ; [0x4352dc:4]=0x41e940 sym.imp.fprintf
│      │    0x00402c48      addiu a1, a1, -0xfbc                       ; argv
│      │    0x00402c4c      lw    a0, 0(v0)
│      │    ; CODE XREF from main @ 0x402c7c
│      │┌─> 0x00402c50      jalr  t9
│      │╎   0x00402c54      nop
│      │╎   0x00402c58      lw    gp, (var_40h)
│      │╎   0x00402c5c      lw    t9, -sym.imp.exit(gp)                ; [0x4351a4:4]=0x41ebb0 sym.imp.exit
│      │╎   0x00402c60      jalr  t9
│      │╎   0x00402c64      addiu a0, zero, -1                         ; argc
│      └──> 0x00402c68      lw    v0, -0x7efc(gp)                      ; [0x4351e4:4]=0
│       ╎   0x00402c6c      lui   a1, 0x42
│       ╎   0x00402c70      lw    a2, 0(s0)
│       ╎   0x00402c74      lw    a0, 0(v0)
│       ╎   0x00402c78      lw    t9, -sym.imp.fprintf(gp)             ; [0x4352dc:4]=0x41e940 sym.imp.fprintf
└       └─< 0x00402c7c      b     0x402c50
```
When running aav (via full analysis)
```
$ rizin -A -qc 'pdf @ main' test/bins/elf/analysis/mipsbe-ip
[.... outputs full of invalid ....]
│     ╎│    0x00402c18      lui   a1, 0x42
│     ╎│    0x00402c1c      .dword 0x00c02021
│     ╎│    0x00402c1e      addi  at, at, -0x505a
│     ╎│    0x00402c22      invalid
│     ╎│    0x00402c26      sdc2  9, 0x24a5(zero)
│     ╎│    0x00402c2a      scd   gp, -0x7044(at)
│     ╎│    0x00402c2e      invalid
│     ╎│    0x00402c32      invalid
│      │    0x00402c36      sd    sp, 0(k1)
│      │    0x00402c3a      srl   s1, zero, 0x1e
│      │    0x00402c3e      lb    a0, 0x3c05(t0)
│      │    0x00402c42      invalid
│      │    0x00402c46      lb    gp, 0x24a5(t7)
│      │    0x00402c4a      scd   a0, -0x73bc(v0)
│      │    0x00402c4e  ~   invalid
│      │    ; CODE XREF from main @ 0x402c7c
│      │┌─> 0x00402c50      jalr  t9
│      │╎   0x00402c54      nop
│      │╎   0x00402c58      lw    gp, (var_40h)
│      │╎   0x00402c5c      lw    t9, -sym.imp.exit(gp)                ; [0x4351a4:4]=0x41ebb0 sym.imp.exit
│      │╎   0x00402c60      jalr  t9
│      │╎   0x00402c64      addiu a0, zero, -1                         ; argc
│      └──> 0x00402c68      lw    v0, -0x7efc(gp)                      ; [0x4351e4:4]=0
│       ╎   0x00402c6c      lui   a1, 0x42
│       ╎   0x00402c70      lw    a2, 0(s0)
│       ╎   0x00402c74      lw    a0, 0(v0)
│       ╎   0x00402c78      lw    t9, -sym.imp.fprintf(gp)             ; [0x4352dc:4]=0x41e940 sym.imp.fprintf
└       └─< 0x00402c7c      b     0x402c50
```

### PR DESCRIPTION
**Pull request by tushar3q34**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [X] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Issue :
- `aav` checks for value pointers. The way is by checking whether a dword has value within the range of search
- Issue arrives when checking for instructions like `lui a1, 0x42` followed by `move a0, a2`. Since alignment in mips is 2 bytes, while searching `3C050042 00C02025`, it also checks for `0042 00C0` which happens to lie in the search range
- Hence it is identified as  unknown`.dword` and by default, the increment is by min op size (2 in this case, rather than 4 byte instruction) which messes up the alignment while disassembling, causing a lot of `invalid` instructions

Fix :
Whenever a match is not found, check whether an instruction lies there. If it does, increase the search pointer (variable `i`) accordingly so as to not check for overlapping instructions

Some tests had additional `UNKNOWN XREFS` that get resolved
Swift binary had extra `.qword` which get resolved

**Test plan**

Added a test that checks for `pdf @ main` after `aav`

**Closing issues**

closes #4942

### CODE REVIEW

File: librz/core/canalysis.c [hunk 1]
```diff
@@ -2953,6 +2953,8 @@ static inline bool aligns(ut64 addr, size_t align) {
 	return align > 0 && addr % align == 0;
 }
 
+static void _CbInRangeAav(RzCore *core, ut64 from, ut64 to, int vsize, void *user);
```
Comment (wargio) [inline librz/core/canalysis.c]: Use snake case

**Review by wargio — CHANGES_REQUESTED** [review]

**Review by notxvilka — APPROVED** [review]
Nice finding! I wonder why only few tests caught this change though.

**Comment by tushar3q34** [comment]
> I wonder why only few tests caught this change though.

It is very rare for two particular instructions to be present adjacent such that they give a value that just so happens to be in the search space. That's why the only testcases which were affected were either mips (2 byte align) or swift x86 (1 byte align) since they were having a lot of extra search checks.

**Comment by wargio** [comment]
tbh, i would probably just add a check and forbid this from mips.

**Comment by tushar3q34** [comment]
> tbh, i would probably just add a check and forbid this from mips.

Sorry I was not able to understand this. Can you please elaborate on the changes I need to make?

**Comment by wargio** [comment]
Sorry I meant that I would forbid invokation of aav under mips arch, but it is OK. Ignore what I wrote

File: librz/core/canalysis.c [hunk 2]
```diff
@@ -3011,6 +3013,7 @@ RZ_API int rz_core_search_value_in_range(RzCore *core, RzInterval search_itv, ut
 		if (size <= vsize) {
 			break;
 		}
+		RzAnalysisOp *op = rz_analysis_op_new();
```
Comment (Rot127) [inline librz/core/canalysis.c:3016]: Free op below before the `goto beach;` statements.

**Review by Rot127 — CHANGES_REQUESTED** [review]
Nice one!

**Review by notxvilka — APPROVED** [review]
