### PR TITLE
Fixes for the `WinKD` debug plugin

### LINKED ISSUE #2560: Microsoft Windows 10 Pro for Workstations (Version 10.0.19044 Build 19044) missing KD profile.
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| Host OS/arch/bits (mandatory)                             | Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220417.1ffba9f
| Guest OS being kernel debugged | Microsoft Windows 10 Pro for Workstations (Version `10.0.19044 Build 19044`)
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | amd64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 3cbde10260fbf8a7a380217c97acd264ac5f3102, build: 1980-01-01__00:00:00

### Expected behavior
The rizin client should attach to the remote kd target VM through the serial device and drop into an interactive debugger session

### Actual behavior
The guest VM is frozen once rizin first connects, but no debugger session is initialized

### Steps to reproduce
1. I amended my Qemu virtual machine configuration by adding the needed serial port device for rizin to connect to:
```xml
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <!-- ... -->
  <qemu:commandline>
    <qemu:arg value="-chardev"/>
    <qemu:arg value="socket,id=serial0,path=/tmp/kd.pipe,nowait,server"/>
    <qemu:arg value="-serial"/>
    <qemu:arg value="chardev:serial0"/>
    <qemu:arg value="-object"/>
    <!-- ... -->
  </qemu:commandline>
</domain>
```
2. Then I enabled kernel debugging over serial in the guest, restarted, and attached rizin:
```console
./build/binrz/rizin/rizin -a x86 -b 64 -D winkd winkd:///tmp/kd.pipe
Opened pipe /tmp/kd.pipe with fd 0x3
ERROR: Could not find a suitable profile for the target OS
ERROR: Could not find a suitable profile for the target OS
[0x00000000]>
Do you want to quit? (Y/n) y
Detaching...
```

### PR DESCRIPTION
**Pull request by GustavoLCR**
# PLEASE DONT SQUASH
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Fixed data race 2da9f9dfedb1abfa50f5601474948ca52b796dfc
* Fixed not being able to write 34b645828f808525eba53416b5f03d706709b7ec
* Fixed breakpoints/stepping weirdness 8a889a8a1a633f2402d215526f74daf9d7fc8920 462d902e6e787b39e5b5245b2ad58ea9ffa0c886 72158cd2d3b91f006221f840b095e2e713cbd5d2
* Fixed protocol implementation bugs 0f563a65953e8cdae243b369b16729fee9ac4607 c00b530d205afcb281f98f462e478be9408168d5 cb624f56a4da6b92a3dda09082d083f463733250 a863fc3e7b66fc17b9989bb2ef28510489163219
* Refactoring 8ed37a84df0fa553637ba21990f06f27cd177484 e5621a869b269a61b5b2527d3819f8b89c46450e 9409c2f190738189243cc030a64c9618deceffc7 1fca54c0b21ad6e0356f700944bc85aa84c83f58
* Fix crashes 4c5544b9b29e7d3f8a129436ad02d81d94d566c5
* Fix kernel modules not being read regression 2a3bbcf341e37ef964fc82f83ba2a8315de8db4a
* Automatically create profile from PDB if it doesn't exist 6c6b6d0bc87d897dd96fd4ab3e6aa59e874f8056 0726e0484c043ad5dc556534972eb19ec733dc0b a0bdde48adcbfa9c19f723b89bd6321afa5c9bd7
* Add profiles 59e6b32e4db309b71d58c2dbf95bbef583d562e6

**Test plan**

Tested manually

**Closing issues**

Closes #2560

### CODE REVIEW

File: librz/debug/p/debug_winkd.c [hunk 1]
```diff
@@ -89,13 +116,61 @@ static int rz_debug_winkd_attach(RzDebug *dbg, int pid) {
...
+	char *exepath, *pdbpath;
+	if (!winkd_download_module_and_pdb(mod,
+		    dbg->corebind.cfgGet(dbg->corebind.core, "pdb.server"),
+		    dbg->corebind.cfgGet(dbg->corebind.core, "pdb.symstore"),
+		    &exepath, &pdbpath)) {
+		RZ_LOG_ERROR("Failed to download module and pdb\n");
+		rz_list_free(modules);
+		return false;
+	}
+	dbg->corebind.cmdf(dbg->corebind.core, "e bin.baddr=0x%" PFMT64x "", mod->addr, pdbpath);
```
Comment (XVilka) [inline librz/debug/p/debug_winkd.c]: Can be this converted to the function? Like previously used `dbg->corebind.cfgGet()` but `dbg->corebind.cfgSet()`?

File: librz/debug/p/debug_winkd.c [hunk 2]
```diff
@@ -89,13 +116,61 @@ static int rz_debug_winkd_attach(RzDebug *dbg, int pid) {
...
+	dbg->corebind.cmdf(dbg->corebind.core, "idp %s", pdbpath);
```
Comment (XVilka) [inline librz/debug/p/debug_winkd.c]: Please add a `TODO: Convert to the API use`.

File: librz/debug/p/debug_winkd.c [hunk 3]
```diff
@@ -268,7 +338,7 @@ RzDebugPlugin rz_debug_plugin_winkd = {
 	.arch = "x86",
 	.bits = RZ_SYS_BITS_32 | RZ_SYS_BITS_64,
 	.init = &rz_debug_winkd_init,
-	.step = &rz_debug_winkd_step,
+	// TODO: .step = &rz_debug_winkd_step,
```
Comment (XVilka) [inline librz/debug/p/debug_winkd.c:346]: Is it unfinished in this PR?

File: librz/main/rizin.c [hunk 4]
```diff
@@ -993,8 +993,9 @@ RZ_API int rz_main_rizin(int argc, const char **argv) {
 					if (!haveRarunProfile) {
 						pfile = strdup(argv[opt.ind++]);
 					}
-					perms = RZ_PERM_RX; // XXX. should work with rw too
-					debug = 2;
+					if (strcmp(debugbackend, "winkd")) {
```
Comment (XVilka) [inline librz/main/rizin.c:996]: I recommend to add the comment that this doesn't work with WinKD and why, if possible.

Comment (XVilka) [inline librz/main/rizin.c:997]: I recommend adding the comment that this doesn't work with WinKD and why, if possible.

File: subprojects/rzwinkd/iob_net.c [hunk 5]
```diff
@@ -407,14 +421,14 @@ bool _verifyhmac(iobnet_t *obj) {
...
-	if (!rz_msg_digest_update(md, obj->buf, obj->size - KDNET_HMAC_SIZE) ||
+	if (!rz_msg_digest_update(md, obj->read_buf, obj->read_size - KDNET_HMAC_SIZE) ||
 		!rz_msg_digest_final(md) ||
 		!(digest = rz_msg_digest_get_result(md, "sha256", NULL))) {
 		rz_msg_digest_free(md);
 		return false;
 	}
 
-	bool result = !memcmp(digest, obj->buf + obj->size - KDNET_HMAC_SIZE, KDNET_HMAC_SIZE);
+	bool result = !memcmp(digest, obj->read_buf + obj->read_size - KDNET_HMAC_SIZE, KDNET_HMAC_SIZE);
```
Comment (XVilka) [inline subprojects/rzwinkd/iob_net.c:431]: I didn't follow the code here deeply, but please be sure to check the validity of the size for the `memcp()` to avoid OOB

**Review by XVilka — CHANGES_REQUESTED** [review]
I am mostly concerned about the removed `step()` method. Is this indented? Does it remove the capability to step?

**Comment by XVilka** [comment]
```
FAILED: subprojects/rzwinkd/librzwinkd.a.p/winkd.c.o 
gcc -Isubprojects/rzwinkd/librzwinkd.a.p -Isubprojects/rzwinkd -I../subprojects/rzwinkd -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -Isubprojects/sdb -I../subprojects/sdb -Isubprojects/sdb/src -I../subprojects/sdb/src -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O2 -g -Werror=sizeof-pointer-memaccess -fvisibility=hidden -DASAN=1 -DRZ_ASSERT_STDOUT=1 -Wno-cpp -fPIC -MD -MQ subprojects/rzwinkd/librzwinkd.a.p/winkd.c.o -MF subprojects/rzwinkd/librzwinkd.a.p/winkd.c.o.d -o subprojects/rzwinkd/librzwinkd.a.p/winkd.c.o -c ../subprojects/rzwinkd/winkd.c
../subprojects/rzwinkd/winkd.c: In function ‘winkd_wait_packet’:
../subprojects/rzwinkd/winkd.c:298:19: error: pointer targets in initialization of ‘char *’ from ‘uint8_t *’ {aka ‘unsigned char *’} differ in signedness [-Werror=pointer-sign]
  298 |      char *path = pkt->data + pkt->length - stc->load_symbols.pathsize;
      |                   ^~~
In file included from ../librz/include/rz_util/rz_assert.h:4,
                 from ../librz/include/rz_vector.h:5,
                 from ../librz/include/rz_util/rz_event.h:12,
                 from ../librz/include/rz_util.h:28,
                 from ../subprojects/rzwinkd/winkd.c:8:
../subprojects/rzwinkd/winkd.c:310:17: error: too many arguments for format [-Werror=format-extra-args]
  310 |     RZ_LOG_WARN("Unknown state change packet type: 0x" PFMT32x "\n", (ut32)pkt->type);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../librz/include/rz_util/rz_log.h:56:34: note: in definition of macro ‘RZ_LOG_WARN’
   56 |  __LINE__, RZ_LOGLVL_WARN, NULL, fmtstr, ##__VA_ARGS__);
      |                                  ^~~~~~
../subprojects/rzwinkd/winkd.c:322:17: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint32_t’ {aka ‘unsigned int’} [-Werror=format=]
  322 |    RZ_LOG_DEBUG("  ret: %016" PFMT64x "\n", rr->ret);
      |                 ^~~~~~~~~~~~~               ~~~~~~~
      |                                               |
      |                                               uint32_t {aka unsigned int}
../librz/include/rz_util/rz_log.h:45:35: note: in definition of macro ‘RZ_LOG_DEBUG’
   45 |  __LINE__, RZ_LOGLVL_DEBUG, NULL, fmtstr, ##__VA_ARGS__);
      |                                   ^~~~~~
In file included from ../librz/include/rz_util.h:7,
                 from ../subprojects/rzwinkd/winkd.c:8:
../librz/include/rz_types.h:372:20: note: format string is defined here
  372 | #define PFMT64x "llx"
cc1: all warnings being treated as errors
```

**Comment by wargio** [comment]
Let me ask this here, @GustavoLCR where do you get these values or how to generate them? https://github.com/rizinorg/rizin/blob/dev/subprojects/rzwinkd/profiles.h#L177

**Comment by XVilka** [comment]
@wargio see https://github.com/rizinorg/rizin/issues/2560#issuecomment-1109618907

File: librz/debug/p/debug_winkd.c (hunk 1 above)
Comment (p371jah) [reply librz/debug/p/debug_winkd.c]: `pdbpath` is redundant here, isn't it?

File: librz/debug/p/debug_winkd.c (hunk 2 above)
Comment (p371jah) [reply librz/debug/p/debug_winkd.c]: Is it safe to pass `pdbpath` in `%s` here? Wouldn't it be better to use `\"%s\"`?

Comment (wargio) [reply librz/debug/p/debug_winkd.c]: use the quotes

Comment (pelijah) [reply librz/debug/p/debug_winkd.c:167]: Hmm but I guess it still be possible to craft path with extra quotes.

File: subprojects/rzwinkd/iob_net.c (hunk 5 above)
Comment (GustavoLCR) [reply subprojects/rzwinkd/iob_net.c:431]: added check in https://github.com/rizinorg/rizin/blob/d352906cd3b00080d58199f55dc983f1e4349dd0/subprojects/rzwinkd/iob_net.c#L444

File: librz/debug/p/debug_winkd.c (hunk 3 above)
Comment (GustavoLCR) [reply librz/debug/p/debug_winkd.c:346]: It didnt work before because it was never implemented, it just returned true. Now rizin will manually do the work to simulate a step.

**Comment by XVilka** [comment]
```
../librz/core/core.c: In function ‘cfgseti’:
../librz/core/core.c:354:9: error: returning ‘RzConfigNode *’ {aka ‘struct rz_config_node_t *’} from a function with return type ‘int’ makes integer from pointer without a cast [-Werror=int-conversion]
  354 |  return rz_config_set_i(core->config, k, v);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../librz/core/core.c: In function ‘cfgset’:
../librz/core/core.c:358:9: error: returning ‘RzConfigNode *’ {aka ‘struct rz_config_node_t *’} from a function with incompatible return type ‘const char *’ [-Werror=incompatible-pointer-types]
  358 |  return rz_config_set(core->config, k, v);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

File: librz/debug/p/debug_dmp.c [hunk 6]
```diff
@@ -136,7 +136,8 @@ static bool rz_debug_dmp_init(RzDebug *dbg, void **user) {
 		const char *symstore = dbg->corebind.cfgGet(dbg->corebind.core, "pdb.symstore");
 		char *pdbpath, *exepath;
 		if (winkd_download_module_and_pdb(&mod, server, symstore, &exepath, &pdbpath)) {
-			dbg->corebind.cmdf(dbg->corebind.core, "idp %s", pdbpath);
+			// TODO: Convert to API call
+			dbg->corebind.cmdf(dbg->corebind.core, "idp \"%s\"", pdbpath);
```
Comment (ret2libc) [inline librz/debug/p/debug_dmp.c:140]: Just use `rz_core_bin_pdb_load` , should work.

File: librz/debug/p/debug_winkd.c (hunk 3 above)
Comment (ret2libc) [reply librz/debug/p/debug_winkd.c:346]: What does it mean that "it manually do the work"? Where? Why was not implemented in `rz_debug_winkd_step`?

File: librz/debug/p/debug_dmp.c (hunk 6 above)
Comment (XVilka) [reply librz/debug/p/debug_dmp.c:140]: @ret2libc it's a function from `librz/core/` but this is the `librz/debug/`

Comment (ret2libc) [reply librz/debug/p/debug_dmp.c:140]: oh sorry my bad...

**Review by XVilka — APPROVED** [review]
LGTM.

File: librz/debug/p/debug_winkd.c (hunk 3 above)
Comment (GustavoLCR) [reply librz/debug/p/debug_winkd.c:346]: @ret2libc It means that rizin will use software stepping (`dbg.swstep`), manually disassemble the current instruction and put a breakpoint in the next instruction to be executed, following jump/rets.
