### PR TITLE
Travis CI compilation error fixes

### LINKED ISSUE #4613: Travis CI native debugger compilation error
We didn't caught them earlier because Travis CI service wasn't running yesterday.

Linux on System Z (S390):
```
usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_gcore':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:793: undefined reference to `linux_generate_corefile'
/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_native_bp':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:740: undefined reference to `arm64_hwbp_add'
/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:741: undefined reference to `arm64_hwbp_del'
collect2: error: ld returned 1 exit status
````
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625811858

Linux on PPC:
```
[1878/2275] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o
In file included from ../librz/debug/p/native/linux_arm64.c:14,
                 from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux/linux_coredump.h:63: warning: "RZ_DEBUG_REG_T" redefined
   63 | #define RZ_DEBUG_REG_T struct user_regs_struct
      | 
In file included from ../librz/debug/p/native/linux_arm64.c:12,
                from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux/linux_debug.h:132: note: this is the location of the previous definition
  132 | #define RZ_DEBUG_REG_T struct powerpc_regs_t
      | 
In file included from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux_arm64.c: In function ‘rz_debug_native_bp’:
../librz/debug/p/native/linux_arm64.c:740:6: warning: implicit declaration of function ‘arm64_hwbp_add’ [-Wimplicit-function-declaration]
  740 |    ? arm64_hwbp_add((RzDebug *)bp->user, bp, b)
      |      ^~~~~~~~~~~~~~
../librz/debug/p/native/linux_arm64.c:741:6: warning: implicit declaration of function ‘arm64_hwbp_del’ [-Wimplicit-function-declaration]
  741 |    : arm64_hwbp_del((RzDebug *)bp->user, bp, b);
      |      ^~~~~~~~~~~~~~
At top level:
../librz/debug/p/native/linux_arm64.c:658:13: warning: ‘ll_arm32_hwbp_set’ defined but not used [-Wunused-function]
  658 | static bool ll_arm32_hwbp_set(pid_t pid, ut64 addr, int size, int wp, int type) {
      |             ^~~~~~~~~~~~~~~~~
[1879/2275] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_native_procfs.c.o
[1880/2275] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_debug.c.o
../librz/debug/p/native/linux/linux_debug.c: In function ‘print_fpu’:
../librz/debug/p/native/linux/linux_debug.c:1146:2: warning: #warning print_fpu not implemented for this platform [-Wcpp]
 1146 | #warning print_fpu not implemented for this platform
      |  ^~~~~~~
../librz/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
../librz/debug/p/native/linux/linux_debug.c:1151:7: warning: variable ‘showfpu’ set but not used [-Wunused-but-set-variable]
 1151 |  bool showfpu = false;
      |       ^~~~~~~
../librz/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_write’:
../librz/debug/p/native/linux/linux_debug.c:1354:55: warning: passing argument 4 of ‘rz_debug_ptrace’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 1354 |   int ret = rz_debug_ptrace(dbg, PTRACE_SETREGS, pid, buf, NULL);
      |                                                       ^~~
In file included from ../librz/debug/p/native/linux/linux_debug.c:6:
../librz/include/rz_debug.h:611:96: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  611 | static inline long rz_debug_ptrace(RzDebug *dbg, rz_ptrace_request_t request, pid_t pid, void *addr, rz_ptrace_data_t data) {
      |                                                                                          ~~~~~~^~~~
At top level:
../librz/debug/p/native/linux/linux_debug.c:1057:13: warning: ‘print_fpu’ defined but not used [-Wunused-function]
 1057 | static void print_fpu(void *f) {
      |             ^~~~~~~~~
[1881/2275] Compiling C object subprojects/rizin-shell-parser/libshell_parser.a.p/src_scanner.c.o
[1882/2275] Linking target librz/debug/librz_debug.so.0.8.0
FAILED: librz/debug/librz_debug.so.0.8.0 

gcc  -o librz/debug/librz_debug.so.0.8.0 librz/debug/librz_debug.so.0.8.0.p/ddesc.c.o librz/debug/librz_debug.so.0.8.0.p/debug.c.o librz/debug/librz_debug.so.0.8.0.p/dreg.c.o librz/debug/librz_debug.so.0.8.0.p/desil.c.o librz/debug/librz_debug.so.0.8.0.p/dmap.c.o librz/debug/librz_debug.so.0.8.0.p/pid.c.o librz/debug/librz_debug.so.0.8.0.p/plugin.c.o librz/debug/librz_debug.so.0.8.0.p/dsession.c.o librz/debug/librz_debug.so.0.8.0.p/dsignal.c.o librz/debug/librz_debug.so.0.8.0.p/serialize_debug.c.o librz/debug/librz_debug.so.0.8.0.p/snap.c.o librz/debug/librz_debug.so.0.8.0.p/trace.c.o librz/debug/librz_debug.so.0.8.0.p/p_bfvm.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_windows.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bf.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bochs.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_dmp.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_gdb.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_io.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_null.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_rap.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_qnx.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_debug.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_coredump.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_procfs.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,librz_debug.so.0.8 -DRZ_ASSERT_STDOUT=1 '-Wl,-rpath,$ORIGIN/../util:$ORIGIN/../cons:$ORIGIN/../socket:$ORIGIN/../hash:$ORIGIN/../crypto:$ORIGIN/../io:$ORIGIN/../bin:$ORIGIN/../demangler:$ORIGIN/../magic:$ORIGIN/../syscall:$ORIGIN/../type:$ORIGIN/../reg:$ORIGIN/../bp:$ORIGIN/../egg:$ORIGIN/../arch:$ORIGIN/../search:$ORIGIN/../config:$ORIGIN/../flag:$ORIGIN/../diff:$ORIGIN/../il' -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/util -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/cons -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/socket -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/hash -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/crypto -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/io -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/bin -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/demangler -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/magic -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/syscall -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/type -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/reg -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/bp -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/egg -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/arch -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/search -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/config -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/flag -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/diff -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/il -Wl,--start-group subprojects/rzgdb/librzgdb.a librz/util/librz_util.so.0.8.0 librz/cons/librz_cons.so.0.8.0 librz/socket/librz_socket.so.0.8.0 subprojects/rzwinkd/librzwinkd.a librz/hash/librz_hash.so.0.8.0 librz/crypto/librz_crypto.so.0.8.0 librz/io/librz_io.so.0.8.0 librz/bin/librz_bin.so.0.8.0 librz/reg/librz_reg.so.0.8.0 librz/bp/librz_bp.so.0.8.0 librz/syscall/librz_syscall.so.0.8.0 librz/egg/librz_egg.so.0.8.0 librz/arch/librz_arch.so.0.8.0 librz/type/librz_type.so.0.8.0 subprojects/rzqnx/librzqnx.a -Wl,--end-group
/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_gcore':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:793: undefined reference to `linux_generate_corefile'
/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_native_bp':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:741: undefined reference to `arm64_hwbp_del'
/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:740: undefined reference to `arm64_hwbp_add'
collect2: error: ld returned 1 exit status
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625811857

Linux on ARM64:
```
../librz/debug/p/native/linux/linux_debug.c: In function ‘print_fpu’:
../librz/debug/p/native/linux/linux_debug.c:1146:2: warning: #warning print_fpu not implemented for this platform [-Wcpp]
 1146 | #warning print_fpu not implemented for this platform
      |  ^~~~~~~
../librz/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
../librz/debug/p/native/linux/linux_debug.c:1250:2: warning: #warning getfpregs not implemented for this platform [-Wcpp]
 1250 | #warning getfpregs not implemented for this platform
      |  ^~~~~~~
../librz/debug/p/native/linux/linux_debug.c:1151:7: warning: variable ‘showfpu’ set but not used [-Wunused-but-set-variable]
 1151 |  bool showfpu = false;
      |       ^~~~~~~
At top level:
../librz/debug/p/native/linux/linux_debug.c:1057:13: warning: ‘print_fpu’ defined but not used [-Wunused-function]
 1057 | static void print_fpu(void *f) {
      |             ^~~~~~~~~
[1880/2275] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o
In file included from ../librz/debug/p/native/linux_arm64.c:14,
                 from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux/linux_coredump.h:63: warning: "RZ_DEBUG_REG_T" redefined
   63 | #define RZ_DEBUG_REG_T struct user_regs_struct
      | 
In file included from ../librz/debug/p/native/linux_arm64.c:12,
                 from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux/linux_debug.h:106: note: this is the location of the previous definition
  106 | #define RZ_DEBUG_REG_T struct user_pt_regs
      | 
In file included from ../librz/debug/p/debug_native.c:46:
../librz/debug/p/native/linux_arm64.c: In function ‘rz_debug_native_bp’:
../librz/debug/p/native/linux_arm64.c:740:6: warning: implicit declaration of function ‘arm64_hwbp_add’ [-Wimplicit-function-declaration]
  740 |    ? arm64_hwbp_add((RzDebug *)bp->user, bp, b)
      |      ^~~~~~~~~~~~~~
../librz/debug/p/native/linux_arm64.c:741:6: warning: implicit declaration of function ‘arm64_hwbp_del’ [-Wimplicit-function-declaration]
  741 |    : arm64_hwbp_del((RzDebug *)bp->user, bp, b);
      |      ^~~~~~~~~~~~~~
At top level:
../librz/debug/p/native/linux_arm64.c:658:13: warning: ‘ll_arm32_hwbp_set’ defined but not used [-Wunused-function]
  658 | static bool ll_arm32_hwbp_set(pid_t pid, ut64 addr, int size, int wp, int type) {
      |             ^~~~~~~~~~~~~~~~~
[1881/2275] Linking target librz/debug/librz_debug.so.0.8.0
FAILED: librz/debug/librz_debug.so.0.8.0 

gcc  -o librz/debug/librz_debug.so.0.8.0 librz/debug/librz_debug.so.0.8.0.p/ddesc.c.o librz/debug/librz_debug.so.0.8.0.p/debug.c.o librz/debug/librz_debug.so.0.8.0.p/dreg.c.o librz/debug/librz_debug.so.0.8.0.p/desil.c.o librz/debug/librz_debug.so.0.8.0.p/dmap.c.o librz/debug/librz_debug.so.0.8.0.p/pid.c.o librz/debug/librz_debug.so.0.8.0.p/plugin.c.o librz/debug/librz_debug.so.0.8.0.p/dsession.c.o librz/debug/librz_debug.so.0.8.0.p/dsignal.c.o librz/debug/librz_debug.so.0.8.0.p/serialize_debug.c.o librz/debug/librz_debug.so.0.8.0.p/snap.c.o librz/debug/librz_debug.so.0.8.0.p/trace.c.o librz/debug/librz_debug.so.0.8.0.p/p_bfvm.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_windows.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bf.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bochs.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_dmp.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_gdb.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_io.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_null.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_rap.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_qnx.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_debug.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_coredump.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_procfs.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,librz_debug.so.0.8 -DRZ_ASSERT_STDOUT=1 '-Wl,-rpath,$ORIGIN/../util:$ORIGIN/../cons:$ORIGIN/../socket:$ORIGIN/../hash:$ORIGIN/../crypto:$ORIGIN/../io:$ORIGIN/../bin:$ORIGIN/../demangler:$ORIGIN/../magic:$ORIGIN/../syscall:$ORIGIN/../type:$ORIGIN/../reg:$ORIGIN/../bp:$ORIGIN/../egg:$ORIGIN/../arch:$ORIGIN/../search:$ORIGIN/../config:$ORIGIN/../flag:$ORIGIN/../diff:$ORIGIN/../il' -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/util -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/cons -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/socket -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/hash -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/crypto -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/io -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/bin -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/demangler -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/magic -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/syscall -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/type -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/reg -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/bp -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/egg -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/arch -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/search -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/config -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/flag -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/diff -Wl,-rpath-link,/home/travis/build/rizinorg/rizin/build/librz/il -Wl,--start-group subprojects/rzgdb/librzgdb.a librz/util/librz_util.so.0.8.0 librz/cons/librz_cons.so.0.8.0 librz/socket/librz_socket.so.0.8.0 subprojects/rzwinkd/librzwinkd.a librz/hash/librz_hash.so.0.8.0 librz/crypto/librz_crypto.so.0.8.0 librz/io/librz_io.so.0.8.0 librz/bin/librz_bin.so.0.8.0 librz/reg/librz_reg.so.0.8.0 librz/bp/librz_bp.so.0.8.0 librz/syscall/librz_syscall.so.0.8.0 librz/egg/librz_egg.so.0.8.0 librz/arch/librz_arch.so.0.8.0 librz/type/librz_type.so.0.8.0 subprojects/rzqnx/librzqnx.a -Wl,--end-group

/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_gcore':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:793: undefined reference to `linux_generate_corefile'
/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_native_bp':
/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:740: undefined reference to `arm64_hwbp_add'
/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:741: undefined reference to `arm64_hwbp_del'

collect2: error: ld returned 1 exit status
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625811859

cc @tushar3q34 @wargio 

It also breaks Docker builds:
```
[1883/2273] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_debug.c.o
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c: In function ‘print_fpu’:
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c:1146:2: warning: #warning print_fpu not implemented for this platform [-Wcpp]
#40 2458.1  #warning print_fpu not implemented for this platform
#40 2458.1   ^~~~~~~
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c:1250:2: warning: #warning getfpregs not implemented for this platform [-Wcpp]
#40 2458.1  #warning getfpregs not implemented for this platform
#40 2458.1   ^~~~~~~
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c:1151:7: warning: variable ‘showfpu’ set but not used [-Wunused-but-set-variable]
#40 2458.1   bool showfpu = false;
#40 2458.1        ^~~~~~~
#40 2458.1 At top level:
#40 2458.1 ../***/librz/debug/p/native/linux/linux_debug.c:1057:13: warning: ‘print_fpu’ defined but not used [-Wunused-function]
#40 2458.1  static void print_fpu(void *f) {
#40 2458.1              ^~~~~~~~~
#40 2459.2 [1884/2273] Compiling C object librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o
#40 2459.2 In file included from ../***/librz/debug/p/native/linux_arm64.c:14,
#40 2459.2                  from ../***/librz/debug/p/debug_native.c:46:
#40 2459.2 ../***/librz/debug/p/native/linux/linux_coredump.h:63: warning: "RZ_DEBUG_REG_T" redefined
#40 2459.2  #define RZ_DEBUG_REG_T struct user_regs_struct
#40 2459.2  
#40 2459.2 In file included from ../***/librz/debug/p/native/linux_arm64.c:12,
#40 2459.2                  from ../***/librz/debug/p/debug_native.c:46:
#40 2459.2 ../***/librz/debug/p/native/linux/linux_debug.h:106: note: this is the location of the previous definition
#40 2459.2  #define RZ_DEBUG_REG_T struct user_pt_regs
#40 2459.2  
#40 2459.2 In file included from ../***/librz/debug/p/debug_native.c:46:
#40 2459.2 ../***/librz/debug/p/native/linux_arm64.c: In function ‘rz_debug_native_bp’:
#40 2459.2 ../***/librz/debug/p/native/linux_arm64.c:740:6: warning: implicit declaration of function ‘arm64_hwbp_add’; did you mean ‘rz_bv_add’? [-Wimplicit-function-declaration]
#40 2459.2     ? arm64_hwbp_add((RzDebug *)bp->user, bp, b)
#40 2459.2       ^~~~~~~~~~~~~~
#40 2459.2       rz_bv_add
#40 2459.2 ../***/librz/debug/p/native/linux_arm64.c:741:6: warning: implicit declaration of function ‘arm64_hwbp_del’; did you mean ‘rz_bp_del’? [-Wimplicit-function-declaration]
#40 2459.2     : arm64_hwbp_del((RzDebug *)bp->user, bp, b);
#40 2459.2       ^~~~~~~~~~~~~~
#40 2459.2       rz_bp_del
#40 2459.2 At top level:
#40 2459.2 ../***/librz/debug/p/native/linux_arm64.c:658:13: warning: ‘ll_arm32_hwbp_set’ defined but not used [-Wunused-function]
#40 2459.2  static bool ll_arm32_hwbp_set(pid_t pid, ut64 addr, int size, int wp, int type) {
#40 2459.2              ^~~~~~~~~~~~~~~~~
#40 2460.6 [1885/2273] Linking target librz/debug/librz_debug.so.0.8.0
#40 2460.6 FAILED: librz/debug/librz_debug.so.0.8.0 
#40 2460.6 cc  -o librz/debug/librz_debug.so.0.8.0 librz/debug/librz_debug.so.0.8.0.p/ddesc.c.o librz/debug/librz_debug.so.0.8.0.p/debug.c.o librz/debug/librz_debug.so.0.8.0.p/dreg.c.o librz/debug/librz_debug.so.0.8.0.p/desil.c.o librz/debug/librz_debug.so.0.8.0.p/dmap.c.o librz/debug/librz_debug.so.0.8.0.p/pid.c.o librz/debug/librz_debug.so.0.8.0.p/plugin.c.o librz/debug/librz_debug.so.0.8.0.p/dsession.c.o librz/debug/librz_debug.so.0.8.0.p/dsignal.c.o librz/debug/librz_debug.so.0.8.0.p/serialize_debug.c.o librz/debug/librz_debug.so.0.8.0.p/snap.c.o librz/debug/librz_debug.so.0.8.0.p/trace.c.o librz/debug/librz_debug.so.0.8.0.p/p_bfvm.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_windows.c.o librz/debug/librz_debug.so.0.8.0.p/p_common_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bf.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_bochs.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_dmp.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_gdb.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_io.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_null.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_rap.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_winkd.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_qnx.c.o librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_debug.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_linux_linux_coredump.c.o librz/debug/librz_debug.so.0.8.0.p/p_native_procfs.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,librz_debug.so.0.8 '-Wl,-rpath,$ORIGIN/../util:$ORIGIN/../cons:$ORIGIN/../socket:$ORIGIN/../hash:$ORIGIN/../crypto:$ORIGIN/../io:$ORIGIN/../bin:$ORIGIN/../demangler:$ORIGIN/../magic:$ORIGIN/../syscall:$ORIGIN/../type:$ORIGIN/../reg:$ORIGIN/../bp:$ORIGIN/../egg:$ORIGIN/../arch:$ORIGIN/../search:$ORIGIN/../config:$ORIGIN/../flag:$ORIGIN/../diff:$ORIGIN/../il' -Wl,-rpath-link,/tmp/build/librz/util -Wl,-rpath-link,/tmp/build/librz/cons -Wl,-rpath-link,/tmp/build/librz/socket -Wl,-rpath-link,/tmp/build/librz/hash -Wl,-rpath-link,/tmp/build/librz/crypto -Wl,-rpath-link,/tmp/build/librz/io -Wl,-rpath-link,/tmp/build/librz/bin -Wl,-rpath-link,/tmp/build/librz/demangler -Wl,-rpath-link,/tmp/build/librz/magic -Wl,-rpath-link,/tmp/build/librz/syscall -Wl,-rpath-link,/tmp/build/librz/type -Wl,-rpath-link,/tmp/build/librz/reg -Wl,-rpath-link,/tmp/build/librz/bp -Wl,-rpath-link,/tmp/build/librz/egg -Wl,-rpath-link,/tmp/build/librz/arch -Wl,-rpath-link,/tmp/build/librz/search -Wl,-rpath-link,/tmp/build/librz/config -Wl,-rpath-link,/tmp/build/librz/flag -Wl,-rpath-link,/tmp/build/librz/diff -Wl,-rpath-link,/tmp/build/librz/il -Wl,--start-group subprojects/rzgdb/librzgdb.a librz/util/librz_util.so.0.8.0 librz/cons/librz_cons.so.0.8.0 librz/socket/librz_socket.so.0.8.0 subprojects/rzwinkd/librzwinkd.a librz/hash/librz_hash.so.0.8.0 librz/crypto/librz_crypto.so.0.8.0 librz/io/librz_io.so.0.8.0 librz/bin/librz_bin.so.0.8.0 librz/reg/librz_reg.so.0.8.0 librz/bp/librz_bp.so.0.8.0 librz/syscall/librz_syscall.so.0.8.0 librz/egg/librz_egg.so.0.8.0 librz/arch/librz_arch.so.0.8.0 librz/type/librz_type.so.0.8.0 subprojects/rzqnx/librzqnx.a -Wl,--end-group
#40 2460.6 /usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_gcore':
#40 2460.6 /tmp/build/../***/librz/debug/p/native/linux_arm64.c:793: undefined reference to `linux_generate_corefile'
#40 2460.6 /usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_native_bp':
#40 2460.6 /tmp/build/../***/librz/debug/p/native/linux_arm64.c:740: undefined reference to `arm64_hwbp_add'
#40 2460.6 /usr/bin/ld: /tmp/build/../***/librz/debug/p/native/linux_arm64.c:741: undefined reference to `arm64_hwbp_del'
#40 2460.6 collect2: error: ld returned 1 exit status
#40 2462.3 [1886/2273] Compiling C object subprojects/***-shell-parser/libshell_parser.a.p/src_scanner.c.o
#40 2462.5 [1887/2273] Compiling C object librz/core/librz_core.so.0.8.0.p/analysis_objc.c.o
#40 2464.4 [1888/2273] Compiling C object librz/core/librz_core.so.0.8.0.p/analysis_tp.c.o
#40 2467.0 [1889/2273] Compiling C object subprojects/***-shell-parser/libshell_parser.a.p/src_parser.c.o
#40 2474.0 [1890/2273] Compiling C object librz/core/librz_core.so.0.8.0.p/agraph.c.o
#40 2474.0 ninja: build stopped: subcommand failed.
#40 2474.0 INFO: autodetecting backend as ninja
#40 2474.0 INFO: calculating backend command to run: /usr/bin/ninja -C /tmp/build
#40 ERROR: process "/bin/sh -c meson setup --prefix=/usr -Dinstall_sigdb=true /tmp/build && \tmeson compile -C /tmp/build && \tmeson install --destdir /tmp/***-install -C /tmp/build" did not complete successfully: exit code: 1
------
 > [linux/arm64 stage-0  8/15] RUN meson setup --prefix=/usr -Dinstall_sigdb=true /tmp/build && 	meson compile -C /tmp/build && 	meson install --destdir /tmp/***-install -C /tmp/build:
2460.6 /usr/bin/ld: /tmp/build/../***/librz/debug/p/native/linux_arm64.c:741: undefined reference to `arm64_hwbp_del'
2460.6 collect2: error: ld returned 1 exit status
```
See https://github.com/rizinorg/rizin/actions/runs/10706760347/job/29700429546#step:9:17440

### PR DESCRIPTION
**Pull request by tushar3q34**
# SQUASH ME

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

1. For Linux on System Z and PPC , added the code for unsupported architecture in `debug_native.c`
2. For Linux on ARM64, removed the unused ARM32 function `static bool ll_arm32_hwbp_set` which was causing error.

**Test plan**

**Closing issues**

closes #4613

### CODE REVIEW

**Comment by tushar3q34** [comment]
@XVilka @wargio Can you please check this PR for Travis CI ?

**Comment by Rot127** [comment]
@tushar3q34 Triggered the CI.

**Comment by XVilka** [comment]
```
/usr/bin/ld: librz/core/librz_core.so.0.8.0.p/linux_heap_glibc.c.o: in function `resolve_tcache_perthread_32':

/home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:953: undefined reference to `rz_debug_get_tls'

/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:957: undefined reference to `rz_debug_native_threads'

/usr/bin/ld: librz/core/librz_core.so.0.8.0.p/linux_heap_glibc64.c.o: in function `resolve_tcache_perthread_64':

/home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:953: undefined reference to `rz_debug_get_tls'

/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:957: undefined reference to `rz_debug_native_threads'

collect2: error: ld returned 1 exit status
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625835785
```
subprojects/tree-sitter-0.21.0/libtree_sitter.a -lrt -lm -Wl,--end-group

/usr/bin/ld: librz/core/librz_core.so.0.8.0.p/linux_heap_glibc.c.o: in function `resolve_tcache_perthread_32':

/home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:953: undefined reference to `rz_debug_get_tls'

/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:957: undefined reference to `rz_debug_native_threads'

/usr/bin/ld: librz/core/librz_core.so.0.8.0.p/linux_heap_glibc64.c.o: in function `resolve_tcache_perthread_64':

/home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:953: undefined reference to `rz_debug_get_tls'

/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/core/linux_heap_glibc.c:957: undefined reference to `rz_debug_native_threads'

collect2: error: ld returned 1 exit status
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625835786
```
librz_arch.so.0.8.0 librz/type/librz_type.so.0.8.0 subprojects/rzqnx/librzqnx.a -Wl,--end-group

/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_gcore':

/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:784: undefined reference to `linux_generate_corefile'

/usr/bin/ld: librz/debug/librz_debug.so.0.8.0.p/p_debug_native.c.o: in function `rz_debug_native_bp':

/home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:731: undefined reference to `arm64_hwbp_add'

/usr/bin/ld: /home/travis/build/rizinorg/rizin/build/../librz/debug/p/native/linux_arm64.c:732: undefined reference to `arm64_hwbp_del'

collect2: error: ld returned 1 exit status
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/625835787

**Comment by tushar3q34** [comment]
I observed that the architectures for linux running in Travis CI are different from `arm`,`arm64` and `x86_64`. Since I created only three files for linux `linux_arm64`, `linux_arm` and `linux_x86_64`, a lot of undefined references are happening.
In this commit, I tried to completely exclude the functions of `debug_native.c` but they are required even for these architectures.
So I will look at the previous version of the repo and create a new file handling miscellaneous architectures in linux and that should resolve this issue.

File: librz/debug/p/native/linux_arm64.c [hunk 1]
```diff
@@ -655,15 +655,6 @@ static int rz_debug_native_drx(RzDebug *dbg, int n, ut64 addr, int sz, int rwx,
 #define PTRACE_SETHBPREGS 30
 #endif
 
-static bool ll_arm32_hwbp_set(pid_t pid, ut64 addr, int size, int wp, int type) {
```
Comment (wargio) [inline librz/debug/p/native/linux_arm64.c:658]: ~~don't delete functions that are used.~~

Comment (wargio) [reply librz/debug/p/native/linux_arm64.c:658]: ah but this is for arm32 and the file is for arm64.

Comment (tushar3q34) [reply librz/debug/p/native/linux_arm64.c:658]: Yes that function was unused

Comment (wargio) [reply librz/debug/p/native/linux_arm64.c:658]: if needed i can test this also on my arm64 machine (the CI also has arm64)

Comment (tushar3q34) [reply librz/debug/p/native/linux_arm64.c:658]: Yeah it will be very helpful if you can tell me the error in arm64
For now, I've figured out how to resolve the other two and as for arm64, the function being there or not doesn't make any difference because it isn't being called infact it was not supposed to be there in the first place, I think I forgot to remove it while refactoring code for the previous PR.
But I don't exactly know the issue yet for arm64.

Comment (wargio) [reply librz/debug/p/native/linux_arm64.c:658]: check the ` Travis CI` output

Comment (wargio) [reply librz/debug/p/native/linux_arm64.c:658]: seems that `arm64_hwbp_add` and `arm64_hwbp_del` are not defined. i guess it's missing their declaration

Comment (tushar3q34) [reply librz/debug/p/native/linux_arm64.c:658]: arm64 build also gives this error : `/librz/debug/p/native/linux_arm64.c:784: undefined reference to linux_generate_corefile`
Function `linux_generate_corefile` is always defined when `__arm64__`,`__i386__`,`__arm__` or `__x86_64__` are present.
And `linux_arm64.c` is compiled when `__arm64__` or `__aarch64__` macros are present.
So for this build, `__arm64__` macro is absent but `__aarch64__` is present unlike other android and linux arm64 builds where both macros are present.
Also `PTRACE_GETREGSET` macro is probably not defined in this build because this macro defined declares and defines both `arm64_hwbp_add` and `arm64_hwbp_del` functions.
And it being undefined gives `arm64_hwbp_add` and `arm64_hwbp_del` undefined error.

**Comment by tushar3q34** [comment]
@wargio @XVilka Can you test this for Travis CI ?

File: librz/debug/p/native/linux_arm64.c (hunk 1 above)
Comment (wargio) [reply librz/debug/p/native/linux_arm64.c:658]: Tonight/tomorrow I will pull your changes and see

**Comment by XVilka** [comment]
Ignore the one of AppVeyor red jobs, it's unrelated new bug https://github.com/rizinorg/rizin/issues/4620

**Comment by tushar3q34** [comment]
> Ignore the one of AppVeyor red jobs, it's unrelated new bug #4620

I think for both of them, `debug_native.c` got compiled successfully.
Ok you meant one job in both of the AppVeyor checks right.
