### PR TITLE
Fix `Pic18 call instructions not detected`

### LINKED ISSUE #4520: Pic18 call instructions not detected
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Arch x86_64
| File format of the file you reverse (mandatory)      | .hex
| Architecture/bits of the file (mandatory)            | PIC18
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.3 @ linux-x86-64

### Expected behavior

Call instructions produce an xref to target instruction.  Call instructions are used to for detecting function starts

### Actual behavior

No xrefs for call instructions. Only one function found in the file.

### Steps to reproduce the behavior
-  https://github.com/rizinorg/rizin-testbins/blob/master/pic18c/FreeRTOS-pic18c.hex

### Additional Logs, screenshots, source code,  configuration dump, ...
image

Drag and drop zip archives containing the Additional info here, don't use external services or link.

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #4520

### CODE REVIEW

File: librz/arch/p/analysis/analysis_pic.c [hunk 1]
```diff
@@ -100,7 +100,7 @@ RzAnalysisPlugin rz_analysis_plugin_pic = {
 	.desc = "PIC analysis plugin",
 	.license = "LGPL3",
 	.arch = "pic",
-	.bits = 8,
+	.bits = 32,
```
Comment (XVilka) [inline librz/arch/p/analysis/analysis_pic.c]: Shouldn't it be multiple values? `.bits = 8 | 16 | 32`? See how it's done in `analysis_mips.c` Same for the asm plugin.

**Review by XVilka — CHANGES_REQUESTED** [review]

**Comment by XVilka** [comment]
You need also to update the tests from `cmd_list`

**Review by XVilka — APPROVED** [review]
