### PR TITLE
Fix #1276: invoke-virtual is now resolved

### LINKED ISSUE #1276: Missing method references in DEX
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04.2 LTS x64
| File format of the file you reverse (mandatory)      | APK
| Architecture/bits of the file (mandatory)            | Dalvik
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64 commit: ad5dd4831782b771a41547602c2cd0ac9657b162, build: 2021-07-06__19:45:082021-01-26__18:17:13

### Expected behavior
List all the function references of a given method.

### Actual behavior
Rizin missed some function references of the given method.

---

For instance, find the references of the following method.
```
Lahmyth/mine/king/ahmyth/ConnectionManager; sendReq ()V
```

When using `axff~CALL` command, Rizin gives the output. 
```
CALL 0x000411ce 0x00041934 method.static.public.Lahmyth_mine_king_ahmyth_IOSocket.Lahmyth_mine_king_ahmyth_IOSocket.method.getInstance__Lahmyth_mine_king_ahmyth_IOSocket
CALL 0x000411d6 0x0004194c method.public.Lahmyth_mine_king_ahmyth_IOSocket.Lahmyth_mine_king_ahmyth_IOSocket.method.getIoSocket__Lio_socket_client_Socket
CALL 0x000411ee 0x00040e40 method.constructor.Lahmyth_mine_king_ahmyth_ConnectionManager_1.Lahmyth_mine_king_ahmyth_ConnectionManager_1.method._init___V
CALL 0x00041206 0x00040e84 method.constructor.Lahmyth_mine_king_ahmyth_ConnectionManager_2.Lahmyth_mine_king_ahmyth_ConnectionManager_2.method._init___V
CALL 0x00041216 0x00044ce8 method.public.Lio_socket_client_Socket.Lio_socket_client_Socket.method.connect__Lio_socket_client_Socket
```

However, if using [Jadx](https://github.com/skylot/jadx) to view the bytecode, you would see some methods are not listed above.

One of these methods is as follows.
```
Lio/socket/client/Socket; on (Ljava/lang/String; Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter;
```

It is called in line 117, with a yellow background.

### Steps to reproduce the behavior
1. Download the [APK](https://github.com/rizinorg/rizin/files/6770399/Ahmyth.zip)
2. Unzip it and open it with Rizin
3. Type in the following commands
```
aaa
s `is~Lahmyth/mine/king/ahmyth/ConnectionManager.method.sendReq[1]`
axff~CALL
```

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix #1276 

```
$ ninja -C build-noasan/ && build-noasan/binrz/rizin/rizin -Qc "aaa ; s sym.Lahmyth_mine_king_ahmyth_ConnectionManager_.sendReq__V ; axff~CALL" apk:///tmp/Ahmyth.apk
CALL 0x000411ce 0x00041934 sym.Lahmyth_mine_king_ahmyth_IOSocket_.getInstance__Lahmyth_mine_king_ahmyth_IOSocket
CALL 0x000411d6 0x0004194c sym.Lahmyth_mine_king_ahmyth_IOSocket_.getIoSocket__Lio_socket_client_Socket
CALL 0x000411ee 0x00040e40 sym.Lahmyth_mine_king_ahmyth_ConnectionManager_1_._init___V
CALL 0x000411f4 0x000453a8 sym.Lio_socket_emitter_Emitter_.on_Ljava_lang_String_Lio_socket_emitter_Emitter_Listener__Lio_socket_emitter_Emitter
CALL 0x00041206 0x00040e84 sym.Lahmyth_mine_king_ahmyth_ConnectionManager_2_._init___V
CALL 0x0004120c 0x000453a8 sym.Lio_socket_emitter_Emitter_.on_Ljava_lang_String_Lio_socket_emitter_Emitter_Listener__Lio_socket_emitter_Emitter
CALL 0x00041216 0x00044ce8 sym.Lio_socket_client_Socket_.connect__Lio_socket_client_Socket
```

a test has been added

### CODE REVIEW

File: librz/core/cmd_analysis.c [hunk 1]
```diff
@@ -6042,6 +6042,73 @@ static void cmd_analysis_ucall_ref(RzCore *core, ut64 addr) {
 	}
 }
 
+static RzFlagItem *core_flag_get_at_as_ref_type(RzCore *core, RzAnalysisXRef *xrefi) {
+	RzListIter *iter;
+	RzFlagItem *item;
+	const RzFlagsAtOffset *flags_at = rz_flag_get_nearest_list(core->flags, xrefi->to, -1);
+#define is_not_in_space(f, i) (rz_flag_space_cur(f) && (i)->space != rz_flag_space_cur(f))
```
Comment (XVilka) [inline librz/core/cmd_analysis.c]: Please separate define from the code with the newlines. Also it might be sensible to swap these two lines to avoid the "flow interruption"

Comment (XVilka) [reply librz/core/cmd_analysis.c]: In fact, I think it's better to make this a small `inline` function instead of the define.

File: librz/flag/flag.c [hunk 2]
```diff
@@ -80,7 +80,7 @@ static void free_item_name(RzFlagItem *item) {
    dir == -1 -> result <= off
```
Comment (XVilka) [inline librz/flag/flag.c]: If you make this function `RZ_API`, please convert the comment to the Doxygen format as well.

Comment (XVilka) [reply librz/flag/flag.c]: I also suggest to rename `dir` to `direction` to be clearer about the purpose of it.

**Review by XVilka — CHANGES_REQUESTED** [review]

File: librz/core/cmd_analysis.c [hunk 3]
```diff
@@ -6042,6 +6042,73 @@ static void cmd_analysis_ucall_ref(RzCore *core, ut64 addr) {
 	}
 }
 
+static RzFlagItem *core_flag_get_at_as_ref_type(RzCore *core, RzAnalysisXRef *xrefi) {
```
Comment (ret2libc) [inline librz/core/cmd_analysis.c]: What do you want to do exactly with this function? Is it something like `rz_flag_get_by_spaces` ?

File: librz/include/rz_flag.h [hunk 4]
```diff
@@ -100,6 +100,7 @@ RZ_API RzFlagItem *rz_flag_get(RzFlag *f, const char *name);
 RZ_API RzFlagItem *rz_flag_get_i(RzFlag *f, ut64 off);
 RZ_API RzFlagItem *rz_flag_get_by_spaces(RzFlag *f, ut64 off, ...);
 RZ_API RzFlagItem *rz_flag_get_at(RzFlag *f, ut64 off, bool closest);
+RZ_API RzFlagsAtOffset *rz_flag_get_nearest_list(RzFlag *f, ut64 off, int dir);
```
Comment (ret2libc) [inline librz/include/rz_flag.h]: I think this function should not be made an RZ_API... This `RzFlagsAtOffset` is just an internal detail.

Comment (ret2libc) [reply librz/include/rz_flag.h]: Use one of the available functions or create a new one that makes sense from the API point of view, but IMO we should avoid exporting this.

File: librz/core/cmd_analysis.c (hunk 3 above)
Comment (wargio) [reply librz/core/cmd_analysis.c]: actually, it is. maybe i should just replace that with the proper one.

File: librz/core/cmd_analysis.c (hunk 1 above)
Comment (wargio) [reply librz/core/cmd_analysis.c]: i am changing this

**Review by ret2libc — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
