### PR TITLE
Fix unregistered comiss type

### LINKED ISSUE #3524: ucomiss type is null
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | 2.2.1-HEAD-f4be9a8 rizin 0.5.2 @ windows-x86-64 commit: e2646b53b0f1aba8202f98b22d345ae73ad0e35f

### Expected behavior
ucomiss type is not 'null'

### Actual behavior
image

### Steps to reproduce the behavior
try `pdfj`
any program which have `ucomiss`  the type in json is 'null'

### PR DESCRIPTION
**Pull request by dvertx**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes #3524
...

### CODE REVIEW

File: librz/include/rz_analysis.h [hunk 1]
```diff
@@ -336,6 +336,7 @@ typedef enum {
 	RZ_ANALYSIS_OP_TYPE_CPL = 45, /* complement */
 	RZ_ANALYSIS_OP_TYPE_CRYPTO = 46,
 	RZ_ANALYSIS_OP_TYPE_SYNC = 47,
+	RZ_ANALYSIS_OP_TYPE_COMISS = 48,
```
Comment (wargio) [inline librz/include/rz_analysis.h]: This type probably should be SIMD

File: librz/analysis/p/analysis_x86_cs.c [hunk 2]
```diff
@@ -742,6 +742,13 @@ static void anop_esil(RzAnalysis *a, RzAnalysisOp *op, ut64 addr, const ut8 *buf
 				dst, width, src, width, dst);
 		}
 		break;
+	// comiss
+	case X86_INS_COMISS:
+	case X86_INS_UCOMISS:
+	case X86_INS_VCOMISS:
+	case X86_INS_VUCOMISS:
+		op->type = RZ_ANALYSIS_OP_TYPE_COMISS;
```
Comment (wargio) [inline librz/analysis/p/analysis_x86_cs.c]: this should probably be `RZ_ANALYSIS_OP_TYPE_SIMD | RZ_ANALYSIS_OP_TYPE_CMP`

File: librz/include/rz_analysis.h (hunk 1 above)
Comment (wargio) [reply librz/include/rz_analysis.h]: like `RZ_ANALYSIS_OP_TYPE_SIMD = 0x04000000,`

File: librz/analysis/p/analysis_x86_cs.c (hunk 2 above)
Comment (dvertx) [reply librz/analysis/p/analysis_x86_cs.c]: You're right, since ucomiss instruction is used to compare floating point values, we should give it 
RZ_ANALYSIS_OP_TYPE_SIMD = 0x04000000.  And this RZ_ANALYSIS_OP_TYPE_SIMD | RZ_ANALYSIS_OP_TYPE_CMP too. Let me change them

Comment (dvertx) [reply librz/analysis/p/analysis_x86_cs.c]: Done

**Review by XVilka — APPROVED** [review]

**Review by wargio — CHANGES_REQUESTED** [review]
Please update the `RZ_ANALYSIS_OP_TYPE_MASK` value also.

**Comment by dvertx** [comment]
> Please update the `RZ_ANALYSIS_OP_TYPE_MASK` value also.

Into what? 0x80ffffff?

**Review by wargio — APPROVED** [review]
