### PR TITLE
Fix tests on s390x (Big endian)

### LINKED ISSUE #6159: Fix Luac plugin on big endian machines
Totally 265 broken tests:
```
[XX] 00h00m00s127ms db/asm/luac_5.2_0 <asm> settable 0 -1 2
-- <asm> settable 0 -1 2 <--> 0a800080
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-0a800080
+8000800a
-- disasm exit status: 0
-- asm exit status: 0
[XX] 00h00m00s132ms db/asm/luac_5.2_0 <asm> sub 2 2 1
-- <asm> sub 2 2 1 <--> 8e400001
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-8e400001
+0100408e
...
```
See full log https://app.travis-ci.com/github/rizinorg/rizin/jobs/638750553#L5534 

cc @SSharshunov this is for you. See https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#manage-endianness

### PR DESCRIPTION
**Pull request by SSharshunov**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes #6159

### CODE REVIEW

File: librz/arch/isa/luac/lua_arch.c [hunk 1]
```diff
@@ -78,7 +78,7 @@ char *get_const_string_b(const LuacBinInfo *lbi, ut64 addr, ut32 index, st32 *da
 	*data_len = const_entrie->data_len;
 	switch (const_entrie->tag) {
 	case LUA_VNUMINT:
-		sprintf(out_buffer, "%d", *(int *)const_entrie->data);
+		sprintf(out_buffer, "%llu", *(ut64 *)const_entrie->data);
```
Comment (Rot127) [inline librz/arch/isa/luac/lua_arch.c]:
```suggestion
		sprintf(out_buffer, "%" PFMT64u ", *(ut64 *)const_entrie->data);
```

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: librz/arch/isa/luac/lua_arch.c [hunk 2]
```diff
@@ -92,7 +92,7 @@ static char *get_const_string_b(const LuacBinInfo *lbi, ut64 addr, ut32 index, s
 	*data_len = const_entrie->data_len;
 	switch (const_entrie->tag) {
 	case LUA_VNUMINT:
-		sprintf(out_buffer, "%d", *(int *)const_entrie->data);
+		sprintf(out_buffer, "%" PFMT64u ", *(ut64 *)const_entrie->data);
```
Comment (notxvilka) [inline librz/arch/isa/luac/lua_arch.c]: `../librz/arch/isa/luac/lua_arch.c:95: error: missing terminating " character`

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: librz/bin/format/luac/parse.c [hunk 3]
```diff
@@ -266,7 +266,9 @@ static ut64 lua_parse_const_entry(const LuaProto *proto, RzBuffer *buffer, int i
 		data_len = sizeof(LUA_NUMBER);
 		recv_data = RZ_NEWS(ut8, data_len);
 		lua_load_block(buffer, recv_data, data_len, offset, data_size);
+		*(ut64 *)recv_data = rz_read_le64(recv_data);
```
Comment (notxvilka) [inline librz/bin/format/luac/parse.c]: This construction looks weird

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: librz/bin/format/luac/parse.c (hunk 3 above)
Comment (SSharshunov) [reply librz/bin/format/luac/parse.c]: Fixed and removed dead code

**Review by notxvilka — APPROVED** [review]
