### PR TITLE
Convert `!` commands to newshell

### LINKED ISSUE #1134: Update currently broken core_plugin_example.c to Newshell API
The example core plugin at https://github.com/rizinorg/rizin/blob/bdface85a24a52d1c4a8cf2daa00dc6099e5db51/librz/core/p/core_plugin_example.c still uses a `.call = rz_cmd_example_call` callback for injecting commands, which does not exist anymore.

For reference, here are some plugins that have been updated:
https://git.sr.ht/~thestr4ng3r/rz-commodore/tree/master/item/src/core_commodore.c
https://github.com/rizinorg/rz-ghidra/blob/dev/src/core_ghidra.cpp
https://github.com/rizinorg/jsdec/blob/master/p/core_pdd.c

It might also be nice to somehow embed this in our build system and add to the test suite in some way.

### PR DESCRIPTION
**Pull request by wargio**
# squash me

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- ✅ `!                        list all historic commands`
  - Moved under `H`
- ✅ `!ls                      execute 'ls' in shell`
- ✅ `!echo $RZ_SIZE           display file size`
  - **Removed** `RZ_BYTES` and `RZ_BLOCK` because useless
- ❌ `!*rzp x                  run rizin command via rzpipe in current session`
  - **Removed**
- ✅ `!!                       save command history to hist file`
  - Moved under `H+`
- ✅ `!!ls~txt                 print output of 'ls' and grep for 'txt'`
- ❌ `!!!cmd [args|$type]      adds the autocomplete value`
  - **Removed**
- ❌ `!!!-cmd [args]           removes the autocomplete value`
  - **Removed**
- ✅ `!-                       clear history in current session`
  - **Moved under** `H-`
- ❌ `!-*                      clear and save empty history log`
  - **Removed**

**Issues**

- Fix https://github.com/rizinorg/rizin/issues/1134

### CODE REVIEW

File: librz/core/cfile.c [hunk 1]
```diff
@@ -561,16 +529,14 @@ CURSOR cursor position(offset from curseek)
...
-
 	rz_sys_setenv("RZ_BIN_LANG", rz_config_get(core->config, "bin.lang"));
 	rz_sys_setenv("RZ_BIN_DEMANGLE", rz_config_get(core->config, "bin.demangle"));
 	rz_sys_setenv("RZ_ARCH", rz_config_get(core->config, "asm.arch"));
 	rz_sys_setenv("RZ_BITS", sdb_fmt("%" PFMT64u, rz_config_get_i(core->config, "asm.bits")));
-	rz_sys_setenv("RZ_COLOR", rz_config_get_i(core->config, "scr.color") ? "1" : "0");
-	rz_sys_setenv("RZ_DEBUG", rz_config_get_b(core->config, "cfg.debug") ? "1" : "0");
-	rz_sys_setenv("RZ_IOVA", rz_config_get_i(core->config, "io.va") ? "1" : "0");
+	rz_sys_setenv("RZ_COLOR", sdb_fmt("%" PFMT64u, rz_config_get_i(core->config, "scr.color")));
+	rz_sys_setenv("RZ_DEBUG", rz_config_get_b(core->config, "cfg.debug") ? "true" : "false");
```
Comment (XVilka) [inline librz/core/cfile.c]: I suggest to just create some uber-simple RzUtil function to convert `bool` to string and use it here.

File: librz/core/p/core_plugin_example.c [hunk 2]
```diff
@@ -1,40 +1,85 @@
+// SPDX-FileCopyrightText: 2021 somebody <somebody@domain.tld>
 // SPDX-License-Identifier: LGPL-3.0-only
 #if 0
```
Comment (XVilka) [inline librz/core/p/core_plugin_example.c]: Can you convert this comment into Doxygen `\file` instead?

**Review by XVilka — CHANGES_REQUESTED** [review]
Overall looks good.

File: librz/core/cmd_descs/cmd_system.yaml [hunk 3]
```diff
@@ -0,0 +1,71 @@
+# SPDX-FileCopyrightText: 2021 RizinOrg <info@rizin.re>
+# SPDX-License-Identifier: LGPL-3.0-only
+---
+name: cmd_system3
```
Comment (ret2libc) [inline librz/core/cmd_descs/cmd_system.yaml]: why `3`?

File: librz/core/cmd_descs/cmd_system.yaml [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+        flags: RZ_CMD_ARG_FLAG_ARRAY
+        optional: true
+    details:
+      - name: Examples
+        entries:
+          - text: "!!"
+            arg_str: "ls~txt"
+            comment: "executes the 'ls' command via system(3) and grep for 'txt'"
+  # These commands should me moved from ! to somewhere else.
+  - name: "!="
```
Comment (ret2libc) [inline librz/core/cmd_descs/cmd_system.yaml]: where did you get these from?

File: librz/core/cmd_descs/cmd_system.yaml (hunk 3 above)
Comment (XVilka) [reply librz/core/cmd_descs/cmd_system.yaml]: Agree. Should be `42`.

File: librz/core/cmd_descs/cmd_system.yaml (hunk 4 above)
Comment (wargio) [reply librz/core/cmd_descs/cmd_system.yaml]: It was a bit confusing having `!<cmd>` and `!<num>` under the same command,
therefore i moved the `show list history` and `execute history N` under `!=`

Btw, I added all my reasoning in my commit message; you can click on the 3 dots and read the body message
image

File: librz/core/cfile.c (hunk 1 above)
Comment (wargio) [reply librz/core/cfile.c]: tbh, i do not see any reason to have this. maybe a macro, but still, not really needed.

File: librz/core/cmd_descs/cmd_system.yaml (hunk 3 above)
Comment (wargio) [reply librz/core/cmd_descs/cmd_system.yaml]: because is the cmd that calls system?

File: librz/core/cmd_system.c [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+		RZ_LOG_ERROR("cannot find command with index %d.\n", index);
+		return RZ_CMD_STATUS_ERROR;
+	}
+
+	int ret = rz_core_cmd0(core, cmd);
+	return !ret ? RZ_CMD_STATUS_OK : RZ_CMD_STATUS_ERROR;
+}
+
+RZ_IPI RzCmdStatus rz_clear_history_handler(RzCore *core, int argc, const char **argv) {
+	if (argc != 1) {
```
Comment (XVilka) [inline librz/core/cmd_system.c]: I think the arguments count now checked by the generic implementation and now unnecessary if they are specified as non-optional in YAML. @ret2libc might correct me on that.

Comment (wargio) [reply librz/core/cmd_system.c]: if it is, i will remove this.

File: librz/core/cmd_descs/cmd_system.yaml (hunk 4 above)
Comment (ret2libc) [reply librz/core/cmd_descs/cmd_system.yaml]: :+1:

File: librz/core/cmd_system.c [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+	}
+
+	return rz_strbuf_drain(sb);
+}
+
+RZ_IPI RzCmdStatus rz_system_handler(RzCore *core, int argc, const char **argv) {
+	if (argc == 1) {
+		rz_line_hist_list();
+		return RZ_CMD_STATUS_OK;
+	}
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: Is this still needed?

File: librz/core/cmd_system.c [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+	rz_core_sysenv_end(core);
+
+	return !ret ? RZ_CMD_STATUS_OK : RZ_CMD_STATUS_ERROR;
+}
+
+RZ_API RzCmdStatus rz_system_to_cons_handler(RzCore *core, int argc, const char **argv) {
+	if (argc < 2) {
+		return RZ_CMD_STATUS_WRONG_ARGS;
+	}
+
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: not necessary

File: librz/core/cmd_system.c [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+	return !ret ? RZ_CMD_STATUS_OK : RZ_CMD_STATUS_ERROR;
+}
+
+RZ_IPI RzCmdStatus rz_list_or_exec_history_handler(RzCore *core, int argc, const char **argv) {
+	if (argc == 1) {
+		rz_line_hist_list();
+		return RZ_CMD_STATUS_OK;
+	} else if (argc > 2) {
+		return RZ_CMD_STATUS_WRONG_ARGS;
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: not necessary

File: librz/core/cmd_system.c (hunk 5 above)
Comment (ret2libc) [reply librz/core/cmd_system.c]: yes it is unnecessary.

File: librz/core/cmd_system.c [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+
+	rz_line_hist_free();
+	return RZ_CMD_STATUS_OK;
+}
+
+RZ_IPI RzCmdStatus rz_history_save_handler(RzCore *core, int argc, const char **argv) {
+	if (argc != 1) {
+		return RZ_CMD_STATUS_WRONG_ARGS;
+	}
+
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: same

File: librz/core/cmd_system.c [hunk 10]
```diff
@@ -0,0 +1,123 @@
...
+					s = p;
+				}
+			}
+			arg += s;
+		}
+		rz_strbuf_appendf(sb, "%s\"", arg);
+	}
+
+	return rz_strbuf_drain(sb);
+}
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: It remains to see whether this works well on windows... I remember that I wanted to switch all this `!` stuff to RzSubprocess API.

File: librz/core/cmd_system.c (hunk 6 above)
Comment (wargio) [reply librz/core/cmd_system.c]: i forgot to remove this.

File: librz/core/cmd_system.c (hunk 10 above)
Comment (wargio) [reply librz/core/cmd_system.c]: I can add a comment to refactor this later.

**Comment by wargio** [comment]
```
E: Failed to fetch http://apt.llvm.org/focal/dists/llvm-toolchain-focal-12/main/binary-amd64/Packages  File has unexpected size (9437 != 9427). Mirror sync in progress? [IP: 151.101.250.49 443]
```

File: test/db/tools/rz [hunk 11]
```diff
@@ -98,6 +98,7 @@ EOF
 RUN
 
 NAME=no-nl-at-eof script
+BROKEN=1
```
Comment (XVilka) [inline test/db/tools/rz]: Why?

**Review by XVilka — APPROVED** [review]
Overall is good to merge even as is. Just a couple minor things.

File: librz/core/cmd_descs/cmd_history.yaml [hunk 12]
```diff
@@ -0,0 +1,29 @@
+# SPDX-FileCopyrightText: 2021 RizinOrg <info@rizin.re>
+# SPDX-License-Identifier: LGPL-3.0-only
+---
+name: cmd_history
+commands:
+  - name: "H"
+    cname: list_or_exec_history
```
Comment (ret2libc) [inline librz/core/cmd_descs/cmd_history.yaml]: i prefer `history_list_or_exec`, `history_clear` and `history_save`. we usually put the "topic" as first word

File: librz/core/cmd_history.c [hunk 13]
```diff
@@ -0,0 +1,31 @@
+RZ_IPI RzCmdStatus rz_list_or_exec_history_handler(RzCore *core, int argc, const char **argv) {
+	if (argc == 1) {
+		rz_line_hist_list();
+		return RZ_CMD_STATUS_OK;
+	}
+
+	int index = atoi(argv[1]);
+	if (index < 1) {
+		RZ_LOG_ERROR("index must be a positive number.\n");
+		return RZ_CMD_STATUS_WRONG_ARGS;
```
Comment (ret2libc) [inline librz/core/cmd_history.c]: Mmm maybe STATUS_ERROR even in this case? This is no different than passing a too big number.

File: librz/core/cmd_system.c [hunk 14]
```diff
@@ -0,0 +1,92 @@
...
+				if (arg[p] == '\\' || arg[p] == '"') {
+					rz_strbuf_append_n(sb, arg + s, p - s);
+					rz_strbuf_append(sb, "\\");
+					s = p;
+				}
+			}
+			arg += s;
+		}
+		rz_strbuf_appendf(sb, "%s\"", arg);
+	}
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: not a big fan of all this logic actually... I *think* @thestr4ng3r already did something like this somewhere. Am I wrong Florian?

File: test/db/tools/rz (hunk 11 above)
Comment (wargio) [reply test/db/tools/rz]: because it does work on my linux but not on the linux machine via the CI and i have no clue why

File: librz/core/cmd_system.c [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+	};
+
+	RzSubprocess *proc = rz_subprocess_start_opt(&opt);
+	if (!proc) {
+		rz_subprocess_fini();
+		return false;
+	}
+
+	// wait max 1 min
+	RzSubprocessWaitReason reason = rz_subprocess_wait(proc, 60000);
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: Why the limit? If you do !vim you don't expect it to be closed after one min

**Comment by XVilka** [comment]
Overall is fine, but could you please run it on more CI configurations, including older CentOS, Debian, Alpine by sending the PR from the `dist-` branch instead?

File: librz/core/cfile.c [hunk 16]
```diff
@@ -492,19 +492,8 @@ RZ_API bool rz_core_file_resize_delta(RzCore *core, st64 delta) {
...
-	if (strstr(cmd, "RZ_BLOCK")) {
-		// remove temporary BLOCK file
-		char *f = rz_sys_getenv("RZ_BLOCK");
-		if (f) {
-			rz_file_rm(f);
-			rz_sys_setenv("RZ_BLOCK", NULL);
-			free(f);
-		}
-	}
+RZ_API void rz_core_sysenv_end(RzCore *core) {
```
Comment (XVilka) [inline librz/core/cfile.c:497]: Since you modify this function anyway, could you please add a Doxygen description here?

File: librz/core/cfile.c [hunk 17]
```diff
@@ -516,33 +505,12 @@ RZ_API void rz_core_sysenv_end(RzCore *core, const char *cmd) {
...
 
-#if DISCUSS
-EDITOR rz_sys_setenv("EDITOR", rz_config_get(core->config, "cfg.editor"));
-CURSOR cursor position(offset from curseek)
-	VERBOSE cfg.verbose
-#endif
-
-	RZ_API char *rz_core_sysenv_begin(RzCore *core, const char *cmd) {
-	char *f, *ret = cmd ? strdup(cmd) : NULL;
+RZ_API void rz_core_sysenv_begin(RzCore *core) {
```
Comment (XVilka) [inline librz/core/cfile.c:511]: Sam (was) here

File: librz/core/cfile.c (hunk 1 above)
Comment (XVilka) [reply librz/core/cfile.c]: In fact there is already: `rz_str_bool()`. Moreover, if you just use `rz_config_get(core->config, "cfg.debug")` it should return "true" or "false" string - it checks if the variable is boolean internally already, see `librz/config/config.c`.

File: librz/core/cmd.c [hunk 18]
```diff
@@ -2087,7 +2081,7 @@ static void rz_w32_cmd_pipe(RzCore *core, char *rizin_cmd, char *shell_cmd) {
 #undef __CLOSE_DUPPED_PIPES
 #endif
 
-RZ_API int rz_core_cmd_pipe(RzCore *core, char *rizin_cmd, char *shell_cmd) {
+RZ_API int rz_core_cmd_pipe_old(RzCore *core, char *rizin_cmd, char *shell_cmd) {
```
Comment (XVilka) [inline librz/core/cmd.c:1896]: Could you please add Doxygen description here?

File: librz/core/cmd.c [hunk 19]
```diff
@@ -2163,6 +2157,59 @@ RZ_API int rz_core_cmd_pipe(RzCore *core, char *rizin_cmd, char *shell_cmd) {
...
+	rz_subprocess_wait(proc, UT64_MAX);
+
+	output = rz_subprocess_out(proc);
+	rz_subprocess_free(proc);
+	rz_subprocess_fini();
+
+	return output;
+}
+
+RZ_API RzCmdStatus rz_core_cmd_pipe(RzCore *core, char *rizin_cmd, int argc, char **argv) {
```
Comment (XVilka) [inline librz/core/cmd.c]: Since this is new API function, add Doxygen please.

**Review by XVilka — CHANGES_REQUESTED** [review]

File: librz/core/cfile.c (hunk 1 above)
Comment (wargio) [reply librz/core/cfile.c]: that code is old. i will revert it back to the original code since i dropped due the new usage of the RzSubprocess

File: librz/core/cfile.c (hunk 16 above)
Comment (wargio) [reply librz/core/cfile.c:497]: dropping support for this.

File: librz/core/cfile.c (hunk 17 above)
Comment (wargio) [reply librz/core/cfile.c:511]: same. dropping support.

File: librz/core/cmd.c (hunk 18 above)
Comment (wargio) [reply librz/core/cmd.c:1896]: not going to happen, since it is old code and likely being removed once the code does work.

File: librz/core/cmd.c (hunk 19 above)
Comment (wargio) [reply librz/core/cmd.c]: not sure if we should support this as an API.

Comment (XVilka) [reply librz/core/cmd.c]: Probably not.

File: librz/include/rz_util/rz_subprocess.h [hunk 20]
```diff
@@ -72,8 +72,8 @@ RZ_API void rz_subprocess_free(RzSubprocess *proc);
 RZ_API RzSubprocessWaitReason rz_subprocess_wait(RzSubprocess *proc, ut64 timeout_ms);
 RZ_API void rz_subprocess_kill(RzSubprocess *proc);
 RZ_API int rz_subprocess_ret(RzSubprocess *proc);
-RZ_API char *rz_subprocess_out(RzSubprocess *proc);
-RZ_API char *rz_subprocess_err(RzSubprocess *proc);
+RZ_API char *rz_subprocess_out(RzSubprocess *proc, int *length);
```
Comment (ret2libc) [inline librz/include/rz_util/rz_subprocess.h]: what about
```suggestion
RZ_API char *rz_subprocess_out(RzSubprocess *proc, size_t *length);
```
?

File: librz/util/subprocess.c [hunk 21]
```diff
@@ -632,7 +620,7 @@ static char **create_child_env(const char *envvars[], const char *envvals[], siz
 	for (size_t i = 0; i < size; i++) {
 		new_env[i] = strdup(environ[i]);
 	}
-	for (size_t i = 0; i <= env_size; i++) {
+	for (size_t i = 0; i <= new_env_size; i++) {
```
Comment (ret2libc) [inline librz/util/subprocess.c:639]: nice catch... I guess it was wrong before.

File: test/db/tools/rz_bin [hunk 22]
```diff
@@ -155,87 +155,87 @@ RUN
...
+CMDS=!!rz-bin -zz ${RZ_FILE} | grep "Password:"
 EXPECT=<<EOF
 86  0x00002619 0x00404019 10  11   .rdata  ascii   Password: 
 EOF
 RUN
 
 NAME=rz-bin -zzz pe
 FILE=bins/pe/ioli/w32/crackme0x00.exe
-CMDS=!rz-bin -zzz ${RZ_FILE} | grep "Password:"
+CMDS=!!rz-bin -zzz ${RZ_FILE} | grep "Password:"
```
Comment (ret2libc) [inline test/db/tools/rz_bin]: I guess this kind of change is now required because the `|` is handled by the rz-shell, so you have to redirect the output/err to rzcons, so that it can be later sent to `grep`, right?

File: librz/core/cfile.c [hunk 23]
```diff
@@ -561,16 +529,14 @@ CURSOR cursor position(offset from curseek)
...
 	rz_sys_setenv("RZ_CONFIG", config_sdb_path);
-
 	rz_sys_setenv("RZ_BIN_LANG", rz_config_get(core->config, "bin.lang"));
 	rz_sys_setenv("RZ_BIN_DEMANGLE", rz_config_get(core->config, "bin.demangle"));
 	rz_sys_setenv("RZ_ARCH", rz_config_get(core->config, "asm.arch"));
 	rz_sys_setenv("RZ_BITS", sdb_fmt("%" PFMT64u, rz_config_get_i(core->config, "asm.bits")));
-	rz_sys_setenv("RZ_COLOR", rz_config_get_i(core->config, "scr.color") ? "1" : "0");
-	rz_sys_setenv("RZ_DEBUG", rz_config_get_b(core->config, "cfg.debug") ? "1" : "0");
-	rz_sys_setenv("RZ_IOVA", rz_config_get_i(core->config, "io.va") ? "1" : "0");
+	rz_sys_setenv("RZ_COLOR", sdb_fmt("%" PFMT64u, rz_config_get_i(core->config, "scr.color")));
```
Comment (ret2libc) [inline librz/core/cfile.c]: `rz_strf` please.

File: librz/core/cmd.c [hunk 24]
```diff
@@ -2163,6 +2157,59 @@ RZ_API int rz_core_cmd_pipe(RzCore *core, char *rizin_cmd, char *shell_cmd) {
...
+	if (!rz_subprocess_init()) {
+		RZ_LOG_ERROR("Cannot initialize subprocess.\n");
+		return NULL;
+	}
+
+	RzSubprocessOpt opt = {
+		.file = argv[0],
+		.args = (const char **)&argv[1],
+		.args_size = argc - 1,
+		.envvars = NULL,
```
Comment (ret2libc) [inline librz/core/cmd.c]: do we want to pass some vars to the subprocess? `RZ_FILE`, `RZ_OFFSET`, `RZ_ENDIAN`, etc.?

File: librz/core/cmd.c (hunk 19 above)
Comment (ret2libc) [reply librz/core/cmd.c]: please anyway a small description would be good IMHO.

File: librz/core/cmd.c [hunk 25]
```diff
@@ -6007,17 +6054,22 @@ DEFINE_HANDLE_TS_FCN_AND_SYMBOL(html_enable_stmt) {
...
+	TSNode command_pipe = ts_node_named_child(node, 1);
+
+	char *rz_cmd = ts_node_sub_string(command_rizin, state->input);
+	if (!rz_cmd) {
+		return RZ_CMD_STATUS_INVALID;
+	}
+
+	RzCmdStatus res = RZ_CMD_STATUS_INVALID;
+	RzCmdParsedArgs *a = ts_node_handle_arg_prargs(state, node, command_pipe, 1, true);
+	if (a && a->argc > 1) {
```
Comment (ret2libc) [inline librz/core/cmd.c:5908]: I would check `if (!a || a->argc <= 1) return INVALID`. Otherwise you just ignore the error, which I think is never good.

File: librz/core/cmd.c [hunk 26]
```diff
@@ -6563,6 +6614,27 @@ RZ_API char *rz_core_cmd_str(RzCore *core, const char *cmd) {
 	return retstr;
 }
 
+RZ_API ut8 *rz_core_cmd_raw(RzCore *core, const char *cmd, int *length) {
+	const char *static_str;
+	ut8 *retstr = NULL;
+	rz_cons_push();
+	if (rz_core_cmd(core, cmd, 0) == -1) {
+		//eprintf ("Invalid command: %s\n", cmd);
```
Comment (ret2libc) [inline librz/core/cmd.c]: `rz_cons_pop`

**Review by ret2libc — COMMENTED** [review]
Awesome work @wargio , thanks a lot for moving this thing forward! I haven't tested it yet, I will do after some more changes, however things look nice so far!

File: librz/include/rz_util/rz_subprocess.h (hunk 20 above)
Comment (wargio) [reply librz/include/rz_util/rz_subprocess.h]: i thought about this, but RzStrbuf does not use size_t.

File: librz/util/subprocess.c (hunk 21 above)
Comment (wargio) [reply librz/util/subprocess.c:639]: i had a huge headache on this since asan was complaining but not telling me where due optimizations.

File: test/db/tools/rz_bin (hunk 22 above)
Comment (wargio) [reply test/db/tools/rz_bin]: Yes. because !! does fetch stdout, and ! does not

File: librz/core/cfile.c (hunk 23 above)
Comment (wargio) [reply librz/core/cfile.c]: i'll reset this back to the original code and even maybe remove this.

File: librz/core/cmd.c (hunk 24 above)
Comment (wargio) [reply librz/core/cmd.c]: hmm i do not know, because i expect the app to eat the stdin not the envvars.

Comment (ret2libc) [reply librz/core/cmd.c]: according to `!??` programs are expected to find some env vars. It seems that in the past implementation that was all set with `rz_core_sysenv_begin`/`rz_core_sysenv_end`. It should be fine to keep this as-is, because current implementation of RzSubprocess just allows to add/replace env variables, but not to remove them. So by setting `.envvars = NULL`  we are really just keeping the parent env vars, which should be fine.

File: librz/util/subprocess.c (hunk 21 above)
Comment (ret2libc) [reply librz/util/subprocess.c:639]: compile with `-buildtype=debug` if that was the problem.

File: librz/include/rz_util/rz_subprocess.h (hunk 20 above)
Comment (ret2libc) [reply librz/include/rz_util/rz_subprocess.h]: :/ ok

File: librz/core/cmd.c (hunk 26 above)
Comment (wargio) [reply librz/core/cmd.c]: i saw that you added this in your PR, should i skip this change ? @ret2libc

File: librz/core/cmd.c (hunk 25 above)
Comment (wargio) [reply librz/core/cmd.c:5908]: that is not true. `res` is `RZ_CMD_STATUS_INVALID` so if that `if` fails, it will return `RZ_CMD_STATUS_INVALID`

**Review by XVilka — APPROVED** [review]
LGTM. But please don't forget to test on `dist-` branch before merging.

**Comment by XVilka** [comment]
94 broken tests: https://builds.sr.ht/~xvilka/job/534811#task-test-0

File: librz/core/cmd.c (hunk 26 above)
Comment (ret2libc) [reply librz/core/cmd.c]: I will just do a separate PR just with this ;) my PR will take some time to be done.

File: librz/core/cmd.c (hunk 25 above)
Comment (ret2libc) [reply librz/core/cmd.c:5908]: Right!

File: librz/core/cfile.c [hunk 27]
```diff
@@ -563,16 +533,14 @@ CURSOR cursor position(offset from curseek)
...
 	rz_sys_setenv("RZ_BIN_DEMANGLE", rz_config_get(core->config, "bin.demangle"));
 	rz_sys_setenv("RZ_ARCH", rz_config_get(core->config, "asm.arch"));
-	rz_sys_setenv("RZ_BITS", sdb_fmt("%" PFMT64u, rz_config_get_i(core->config, "asm.bits")));
-	rz_sys_setenv("RZ_COLOR", rz_config_get_i(core->config, "scr.color") ? "1" : "0");
-	rz_sys_setenv("RZ_DEBUG", rz_config_get_b(core->config, "cfg.debug") ? "1" : "0");
-	rz_sys_setenv("RZ_IOVA", rz_config_get_i(core->config, "io.va") ? "1" : "0");
+	rz_sys_setenv("RZ_BITS", rz_config_get(core->config, "asm.bits"));
+	rz_sys_setenv("RZ_COLOR", rz_config_get(core->config, "scr.color"));
+	rz_sys_setenv("RZ_DEBUG", rz_config_get(core->config, "cfg.debug"));
+	rz_sys_setenv("RZ_IOVA", rz_config_get(core->config, "io.va"));
```
Comment (ret2libc) [inline librz/core/cfile.c]: This is not exactly the same as before.. For example, for booleans vars it would returne `true`/`false` instead of `1`/`0` as before. I think for env vars it is more common to have 1/0 ?

File: librz/core/cmd_history.c [hunk 28]
```diff
@@ -0,0 +1,31 @@
+RZ_IPI RzCmdStatus rz_history_list_or_exec_handler(RzCore *core, int argc, const char **argv) {
+	if (argc == 1) {
+		rz_line_hist_list();
+		return RZ_CMD_STATUS_OK;
+	}
+
+	int index = atoi(argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_history.c:7]: `rz_num`?

File: librz/core/cmd_system.c [hunk 29]
```diff
@@ -0,0 +1,217 @@
...
+	const char *bin_lang = rz_config_get(core->config, "bin.lang");
+	const char *cfg_debug = rz_config_get(core->config, "cfg.debug");
+	const char *io_va = rz_config_get(core->config, "io.va");
+	const char *pdb_server = rz_config_get(core->config, "pdb.server");
+	const char *scr_color = rz_config_get(core->config, "scr.color");
+	const char *endian = rz_str_bool(core->rasm->big_endian);
+	char *cfg_path = config_path(core);
+	snprintf(file_size, sizeof(file_size), "%" PFMT64u, core->file ? rz_io_fd_size(core->io, core->file->fd) : 0);
+	snprintf(core_offset, sizeof(core_offset), "%" PFMT64u, core->offset);
+	snprintf(block_size, sizeof(block_size), "%u", core->blocksize);
```
Comment (ret2libc) [inline librz/core/cmd_system.c]:
```suggestion
	rz_strf(file_size, "%" PFMT64u, core->file ? rz_io_fd_size(core->io, core->file->fd) : 0);
	rz_strf(core_offset, "%" PFMT64u, core->offset);
	rz_strf(block_size, "%u", core->blocksize);
```

File: librz/core/cmd_system.c [hunk 30]
```diff
@@ -0,0 +1,217 @@
...
+		core_offset,
+		endian,
+		bin_demangle,
+		bin_lang,
+		pdb_server,
+		io_va,
+		scr_color,
+		block_size,
+		cfg_debug,
+		cfg_path ? cfg_path : ""
```
Comment (ret2libc) [inline librz/core/cmd_system.c]:
```suggestion
		rz_str_get(cfg_path)
```

File: librz/core/cmd_system.c [hunk 31]
```diff
@@ -0,0 +1,217 @@
...
+		return false;
+	}
+
+	if (!rz_subprocess_init()) {
+		RZ_LOG_ERROR("Cannot initialize subprocess.\n");
+		rz_list_free(alloc);
+		rz_file_rm(cfg_path);
+		free(cfg_path);
+		free(args);
+		return false;
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: put this at the end of the function and use `goto`, it will simplify errors handling and make sure things are done in the right order on each error.

File: librz/core/cmd_system.c [hunk 32]
```diff
@@ -0,0 +1,217 @@
...
+	} else if (strlen(env) == len) {
+		return value;
+	}
+
+	if ((it = rz_list_find_ptr(alloc, (void *)arg))) {
+		string = it->data;
+	} else {
+		string = strdup(arg);
+	}
+
```
Comment (ret2libc) [inline librz/core/cmd_system.c]: I don't see what advantages `alloc` array would bring. I would just go with `rz_str_replace` and remove `alloc`. Moreover, you can only find the same `arg` in `alloc` only if it's the same argv[i], so probably a list is not really necessary anyway.

**Review by ret2libc — COMMENTED** [review]
Just looked at some parts for now! Doing another round in a bit.

File: librz/core/cmd.c [hunk 33]
```diff
@@ -2163,6 +1925,66 @@ RZ_API int rz_core_cmd_pipe(RzCore *core, char *rizin_cmd, char *shell_cmd) {
...
+	return output;
+}
+
+/**
+ * \brief Executes a rizin command and pipes the result to the stdin when calling execvp
+ *
+ * Executes a rizin command and the raw bytes of the stdout is returned.
+ * The output is then used as stdin for execvp.
+ * The output of the execvp is then sent into RzCons.
+ * */
```
Comment (ret2libc) [inline librz/core/cmd.c]: This should be better explained. In particular, it is not clear what is piped where. In this case, `rizin_cmd` is the first command and its output is piped as stdin of the command specified in (argc, argv).

File: librz/core/cmd.c (hunk 26 above)
Comment (ret2libc) [reply librz/core/cmd.c]: This is still to be done.

File: librz/core/cmd.c [hunk 34]
```diff
@@ -6565,6 +6391,32 @@ RZ_API char *rz_core_cmd_str(RzCore *core, const char *cmd) {
 	return retstr;
 }
 
+/**
+ * \brief Executes a rizin command and returns the raw stdout and its length
+ *
+ * Executes a rizin command and returns the raw stdout and its length.
+ * */
+RZ_API ut8 *rz_core_cmd_raw(RzCore *core, const char *cmd, int *length) {
```
Comment (ret2libc) [inline librz/core/cmd.c:6474]: Probably this can be unified with rz_core_cmd_str to avoid code dup.

File: librz/core/cfile.c (hunk 27 above)
Comment (wargio) [reply librz/core/cfile.c]: no. this better and this stuff is not used besides the user itself.

File: librz/core/cmd_history.c (hunk 28 above)
Comment (wargio) [reply librz/core/cmd_history.c:7]: no. i expect a number and i want a number. atoi is enough

File: librz/core/cmd_system.c (hunk 32 above)
Comment (wargio) [reply librz/core/cmd_system.c]: alloc, is just a simple idea where i place the allocated strings and just free them via rz_list so i am sure that i never forget to free an allocated value, so i do not have to care whether argv is allocated on the heap or not, using directly rz_str_replace is a super bad idea since you do not know where those arguments are really allocated.

File: librz/core/p/core_plugin_example.c [hunk 35]
```diff
@@ -1,41 +1,93 @@
 // SPDX-FileCopyrightText: 2021 RizinOrg <info@rizin.re>
 // SPDX-License-Identifier: LGPL-3.0-only
-#if 0
-gcc -o core_plugin_example.so -O3 -std=c99 -Wall -fPIC `pkg-config --cflags --libs rz_core` core_plugin_example.c -shared
-mkdir -p ~/.config/rizin/plugins
-mv core_plugin_example.so ~/.config/rizin/plugins
-#endif
+
```
Comment (ret2libc) [inline librz/core/p/core_plugin_example.c:3]: Awesome! Is this compiled anyhow while testing rizin? I was also wondering.. Aren't unit tests enough to showcase how to write a new command?

File: test/db/io/baddr [hunk 36]
```diff
@@ -17,7 +17,7 @@ RUN
 
 NAME=3: io.baddr
 FILE=bins/elf/analysis/pie
-CMDS=!rz-bin -B 0xf00000 -re ${RZ_FILE} | grep 0x
+CMDS=!!rz-bin -B 0xf00000 -re ${RZ_FILE} | grep 0x
```
Comment (ret2libc) [inline test/db/io/baddr]: I think this should be kinda automatic or, at least, the default behaviour, without having to use `!!` all the time.
If we read the help of `|` it is `| <cmd> | <program> # Pipe output of command to program`, so by using `|` the user already express his will to pipe the output of one "command" to another program. 

Do you think it would make sense to detect the `pipe` and assume output should be redirected to rzcons?

File: librz/util/subprocess.c [hunk 37]
```diff
@@ -36,13 +36,17 @@ static bool create_pipe_overlap(HANDLE *pipe_read, HANDLE *pipe_write, LPSECURIT
 		CloseHandle(*pipe_read);
 		return FALSE;
 	}
+
+	SetEnvironmentVariable(TEXT("RZ_PIPE_PATH"), name);
```
Comment (ret2libc) [inline librz/util/subprocess.c:40]: Why is this necessary? What does it do?

File: librz/core/p/core_plugin_example.c (hunk 35 above)
Comment (wargio) [reply librz/core/p/core_plugin_example.c:3]: yes

File: test/db/io/baddr (hunk 36 above)
Comment (wargio) [reply test/db/io/baddr]: i disagree
you can't know if this is piped, or not

File: librz/util/subprocess.c [hunk 38]
```diff
@@ -132,29 +136,29 @@ static LPWCH override_env(const char *envvars[], const char *envvals[], size_t e
...
+	} else {
+		snprintf(cmd_exe, sizeof(cmd_exe), "%s", opt->file);
+	}
 
 	char **argv = calloc(opt->args_size + 1, sizeof(char *));
 	if (!argv) {
 		return NULL;
 	}
-	argv[0] = (char *)opt->file;
+	argv[0] = ""; // a space is required to work correctly.
```
Comment (ret2libc) [inline librz/util/subprocess.c:161]: why the `cmd_exe` is not placed in `argv[0]`?

File: librz/core/p/core_plugin_example.c (hunk 35 above)
Comment (ret2libc) [reply librz/core/p/core_plugin_example.c:3]: Where is this compiled?

File: test/db/io/baddr (hunk 36 above)
Comment (ret2libc) [reply test/db/io/baddr]: Why can't you? In `pipe_stmt` handler you know if a program is piped or not.

File: librz/core/cmd.c [hunk 39]
```diff
@@ -6008,17 +5830,22 @@ DEFINE_HANDLE_TS_FCN_AND_SYMBOL(html_enable_stmt) {
...
-	char *second_str = ts_node_sub_string(second_cmd, state->input);
-	int value = state->core->num->value;
-	RzCmdStatus res = rz_cmd_int2status(rz_core_cmd_pipe(state->core, first_str, second_str));
-	state->core->num->value = value;
-	free(first_str);
-	free(second_str);
+	TSNode command_rizin = ts_node_named_child(node, 0);
+	TSNode command_pipe = ts_node_named_child(node, 1);
+
+	char *rz_cmd = ts_node_sub_string(command_rizin, state->input);
```
Comment (ret2libc) [inline librz/core/cmd.c]: This is probably unnecessary. We can probably use `handle_ts_stmt` as done elsewhere to direclty work with the TSNode, so we avoid going again through the whole tree-sitter parsing and handling.

File: test/unit/test_rzpipe.c [hunk 40]
```diff
@@ -11,7 +11,7 @@ static bool test_rzpipe(void) {
 	RzPipe *r = rzpipe_open(RIZIN_BUILD_PATH " -q0 =");
 	mu_assert("rzpipe can spawn", r);
 	char *hello = rzpipe_cmd(r, "?e hello world");
-	mu_assert_streq(hello, "hello world\n", "rzpipe hello world");
+	mu_assert_streq(hello, "[0x00000000]> hello world\n", "rzpipe hello world");
```
Comment (ret2libc) [inline test/unit/test_rzpipe.c]: I think this change is wrong. The output of the `?e` command is just the string, not the prompt + string.

File: librz/core/cfile.c (hunk 27 above)
Comment (ret2libc) [reply librz/core/cfile.c]: How is this better exactly? Anyway, I'm ok with having `true`/`false` instead of 1/0, but please update the documentation because it says 1/0.

File: librz/util/subprocess.c (hunk 38 above)
Comment (wargio) [reply librz/util/subprocess.c:161]: because we are calling `CreateProcessA` properly. check MS guide.

File: librz/util/subprocess.c (hunk 37 above)
Comment (wargio) [reply librz/util/subprocess.c:40]: used by rz-pipe on windows.

File: test/db/io/baddr (hunk 36 above)
Comment (wargio) [reply test/db/io/baddr]: yes, but what if my cmd is like 
```
[0x00000000] `aaa | bbb` | ccc
```

File: librz/util/subprocess.c (hunk 37 above)
Comment (ret2libc) [reply librz/util/subprocess.c:40]: I see :/ Does linux needs it too?

File: librz/core/cfile.c (hunk 27 above)
Comment (wargio) [reply librz/core/cfile.c]: book needs to be updated anyway after this PR

Comment (ret2libc) [reply librz/core/cfile.c]: I meant the rizin doc for `%??`.

By the way, I changed my mind. I think there is no need to do this change here and now. In particular, there are places that seem to assume boolean env vars as 1/0 and not true/false,  so I'll revert these.

File: librz/util/subprocess.c (hunk 37 above)
Comment (wargio) [reply librz/util/subprocess.c:40]: as far i know, nope.

File: test/db/io/baddr (hunk 36 above)
Comment (ret2libc) [reply test/db/io/baddr]: Not sure about it's better `!!<prog1> | <prog2>` or `!<prog1> | <prog2>`...

Choosing `!!<prog1> | <prog2>` means that essentially you never use `!<prog1> | <prog2>` and you have to type `!!` every time. Also, as a user you first do `!ls` and then you probably want to grep it and suddenly you have to do `!!ls` instead of just `!ls` if you want to pipe. On the other hand, this maintains the semantic of `!` and `!!`.

Choosing `!<prog1> | <prog2>` and make sure that `!<prog1>` automatically redirects stdout to rzcons whenever a pipe is used means that as a user it's easier to construct a command without really having to *know* about rzcons (which is a very internal thing after all..). However, it loses a bit the semantic of `!` vs `!!`.

WDYT @wargio  @XVilka @thestr4ng3r ?

File: librz/util/subprocess.c [hunk 41]
```diff
@@ -132,29 +136,29 @@ static LPWCH override_env(const char *envvars[], const char *envvals[], size_t e
...
-	while (*str) {
-		if (str[0] == '\r' &&
-			!(str - start >= 4 && !strncmp(str - 4, RZ_CONS_CLEAR_SCREEN, 4))) {
-			memmove(str, str + 1, strlen(str + 1) + 1);
-			continue;
-		}
-		str++;
-	}
-}
-
```
Comment (ret2libc) [inline librz/util/subprocess.c:146]: @wargio I see this was removed from subprocess, but now old users of the subprocess API has to do this themselves. Did you remove this because you want to get the raw stdout/stderr of a program?

What do you think if we use these API?
```
RZ_API char *rz_subprocess_out_str(RzSubprocess *proc);
RZ_API char *rz_subprocess_err_str(RzSubprocess *proc);
RZ_API ut8 *rz_subprocess_out(RzSubprocess *proc, int *length);
RZ_API ut8 *rz_subprocess_err(RzSubprocess *proc, int *length);
```
The `_str` APIs apply `remove_cr` before returning the strings, so we don't need to replicate this function everywhere.

Together with this change we should also change a bit the `RzSubprocessOutput` structure. Something like:
```
typedef struct rz_process_output_t {
	char *out_str; // stdout
	char *err_str; // stderr
        ut8 *out, *err;
        int out_len, err_len;
	int ret; // exit code of the process
	bool timeout;
} RzSubprocessOutput;
```
Comments?

Comment (wargio) [reply librz/util/subprocess.c:146]: stdout needs to be raw. it's up to the user to know what there will be in the buffer.
this is the reason you can do `cat mybinfile | hexdump -C` for example

Comment (wargio) [reply librz/util/subprocess.c:146]: The remove_cr function shall not be there because the only one complaining about this is the testsuite, therefore that is a testsuite issue not an issue related to the pipe, nor subprocess

File: test/db/io/baddr (hunk 36 above)
Comment (wargio) [reply test/db/io/baddr]: for me you can remove `!!` and merge them into `!` and do the autodetect for pipe/grep/etc..

File: librz/util/subprocess.c (hunk 41 above)
Comment (ret2libc) [reply librz/util/subprocess.c:146]: I agree, that's why I kept the raw stdout in the proposal above. However, other times you just want the string and you want a "cleaned" string (e.g. by running remove_cr function), so I was thinking about providing that from RzSubprocess itself instead of having every user of the API definiting their own remove_cr function.

Also, no matter what we should probably add the `out_len`/`err_len` fields.

Comment (ret2libc) [reply librz/util/subprocess.c:146]: cc @thestr4ng3r you wrote that piece of code, right?

Comment (thestr4ng3r) [reply librz/util/subprocess.c:146]: This `remove_cr` implementation is super inefficient so I can only assume I wrote it to only be used as part of `rz-test`, where it doesn't really matter.
If another user of `RzSubprocess` needs this, the functionality should not be provided as part of the subprocess api but as just an independent `rz_str_` function that can be called.
So for me the move to `rz-test/run.c` as it is done here seems good.

Comment (ret2libc) [reply librz/util/subprocess.c:146]: Ok thanks for confirming @thestr4ng3r . Then I will just make sure to add `out_len`/`err_len` to `RzSubprocessOutput` and that's it.

File: test/db/io/baddr (hunk 36 above)
Comment (XVilka) [reply test/db/io/baddr]: I think autodetection will provide the best user experience, indeed

File: librz/util/subprocess.c (hunk 38 above)
Comment (XVilka) [reply librz/util/subprocess.c:161]: `""` is not a "space" though, it's an empty string.

File: test/db/cmd/feat_redirect [hunk 42]
```diff
@@ -2,9 +2,9 @@ NAME="pb>x;!wc -c x"
 FILE=malloc://1024
 CMDS=<<EOF
 p8 10 > dump
-!wc -c dump|awk "{print \$1}"
+!!wc -c dump|awk "{print \$1}"
```
Comment (XVilka) [inline test/db/cmd/feat_redirect]: Does this need to be updated too then?

File: test/db/cmd/cmd_system [hunk 43]
```diff
@@ -16,14 +16,14 @@ RUN
 
 NAME=!| grep
 FILE==
-CMDS=!echo magic|grep bob
+CMDS=!!echo magic|grep bob
```
Comment (XVilka) [inline test/db/cmd/cmd_system]: And here

**Review by XVilka — CHANGES_REQUESTED** [review]

File: test/db/cmd/feat_redirect (hunk 42 above)
Comment (ret2libc) [reply test/db/cmd/feat_redirect]: Yeah all these changes can be reverted back if we are ok with the auto detection.

File: librz/core/cmd_system.c [hunk 44]
```diff
@@ -143,7 +143,7 @@ static bool system_exec(RzCore *core, int argc, const char **argv, char **output
 		.envvals = envvals,
 		.env_size = RZ_ARRAY_SIZE(envvars),
 		.stdin_pipe = RZ_SUBPROCESS_PIPE_NONE,
-		.stdout_pipe = output ? RZ_SUBPROCESS_PIPE_CREATE : RZ_SUBPROCESS_PIPE_NONE,
+		.stdout_pipe = force_output || core->is_pipe ? RZ_SUBPROCESS_PIPE_CREATE : RZ_SUBPROCESS_PIPE_NONE,
```
Comment (wargio) [inline librz/core/cmd_system.c]: isn't easier to check for the output ptr?

Comment (ret2libc) [reply librz/core/cmd_system.c]: I was not sure it is possible to do that way, because when you execute `!<cmd>` in some cases you want the output, in others you don't want it. So from rz_system_handler you have to always pass the `output` var.

Comment (wargio) [reply librz/core/cmd_system.c]: yes, but the output needs to go somewhere and return it, so the output pointer MUST be non NULL.

Comment (wargio) [reply librz/core/cmd_system.c]: i would move the core->is_pipe check one function above, then pass the pointer accordingly to the check.
i mean, this way also works.

**Comment by XVilka** [comment]
```
clang-cl" "-Ibinrz/rz-test\rz-test.exe.p" "-I." "-I.." "-I..\librz\include" "-Isubprojects\sdb" "-I..\subprojects\sdb" "-Isubprojects\sdb\src" "-I..\subprojects\sdb\src" "-I..\shlr\spp" "/MD" "/nologo" "/showIncludes" "/W2" "/O2" "-fcommon" "-D__STDC__=1" "-D_CRT_DECLARE_NONSTDC_NAMES " "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_DEPRECATE" "-Werror=sizeof-pointer-memaccess" "/Fdbinrz/rz-test\rz-test.exe.p\run.c.pdb" /Fobinrz/rz-test/rz-test.exe.p/run.c.obj "/c" ../binrz/rz-test/run.c
../binrz/rz-test/run.c(12,10): error: 'unsigned char *' and 'char *' are not pointers to compatible types
                        !(str - start >= 4 && !strncmp(str - 4, RZ_CONS_CLEAR_SCREEN, 4))) {
                          ~~~ ^ ~~~~~
../binrz/rz-test/run.c(12,35): warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        !(str - start >= 4 && !strncmp(str - 4, RZ_CONS_CLEAR_SCREEN, 4))) {
                                                       ^~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h(272,44): note: passing argument to parameter '_Str1' here
    _In_reads_or_z_(_MaxCount) char const* _Str1,
                                           ^
../binrz/rz-test/run.c(13,33): warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        memmove(str, str + 1, strlen(str + 1) + 1);
                                                     ^~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h(216,24): note: passing argument to parameter '_Str' here
    _In_z_ char const* _Str
                       ^
2 warnings and 1 error generated.
[1510/1682] Linking target test/unit/auxiliary/subprocess-interactive.exe
```

**Comment by XVilka** [comment]
```
"cl" "-Ibinrz/rz-test\rz-test.exe.p" "-I." "-I.." "-I..\librz\include" "-Isubprojects\sdb" "-I..\subprojects\sdb" "-Isubprojects\sdb\src" "-I..\subprojects\sdb\src" "-I..\shlr\spp" "/MT" "/nologo" "/showIncludes" "/W2" "/O2" "/Gw" "/Fdbinrz/rz-test\rz-test.exe.p\run.c.pdb" /Fobinrz/rz-test/rz-test.exe.p/run.c.obj "/c" ../binrz/rz-test/run.c
../binrz/rz-test/run.c(9): error C2146: syntax error: missing ')' before identifier 's'
../binrz/rz-test/run.c(9): error C2059: syntax error: ')'
[1436/1658] Compiling C object binrz/rz-test/rz-test.exe.p/rz-test.c.obj
[1437/1658] Compiling C object binrz/rz-test/rz-test.exe.p/load.c.obj
ninja: build stopped: subcommand failed.
```

**Comment by XVilka** [comment]
```
FAILED: test/unit/test_subprocess.exe.p/test_subprocess.c.obj 
"clang-cl" "-Itest/unit\test_subprocess.exe.p" "-I." "-I.." "-I..\librz\include" "-Itest/unit" "-I..\test\unit" "-Isubprojects\sdb" "-I..\subprojects\sdb" "-Isubprojects\sdb\src" "-I..\subprojects\sdb\src" "-I..\shlr\spp" "-Ishlr" "-I..\shlr" "-I..\librz\asm\arch\include" "-I..\librz\asm\arch" "-I..\librz\asm\arch\h8300" "-I..\librz\asm\arch\hexagon" "-I..\librz\asm\arch\msp430" "-I..\librz\asm\arch\rsp" "-I..\librz\asm\arch\mcore" "-I..\librz\asm\arch\v850" "-I..\librz\asm\arch\propeller" "-I..\librz\asm\arch\ebc" "-I..\librz\asm\arch\cr16" "-I..\librz\asm\arch\8051" "-I..\librz\asm\arch\v810" "-I..\librz\asm\arch\or1k" "-I..\librz\analysis\arch\gb" "-I..\librz\analysis\arch\hexagon" "-I..\librz\bin\format\elf" "-I..\librz\bin\mangling" "-I..\librz\bin\format" "-I..\shlr\heap\include\rz_windows" "-I..\librz\type\parser" "/MD" "/nologo" "/showIncludes" "/W2" "/O2" "-fcommon" "-D__STDC__=1" "-D_CRT_DECLARE_NONSTDC_NAMES " "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_DEPRECATE" "-Werror=sizeof-pointer-memaccess" "/Fdtest/unit\test_subprocess.exe.p\test_subprocess.c.pdb" /Fotest/unit/test_subprocess.exe.p/test_subprocess.c.obj "/c" ../test/unit/test_subprocess.c
../test/unit/test_subprocess.c(17,10): error: 'unsigned char *' and 'char *' are not pointers to compatible types
                        !(str - start >= 4 && !strncmp(str - 4, RZ_CONS_CLEAR_SCREEN, 4))) {
                          ~~~ ^ ~~~~~
../test/unit/test_subprocess.c(17,35): warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        !(str - start >= 4 && !strncmp(str - 4, RZ_CONS_CLEAR_SCREEN, 4))) {
                                                       ^~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h(272,44): note: passing argument to parameter '_Str1' here
    _In_reads_or_z_(_MaxCount) char const* _Str1,
                                           ^
../test/unit/test_subprocess.c(18,33): warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        memmove(str, str + 1, strlen(str + 1) + 1);
                                                     ^~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h(216,24): note: passing argument to parameter '_Str' here
    _In_z_ char const* _Str
                       ^
2 warnings and 1 error generated.
[1659/1682] Compiling C object test/unit/test_task.exe.p/test_task.c.obj
[1660/1682] Compiling C object test/unit/test_tree.exe.p/test_tree.c.obj
ninja: build stopped: subcommand failed
```

**Review by ret2libc — APPROVED** [review]
To me things are in good shape right now. Good work @wargio !! Please review this as well, in particular the latest changes I did.

**Review by XVilka — APPROVED** [review]

File: librz/core/p/core_plugin_example.c (hunk 35 above)
Comment (wargio) [reply librz/core/p/core_plugin_example.c:3]: on my machine.
