### PR TITLE
Type parser can now handle parenthesized declarations correctly

### LINKED ISSUE #2190: `rz_type_parse_string_single` segfaults when parsing a complex type
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux, x86-64
| File format of the file you reverse (mandatory)      | Not relevant
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: ecfdb01ec772dfe978a585a540df6f86c340f73d, build: 2022-01-10__14:00:58

### Type causing segfault

```c
struct gamma {
    wchar_t (*(*dunk)[])(int, const char*);
} sigma;
```

### Expected behavior

No segmentation fault happens, and the type is parsed correctly.

### Actual behavior

`rz_type_parse_string_single` encounters a segmentation fault because of calling `strdup(NULL)`. Backtrace:

```
#1  0x00007fb4d9b32e3f in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007fb4d9c96c90 in parse_type_declarator_node (state=0x559070b67980, node=...,
    text=0x559070b89890 "__TYPE_EXPRESSION struct gamma {\n\twchar_t (*(*dunk)[])(int, const char*);\n} sigma;", tpair=0x7fff8adffee8,
    identifier=0x7fff8adffee0) at ../librz/type/parser/types_parser.c:1690
#3  0x00007fb4d9c91f3a in parse_struct_node (state=0x559070b67980, node=...,
    text=0x559070b89890 "__TYPE_EXPRESSION struct gamma {\n\twchar_t (*(*dunk)[])(int, const char*);\n} sigma;", tpair=0x7fff8ae00198,
    is_const=false) at ../librz/type/parser/types_parser.c:554
#4  0x00007fb4d9c948ef in parse_type_node_single (state=0x559070b67980, node=...,
    text=0x559070b89890 "__TYPE_EXPRESSION struct gamma {\n\twchar_t (*(*dunk)[])(int, const char*);\n} sigma;", tpair=0x7fff8ae00198,
    is_const=false) at ../librz/type/parser/types_parser.c:1183
#5  0x00007fb4d9c97122 in parse_type_descriptor_single (state=0x559070b67980, node=...,
    text=0x559070b89890 "__TYPE_EXPRESSION struct gamma {\n\twchar_t (*(*dunk)[])(int, const char*);\n} sigma;", tpair=0x7fff8ae00198)
    at ../librz/type/parser/types_parser.c:1762
#6  0x00007fb4d9c8f0fb in rz_type_parse_string_single (parser=0x559070b6dd10,
    code=0x559070b07470 "struct gamma {\n\twchar_t (*(*dunk)[])(int, const char*);\n} sigma;", error_msg=0x7fff8ae01638)
    at ../librz/type/parser/c_cpp_parser.c:354
```

### Steps to reproduce the behavior

Use the Rizin API and call `rz_type_parse_string_single` with appropriate arguments.

This bug was encountered while testing for #1272.

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [x] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Previous behavior:

```
[0x00000000]> td "struct foo { wchar_t (*(*bar)[])(int, const char*); }"
WARNING: c_parser_callable_type_store: assertion 'state && name && type' failed (line 99)
```

New behavior:

```
[0x00000000]> td "struct foo { wchar_t (*(*bar)[])(int, const char*); }"
[0x00000000]> tc foo
struct foo {
        wchar_t (*((*bar)[]))(int arg0, const char *arg1);
};
```

**Test plan**

Added an integration test and unit test for the type.

**Closing issues**

Closes #2190.

### CODE REVIEW

File: librz/type/function.c [hunk 1]
```diff
@@ -410,44 +415,111 @@ RZ_API bool rz_type_is_callable_ptr(RZ_NONNULL const RzType *type) {
...
+		return callable_ptr_unwrap(type->pointer.type, stack);
+	} else if (type->kind == RZ_TYPE_KIND_ARRAY) {
+		st64 *array_len = RZ_NEW(st64);
+		*array_len = type->array.count;
+		rz_stack_push(stack, array_len);
+
+		return callable_ptr_unwrap(type->array.type, stack);
 	}
+
 	return type->kind == RZ_TYPE_KIND_CALLABLE ? type->callable : NULL;
```
Comment (DMaroo) [inline librz/type/function.c:458]: Not sure if I should check here whether the type wrapping the callable is a pointer type. For example, the following type cannot be compiled but [cdecl](cdecl.org) parses it without error (and outputs the expected meaning).

```c
char (chunk[3])(int, const char *);
```

Should I be allowing such a type or not is the question? Or should I enforce that there cannot be direct function arrays and only pointers to functions are allowed?

Comment (notxvilka) [reply librz/type/function.c:458]: I don't think it makes any sense in the context of analyzing the compiled code - there are only function pointers in the disassembly. So I suppose only pointers to functions should be allowed.

**Review by notxvilka — CHANGES_REQUESTED** [review]
```
n function ‘callable_name_or_ptr’,
    inlined from ‘callable_as_string’ at ../librz/type/function.c:528:24,
    inlined from ‘callable_as_string’ at ../librz/type/function.c:521:13:
../librz/type/function.c:485:61: error: ‘last_kind’ may be used uninitialized [-Werror=maybe-uninitialized]
  485 |                         if (!innermost_wrapper && last_kind != current_kind) {
      |                                                   ~~~~~~~~~~^~~~~~~~~~~~~~~
../librz/type/function.c: In function ‘callable_as_string’:
../librz/type/function.c:470:28: note: ‘last_kind’ was declared here
  470 |                 RzTypeKind last_kind;
      |                            ^~~~~~~~~
cc1: all warnings being treated as errors
```
```
Missing type comment at <rizin/librz/type/function.c:443:98> (token is not a comment)
Missing type comment at <rizin/librz/type/function.c:461:102> (token is not a comment)
Missing type comment at <rizin/librz/type/function.c:521:131> (token is not a comment)
```

**Review by wargio — APPROVED** [review]
