### PR TITLE
Fix #1416: Fix `dte`

### LINKED ISSUE #1416: `dte` doesn't show ESIL trace
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 34 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/31fc5fbf22e60b2e681f4acc20bba82b9a83f079

### Expected behavior

`dte` shows the trace information

### Actual behavior

```
[0x00006b10]> aets+
```
Then if we step it multiple times, `dte` shows nothing

### Steps to reproduce the behavior

```
rizin /bin/ls
aei
aeim
aets+
# check registers for the initial state if everything is alright
5aes
# check registers that steps performed succesfully
dte
```
Moreover, if you run `aets-` after that, it shows:
```
[0x00006b10]> aets-
No ESIL trace started
```
Thus, likely `aets+` has never started

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes `dte` so that its output matches https://github.com/rizinorg/rizin/issues/1416#issuecomment-895775992, expect that the printing order has been changed to better reflect reality (not guaranteed to reflect reality though).

**Test plan**

Check whether trace is as expected. All builds should be green.

**Closing issues**

Closes #1416.

### CODE REVIEW

File: librz/analysis/esil/esil_trace.c [hunk 1]
```diff
@@ -367,7 +369,83 @@ RZ_API void rz_analysis_esil_trace_restore(RzAnalysisEsil *esil, int idx) {
 }
 
 static void print_instruction_trace(RzILTraceInstruction *instruction, int idx) {
-	printf("[%d]instruction addr -> %" PFMT64x "\n", idx, instruction->addr);
+	void **it;
+	bool first;
+	printf("%d.addr=0x%" PFMT64x "\n", idx, instruction->addr);
```
Comment (wargio) [inline librz/analysis/esil/esil_trace.c]: rz_cons here?

**Review by wargio — CHANGES_REQUESTED** [review]
same for all the other printf

File: librz/analysis/esil/esil_trace.c (hunk 1 above)
Comment (kazarmy) [reply librz/analysis/esil/esil_trace.c]: ok a9dcadf708ddcdf1f504032e8cbef732d664beb3

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
