### PR TITLE
String search performance improvement

### LINKED ISSUE #5369: Failing test: String Search -  utf16be - Armenian
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux
| File format of the file you reverse (mandatory)      | ...
| Architecture/bits of the file (mandatory)            | s390x be
| `rizin -v` full output, **not truncated** (mandatory)  | dev

### Expected behavior

Finds string

### Actual behavior

String not found

### Steps to reproduce the behavior

As in `test/db/cmd/cmd_search_z` `String Search - Encoding: utf16be - Armenian - Fast on BE systems`

### Additional Logs, screenshots, source code,  configuration dump, ...

https://app.travis-ci.com/github/rizinorg/rizin/jobs/635275629#L4550

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Based on: https://github.com/rizinorg/rizin/pull/5378

Improves performance of string searches which are unaligned or have a different endianness than the host system.

The improvements are:

UTF-32 foreign endianness and/or misaligned hits: `~0m17.768s => ~0m0.540s`
UTF-16 foreign endianness and/or misaligned hits: `~0m45.271s => ~0m0.463s`

**Test plan**

All green

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/5369

### CODE REVIEW

**Comment by notxvilka** [comment]
Rebase pls

**Review by notxvilka — CHANGES_REQUESTED** [review]
Rebase please

**Review by notxvilka — APPROVED** [review]

File: librz/include/rz_util/rz_regex.h [hunk 1]
```diff
@@ -74,6 +74,7 @@ typedef struct {
 		RzRegex16 *re16;
 		RzRegex32 *re32;
 	};
+	void *jit_stack; ///< The JIT stac for this pattern. Must only be used by one thread at a time.
```
Comment (notxvilka) [inline librz/include/rz_util/rz_regex.h]: A typo in `stac`

File: librz/search/options.c [hunk 2]
```diff
@@ -72,6 +72,11 @@ RZ_API bool rz_search_opt_set_max_threads(RZ_NONNULL RzSearchOpt *opt, RzThreadN
 	return true;
 }
 
+RZ_API size_t rz_search_opt_get_max_threads(RZ_NONNULL const RzSearchOpt *opt) {
```
Comment (notxvilka) [inline librz/search/options.c:78]: Maybe worth adding Doxygen too?

**Review by wargio — APPROVED** [review]
