### PR TITLE
RISCV: Make analysis function set mnemonic field to enable ROP search

### LINKED ISSUE #5545: regex search not work in risc-v binary
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | darwin arm 64
| File format of the file you reverse (mandatory)      | raw binary
| Architecture/bits of the file (mandatory)            | risc-v 64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.9.0 @ darwin-arm-64 commit: 856c28f1e8c7e2d3f6b9789d4d0f4aa70c6d242f

### Expected behavior
regex search should show all results which match the regex pattern, no FP, no TP

### Actual behavior
regex not work in risc-v binary

### Steps to reproduce the behavior
I am sry I can't share the origin binary, but I test it in a just random data, same issue.
I use following cmd to parse and search
```
rizin -a riscv b 64 -B 0x10000000 -nn test
```
this will show a lot results which shouldn't hit the search
```
/R/ "jal"
```
this will show nothing while there should be some result
```
/R/ "jalr.*a.*"
``` 

### Additional Logs, screenshots, source code,  configuration dump, ...

Image

### PR DESCRIPTION
**Pull request by moste00**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**
Fixing https://github.com/rizinorg/rizin/issues/5545, ROP search used to not work correctly with RISC-V

...

**Test plan**

...

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/5545

### CODE REVIEW

**Review by notxvilka — APPROVED** [review]

**Review by notxvilka — CHANGES_REQUESTED** [review]
Please add a test, if possible. But please use some small file so it can be finished quickly.

File: librz/arch/p/analysis/analysis_riscv_cs.c [hunk 1]
```diff
@@ -1911,6 +1911,8 @@ int analyze_op(RzAnalysis *analysis, RzAnalysisOp *op, ut64 addr, const ut8 *buf
 	}
 beach:
 	if (insn) {
+		op->mnemonic = rz_str_newf("%s %s", insn->mnemonic, insn->op_str);
```
Comment (wargio) [inline librz/arch/p/analysis/analysis_riscv_cs.c]:
```suggestion
		if (mask & RZ_ANALYSIS_OP_MASK_DISASM) {
			op->mnemonic = rz_str_newf("%s%s%s", insn->mnemonic, insn->op_str ? " " : "", rz_str_get(insn->op_str));
		}
```

File: librz/core/rop.c [hunk 2]
```diff
@@ -1539,6 +1539,8 @@ static void set_increment_based_on_arch(const RzCore *core, const char *arch, in
 		*increment = rz_config_get_i(core->config, "asm.bits") == 16 ? 2 : 4;
 	} else if (RZ_STR_EQ(arch, "avr")) { // AVR is halfword aligned.
 		*increment = 2;
+	} else if (RZ_STR_EQ(arch, "riscv")) {
+		*increment = 2;
```
Comment (wargio) [inline librz/core/rop.c]: there is an rz_analysis api for the PC alignment.

**Review by notxvilka — APPROVED** [review]
