### PR TITLE
Python 3.11

### LINKED ISSUE #3130: Python  3.12, and 3.13 versions bytecode support
- [x] https://docs.python.org/3.10/whatsnew/3.10.html
- [x] https://docs.python.org/3.11/whatsnew/3.11.html
- [ ] https://docs.python.org/3.12/whatsnew/3.12.html
- [ ] https://docs.python.org/3.13/whatsnew/3.13.html

See also `dis` module from the corresponding Python versions: https://docs.python.org/3/library/dis.html

The changes are possibly required in these files:
- https://github.com/rizinorg/rizin/tree/dev/librz/bin/format/pyc
- https://github.com/rizinorg/rizin/blob/dev/librz/bin/p/bin_pyc.c
- https://github.com/rizinorg/rizin/tree/dev/librz/asm/arch/pyc
- https://github.com/rizinorg/rizin/blob/dev/librz/analysis/p/analysis_pyc.c
- https://github.com/rizinorg/rizin/blob/dev/test/db/formats/pyc
- https://github.com/rizinorg/rizin-testbins/tree/master/pyc

# 3.10
CPython bytecode changes
The MAKE_FUNCTION instruction now accepts either a dict or a tuple of strings as the function’s annotations. (Contributed by Yurii Karabas and Inada Naoki in [bpo-42202](https://bugs.python.org/issue?@action=redirect&bpo=42202).)

# 3.11
<h2 style="font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; background-color: white; font-weight: normal; color: rgb(26, 26, 26); border: 0px; margin: 0px; padding: 0.3em 0px; font-size: 25.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CPython bytecode changes<a class="headerlink" href="https://docs.python.org/3.11/whatsnew/3.11.html#cpython-bytecode-changes" title="Permalink to this headline" style="color: rgb(0, 114, 170); text-decoration: none; visibility: hidden; font-size: 0.8em; padding: 0px 4px;"></a></h2><p style="hyphens: auto; text-align: left; line-height: 1.4; color: rgb(34, 34, 34); font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The bytecode now contains inline cache entries, which take the form of the newly-added<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-CACHE" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">CACHE</span></code></a><span> </span>instructions. Many opcodes expect to be followed by an exact number of caches, and instruct the interpreter to skip over them at runtime. Populated caches can look like arbitrary instructions, so great care should be taken when reading or modifying raw, adaptive bytecode containing quickened data.</p><section id="new-opcodes" style="color: rgb(34, 34, 34); font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span id="whatsnew311-added-opcodes"></span><h3 style="font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; background-color: white; font-weight: normal; color: rgb(26, 26, 26); border: 0px; margin: 0px; padding: 0.3em 0px; font-size: 22.4px;">New opcodes<a class="headerlink" href="https://docs.python.org/3.11/whatsnew/3.11.html#new-opcodes" title="Permalink to this headline" style="color: rgb(0, 114, 170); text-decoration: none; visibility: hidden; font-size: 0.8em; padding: 0px 4px;"></a></h3><ul class="simple"><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-ASYNC_GEN_WRAP" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">ASYNC_GEN_WRAP</span></code></a>,<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-RETURN_GENERATOR" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">RETURN_GENERATOR</span></code></a><span> </span>and<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-SEND" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">SEND</span></code></a>, used in generators and co-routines.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-COPY_FREE_VARS" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">COPY_FREE_VARS</span></code></a>, which avoids needing special caller-side code for closures.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-JUMP_BACKWARD_NO_INTERRUPT" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">JUMP_BACKWARD_NO_INTERRUPT</span></code></a>, for use in certain loops where handling interrupts is undesirable.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-MAKE_CELL" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">MAKE_CELL</span></code></a>, to create<span> </span><a class="reference internal" href="https://docs.python.org/3.11/c-api/cell.html#cell-objects" style="color: rgb(0, 114, 170); text-decoration: none;"><span class="std std-ref">Cell Objects</span></a>.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-CHECK_EG_MATCH" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">CHECK_EG_MATCH</span></code></a><span> </span>and<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-PREP_RERAISE_STAR" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">PREP_RERAISE_STAR</span></code></a>, to handle the<span> </span><a class="reference internal" href="https://docs.python.org/3.11/whatsnew/3.11.html#whatsnew311-pep654" style="color: rgb(0, 114, 170); text-decoration: none;"><span class="std std-ref">new exception groups and except*</span></a><span> </span>added in<span> </span><span class="target" id="index-30"></span><a class="pep reference external" href="https://peps.python.org/pep-0654/" style="color: rgb(0, 114, 170); text-decoration: none;"><strong>PEP 654</strong></a>.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-PUSH_EXC_INFO" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">PUSH_EXC_INFO</span></code></a>, for use in exception handlers.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;"><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-RESUME" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">RESUME</span></code></a>, a no-op, for internal tracing, debugging and optimization checks.</p></li></ul></section><section id="replaced-opcodes" style="color: rgb(34, 34, 34); font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span id="whatsnew311-replaced-opcodes"></span><h3 style="font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; background-color: white; font-weight: normal; color: rgb(26, 26, 26); border: 0px; margin: 0px; padding: 0.3em 0px; font-size: 22.4px;">Replaced opcodes<a class="headerlink" href="https://docs.python.org/3.11/whatsnew/3.11.html#replaced-opcodes" title="Permalink to this headline" style="color: rgb(0, 114, 170); text-decoration: none; visibility: hidden; font-size: 0.8em; padding: 0px 4px;"></a></h3><div class="responsive-table__container">

Replaced Opcode(s) | New Opcode(s) | Notes
-- | -- | --
BINARY_*INPLACE_* | BINARY_OP | Replaced all numeric binary/in-place opcodes with a single opcode
CALL_FUNCTIONCALL_FUNCTION_KWCALL_METHOD | CALLKW_NAMESPRECALLPUSH_NULL | Decouples argument shifting for methods from handling of keyword arguments; allows better specialization of calls
DUP_TOPDUP_TOP_TWOROT_TWOROT_THREEROT_FOURROT_N | COPYSWAP | Stack manipulation instructions
JUMP_IF_NOT_EXC_MATCH | CHECK_EXC_MATCH | Now performs check but doesn’t jump
JUMP_ABSOLUTEPOP_JUMP_IF_FALSEPOP_JUMP_IF_TRUE | JUMP_BACKWARDPOP_JUMP_BACKWARD_IF_*POP_JUMP_FORWARD_IF_* | See 3; TRUE, FALSE, NONE and NOT_NONE variants for each direction
SETUP_WITHSETUP_ASYNC_WITH | BEFORE_WITH | with block setup

</div><dl class="footnote brackets" style="margin-bottom: 15px;"><dt class="label" id="bytecode-jump" style="float: left; margin-right: 0.5em;"><span class="brackets"><a class="fn-backref" href="https://docs.python.org/3.11/whatsnew/3.11.html#id4" style="color: rgb(0, 114, 170); text-decoration: none;">3</a></span></dt><dd style="margin-top: 3px; margin-bottom: 0px; margin-left: 30px; hyphens: auto; text-align: left; line-height: 1.4;"><p style="margin-top: 0px; hyphens: auto; text-align: left; line-height: 1.4; margin-bottom: 0px;">All jump opcodes are now relative, including the existing<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-JUMP_IF_TRUE_OR_POP" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">JUMP_IF_TRUE_OR_POP</span></code></a><span> </span>and<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-JUMP_IF_FALSE_OR_POP" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">JUMP_IF_FALSE_OR_POP</span></code></a>. The argument is now an offset from the current instruction rather than an absolute location.</p></dd></dl></section><section id="changed-removed-opcodes" style="color: rgb(34, 34, 34); font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span id="whatsnew311-changed-removed-opcodes"></span><span id="whatsnew311-removed-opcodes"></span><span id="whatsnew311-changed-opcodes"></span><h3 style="font-family: &quot;Lucida Grande&quot;, Arial, sans-serif; background-color: white; font-weight: normal; color: rgb(26, 26, 26); border: 0px; margin: 0px; padding: 0.3em 0px; font-size: 22.4px;">Changed/removed opcodes<a class="headerlink" href="https://docs.python.org/3.11/whatsnew/3.11.html#changed-removed-opcodes" title="Permalink to this headline" style="color: rgb(0, 114, 170); text-decoration: none; visibility: hidden; font-size: 0.8em; padding: 0px 4px;"></a></h3><ul class="simple"><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;">Changed<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-MATCH_CLASS" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">MATCH_CLASS</span></code></a><span> </span>and<span> </span><a class="reference internal" href="https://docs.python.org/3.11/library/dis.html#opcode-MATCH_KEYS" style="color: rgb(0, 114, 170); text-decoration: none;"><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">MATCH_KEYS</span></code></a><span> </span>to no longer push an additional boolean value to indicate success/failure. Instead,<span> </span><code class="docutils literal notranslate" style="background-color: rgb(236, 240, 243); padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">None</span></code><span> </span>is pushed on failure in place of the tuple of extracted values.</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;">Changed opcodes that work with exceptions to reflect them now being represented as one item on the stack instead of three (see<span> </span><a class="reference external" href="https://github.com/python/cpython/issues/89874" style="color: rgb(0, 114, 170); text-decoration: none;">gh-89874</a>).</p></li><li style="hyphens: auto; text-align: left; line-height: 1.4;"><p style="hyphens: auto; margin-bottom: 0px; text-align: left; line-height: 1.4; margin-top: 0px;">Removed<span> </span><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">COPY_DICT_WITHOUT_KEYS</span></code>,<span> </span><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">GEN_START</span></code>,<span> </span><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">POP_BLOCK</span></code>,<span> </span><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">SETUP_FINALLY</span></code><span> </span>and<span> </span><code class="xref std std-opcode docutils literal notranslate" style="background-color: transparent; padding: 0px 1px; font-size: 15.44px; font-family: ui-monospace, &quot;Cascadia Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Liberation Mono&quot;, Menlo, Monaco, Consolas, monospace; font-weight: normal; border-radius: 3px;"><span class="pre" style="hyphens: none; white-space: nowrap;">YIELD_FROM</span></code>.</p></li></ul></section>CPython bytecode changes
The bytecode now contains inline cache entries, which take the form of the newly-added [CACHE](https://docs.python.org/3.11/library/dis.html#opcode-CACHE) instructions. Many opcodes expect to be followed by an exact number of caches, and instruct the interpreter to skip over them at runtime. Populated caches can look like arbitrary instructions, so great care should be taken when reading or modifying raw, adaptive bytecode containing quickened data.

New opcodes
[ASYNC_GEN_WRAP](https://docs.python.org/3.11/library/dis.html#opcode-ASYNC_GEN_WRAP), [RETURN_GENERATOR](https://docs.python.org/3.11/library/dis.html#opcode-RETURN_GENERATOR) and [SEND](https://docs.python.org/3.11/library/dis.html#opcode-SEND), used in generators and co-routines.

[COPY_FREE_VARS](https://docs.python.org/3.11/library/dis.html#opcode-COPY_FREE_VARS), which avoids needing special caller-side code for closures.

[JUMP_BACKWARD_NO_INTERRUPT](https://docs.python.org/3.11/library/dis.html#opcode-JUMP_BACKWARD_NO_INTERRUPT), for use in certain loops where handling interrupts is undesirable.

[MAKE_CELL](https://docs.python.org/3.11/library/dis.html#opcode-MAKE_CELL), to create [Cell Objects](https://docs.python.org/3.11/c-api/cell.html#cell-objects).

[CHECK_EG_MATCH](https://docs.python.org/3.11/library/dis.html#opcode-CHECK_EG_MATCH) and [PREP_RERAISE_STAR](https://docs.python.org/3.11/library/dis.html#opcode-PREP_RERAISE_STAR), to handle the [new exception groups and except*](https://docs.python.org/3.11/whatsnew/3.11.html#whatsnew311-pep654) added in [PEP 654](https://peps.python.org/pep-0654/).

[PUSH_EXC_INFO](https://docs.python.org/3.11/library/dis.html#opcode-PUSH_EXC_INFO), for use in exception handlers.

[RESUME](https://docs.python.org/3.11/library/dis.html#opcode-RESUME), a no-op, for internal tracing, debugging and optimization checks.

Replaced opcodes
Replaced Opcode(s)

New Opcode(s)

Notes

BINARY_*
INPLACE_*
[BINARY_OP](https://docs.python.org/3.11/library/dis.html#opcode-BINARY_OP)

Replaced all numeric binary/in-place opcodes with a single opcode

CALL_FUNCTION
CALL_FUNCTION_KW
CALL_METHOD
[CALL](https://docs.python.org/3.11/library/dis.html#opcode-CALL)
[KW_NAMES](https://docs.python.org/3.11/library/dis.html#opcode-KW_NAMES)
[PRECALL](https://docs.python.org/3.11/library/dis.html#opcode-PRECALL)
[PUSH_NULL](https://docs.python.org/3.11/library/dis.html#opcode-PUSH_NULL)
Decouples argument shifting for methods from handling of keyword arguments; allows better specialization of calls

DUP_TOP
DUP_TOP_TWO
ROT_TWO
ROT_THREE
ROT_FOUR
ROT_N
[COPY](https://docs.python.org/3.11/library/dis.html#opcode-COPY)
[SWAP](https://docs.python.org/3.11/library/dis.html#opcode-SWAP)
Stack manipulation instructions

JUMP_IF_NOT_EXC_MATCH
[CHECK_EXC_MATCH](https://docs.python.org/3.11/library/dis.html#opcode-CHECK_EXC_MATCH)
Now performs check but doesn’t jump

JUMP_ABSOLUTE
POP_JUMP_IF_FALSE
POP_JUMP_IF_TRUE
[JUMP_BACKWARD](https://docs.python.org/3.11/library/dis.html#opcode-JUMP_BACKWARD)
[POP_JUMP_BACKWARD_IF_*](https://docs.python.org/3.11/library/dis.html#opcode-POP_JUMP_BACKWARD_IF_TRUE)
[POP_JUMP_FORWARD_IF_*](https://docs.python.org/3.11/library/dis.html#opcode-POP_JUMP_FORWARD_IF_TRUE)
See [3](https://docs.python.org/3.11/whatsnew/3.11.html#bytecode-jump); TRUE, FALSE, NONE and NOT_NONE variants for each direction

SETUP_WITH
SETUP_ASYNC_WITH
[BEFORE_WITH](https://docs.python.org/3.11/library/dis.html#opcode-BEFORE_WITH)

[with](https://docs.python.org/3.11/reference/compound_stmts.html#with) block setup

[3](https://docs.python.org/3.11/whatsnew/3.11.html#id4)
All jump opcodes are now relative, including the existing [JUMP_IF_TRUE_OR_POP](https://docs.python.org/3.11/library/dis.html#opcode-JUMP_IF_TRUE_OR_POP) and [JUMP_IF_FALSE_OR_POP](https://docs.python.org/3.11/library/dis.html#opcode-JUMP_IF_FALSE_OR_POP). The argument is now an offset from the current instruction rather than an absolute location.

Changed/removed opcodes
Changed [MATCH_CLASS](https://docs.python.org/3.11/library/dis.html#opcode-MATCH_CLASS) and [MATCH_KEYS](https://docs.python.org/3.11/library/dis.html#opcode-MATCH_KEYS) to no longer push an additional boolean value to indicate success/failure. Instead, None is pushed on failure in place of the tuple of extracted values.

Changed opcodes that work with exceptions to reflect them now being represented as one item on the stack instead of three (see [gh-89874](https://github.com/python/cpython/issues/89874)).

Removed COPY_DICT_WITHOUT_KEYS, GEN_START, POP_BLOCK, SETUP_FINALLY and YIELD_FROM.

# 3.12

- Removed the [LOAD_METHOD](https://docs.python.org/3.12/library/dis.html#opcode-LOAD_METHOD) instruction. It has been merged into [LOAD_ATTR](https://docs.python.org/3.12/library/dis.html#opcode-LOAD_ATTR). [LOAD_ATTR](https://docs.python.org/3.12/library/dis.html#opcode-LOAD_ATTR) will now behave like the old [LOAD_METHOD](https://docs.python.org/3.12/library/dis.html#opcode-LOAD_METHOD) instruction if the low bit of its oparg is set. (Contributed by Ken Jin in [gh-93429](https://github.com/python/cpython/issues/93429).)

- Removed the JUMP_IF_FALSE_OR_POP and JUMP_IF_TRUE_OR_POP instructions. (Contributed by Irit Katriel in [gh-102859](https://github.com/python/cpython/issues/102859).)

# 3.13

The oparg of [YIELD_VALUE](https://docs.python.org/3.13/library/dis.html#opcode-YIELD_VALUE) is now 1 if the yield is part of a yield-from or await, and 0 otherwise. The oparg of [RESUME](https://docs.python.org/3.13/library/dis.html#opcode-RESUME) was changed to add a bit indicating if the except-depth is 1, which is needed to optimize closing of generators. (Contributed by Irit Katriel in [gh-111354](https://github.com/python/cpython/issues/111354).)

### PR DESCRIPTION
**Pull request by well-mannered-goat**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Added  version support for python 3.11.0 version
- added magic numbers for new versions
- modified marshal to read new fields from pyc file like localplusnames, localpluskinds,qualname,exceptiontable
- extracting varnames, freevars, cellvars from localplusnames, localpluskinds
- adding new opcodes
- added analysis for the new opcodes
- added some missing opcodes I found
- added test for pyc 3.11.0 version

the dis module of python also prints out exceptions at the end of a code object. I didnt really find doc for it so didnt implement it as of now, would implement in the next version upgrade if I find something.

If I miss out on something, let me know
There were many new changes added in 3.11.0 version, I have tried to add most of them.

**Test plan**

I will be pushing the 3.11.0 pyc file in rizin-testbins

rz-test test/db/formats/pyc

**Closing issues**

partially closes #3130

### CODE REVIEW

File: librz/bin/format/pyc/pyc_magic.c [hunk 1]
```diff
@@ -261,13 +261,44 @@ static struct pyc_version versions[] = {
...
+	{ 0x0a0d0dcb, "v3.12.0b2", "6e0c8ff5e51c733a0414c08c6246cf5014489d26" },
+	{ 0x0a0d0dcb, "v3.12.0b3", "458da29f0fa8370c9cdce0ffa15db7ff5de5b00a" },
+	{ 0x0a0d0dcb, "v3.12.0b4", "9a57b2d1665d34237a7f6070a823c30aa7861c6a" },
+	{ 0x0a0d0dcb, "v3.12.0rc1", "63bcd91daccc7c873d57e21406d038f8216b6ddf" },
+	{ 0x0a0d0dcb, "v3.12.0rc2", "f1dc634f853e1eaa581920955d50da51e05203d4" },
+	{ 0x0a0d0dcb, "v3.12.0rc3", "8dec3349e7786a9d0aef3f127c9923daf4169f9d" },
+	{ 0x0a0d0dcb, "v3.12.1", "2305ca51448552542b2414186252123a8dc87db7" },
+	{ 0x0a0d0dcb, "v3.12.2", "961fed42b52f83d2e6d63f33b5f395002e0c9325" },
+	{ 0x0a0d0dcb, "v3.12.3", "f6650f9ad73359051f3e558c2431a109bc016664" },
+	{ 0x0a0d0dcb, "v3.12.4", "8e8a4baf652f6e1cee7acde9d78c4b6154539748" },
```
Comment (notxvilka) [inline librz/bin/format/pyc/pyc_magic.c:301]: Could you please add values for `3.13` series? Just versions

**Review by notxvilka — CHANGES_REQUESTED** [review]
.

**Comment by notxvilka** [comment]
@well-mannered-goat please also rebase to trigger all tests

File: librz/bin/format/pyc/marshal.c [hunk 2]
```diff
@@ -882,6 +892,57 @@ static pyc_object *copy_object(pyc_object *object) {
 	return copy;
 }
 
+// populate varnames, freevars, cellvars version >=3.11.0
+
+static void extract_variables_from_localplus(pyc_object *localplusnames, pyc_object *localpluskinds, pyc_object **varnames, pyc_object **freevars, pyc_object **cellvars, bool *error) {
```
Comment (notxvilka) [inline librz/bin/format/pyc/marshal.c]: Please split this long line

File: librz/bin/format/pyc/marshal.c [hunk 3]
```diff
@@ -882,6 +892,57 @@ static pyc_object *copy_object(pyc_object *object) {
...
+	}
+
+	RzList *names_list = (RzList *)localplusnames->data;
+	ut8 *kinds_list = (ut8 *)localpluskinds->data;
+
+	*varnames = RZ_NEW0(pyc_object);
+	*freevars = RZ_NEW0(pyc_object);
+	*cellvars = RZ_NEW0(pyc_object);
+
+	if (!*varnames || !*cellvars || !*freevars) {
```
Comment (notxvilka) [inline librz/bin/format/pyc/marshal.c:916]: Memory leaks here

File: librz/bin/format/pyc/marshal.c [hunk 4]
```diff
@@ -996,6 +1075,16 @@ static pyc_object *get_code_object(RzBinPycObj *pyc, RzBuffer *buffer) {
...
 	}
 
+	if (v311_to_latest) {
+		cobj->exceptiontable = get_object(pyc, buffer);
+	} else {
+		cobj->exceptiontable = NULL;
+	}
+
+	if (v311_to_latest) {
+		extract_variables_from_localplus(cobj->localsplusnames, cobj->localspluskinds, &cobj->varnames, &cobj->freevars, &cobj->cellvars, &error);
```
Comment (notxvilka) [inline librz/bin/format/pyc/marshal.c]: Split the line

**Review by notxvilka — CHANGES_REQUESTED** [review]

**Comment by well-mannered-goat** [comment]
found out that i had missed out on analysis of some opcodes, added it
i was thinking of adding 3.12.0 and 3.13.0 version support after this, should i do it in this PR itself??

i havent read the docs extensively yet, but thought that 3.11.0 had many changes so might as well submit a PR for review

thanks for the help :)

**Comment by notxvilka** [comment]
> found out that i had missed out on analysis of some opcodes, added it i was thinking of adding 3.12.0 and 3.13.0 version support after this, should i do it in this PR itself??

I recommend keeping separate PRs for 3.12 and 3.13

**Review by notxvilka — APPROVED** [review]
@Rot127 @wargio please take a look too

File: librz/arch/isa/pyc/opcode_analysis.c [hunk 5]
```diff
@@ -894,6 +894,14 @@ static void analysis_POP_JUMP_FORWARD_IF_FALSE(RzAnalysisOp *op, pyc_opcode_obje
 	op->type = RZ_ANALYSIS_OP_TYPE_CJMP;
 }
 
+static void analysis_POP_JUMP_FORWARD_IF_NOT_NONE(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_analysis.c]: `inline` please

Comment (Rot127) [reply librz/arch/isa/pyc/opcode_analysis.c]: Also all the others.

File: librz/arch/isa/pyc/opcode_311.c [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+
+#include "opcode.h"
+
+pyc_opcodes *opcode_311(void) {
+	pyc_opcodes *ret = opcode_310();
+	if (!ret) {
+		return NULL;
+	}
+
+	ret->version_sig = (void *(*)())opcode_310;
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_311.c]: Please define the function pointer in a separated `typedef` and then cast here.

File: librz/arch/isa/pyc/opcode_311.c [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+	rm_op(.op_obj = ret->opcodes, .op_name = "SETUP_FINALLY", .op_code = 122);
+	rm_op(.op_obj = ret->opcodes, .op_name = "YIELD_FROM", .op_code = 72);
+	// // Remove BINARY_*
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_MATRIX_MULTIPLY", .op_code = 16);
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_POWER", .op_code = 19);
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_MULTIPLY", .op_code = 20);
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_MODULO", .op_code = 22);
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_ADD", .op_code = 23);
+	rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_SUBTRACT", .op_code = 24);
+	// rm_op(.op_obj = ret->opcodes, .op_name = "BINARY_SUBSCR", .op_code = 25); Still there in source code, docs mention BINARY_* removed
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_311.c]:
```suggestion
```

File: librz/arch/isa/pyc/opcode_311.c [hunk 8]
```diff
@@ -0,0 +1,114 @@
...
+
+	// // New Opcodes
+	def_op(.op_obj = ret->opcodes, .op_name = "ASYNC_GEN_WRAP", .op_code = 87, .pop = 1, .push = 1);
+	def_op(.op_obj = ret->opcodes, .op_name = "RETURN_GENERATOR", .op_code = 75, .pop = 0, .push = 0);
+	def_op(.op_obj = ret->opcodes, .op_name = "SEND", .op_code = 123, .pop = 1, .push = 1);
+	def_op(.op_obj = ret->opcodes, .op_name = "COPY_FREE_VARS", .op_code = 149, .pop = 0, .push = 0);
+	def_op(.op_obj = ret->opcodes, .op_name = "MAKE_CELL", .op_code = 135, .pop = 0, .push = 0);
+
+	def_op(.op_obj = ret->opcodes, .op_name = "CHECK_EXC_MATCH", .op_code = 36, .pop = 1, .push = 1);
+	def_op(.op_obj = ret->opcodes, .op_name = "CHECK_EG_MATCH", .op_code = 37, .pop = 9, .push = 1); // Conditional pushing and popping, I dont know how that is implemented in analysis.
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_311.c]:
```suggestion
	def_op(.op_obj = ret->opcodes, .op_name = "CHECK_EG_MATCH", .op_code = 37, .pop = 9, .push = 1);
```

Seems to be resolved in opcode_analysis.c?

File: librz/arch/isa/pyc/opcode_analysis.c [hunk 9]
```diff
@@ -732,6 +732,204 @@ static void analysis_SETUP_ASYNC_WITH(RzAnalysisOp *op, pyc_opcode_object *op_ob
...
+	analysis_push(op, op_obj, oparg, RZ_ANALYSIS_OP_TYPE_UNK, 1);
+}
+
+static void analysis_RESUME(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_NOP;
+}
+
+static void analysis_JUMP_BACKWARD_NO_INTERRUPT(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_JMP;
+	op->jump = op->addr + 2 - 2 * oparg; // addr + ((is_python36) ? 2 : 3) - JMP_OFFSET(ops, oparg);
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_analysis.c]:
```suggestion
	op->jump = op->addr + 2 - 2 * oparg;
```

File: librz/arch/isa/pyc/opcode_analysis.c [hunk 10]
```diff
@@ -732,6 +732,204 @@ static void analysis_SETUP_ASYNC_WITH(RzAnalysisOp *op, pyc_opcode_object *op_ob
...
+	analysis_push(op, op_obj, oparg, RZ_ANALYSIS_OP_TYPE_PUSH, 1);
+}
+
+static void analysis_SWAP(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_UNK;
+}
+
+static void analysis_JUMP_BACKWARD(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_JMP;
+	op->jump = op->addr + 2 - 2 * oparg; // addr + ((is_python36) ? 2 : 3) - JMP_OFFSET(ops, oparg);
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_analysis.c]:
```suggestion
	op->jump = op->addr + 2 - 2 * oparg;
```

File: librz/arch/isa/pyc/opcode_analysis.c [hunk 11]
```diff
@@ -732,6 +732,204 @@ static void analysis_SETUP_ASYNC_WITH(RzAnalysisOp *op, pyc_opcode_object *op_ob
...
+	op->type = RZ_ANALYSIS_OP_TYPE_CJMP;
+}
+
+static void analysis_POP_JUMP_FORWARD_IF_NONE(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_CJMP;
+}
+
+static void analysis_POP_JUMP_BACKWARD_IF_TRUE(RzAnalysisOp *op, pyc_opcode_object *op_obj, ut32 oparg) {
+	op->type = RZ_ANALYSIS_OP_TYPE_CJMP;
+	op->jump = op->addr + 2 - 2 * oparg; // addr + ((is_python36) ? 2 : 3) - JMP_OFFSET(ops, oparg);
```
Comment (Rot127) [inline librz/arch/isa/pyc/opcode_analysis.c]: Also here, remove the comment. If those comments should hint to different behavior for Python 3.6, please make this more explicit and write it out. Otherwise, it is hard to understand.

File: librz/bin/format/pyc/marshal.c [hunk 12]
```diff
@@ -882,6 +892,66 @@ static pyc_object *copy_object(pyc_object *object) {
...
+	(*cellvars)->type = localplusnames->type;
+
+	RzListIter *iter;
+	pyc_object *name;
+	int offset = 0;
+
+	rz_list_foreach (names_list, iter, name) {
+		ut8 kind = kinds_list[offset];
+
+		if (kind & 0x20) { // CO_FAST_LOCAL
```
Comment (Rot127) [inline librz/bin/format/pyc/marshal.c]: Can you move those magic numbers `0x20`, `0x40` etc into some `#defines` please? What the bits mean.

```
#define RZ_PYC_311_CO_FAST_LOCAL 0x20
```

I suppose? You can remove the comments afterwards.

**Review by Rot127 — CHANGES_REQUESTED** [review]
Good job! I have just those nitpicks.
Please run the tests with LSAN enabled to check for leaks, if you haven't done so already.

File: librz/arch/isa/pyc/opcode_311.c (hunk 8 above)
Comment (well-mannered-goat) [reply librz/arch/isa/pyc/opcode_311.c]: I dont think so, I tried reading for some opcodes of previous versions that pushed and popped conditionally.
but didnt find something of use, and in opcode_*.c most of the time they are defined with pop=9 and push=1

File: librz/arch/isa/pyc/opcode_analysis.c (hunk 11 above)
Comment (well-mannered-goat) [reply librz/arch/isa/pyc/opcode_analysis.c]: i have taken it from analysis_pyc.c i believe, initially opcodes have their jump values initialized there, and each opcode has its analysis (if a function for it exists).

from python 3.11.0 version jump opcodes are relative, and so backward jumps have positive argument but go backwards

I can explicitly define a function just like analysis_pop and analysis_push i guess in opcode_analysis.c

File: librz/bin/format/pyc/marshal.c (hunk 12 above)
Comment (well-mannered-goat) [reply librz/bin/format/pyc/marshal.c]: will do it

File: librz/arch/isa/pyc/opcode_311.c (hunk 8 above)
Comment (Rot127) [reply librz/arch/isa/pyc/opcode_311.c]: Conditional instructions are generally marked with the `op_type`. There is a `RZ_ANALYSIS_OP_TYPE_COND` bit to set. Even if it doesn't have much impact, you can set it. Just for the future. So we don't miss known information.

Comment (well-mannered-goat) [reply librz/arch/isa/pyc/opcode_311.c]: oh ok

File: librz/arch/isa/pyc/opcode_analysis.c (hunk 10 above)
Comment (wargio) [reply librz/arch/isa/pyc/opcode_analysis.c]: add some parenthesis

**Review by Rot127 — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]
