### PR TITLE
When initializing the types DB look at build directory first.

### LINKED ISSUE #2905: Failing `analysis_global_var` on v0.4.1 release
My environment: ArchLinux, x86_64, GCC 12.1.1 20220730

1. Get https://github.com/rizinorg/rizin/releases/download/v0.4.0/rizin-src-v0.4.0.tar.xz
2. Unpack it, and cd into rizin-v0.4.0
3. Get test/bins: make -C test/bins (I got 7d0c31ac7711de9c4d37f5047200dc5a407ff713)
4. Run: meson -Duse_sys_libzip=enabled build
   Note: with bundled libzip, build will fail with:
```
../subprojects/libzip-1.7.3/lib/zip_name_locate.c:65:41: error: ‘strcasecmp’ undeclared (first use in this function); did you mean ‘strncmp’?
```
5. Run test: cd build; ninja test
```
[...]
 91/103 rizin:integration / analysis_global_var                     FAIL            0.11s   exit status 1
>>> MALLOC_PERTURB_=45 /home/iyzsong/tmp/rizin-v0.4.0/build/test/integration/test_analysis_global_var
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
test_rz_analysis_global_var ERR
[XX] Fail at line 51: get global var by addr: expected to not be NULL but it was.

test_flag_confusion_space_name OK
test_flag_confusion_addr OK
test_flag_confusion_delete ERR
[XX] Fail at line 227: get global var by addr: expected to not be NULL but it was.

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

 92/103 rizin:integration / bin                                     OK              0.03s
 93/103 rizin:integration / bin_vfiles                              OK              0.04s
 94/103 rizin:integration / autocmplt                               OK              0.31s
 95/103 rizin:integration / cpu_platform_profiles                   OK              0.16s
 96/103 rizin:integration / dwarf_info                              OK              0.02s
 97/103 rizin:integration / dwarf                                   OK              0.07s
 98/103 rizin:integration / open_analyse_save_load_project          OK              3.09s
 99/103 rizin:integration / pdb                                     OK              0.17s
100/103 rizin:integration / project_migrate                         OK              0.22s
101/103 rizin:integration / rzpipe                                  OK              0.10s
102/103 rizin:integration / dwarf_integration                       OK              3.70s
103/103 rizin:integration / sign_integration                        FAIL            0.14s   exit status 1
>>> MALLOC_PERTURB_=169 /home/iyzsong/tmp/rizin-v0.4.0/build/test/integration/test_sign_integration
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
test_analysis_sign_za_ppc ERR
[XX] Fail at line 59: vars count: expected 7, got 5.

test_analysis_sign_za_mips ERR
[XX] Fail at line 134: vars count: expected 17, got 13.

stderr:
WARNING: No calling convention defined for this file, analysis may be inaccurate.
WARNING: No calling convention defined for this file, analysis may be inaccurate.
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

 91/103 rizin:integration / analysis_global_var            FAIL            0.11s   exit status 1
103/103 rizin:integration / sign_integration               FAIL            0.14s   exit status 1

Ok:                 101
Expected Fail:      0
Fail:               2
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

### PR DESCRIPTION
**Pull request by arrowd**
This removes the need for header hacks in units tests. Partially fixes #2905

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [X] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

`ninja test` now passes more tests without prior `ninja install`.

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/2905

### CODE REVIEW

File: librz/analysis/analysis.c [hunk 1]
```diff
@@ -294,7 +294,9 @@ RZ_API bool rz_analysis_set_bits(RzAnalysis *analysis, int bits) {
 			rz_type_db_set_bits(analysis->typedb, bits);
 			rz_type_db_set_address_bits(analysis->typedb, rz_analysis_get_address_bits(analysis));
 			if (!is_hack) {
-				char *types_dir = rz_path_system(RZ_SDB_TYPES);
+				char *types_dir = rz_path_realpath(RZ_BUILD_SDB_TYPES);
+				if (!types_dir)
+					types_dir = rz_path_system(RZ_SDB_TYPES);
```
Comment (wargio) [inline librz/analysis/analysis.c]: brackets.

**Comment by wargio** [comment]
```
test_dwarf_function_parsing_go ERR
[XX] Fail at line 238: Wrong key - value pair: expected fcn, got NULL.
```

**Comment by arrowd** [comment]
> ```
> test_dwarf_function_parsing_go ERR
> [XX] Fail at line 238: Wrong key - value pair: expected fcn, got NULL.
> ```

Hmm, I don't see this locally. Maybe try `meson --wipe` to rule out meson sillyness?

**Comment by XVilka** [comment]
When green, it should be resent from `dist-` branch from inside rizinorg to trigger all possible CI jobs.

**Review by ret2libc — CHANGES_REQUESTED** [review]
I think this fix is not right, because the "build" directory in Rizin does not make sense (the build dir is just a development concept, you won't have a build dir when a user installs rizin).

What is the problem you are trying to solve with this patch? Maybe we can find an alternative solution.

**Comment by arrowd** [comment]
Running `ninja test` right after compiling rizin doesn't work because it looks for its data files in the installation prefix.

**Comment by ret2libc** [comment]
> Running `ninja test` right after compiling rizin doesn't work because it looks for its data files in the installation prefix.

Did you try `meson test` instead of `ninja test`? AFAIR https://github.com/rizinorg/rizin/blob/dev/test/unit/meson.build#L3 was done on purpose to fix this issue.

**Comment by arrowd** [comment]
> Did you try meson test instead of ninja test?

It is the same

> AFAIR https://github.com/rizinorg/rizin/blob/dev/test/unit/meson.build#L3 was done on purpose to fix this issue.

Yep, it doesn't cover all cases. This test fails for me: https://github.com/rizinorg/rizin/blob/dev/test/unit/test_analysis_var.c#L290

**Comment by ret2libc** [comment]
I see.

You should apply this patch:
```diff
diff --git a/test/integration/meson.build b/test/integration/meson.build
index df95e0ddd0..2743147d2d 100644
--- a/test/integration/meson.build
+++ b/test/integration/meson.build
@@ -1,6 +1,7 @@
 if get_option('enable_tests')
   test_conf_data = configuration_data()
   test_conf_data.set_quoted('RIZIN_BUILD_PATH', rizin_exe.full_path())
+  test_conf_data.set_quoted('TEST_BUILD_TYPES_DIR', fs.as_posix(types_build_dir))
   test_config_h = configure_file(
     input: 'test_config.h.in',
     output: 'test_config.h',
```

and then do something like this:
```diff
@@ -27,9 +28,8 @@ static bool test_parse_dwarf_types(void) {
        // TODO fix, how to correctly promote binary info to the RzAnalysis in unit tests?
        rz_analysis_set_cpu(analysis, "x86");
        rz_analysis_set_bits(analysis, 32);
-       char *types_dir = rz_path_system(RZ_SDB_TYPES);
+       const char *types_dir = TEST_BUILD_TYPES_DIR;
        rz_type_db_init(analysis->typedb, types_dir, "x86", 32, "linux");
-       free(types_dir);
```
or this
```diff
diff --git a/test/integration/test_analysis_global_var.c b/test/integration/test_analysis_global_var.c
index a87d30163b..5acf24f821 100644
--- a/test/integration/test_analysis_global_var.c
+++ b/test/integration/test_analysis_global_var.c
@@ -3,12 +3,16 @@

 #include <rz_analysis.h>
 #include <rz_core.h>
+#include "test_config.h"
 #include "../unit/minunit.h"

 bool test_rz_analysis_global_var() {
        RzCore *core = rz_core_new();
        RzAnalysis *analysis = core->analysis;

+       const char *types_dir = TEST_BUILD_TYPES_DIR;
+       rz_type_db_init(analysis->typedb, types_dir, "x86", 32, "linux");
+
        RzAnalysisVarGlobal *glob = rz_analysis_var_global_new("foo", 0x1337);
        mu_assert_notnull(glob, "create a global variable");
        mu_assert_streq(glob->name, "foo", "global var name");
```

In other words, there are some places that are still using the default `RZ_SDB_TYPES` directory, however tests should use the `TEST_BUILD_TYPES_DIR`. It is not ideal, but it's better to change the tests rather than introducing code in the real code that is not used by end users.

**Comment by arrowd** [comment]
Yes, this change also fixes the testcase for me.

**Comment by ret2libc** [comment]
> Yes, this change also fixes the testcase for me.

Great! Happy it worked.
Could you also fix the problem in the other places under `test/` where `RZ_SDB_TYPES` is used instead of `TEST_BUILD_TYPES_DIR`, please?

**Comment by arrowd** [comment]
Absolutely. I just thought it is better to do iteratively with small PRs. Do you want a large one instead?

**Comment by ret2libc** [comment]
I think it's fine to do it in this PR because although you are going to touch a few lines the changes should look all the same. Also, keep in mind you should touch only the test files, not the other files.

**Comment by arrowd** [comment]
How do I initialize `analysis->sdb_cc` with build dir path?

**Comment by wargio** [comment]
> How do I initialize `analysis->sdb_cc` with build dir path?

https://github.com/rizinorg/rizin/blob/dev/librz/core/canalysis.c#L5574

**Comment by ret2libc** [comment]
> How do I initialize `analysis->sdb_cc` with build dir path?

Where/why do you need it?

**Comment by arrowd** [comment]
test/unit/test_analysis_var fails for me with

[XX] Fail at line 389: rz_analysis_var_is_arg based on call conversion rdi: expected true, got false

I suspect this is because calling convention database isn't populated (`fcn->cc` is NULL). Am I wrong in my analysis?

**Comment by wargio** [comment]
add a check if not null

**Comment by ret2libc** [comment]
Have you tried what I proposed in https://github.com/rizinorg/rizin/pull/3622#issuecomment-1618389671 ?

**Comment by arrowd** [comment]
Let me reiterate. I'm fixing a problem when it is not possible to run tests without prior `ninja install`. Changes in this PR make tests some look into build directory when searching for database files. This fixes these tests for me.

However, some other tests cannot be fixed that way. For instance, `test/unit/test_analysis_var.c:test_rz_analysis_var_is_arg` fails because it lacks calling convention data and there is no function like `rz_type_db_init` to pass it a path to the build dir. Do you have an idea how to fix that?

**Comment by XVilka** [comment]
> `test/unit/test_analysis_var.c:test_rz_analysis_var_is_arg` fails because it lacks calling convention data and there is no function like `rz_type_db_init` to pass it a path to the build dir. Do you have an idea how to fix that?

It's better probably to do a small refactor and provide such function for calling conventions as well.
Something like `rz_analysis_cc_init()`

Currently it's a part of `rz_core_analysis_cc_init()`, some of the relevant code could be moved into this new function that also accepts path as argument, and make `rz_core_analysis_cc_init()` calling it.

**Comment by ret2libc** [comment]
> Let me reiterate. I'm fixing a problem when it is not possible to run tests without prior `ninja install`. Changes in this PR make tests some look into build directory when searching for database files. This fixes these tests for me.
> 
> 
> 
> However, some other tests cannot be fixed that way. For instance, `test/unit/test_analysis_var.c:test_rz_analysis_var_is_arg` fails because it lacks calling convention data and there is no function like `rz_type_db_init` to pass it a path to the build dir. Do you have an idea how to fix that?

Can't you add the call to rz_type_db_init like shown in my comment?

**Comment by XVilka** [comment]
> > Let me reiterate. I'm fixing a problem when it is not possible to run tests without prior `ninja install`. Changes in this PR make tests some look into build directory when searching for database files. This fixes these tests for me.
> > However, some other tests cannot be fixed that way. For instance, `test/unit/test_analysis_var.c:test_rz_analysis_var_is_arg` fails because it lacks calling convention data and there is no function like `rz_type_db_init` to pass it a path to the build dir. Do you have an idea how to fix that?
> 
> Can't you add the call to rz_type_db_init like shown in my comment?

`rz_type_db_init()` doesn't handle conventions, it's done by `rz_core_analysis_cc_init()` which hardcodes paths. See my comment on how properly handle this.

**Comment by arrowd** [comment]
This change fixes the test for me, but I don't like it. With `rz_analysis_cc_init` addition we now need to somehow skip calling `sdb_reset()` during `rz_core_analysis_cc_init` to not overwrite previous SDB paths. Right now I just check if the new path doesn't exist, but it feels like a hack.

File: librz/core/canalysis.c [hunk 2]
```diff
@@ -5560,29 +5560,39 @@ static void sdb_concat_by_path(Sdb *s, const char *path) {
 	sdb_free(db);
 }
 
-RZ_API void rz_core_analysis_cc_init(RzCore *core) {
+RZ_API bool rz_analysis_cc_init(RzCore *core, RZ_NULLABLE const char *path) {
```
Comment (wargio) [inline librz/core/canalysis.c:5563]: if you want this to be only rz_analysis, the it should be moved under the analysis directory, not under core.

Comment (wargio) [inline librz/core/canalysis.c]: This code requires `RzCore` so keep the original name, or make this as `static` (and remove `RZ_API` & the prefix `rz_`) so this will never be called by anybody else besides `rz_core_analysis_cc_init`

Comment (arrowd) [reply librz/core/canalysis.c]: This is not a rename, it is a new function with name suggested by @XVilka

Comment (XVilka) [reply librz/core/canalysis.c]: Yes, it should be a new function that this old function uses too

Comment (wargio) [reply librz/core/canalysis.c]: can i suggest then this name? `rz_core_analysis_cc_init_by_path`

File: librz/core/canalysis.c [hunk 3]
```diff
@@ -5560,29 +5560,39 @@ static void sdb_concat_by_path(Sdb *s, const char *path) {
...
-	free(types_dir);
-	free(home_types_dir);
+
+	if (path[0] == '/') {
+		types_dir = path;
+		home_types_dir = "";
+	} else {
+		types_dir = rz_path_system(path);
+		home_types_dir = rz_path_home_prefix(path);
+	}
```
Comment (ret2libc) [inline librz/core/canalysis.c]: Can I suggest we just provide `path` and `homepath` as argument of this function instead of doing this thing? It seems a bit hacky and I'm not sure it works in all configurations (e.g. when building Rizin in portable mode).

Comment (wargio) [reply librz/core/canalysis.c]: agreed

**Comment by arrowd** [comment]
Should be fine now.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
`analysis_var` test fails:

```
13/100 rizin:unit / analysis_var         FAIL            1.19s   exit status 1
>>> MALLOC_PERTURB_=68 LD_LIBRARY_PATH=/home/runner/work/rizin/rizin/build/librz/hash:/home/runner/work/rizin/rizin/build/librz/flag:/home/runner/work/rizin/rizin/build/librz/asm:/home/runner/work/rizin/rizin/build/librz/socket:/home/runner/work/rizin/rizin/build/librz/diff:/home/runner/work/rizin/rizin/build/librz/config:/home/runner/work/rizin/rizin/build/librz/io:/home/runner/work/rizin/rizin/build/librz/core:/home/runner/work/rizin/rizin/build/librz/magic:/home/runner/work/rizin/rizin/build/librz/util:/home/runner/work/rizin/rizin/build/librz/il:/home/runner/work/rizin/rizin/build/librz/bin:/home/runner/work/rizin/rizin/build/librz/egg:/home/runner/work/rizin/rizin/build/librz/type:/home/runner/work/rizin/rizin/build/librz/search:/home/runner/work/rizin/rizin/build/librz/lang:/home/runner/work/rizin/rizin/build/librz/sign:/home/runner/work/rizin/rizin/build/librz/bp:/home/runner/work/rizin/rizin/build/librz/crypto:/home/runner/work/rizin/rizin/build/librz/cons:/home/runner/work/rizin/rizin/build/librz/demangler:/home/runner/work/rizin/rizin/build/librz/parse:/home/runner/work/rizin/rizin/build/librz/analysis:/home/runner/work/rizin/rizin/build/librz/main:/home/runner/work/rizin/rizin/build/librz/reg:/home/runner/work/rizin/rizin/build/librz/syscall:/home/runner/work/rizin/rizin/build/librz/debug:/home/runner/lib/x86_64-linux-gnu:/home/runner/lib:/home/runner/lib64: /home/runner/work/rizin/rizin/build/test/unit/test_analysis_var
```

**Comment by arrowd** [comment]
Can't find any error messages in the test log.

**Comment by XVilka** [comment]
It only happens on ASAN build, I suspect it detected memory violation. Could you try to run it with your patches and ASAN enabled locally?

**Comment by wargio** [comment]
if you have issues with asan link order, just do `export ASAN_OPTIONS=verify_asan_link_order=0`
And if you have issues with memleaks, `export ASAN_OPTIONS=detect_leaks=0`

https://github.com/google/sanitizers/wiki/AddressSanitizerFlags#run-time-flags

**Comment by XVilka** [comment]
@arrowd could you please update this today? So that it makes its way into 0.6.0? If not - lets postpone to the next release (0.7.0)

**Comment by XVilka** [comment]
Moved to 0.7.0

**Comment by XVilka** [comment]
I imported changes to https://github.com/rizinorg/rizin/pull/3719 to trigger all kinds of CI jobs.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
It passed all tests in https://github.com/rizinorg/rizin/pull/3719, including EXTRA_PREFIX, Android, and Windows, thus I added it back to 0.6.0 and it's ready to be merged, IMHO (Ignore stuck Travis CI PPC job - it's something on their side).

**Comment by XVilka** [comment]
@ret2libc @wargio take a look please and merge if you are fine with it.

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Looks good to me, thanks a lot!!
