### PR TITLE
Fix: overflow of core->block in the handler of command plf

### LINKED ISSUE #3733: `plf` doesn't print RzIL for all instructions of a function
1. `rizin malloc://10240`
2. `. ./arm64_rzil_test.rz`
3. `aaa`
4. `pdf` to see that function is recognized and disassembled succefully
5. `plf` and observe that RzIL output suddenly stops after 0x100 address:

```
0xf0 (set x3 (cast 64 false (loadw 0 32 (+ (var x10) (<< (cast 64 false (cast 32 false (var x3))) (bv 6 0x2) false)))))
0xf4 (set x0 (cast 64 false (^ (cast 32 false (var x0)) (cast 32 false (var x5)))))
0xf8 (set x0 (cast 64 false (^ (cast 32 false (var x0)) (cast 32 false (var x3)))))
0xfc (set x15 (cast 64 false (& (cast 32 false (var x15)) (bv 32 0xff))))
0x100
0x104
0x108
0x10c
0x110
0x114
```

[arm64_rzil_test.rz.gz](https://github.com/rizinorg/rizin/files/12287942/arm64_rzil_test.rz.gz)

cc @PeiweiHu

### PR DESCRIPTION
**Pull request by PeiweiHu**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Please tell me if it's necessary to upload [arm64_rzil_test.rz.gz](https://github.com/rizinorg/rizin/files/12287942/arm64_rzil_test.rz.gz) to rizin-testbins and write new related test for command `plf`.

**Test plan**

CI is green.

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/3733

### CODE REVIEW

File: librz/core/cmd/cmd_print.c [hunk 1]
```diff
@@ -4012,8 +4013,12 @@ RZ_IPI RzCmdStatus rz_print_function_rzil_handler(RzCore *core, int argc, const
 	}
 
 	ut64 size = end - start;
+	if (size > old_blocksize) {
+		rz_core_block_size(core, size);
+	}
```
Comment (wargio) [inline librz/core/cmd/cmd_print.c]: you can always run it since you are always resetting the size later.

**Review by XVilka — APPROVED** [review]
I suggest adding the test especially since we plan to get rid of `core->block`: https://github.com/rizinorg/rizin/issues/2695

File: librz/core/cmd/cmd_print.c (hunk 1 above)
Comment (PeiweiHu) [reply librz/core/cmd/cmd_print.c]: Thank you.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
