### PR TITLE
Fix #5679

### LINKED ISSUE #5679: `el` and `ell` commands output colorization
In https://github.com/rizinorg/rizin/pull/5466 the output of `el` was colorized, but for some reason it doesn't work properly anymore:

Image

Moreover, it makes sense to properly pad and format `ell` output as well and colorize it similarly to the `el` output:

Image

### PR DESCRIPTION
**Pull request by Sl4y3r-07**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**
This pr fixes the ell command padding and added the support for colorised output.

### CODE REVIEW

**Comment by Sl4y3r-07** [comment]
@notxvilka can you please review it

**Comment by wargio** [comment]
add a screenshot of before and after

**Comment by Sl4y3r-07** [comment]
Before
image
After 
image

File: librz/core/cconfig.c [hunk 1]
```diff
@@ -1885,11 +1885,23 @@ static void config_print_node(RzConfig *cfg, RzConfigNode *node, RzCmdStateOutpu
...
+			RzColor color_meta_val = rz_cons_pal_get("comment");
+			RzColor reset_val = rz_cons_pal_get("help");
+			rz_cons_rgb_str(color_name, sizeof(color_name), &color_name_val);
+			rz_cons_rgb_str(color_value, sizeof(color_value), &color_value_val);
+			rz_cons_rgb_str(color_meta, sizeof(color_meta), &color_meta_val);
+			rz_cons_rgb_str(reset_str, sizeof(reset_str), &reset_val);
+		} else {
+			color_name[0] = color_value[0] = color_meta[0] = reset_str[0] = '\0';
+		}
+		rz_cons_printf("%s%20s = %s%s %s%s; %s%s", color_name, node->name, color_value, node->value, color_meta, rz_config_node_is_ro(node) ? "(ro)" : "", reset_str, node->desc);
```
Comment (wargio) [inline librz/core/cconfig.c]: for sake of readability extract the `rz_config_node_is_ro(node) ? "(ro)" : ""` into a variable

**Review by wargio — CHANGES_REQUESTED** [review]
LGTM, it's a great change! just address my comment and i think we could merge.

**Review by Rot127 — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]

**Comment by notxvilka** [comment]
@Sl4y3r-07 you messed up the history

**Comment by Sl4y3r-07** [comment]
> @Sl4y3r-07 you messed up the history

Yeah, I'm very sorry for that. Fixing the issue. A CI check was failing and in-order to fix that, this happened.

**Comment by Sl4y3r-07** [comment]
Is it fine now? @notxvilka

**Review by notxvilka — APPROVED** [review]
Yes, it's fine now
