### PR TITLE
Sparc/MC680x0 Mach-O issues

### LINKED ISSUE #4359: Mach-O: problems of parsing HPPA and SPARC sub-binaries of the universal binary
```
ℤ file 2048-NeXTSTEP
2048-NeXTSTEP: Mach-O universal binary with 4 architectures: [m68k:
- Mach-O executable m68k] [i386:
- Mach-O executable i386] [hppa 7100:
- Mach-O executable hppa 7100] [SPARC:
- Mach-O executable SPARC]
2048-NeXTSTEP (for architecture m68k):	Mach-O executable m68k
2048-NeXTSTEP (for architecture i386):	Mach-O executable i386
2048-NeXTSTEP (for architecture hppa):	Mach-O executable hppa 7100
2048-NeXTSTEP (for architecture sparc):	Mach-O executable SPARC
ℤ rizin 2048-NeXTSTEP
ERROR: unknown thread state structure
ERROR: mach0: Cannot parse thread
 -- Use '-e bin.strings=false' to disable automatic string search when loading the binary.
[0x00002000]> i
fd       3
file     2048-NeXTSTEP
size     0x30000
humansz  192K
mode     r-x
format   mach0
iorw     false
block    0x100
packet   xtr.fatmach0
type     Executable file
arch     arm
cpu      N/A
baddr    0x00002000
binsz    0x0000e000
bintype  mach0
bits     64
class    MACH0
compiler N/A
dbg_file N/A
endian   LE
hdr.csum N/A
guid     N/A
intrp    N/A
laddr    0x00000000
lang     c
machine  mc68030
maxopsz  4
minopsz  4
os       darwin
cc       N/A
pcalign  4
rpath    N/A
subsys   unknown
stripped false
crypto   false
havecode true
va       true
sanitiz  false
static   true
linenum  false
lsyms    false
canary   false
PIE      false
RELROCS  false
NX       false
[0x00002000]>
```
```
rz-bin -i -f hppa 2048-NeXTSTEP
ERROR: unknown thread state structure
ERROR: mach0: Cannot parse thread
WARNING: rz_bin_file_find_by_arch_bits: assertion 'bin && arch' failed (line 157)
WARNING: rz_bin_file_set_obj: assertion 'bin && bf' failed (line 253)
[Archs]
offset     size  arch       machine
-------------------------------------
0x00002000 49152 mc680x0_32 mc68030
0x0000e000 40960 x86_32     386
0x00018000 49152 hppa_32    hppa7100
0x00024000 49152 sparc_32   all

[Imports]
nth vaddr bind type lib name
```
If you extract subbins with `rz-bin -x` command, then open them individually, you will see that HPPA and SPARC binaries are poorly parsed/analyzed

[2048-NeXTSTEP.zip](https://github.com/rizinorg/rizin/files/14615713/2048-NeXTSTEP.zip)

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Fixes three things:
1. Adds two more register layouts (Sparc, m68k) for Mach-O thread_status notes.
2. Fixes the issue of endianess not being handled properly for Mach-O files (it assumed only PPC is always big endian or ignored it).
3. Adds a command to switch between the different binaries of a fat binary.

**Test plan**

Added

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/4359

### CODE REVIEW

File: librz/bin/format/mach0/mach0_specs.h [hunk 1]
```diff
@@ -190,6 +190,38 @@ struct arm_thread_state64 {
...
 };
 
+/**
+ * \brief This layout is guessed. I couldn't find a reference online
+ * implementing linking of Mach-O Sparc binaries and has the layout of the thread state.
+ * The layout below is the one used for the registers in the ELF core dumps.
+ * I use this in the hope the Mach-O and ELF devs had some
+ * commen documentation they were refering to.
+ */
+struct sparc_thread_state64 {
```
Comment (wargio) [inline librz/bin/format/mach0/mach0_specs.h:200]: are you sure that `LC_THREAD` is supported by the old mach0 bins?

Comment (wargio) [reply librz/bin/format/mach0/mach0_specs.h:200]: if you have a binary for both, i could check via otool if it says anything.

Comment (Rot127) [reply librz/bin/format/mach0/mach0_specs.h:200]: Actually, you are right. I just never thought about that the old Sparc processors might all be one threaded.

File: librz/bin/bfile.c [hunk 2]
```diff
@@ -80,9 +80,26 @@ static RzBinPlugin *get_plugin_from_buffer(RzBin *bin, const char *pluginname, R
...
+		}
+		RzBinXtrData *xtr_data;
+		RzListIter *iter_xtr;
+		rz_list_foreach (binfile->xtr_data, iter_xtr, xtr_data) {
+			xtr_data->loaded = false;
+		}
+	}
+}
+
+RZ_API bool rz_bin_file_set_xtr_data_as_current_obj(RzBin *bin, RzBinFile *bf, RzBinObjectLoadOptions *opts, RzBinXtrData *data) {
```
Comment (notxvilka) [inline librz/bin/bfile.c]: Add Doxygen please

File: librz/core/cbin.c [hunk 3]
```diff
@@ -4649,37 +4652,24 @@ static int bin_versioninfo(RzCore *r, PJ *pj, int mode) {
 	return true;
 }
 
-RZ_API int rz_core_bin_set_arch_bits(RzCore *r, const char *name, const char *arch, ut16 bits) {
-	int fd = rz_io_fd_get_current(r->io);
-	RzIODesc *desc = rz_io_desc_get(r->io, fd);
+RZ_API int rz_core_bin_set_arch_bits(RzCore *r, RZ_DEPRECATE const char *filename, const char *arch, ut16 bits) {
```
Comment (notxvilka) [inline librz/core/cbin.c]: Please add Doxygen since you modified it

**Review by notxvilka — APPROVED** [review]
Looks good!

**Comment by Rot127** [comment]
Windows test fail:
> Build execution time has reached the maximum allowed time for your plan (90 minutes).

**Review by notxvilka — APPROVED** [review]

File: librz/bin/format/mach0/mach0.c [hunk 4]
```diff
@@ -1070,8 +1070,36 @@ static int parse_thread(struct MACH0_(obj_t) * bin, struct load_command *lc, ut6
...
+		pc_offset = ptr_thread + rz_offsetof(struct mc680x0_thread_state, pc);
+		arw_ptr = (ut8 *)&bin->thread_state.mc680x0;
+		arw_sz = sizeof(struct mc680x0_thread_state);
+		break;
+	case CPU_TYPE_SPARC:
+		if (ptr_thread + sizeof(struct sparc_thread_state64) > bin->size) {
+			return false;
+		}
+		if (rz_buf_fread_at(bin->b, ptr_thread,
+			    (ut8 *)&bin->thread_state.mc680x0, bin->big_endian ? "36L" : "36l", 1) == -1) {
```
Comment (notxvilka) [inline librz/bin/format/mach0/mach0.c]: Is this a typo? Should this one be `thread_state.sparc` instead?

**Review by notxvilka — CHANGES_REQUESTED** [review]
Seems there is a copy-paste error.
