### PR TITLE
[DEX] Add relocation support

### LINKED ISSUE #2416: Some method references in Dex are missing
### Work environment

| Questions                                             | Answers                                                      |
| ----------------------------------------------------- | ------------------------------------------------------------ |
| OS/arch/bits (mandatory)                              | Ubuntu 20.04                                                 |
| File format of the file you reverse (mandatory)       | APK                                                          |
| Architecture/bits of the file (mandatory)             | Dalvik                                                       |
| `rizin -v` full output, **not truncated** (mandatory) | rizin 0.4.0-git @ linux-x86-64<br/>commit: 7b16c102654932cfae7f1d0ea3d2b909754ae9f9, build: 2022-03-16__08:32:49 |

### Expected behavior

Detect all the method references in Dex.

### Actual behavior

Some method references were missing.

In the following scenario, I looked into a method's instruction at address `0x496f6`. According to the disassembled result, it holds a reference to method `sendTextMessage`. However, commands `axl` and `axf` both missed that reference.

```
➜ rizin apk://13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk 
 -- Use 'e asm.offset=true' to show offsets in 16bit segment addressing mode.
[0x00028498]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Finding xrefs in noncode section with analysis.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x000af474 (aav)
[x] 0x00000000-0x000af474 in 0x0-0xaf474 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[ERROR: sigdb path is unknown or invalid (path: /usr/local/share/rizin/sigdb)
[x] Applied 0 FLIRT signatures via sigdb
[0x00028498]> pd 1 @ 0x496f6
│           0x000496f6      invoke-virtual/range {v2..v7}, Landroid/telephony/SmsManager;->sendTextMessage(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/app/PendingIntent;Landroid/app/PendingIntent;)V
[0x00028498]> axl~496f6
[0x00028498]> axl~sendTextMessage
[0x00028498]> axf @ 0x496f6
[0x00028498]> 

```

### Steps to reproduce the behavior
- Open the [APK](https://github.com/quark-engine/apk-malware-samples/raw/master/13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk) with Rizin
- Type in the following commands.

```
aaa
pd 1 @ 0x496f6
axl~496f6
axl~sendTextMessage
axf @ 0x496f6
```

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix #2416 

before
image

after
image

### CODE REVIEW

File: librz/bin/format/dex/dex.h [hunk 1]
```diff
@@ -9,6 +9,10 @@
 #include <rz_util.h>
 #include <rz_bin.h>
 
+#define RZ_DEX_RELOC_TARGETS "reloc-targets"
+#define RZ_DEX_VIRT_ADDRESS  0x0100000000
```
Comment (thestr4ng3r) [inline librz/bin/format/dex/dex.h:13]: Why not have this just 0?

Comment (wargio) [reply librz/bin/format/dex/dex.h:13]: because i do not know why, but on mapped phy regions it will fail.
like if i map X:phy to X:virt it will fail, but as long as the mem regions are not over each other even if part of 2 different worlds, it will work.

Comment (wargio) [reply librz/bin/format/dex/dex.h:13]: and this is an issue with RzIO world, not dex.

Comment (wargio) [reply librz/bin/format/dex/dex.h:13]: And more specifically, analysis will fail.

Comment (thestr4ng3r) [reply librz/bin/format/dex/dex.h:13]: That is strange though and needs investigation, since pie elf usually also map at 0 and those work.

Comment (wargio) [reply librz/bin/format/dex/dex.h:13]: i guess we can push this in another PR

**Review by thestr4ng3r — APPROVED** [review]
