### PR TITLE
Fix #2088 - Fix resource exhaustion in dwarf parsing

### LINKED ISSUE #2088: Reading oversized debug section causes system resource exhaustion
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04.1 x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 1d3f029d0775ab39cfbc14f322a328e820694ea5, build: 2021-12-10__10:17:37

### Expected behavior
Rizin should analyze the binary without exhausting system resources.

### Actual behavior
Reading the `.debug_lines` section causes Rizin to be killed because of resource exhaustion.

### Steps to reproduce the behavior
Analize this binary using `aaa` or `-A` command line argument: [binaries.zip](https://github.com/rizinorg/rizin/files/7693104/binaries.zip)

### Additional Logs, screenshots, source code,  configuration dump, ...

```
❯ rizin -A id:000001,sig:09,src:022799,time:168198297,op:flip2,pos:17092
[1]    17079 killed     rizin -A 
```
In this binary, the section header for the `.debug_lines` section specifies a size that is far greater that the actual section's size.
Note that this size must be big enough to cause resource exhaustion but not too big so it can be allocated (this example uses the 16 gb of ram in my pc). If it's too big allocation will fail:

```
❯ rizin -A bigger_alloc
=================================================================
==18391==ERROR: AddressSanitizer: allocator is out of memory trying to allocate 0x400000000 bytes                                                     
    #0 0x7f6d55af9dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x56208608c359 in rz_bin_dwarf_parse_line ../librz/bin/dwarf.c:2147

==18391==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: out-of-memory (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6) in calloc
==18391==ABORTING
```

Allocation of this buffer is made at `dwarf.c:3147` and the call to `rz_buf_read_at` at line 2151 causes the resource exhaustion. This function calls `rz_buf_read` that uses memset to fill the remainder of the buffer that could not be read from the binary causing high memory and cpu consumption.

There are several functions in `dwarf.c` that read other debug sections and may have the same problem when the section size defined in the section header is greater than the actual section size. All this functions use `rz_buf_read_at` or `get_section_bytes` so it may be posible to recreate this problem for `.debug_info`, `.debug_str`, `.debug_aranges`, `.debug_abbrev` and `.debug_loc`.

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Don't trust section size to make allocations in dwarf parsing

**Test plan**

Tests pass

**Closing issues**

Fixes #2088

### CODE REVIEW

File: librz/bin/dwarf.c [hunk 1]
```diff
@@ -2035,7 +2035,7 @@ static RzBinDwarfDebugAbbrev *parse_abbrev_raw(const ut8 *obuf, size_t len) {
 	return da;
 }
 
-RzBinSection *getsection(RzBinFile *binfile, const char *sn) {
+static inline RzBinSection *getsection(RzBinFile *binfile, const char *sn) {
```
Comment (ret2libc) [inline librz/bin/dwarf.c]:
```suggestion
static RzBinSection *getsection(RzBinFile *binfile, const char *sn) {
```
no need for inline, compiler will automatically inline it if it can.

File: librz/bin/dwarf.c [hunk 2]
```diff
@@ -2060,10 +2060,10 @@ static ut8 *get_section_bytes(RzBinFile *binfile, const char *sect_name, size_t
 	if (!section) {
 		return NULL;
 	}
-	if (section->size > binfile->size) {
+	if (section->paddr >= binfile->size) {
```
Comment (ret2libc) [inline librz/bin/dwarf.c:2063]: shouldn't we also check the ->size of the section?

**Review by ret2libc — COMMENTED** [review]
Looks much nicer.

File: librz/bin/dwarf.c (hunk 2 above)
Comment (GustavoLCR) [reply librz/bin/dwarf.c:2063]: @ret2libc Check is done here, so we get either the size of the section or from the section start until the end of the file  https://github.com/rizinorg/rizin/blob/0bc9779e018a4e549ec791be816260b7e6684314/librz/bin/dwarf.c#L2066

**Review by XVilka — APPROVED** [review]
