### PR TITLE
[AArch64/ARM64] Update to Capstone `v6/auto-sync`

### LINKED ISSUE #3175: Pointer authentication-related instructions parsed as "invalid"
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS Monterey 12.6, Apple M1
| File format of the file you reverse (mandatory)      | Mach-O 64-bit dynamically linked shared library arm64e
| Architecture/bits of the file (mandatory)            | arm64e
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 @ darwin-arm-64 commit: 3a291799474a9c23662c5e3e936141bfccd49094

### Expected behavior
All of the opcodes are parsed correctly

### Actual behavior
Instructions such as AUTA, [BRAA](https://developer.arm.com/documentation/ddi0596/2021-09/Base-Instructions/BRAA--BRAAZ--BRAB--BRABZ--Branch-to-Register--with-pointer-authentication-?lang=en) are shown as "invalid"

### Steps to reproduce the behavior
- Please share the binary if it is shareable by drag and dropping it here in a zip archive (mandatory)
[CoreML.zip](https://github.com/rizinorg/rizin/files/9968185/CoreML.zip)

```
➜  streaming_coreml rizin CoreML
[0x19df24000]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x19df24000]> sf sym._objc_msgSend_init
[0x19e5706a0]> e asm.bytes=true
[0x19e5706a0]> pd 6
            ; XREFS: CALL 0x19df27270  CALL 0x19e169254  CALL 0x19e16d6d8  
            ; XREFS: CALL 0x19e19ca64  CALL 0x19e1b9520  CALL 0x19e1f3b80  
            ; XREFS: CALL 0x19e24dfe0  CALL 0x19e26df70  CALL 0x19e294fa8  
┌ sym._objc_msgSend_init ();
│ bp: 0 (vars 0, args 0)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
│           0x19e5706a0      01e11bb0       adrp  x1, 0x1d6191000
│           0x19e5706a4      21e046f9       ldr   x1, [x1, 0xdc0]      ; [0xdc0:4]=-1 ; 3520
│           0x19e5706a8      11ce21f0       adrp  x17, 0x1e1f33000
│           0x19e5706ac      31420c91       add   x17, x17, 0x310
│           0x19e5706b0      300240f9       ldr   x16, [x17]
└           0x19e5706b4      110a1fd7       invalid
[0x19e5706a0]> 
```

I lookup up the `0x110a1fd7` (binary `0b11010111000111110000101000010001`) opcode and found it matches the [BRAA](https://developer.arm.com/documentation/ddi0596/2021-09/Base-Instructions/BRAA--BRAAZ--BRAB--BRABZ--Branch-to-Register--with-pointer-authentication-?lang=en) instruction.

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Updates the AArch64/ARM64 module to Capstone's v6/auto-sync version.

Requires https://github.com/capstone-engine/capstone/pull/2026 to be merged

**Test plan**

- Test build with different CS ver. < 6
- All green

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3175

### CODE REVIEW

File: test/db/cmd/cmd_plf [hunk 1]
```diff
@@ -75,7 +75,7 @@ EXPECT=<<EOF
 0x70 (set x10 (cast 64 false (let res (cast 8 false (>> (cast 32 false (var x14)) (bv 6 0x10) false)) (cast 32 false (var res)))))
 0x74 (set x9 (+ (var x8) (bv 64 0x800)))
 0x78 (set x0 (cast 64 false (loadw 0 32 (+ (var x9) (<< (cast 64 false (cast 32 false (var x10))) (bv 6 0x2) false)))))
-0x7c (set x3 (cast 64 false (>> (cast 32 false (var x13)) (bv 5 0x18) false)))
+0x7c (set x3 (cast 64 false (>> (cast 32 false (var x13)) (bv 6 0x18) false)))
```
Comment (XVilka) [inline test/db/cmd/cmd_plf:78]: Did you check the reason why this change happened? `bv 5 0x18` becomes `bv 6 0x18` in many places

File: test/db/cmd/cmd_plf [hunk 2]
```diff
@@ -59,7 +59,7 @@ EXPECT=<<EOF
 0x30 (seq (set addr (+ (var x8) (bv 64 0x8))) (set x14 (cast 64 false (loadw 0 32 (var addr)))) (set x8 (cast 64 false (loadw 0 32 (+ (var addr) (bv 64 0x4))))))
 0x34 (set x14 (cast 64 false (^ (cast 32 false (var x10)) (cast 32 false (var x14)))))
 0x38 (set x15 (cast 64 false (^ (cast 32 false (var x11)) (cast 32 false (var x8)))))
-0x3c (set x8 (bv 64 0x5fe9c))
+0x3c (set x8 (bv 64 0x5fe60))
```
Comment (XVilka) [inline test/db/cmd/cmd_plf:62]: Did you check if it's valid operand (matches the disasm)?

File: test/db/cmd/cmd_plf [hunk 3]
```diff
@@ -45,11 +45,11 @@ plf
 EOF
 EXPECT=<<EOF
 0x0 (set x8 (cast 64 false (load 0 (+ (var x2) (bv 64 0x104)))))
-0x4 (branch (lsb (>> (cast 64 false (var x8)) (bv 6 0x1) false)) (jmp (bv 64 0x10)) nop)
+0x4 (branch (lsb (>> (cast 64 false (cast 32 false (var x8))) (bv 6 0x1) false)) (jmp (bv 64 0x10)) nop)
```
Comment (XVilka) [inline test/db/cmd/cmd_plf:48]: Why new `cast` operation?

File: test/db/cmd/cmd_plf [hunk 4]
```diff
@@ -719,15 +719,15 @@ EXPECT=<<EOF
...
+0xa8c (set x12 (cast 64 false (>> (cast 32 false (var x13)) (bv 6 0x18) false)))
 0xa90 (set x11 (cast 64 false (loadw 0 32 (+ (var x11) (<< (cast 64 false (cast 32 false (var x12))) (bv 6 0x2) false)))))
 0xa94 (set x17 (cast 64 false (^ (cast 32 false (var x14)) (cast 32 false (var x4)))))
 0xa98 (set x8 (cast 64 false (^ (cast 32 false (var x8)) (cast 32 false (var x6)))))
 0xa9c (set x8 (cast 64 false (^ (cast 32 false (var x8)) (cast 32 false (var x9)))))
 0xaa0 (set x8 (cast 64 false (^ (cast 32 false (var x8)) (cast 32 false (var x10)))))
 0xaa4 (set x8 (cast 64 false (^ (cast 32 false (var x8)) (cast 32 false (var x11)))))
 0xaa8 (set x9 (cast 64 false (& (cast 32 false (var x15)) (bv 32 0xff))))
-0xaac (set x10 (bv 64 0x60e9c))
+0xaac (set x10 (bv 64 0x603f0))
```
Comment (XVilka) [inline test/db/cmd/cmd_plf:730]: Same here

**Review by XVilka — CHANGES_REQUESTED** [review]
@wargio @thestr4ng3r, please take a good look too.

**Review by XVilka — CHANGES_REQUESTED** [review]
Fails to compile:
```
FAILED: librz/analysis/librz_analysis.so.0.7.0.p/p_analysis_arm_cs.c.o 
tcc -Ilibrz/analysis/librz_analysis.so.0.7.0.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -I../librz/analysis/arch/gb -Ilibrz/util/sdb/src -I../librz/util/sdb/src -I../librz/asm/arch/include -I../librz/asm/arch -I../librz/asm/arch/h8300 -I../librz/asm/arch/hexagon -I../librz/asm/arch/msp430 -I../librz/asm/arch/rsp -I../librz/asm/arch/mcore -I../librz/asm/arch/v850 -I../librz/asm/arch/propeller -I../librz/asm/arch/ebc -I../librz/asm/arch/cr16 -I../librz/asm/arch/8051 -I../librz/asm/arch/v810 -I../librz/asm/arch/or1k -I../librz/asm/arch/tricore -I../librz/bin/format -I../librz/type/parser -I../subprojects/capstone-next/include -I../subprojects/capstone-next/include/capstone -Wall -O2 -g -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -D_GNU_SOURCE -Werror=sizeof-pointer-memaccess -fvisibility=hidden -MD -MF librz/analysis/librz_analysis.so.0.7.0.p/p_analysis_arm_cs.c.o.d -o librz/analysis/librz_analysis.so.0.7.0.p/p_analysis_arm_cs.c.o -c ../librz/analysis/p/analysis_arm_cs.c
../librz/analysis/p/analysis_arm_cs.c:1249: error: 'ARM_INS_NOP' undeclared
[1444/2056] Compiling C object librz/analysis/librz_analysis.so.0.7.0.p/p_analy
```

File: test/db/cmd/cmd_plf (hunk 2 above)
Comment (Rot127) [reply test/db/cmd/cmd_plf:62]: It is. Must have been wrong before:

```
07:14 $ > echo "0x08,0xf3,0x2f,0x10" | llvm-mc-18 --disassemble --arch=aarch64 --show-encoding --print-imm-hex
	.text
	adr	x8, #392800                     // encoding: [0x08,0xf3,0x2f,0x10]

07:14 $ > ./cstool -d aarch64 08f32f10
 0  08 f3 2f 10  adr	x8, 0x5fe60
	ID: 22 (adr)
	op_count: 2
		operands[0].type: REG = x8
		operands[0].access: WRITE
		operands[1].type: IMM = 0x5fe60
		operands[1].access: READ
	Registers modified: x8
```

File: test/db/cmd/cmd_plf (hunk 1 above)
Comment (Rot127) [reply test/db/cmd/cmd_plf:78]: Because alias are no longer handled as "pure" instructions the decoding path is a different one. These ones are usually `LSR` which are an alias for `UBFM`. And the immediate of the `UBFM` instruction is 6bit. Hence the correction.

File: test/db/cmd/cmd_plf (hunk 3 above)
Comment (Rot127) [reply test/db/cmd/cmd_plf:48]: This is `tbnz	w8, #1, 0xc`. The value of `w8` equals `(ut32) x8` since `x8` is a 64bit register. But the IL implementation operates generally on 64bit numbers. The extra cast is necessary to drop the leading 32bit.

File: test/db/cmd/cmd_plf (hunk 4 above)
Comment (Rot127) [reply test/db/cmd/cmd_plf:730]: Same as above. The previous value was simply incorrect.

**Review by wargio — APPROVED** [review]
lgtm

**Review by XVilka — CHANGES_REQUESTED** [review]
This new output definitely looks wrong:
```
[XX] db/analysis/arm ELF ARM: function arg
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e asm.calls=false
e asm.bytes=true
afr@ main
afva@ sym.call
pdf@ sym.call
' bins/elf/analysis/armcall
-- stdout
--- expected
+++ actual
@@ --1,17 +-1,20 @@
             ; CALL XREF from main @ 0x10468
-/ sym.call(int32_t arg1);
+/ sym.call(int32_t arg1, int32_t var_7fffffffffffffe0h, int32_t var_7fffffffffffffe4h);
 |           ; arg int32_t arg1 @ r0
-|           ; var int32_t var_ch @ stack - 0xc
+|           ; arg int32_t var_7fffffffffffffe0h @ stack + 0x7fffffffffffffe0
+|           ; arg int32_t var_7fffffffffffffe4h @ stack + 0x7fffffffffffffe4
 |           0x00010420      00482de9       push  {fp, lr}
 |           0x00010424      04b08de2       add   fp, sp, 4
 |           0x00010428      08d04de2       sub   sp, sp, 8
-|           0x0001042c      08000be5       str   r0, [var_ch]          ; 0x8 ; 8 ; arg1
+|           0x0001042c      08000be5       str   r0, [var_7fffffffffffffe4h] ; 0x8 ; 8 ; arg1
 |           0x00010430      14009fe5       ldr   r0, [0x0001044c]      ; [0x1044c:4]=0x104f0
-|           0x00010434      08101be5       ldr   r1, [var_ch]          ; 0x8 ; 8
+|           0x00010434      08101be5       ldr   r1, [var_7fffffffffffffe4h] ; 0x8 ; 8
 |           0x00010438      a2ffffeb       bl    sym.imp.printf
 |           0x0001043c      0030a0e3       mov   r3, 0
 |           0x00010440      0300a0e1       mov   r0, r3
 |           0x00010444      04d04be2       sub   sp, fp, 4
-\           0x00010448      0088bde8       pop   {fp, pc}
+|           0x00010448      0088bde8       pop   {fp, pc}
+|           ; DATA XREF from sym.call @ 0x10430
+\           0x0001044c      f0040100       strdeq r0, r1, [r1], -r0
```

Some other tests, e.g. that detect stackptr could be probably just updated

**Comment by Rot127** [comment]
Waiting for https://github.com/capstone-engine/capstone/pull/2216
Hopefully this is finally it.

**Comment by XVilka** [comment]
These two tests look better with the new output, I think:
```
[XX] db/cmd/dwarf "ARM types"
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aaa
afvl @ dbg.main
pdf @ dbg.new_some
aaa
' bins/elf/test_app2/test_app2.elf
-- stdout
--- expected
+++ actual
@@ -1,8 +1,8 @@
-var int16_t var_38h @ stack - 0x38
-var int16_t var_34h @ stack - 0x34
-var int16_t var_30h @ stack - 0x30
-var int16_t var_2ch @ stack - 0x2c
-var int16_t var_1ch @ stack - 0x1c
+var int32_t var_38h @ stack - 0x38
+var int32_t var_34h @ stack - 0x34
+var int32_t var_30h @ stack - 0x30
+var int32_t var_2ch @ stack - 0x2c
+var int32_t var_1ch @ stack - 0x1c
```

**Comment by Rot127** [comment]
They do! Pretty sure they weren't very correct before.

**Comment by XVilka** [comment]
@Rot127 I checked the test binary and it seems that new output is right - those two do not look like a code
```
[XX] db/analysis/tricore tricore analysis elf
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e asm.arch=tricore
aaa
afl
pdf
s 0x800842f0
pdf
' bins/tricore/ASCLIN_UART_1_KIT_TC397_TFT_stripped.elf
-- stdout
--- expected
+++ actual
@@ --1,8 +-1,6 @@
 0x80080020    1 10           entry0
-0x8008245a    1 6            fcn.8008245a
-0x80082564    1 12           fcn.80082564
 0x800842f0   13 486          fcn.800842f0
 0x80084158   13 408          fcn.80084158
 0x80083efe    1 430          fcn.80083efe
```
@imbillow please confirm

**Review by b1llow — APPROVED** [review]

**Comment by b1llow** [comment]
> @Rot127 I checked the test binary and it seems that new output is right - those two do not look like a code
> 
> ```
> [XX] db/analysis/tricore tricore analysis elf
> RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e asm.arch=tricore
> aaa
> afl
> pdf
> s 0x800842f0
> pdf
> ' bins/tricore/ASCLIN_UART_1_KIT_TC397_TFT_stripped.elf
> -- stdout
> --- expected
> +++ actual
> @@ --1,8 +-1,6 @@
>  0x80080020    1 10           entry0
> -0x8008245a    1 6            fcn.8008245a
> -0x80082564    1 12           fcn.80082564
>  0x800842f0   13 486          fcn.800842f0
>  0x80084158   13 408          fcn.80084158
>  0x80083efe    1 430          fcn.80083efe
> ```
> 
> @imbillow please confirm

Yes, from the section information it seems that both addresses belong to the .rodata ection.

**Comment by XVilka** [comment]
@Rot127 this test looks wrong (the new output) though:
```
[XX] db/analysis/x86_32 push [esp + 8] variable detection
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e asm.arch=x86
e asm.bits=32
wa "push ebp; mov esp, ebp; sub esp, 64; mov [esp+4], 4; mov [esp+8], 8; mov [esp+0xC], 0xC; push dword [esp+8]; ret"
af
pdf
' =
-- stdout
--- expected
+++ actual
@@ -1,12 +1,13 @@
-/ fcn.00000000();
+/ fcn.00000000(int32_t arg_4h);
 |           ; var int32_t var_40h @ stack - 0x40
 |           ; var int32_t var_3ch @ stack - 0x3c
 |           ; var int32_t var_38h @ stack - 0x38
+|           ; arg int32_t arg_4h @ stack + 0x4
 |           0x00000000      push  ebp
 |           0x00000001      mov   esp, ebp
 |           0x00000003      sub   esp, 0x40
 |           0x00000006      mov   dword [var_40h], 4
 |           0x0000000e      mov   dword [var_3ch], 8
 |           0x00000016      mov   dword [var_38h], 0xc                 ; [0xc:4]=0x44c70000
-|           0x0000001e      push  dword [var_3ch]
+|           0x0000001e      push  dword [arg_4h]
 \           0x00000022      ret
```

**Comment by XVilka** [comment]
Only one broken test left:
```
[XX] db/cmd/types bashbot test (arm 32-bits)
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 's main
af
aaft
afvl
' bins/elf/bashbot.arm.gcc.O0.elf
-- stdout
--- expected
+++ actual
@@ -1,22 +1,22 @@
-var int32_t var_1454h @ stack - 0x1454
-var void *var_1438h @ stack - 0x1438
-var const char *s1 @ stack - 0x1038
-var int *wstatus @ stack - 0x44
+var int32_t var_1460h @ stack - 0x1460
+var void *var_1444h @ stack - 0x1444
+var const char *s1 @ stack - 0x1044
+var int *wstatus @ stack - 0x50
+var int32_t var_4ch @ stack - 0x4c
+var const char *var_48h @ stack - 0x48
+var int32_t var_44h @ stack - 0x44
 var int32_t var_40h @ stack - 0x40
-var const char *var_3ch @ stack - 0x3c
-var int32_t var_38h @ stack - 0x38
-var int32_t var_34h @ stack - 0x34
+var int32_t var_3ch @ stack - 0x3c
+var pid_t pid @ stack - 0x38
+var const char *v2 @ stack - 0x34
 var int32_t var_30h @ stack - 0x30
-var pid_t pid @ stack - 0x2c
-var const char *v2 @ stack - 0x28
+var const char *src @ stack - 0x2c
+var int32_t var_28h @ stack - 0x28
 var int32_t var_24h @ stack - 0x24
-var const char *src @ stack - 0x20
-var int32_t var_1ch @ stack - 0x1c
+var const char *s @ stack - 0x20
+var const char *var_1ch @ stack - 0x1c
 var int32_t var_18h @ stack - 0x18
-var const char *s @ stack - 0x14
-var const char *var_10h @ stack - 0x10
-var int32_t var_ch @ stack - 0xc
-var int32_t var_8h @ stack - 0x8
-var const char *option @ stack - 0x4
+var int32_t var_14h @ stack - 0x14
+var const char *option @ stack - 0x10
 arg int argc @ r0
 arg char **argv @ r1
```

File: librz/analysis/op.c [hunk 5]
```diff
@@ -213,6 +214,8 @@ RZ_API bool rz_analysis_op_ismemref(int t) {
 	case RZ_ANALYSIS_OP_TYPE_STORE:
 	case RZ_ANALYSIS_OP_TYPE_LEA:
 	case RZ_ANALYSIS_OP_TYPE_CMP:
+	case RZ_ANALYSIS_OP_TYPE_POP:
```
Comment (XVilka) [inline librz/analysis/op.c:217]: Nice finding!

File: subprojects/capstone-next.wrap [hunk 6]
```diff
@@ -1,5 +1,5 @@
 [wrap-git]
 url = https://github.com/capstone-engine/capstone.git
-revision = b87cf06209bbcc092692cb85438e7ece20994104
+revision = 4fc80d82f9134e5b4ed0173a7c79a9b221c87626
```
Comment (XVilka) [inline subprojects/capstone-next.wrap]: Please update to the latest commit

File: subprojects/capstone-v4.wrap [hunk 7]
```diff
@@ -1,6 +1,5 @@
-[wrap-file]
-source_url = https://github.com/capstone-engine/capstone/archive/4.0.2.tar.gz
-source_filename = 4.0.2.tar.gz
-source_hash = 7c81d798022f81e7507f1a60d6817f63aa76e489aa4e7055255f21a22f5e526a
+[wrap-git]
+url = https://github.com/capstone-engine/capstone.git
```
Comment (XVilka) [inline subprojects/capstone-v4.wrap:2]: What is the plan for those? Asking capstone devs to make 4.0.3 and 5.0.2 releases?

**Review by XVilka — CHANGES_REQUESTED** [review]
All nice changes, but there are couple nitpicks.
Capstone-sys fails:
```
 FAILED: librz/asm/librz_asm.so.0.7.0.p/p_asm_arm_cs.c.o 
gcc -Ilibrz/asm/librz_asm.so.0.7.0.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -I../librz/asm/arch/include -I../librz/asm/arch -I../librz/asm/arch/h8300 -I../librz/asm/arch/hexagon -I../librz/asm/arch/msp430 -I../librz/asm/arch/rsp -I../librz/asm/arch/mcore -I../librz/asm/arch/v850 -I../librz/asm/arch/propeller -I../librz/asm/arch/ebc -I../librz/asm/arch/cr16 -I../librz/asm/arch/8051 -I../librz/asm/arch/v810 -I../librz/asm/arch/or1k -I../librz/asm/arch/tricore -Ilibrz/util/sdb/src -I../librz/util/sdb/src -I../librz/bin/format -Isubprojects/rzspp -I../subprojects/rzspp -I/usr/include/capstone -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -D_GNU_SOURCE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -Wno-cpp -fPIC -MD -MQ librz/asm/librz_asm.so.0.7.0.p/p_asm_arm_cs.c.o -MF librz/asm/librz_asm.so.0.7.0.p/p_asm_arm_cs.c.o.d -o librz/asm/librz_asm.so.0.7.0.p/p_asm_arm_cs.c.o -c ../librz/asm/p/asm_arm_cs.c
../librz/asm/p/asm_arm_cs.c: In function ‘disassemble’:
../librz/asm/p/asm_arm_cs.c:134:49: error: implicit declaration of function ‘CS_AARCH64pre’ [-Werror=implicit-function-declaration]
  134 |                 ret = (a->bits == 64) ? cs_open(CS_AARCH64pre(CS_ARCH_), mode, &ctx->cd) : cs_open(CS_ARCH_ARM, mode, &ctx->cd);
      |                                                 ^~~~~~~~~~~~~
../librz/asm/p/asm_arm_cs.c:134:63: error: ‘CS_ARCH_’ undeclared (first use in this function); did you mean ‘CS_ARCH_ALL’?
  134 |                 ret = (a->bits == 64) ? cs_open(CS_AARCH64pre(CS_ARCH_), mode, &ctx->cd) : cs_open(CS_ARCH_ARM, mode, &ctx->cd);
      |                                                               ^~~~~~~~
      |                                                               CS_ARCH_ALL
../librz/asm/p/asm_arm_cs.c:134:63: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
```

Please also rebase on top of the latest `dev`.
Apart from that - LGTM.

File: subprojects/capstone-v4.wrap (hunk 7 above)
Comment (Rot127) [reply subprojects/capstone-v4.wrap:2]: Yes, Though I think @kabeor wants to release it with the pre-release together?

File: librz/analysis/op.c (hunk 5 above)
Comment (Rot127) [reply librz/analysis/op.c:217]: There are probably more of those little in-precise implementations. IMHO the problem is, we miss an abstract concept of stack frames for static analysis.

It's all spread around some struct members and functions like those (all of which miss documentation, so variables like `RzAnalysisOp->stackptr` are used differently between `x86` and other archs). All of which is somehow baked together in `var.c`.

**Comment by Rot127** [comment]
@XVilka `Capstone-sys` fails because the macros for meta-programming (`CS_AARCH64()` and the like) are not yet released and in the repos. Once this is the case, the test will succeed again.
We could add a header file with those macros until the new v5 and v4 release is in the repos?

**Comment by XVilka** [comment]
> @XVilka `Capstone-sys` fails because the macros for meta-programming (`CS_AARCH64()` and the like) are not yet released and in the repos. Once this is the case, the test will succeed again. We could add a header file with those macros until the new v5 and v4 release is in the repos?

Adding a header is fine. Otherwise, we would have to wait for months or years.

**Comment by XVilka** [comment]
@Rot127 please rebase it too

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@Rot127 fails to compile with MSVC: https://ci.appveyor.com/project/rizinorg/rizin/builds/48776691/job/jstt9c463d6evru9

**Comment by XVilka** [comment]
@Rot127 some error still persists:
```
./librz/analysis/arch/arm/arm_il64.c(2099): error C2121: '#': invalid character: possibly the result of a macro expansion
../librz/analysis/arch/arm/arm_il64.c(2099): error C2059: syntax error: 'if'
../librz/analysis/arch/arm/arm_il64.c(2109): warning C4003: not enough arguments for function-like macro invocation 'CS_aarch64'
../librz/analysis/arch/arm/arm_il64.c(2117): warning C4003: not enough arguments for function-like macro invocation 'CS_aarch64'
```

**Review by XVilka — APPROVED** [review]
Feel free to squash-merge this PR with a good commit message.

Ignore the red OpenBSD, it's timeout:
```
[XX] TIMEOUT db/rzil/arm32 emulateme_vfp
RZ_NOPLUGINS=1 /home/build/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'o malloc://0x1000 0x40000
o malloc://0x10 0x50000
# `o` resets the cpu for analysis.cpu
s main
e asm.bits=32
e asm.cpu=v8
aezi
e io.cache=1
ar sp=0x41000
aezsu 0x10548 # after vsub
ar d7
aezsu 0x10554 # after vmul
ar d7
aezs # after vadd
ar d7
aezs # after vcvt
ar d16
aezsu 0x1058c # before printf
ar r2
ar r3
pxq 16 @ sp
' bins/elf/emulateme_vfp.arm32
-- exit status: -1
```

The rest of CI is green. Good job!
