### PR TITLE
DWARF loading '.debug_str_offsets', '.debug_line_str' and relocate

### LINKED ISSUE #3816: Failure to parse some typedef types in DWARF
Fails to load the types from DWARF (ARMv7 binary, cannot share):
```
[0x08000b6c]> pdf @ dbg.Subsystem1_SetSomethingConfig
            ; CALL XREF from dbg.subsystem1_something_init @ 0x8010408
            ;-- Subsystem1_SetSomethingConfig:
╭ dbg.Subsystem1_SetSomethingConfig(unknown_t *base, unknown_t *config, unknown_t port);
│           ; arg unknown_t *base @ r0
│           ; arg unknown_t *config @ r1
│           ; arg unknown_t port @ r2
│           ; var uint32_t configValue @ r1
│           ; var uint8_t index @ r6
│           0x0806d7d8      f8b5           push  {r3, r4, r5, r6, r7, lr}
│           0x0806d7da      0446           mov   r4, r0                ; arg1
│           0x0806d7dc      0d46           mov   r5, r1                ; arg2
│           0x0806d7de      5608           lsrs  r6, r2, 1             ; arg3
│       ╭─> 0x0806d7e0      2046           mov   r0, r4                ; int16_t arg1
│       ╎   0x0806d7e2      fff777fe       bl    dbg.Subsystem1_GetSomethingStatus ; dbg.Subsystem1_GetSomethingStatus
│       ╎   0x0806d7e6      0028           cmp   r0, 0
│       ╰─< 0x0806d7e8      fad0           beq   0x806d7e0
```
Here is the excerpt from the dwarfdump:
```
0x000375b6:   DW_TAG_typedef
                DW_AT_name	("Subsystem1_Type")
                DW_AT_decl_column	(0x03)
                DW_AT_type	(0x0003738e "structure ")

0x000382c0:   DW_TAG_pointer_type
                DW_AT_byte_size	(0x04)
                DW_AT_type	(0x000375b6 "Subsystem1_Type")

0x0003822f:   DW_TAG_typedef
                DW_AT_name	("some_config_t")
                DW_AT_decl_column	(0x03)
                DW_AT_type	(0x00038132 "_some_config")

0x0018d89e:   DW_TAG_structure_type
                DW_AT_name	("_some_config")
                DW_AT_byte_size	(0x20)
                DW_AT_decl_line	(273)
                DW_AT_decl_column	(0x10)
                DW_AT_sibling	(0x0018d99b)

0x0018d8ac:     DW_TAG_member
                  DW_AT_name	("member1")
                  DW_AT_decl_line	(275)
                  DW_AT_decl_column	(0x0e)
                  DW_AT_type	(0x0018c94c "uint32_t")
                  DW_AT_data_member_location	(0x00)

0x0018d8ba:     DW_TAG_member
                  DW_AT_name	("member2")
                  DW_AT_decl_line	(276)
                  DW_AT_decl_column	(0x0a)
                  DW_AT_type	(0x0018d71e "_Bool")
                  DW_AT_data_member_location	(0x04)

0x0018d99a:     NULL

0x00037f01:   DW_TAG_enumeration_type
                DW_AT_name	("_some_enum")
                DW_AT_encoding	(DW_ATE_unsigned)
                DW_AT_byte_size	(0x01)
                DW_AT_type	(0x000372a4 "unsigned char")
                DW_AT_decl_line	(189)
                DW_AT_decl_column	(0x0e)
                DW_AT_sibling	(0x00037f32)

0x00037f13:     DW_TAG_enumerator
                  DW_AT_name	("caseA1")
                  DW_AT_const_value	(0x00)

0x00037f19:     DW_TAG_enumerator
                  DW_AT_name	("caseA2")
                  DW_AT_const_value	(0x01)

0x00037f1f:     DW_TAG_enumerator
                  DW_AT_name	("caseB1")
                  DW_AT_const_value	(0x02)


0x00037f32:   DW_TAG_typedef
                DW_AT_name	("some_enum_t")
                DW_AT_decl_line	(196)
                DW_AT_decl_column	(0x03)
                DW_AT_type	(0x00037f01 "_some_enum")


0x0018e551:   DW_TAG_subprogram
                DW_AT_external	(true)
                DW_AT_name	("Subsystem1_SetFlashConfig")
                DW_AT_decl_column	(0x06)
                DW_AT_prototyped	(true)
                DW_AT_low_pc	(0x0806d7d8)
                DW_AT_high_pc	(0x0806d8e0)
                DW_AT_frame_base	(DW_OP_call_frame_cfa)
                DW_AT_GNU_all_call_sites	(true)
                DW_AT_sibling	(0x0018e610)

0x0018e568:     DW_TAG_formal_parameter
                  DW_AT_name	("base")
                  DW_AT_decl_column	(0x2b)
                  DW_AT_type	(0x0018dac9 "Subsystem1_Type *")
                  DW_AT_location	(0x000e1d8c: 
                     [0x0806d7d8, 0x0806d7e0): DW_OP_reg0 R0
                     [0x0806d7e0, 0x0806d8e0): DW_OP_reg4 R4)
                  DW_AT_GNU_entry_view	(0x000e1d88)

0x0018e57d:     DW_TAG_formal_parameter
                  DW_AT_name	("config")
                  DW_AT_decl_column	(0x4a)
                  DW_AT_type	(0x0018e610 "some_config_t *")
                  DW_AT_location	(0x000e1dae: 
                     [0x0806d7d8, 0x0806d7f6): DW_OP_reg1 R1
                     [0x0806d7f6, 0x0806d8e0): DW_OP_reg5 R5)
                  DW_AT_GNU_entry_view	(0x000e1daa)

0x0018e592:     DW_TAG_formal_parameter
                  DW_AT_name	("port")
                  DW_AT_decl_column	(0x61)
                  DW_AT_type	(0x0018d699 "some_enum_t")
                  DW_AT_location	(0x000e1dd0: 
                     [0x0806d7d8, 0x0806d875): DW_OP_reg2 R2
                     [0x0806d875, 0x0806d8e0): DW_OP_GNU_entry_value(DW_OP_reg2 R2), DW_OP_stack_value)
                  DW_AT_GNU_entry_view	(0x000e1dcc)

0x0018e5a7:     DW_TAG_variable
                  DW_AT_name	("configValue")
                  DW_AT_decl_column	(0x0e)
                  DW_AT_type	(0x0018c94c "uint32_t")
                  DW_AT_location	(0x000e1df7: 
                     [0x0806d7d8, 0x0806d82e): DW_OP_lit0, DW_OP_stack_value
                     [0x0806d82e, 0x0806d840): DW_OP_reg1 R1
                     [0x0806d840, 0x0806d875): DW_OP_reg3 R3)
                  DW_AT_GNU_entry_view	(0x000e1df1)

0x0018e5bc:     DW_TAG_variable
                  DW_AT_name	("index")
                  DW_AT_decl_line	(470)
                  DW_AT_decl_column	(0x0d)
                  DW_AT_type	(0x0018c921 "uint8_t")
                  DW_AT_location	(0x000e1e23: 
                     [0x0806d7e0, 0x0806d8e0): DW_OP_reg6 R6)
                  DW_AT_GNU_entry_view	(0x000e1e21)
```

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3816

### CODE REVIEW

File: librz/bin/dwarf/abbrev.c [hunk 1]
```diff
@@ -154,14 +155,14 @@ static bool RzBinDwarfDebugAbbrevs_parse(RzBinDwarfDebugAbbrevs *abbrevs, RzBuff
 /**
  * \brief Parse .debug_abbrev section
  * \param buffer  Buffer to parse
- * \return RzBinDwarfDebugAbbrevs object
+ * \return RzBinDwarfAbbrevs object
  */
-RZ_API RzBinDwarfDebugAbbrevs *rz_bin_dwarf_abbrev_from_buf(RZ_OWN RZ_NONNULL RzBuffer *buffer) {
-	rz_return_val_if_fail(buffer, NULL);
-	RzBinDwarfDebugAbbrevs *abbrevs = RZ_NEW0(RzBinDwarfDebugAbbrevs);
+RZ_API RzBinDwarfAbbrev *rz_bin_dwarf_abbrev_new(RZ_OWN RZ_NONNULL RzBinEndianReader *reader) {
```
Comment (XVilka) [inline librz/bin/dwarf/abbrev.c]: Add ownership

File: librz/core/cbin.c [hunk 2]
```diff
@@ -632,11 +632,7 @@ RZ_API bool rz_core_bin_apply_dwarf(RzCore *core, RzBinFile *binfile) {
 		return false;
 	}
 
-	RzBinDWARFOption opt = {
-		.line_mask = RZ_BIN_DWARF_LINE_INFO_MASK_LINES,
-		.flags = RZ_BIN_DWARF_ALL - RZ_BIN_DWARF_LOC
-	};
-	RzBinDWARF *dw = rz_bin_dwarf_from_file(binfile, &opt);
```
Comment (XVilka) [inline librz/core/cbin.c:639]: Why removing these?

File: test/db/abi/compilers/gcc [hunk 3]
```diff
@@ -26,7 +26,7 @@ CMDS=<<EOF
 id~?
 EOF
 EXPECT=<<EOF
-25813
+24358
```
Comment (XVilka) [inline test/db/abi/compilers/gcc]: What made this significant difference? Can you show an excerpt of what disappeared?

File: test/db/analysis/vars [hunk 4]
```diff
@@ -547,19 +547,19 @@ EXPECT=<<EOF
...
-|           0x0000113c      push  rbp
+|           0x0000113c      push  rbp                                  ; main.c:9
 |           0x0000113d      mov   rbp, rsp
 |           0x00001140      sub   rsp, 0x10
-|           0x00001144      mov   dword [lightbulb], 1
-|           0x0000114b      mov   dword [sun], 2
-|           0x00001152      mov   dword [last], 3
-|           0x00001159      mov   dword [chance], 4
-|           0x00001160      mov   eax, 0
+|           0x00001144      mov   dword [lightbulb], 1                 ; main.c:15
```
Comment (XVilka) [inline test/db/analysis/vars:553]: Nicer new output, great!

**Review by XVilka — CHANGES_REQUESTED** [review]

**Comment by XVilka** [comment]
Also, seems it affected calculation of offsets for sections:
```
[XX] db/cmd/dwarf Compressed debug sections zlib
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'iS
id
' bins/elf/float_ex1/float_ex1_arm_clang.dw.zlib
-- stdout
--- expected
+++ actual
@@ -1,27 +1,27 @@
 paddr      size  vaddr      vsize align perm name                    type       flags                    
 ---------------------------------------------------------------------------------------------------------
 0x00000000 0x0   0x08000000 0x0   0x0   ----                         NULL       
-0x00001b7e 0x15d 0x08001b7e 0x15d 0x0   ---- .strtab                 STRTAB     
+0x00001b5e 0x15d 0x08001b5e 0x15d 0x0   ---- .strtab                 STRTAB     
 0x00000040 0x26c 0x08000040 0x26c 0x0   -r-x .text                   PROGBITS   alloc,execute
-0x00000fa8 0x168 0x08000fa8 0x168 0x0   ---- .rela.text              RELA       info
+0x00000f88 0x168 0x08000f88 0x168 0x0   ---- .rela.text              RELA       info
 0x000002ac 0x4c  0x080002ac 0x4c  0x0   -r-- .rodata.str1.1          PROGBITS   alloc,merge,strings
 0x000002f8 0x100 0x080002f8 0x100 0x0   ---- .debug_abbrev           PROGBITS   compressed
 0x000003f8 0x461 0x080003f8 0x461 0x0   ---- .debug_info             PROGBITS   compressed
-0x00001110 0x60  0x0[800](https://github.com/rizinorg/rizin/actions/runs/6155570684/job/16702682039?pr=3848#step:12:801)1110 0x60  0x0   ---- .rela.debug_info        RELA       info
-0x00000860 0x29  0x08000860 0x29  0x0   ---- .debug_str_offsets      PROGBITS   compressed
-0x00001170 0x810 0x08001170 0x810 0x0   ---- .rela.debug_str_offsets RELA       info
-0x00000890 0x1b9 0x08000890 0x1b9 0x0   ---- .debug_str              PROGBITS   merge,strings,compressed
-0x00000a50 0x2a  0x08000a50 0x2a  0x0   ---- .debug_addr             PROGBITS   compressed
-0x00001980 0x90  0x08001980 0x90  0x0   ---- .rela.debug_addr        RELA       info
-0x00000a7a 0x22  0x08000a7a 0x22  0x0   ---- .comment                PROGBITS   merge,strings
-0x00000a9c 0x0   0x08000a9c 0x0   0x0   ---- .note.GNU-stack         PROGBITS   
-0x00000aa0 0x90  0x08000aa0 0x90  0x0   -r-- .eh_frame               PROGBITS   alloc
-0x00001a10 0x48  0x08001a10 0x48  0x0   ---- .rela.eh_frame          RELA       info
-0x00000b30 0x113 0x08000b30 0x113 0x0   ---- .debug_line             PROGBITS   compressed
-0x00001a58 0x120 0x08001a58 0x120 0x0   ---- .rela.debug_line        RELA       info
-0x00000c48 0xb9  0x08000c48 0xb9  0x0   ---- .debug_line_str         PROGBITS   merge,strings,compressed
-0x00001b78 0x6   0x08001b78 0x6   0x0   ---- .llvm_addrsig           0x6fff4c03 exclude
-0x00000d08 0x2a0 0x08000d08 0x2a0 0x0   ---- .symtab                 SYMTAB     
+0x000010f0 0x60  0x080010f0 0x60  0x0   ---- .rela.debug_info        RELA       info
+0x00000859 0x29  0x08000859 0x29  0x0   ---- .debug_str_offsets      PROGBITS   compressed
+0x00001150 0x810 0x08001150 0x810 0x0   ---- .rela.debug_str_offsets RELA       info
+0x00000882 0x1b9 0x08000882 0x1b9 0x0   ---- .debug_str              PROGBITS   merge,strings,compressed
+0x00000a3b 0x2a  0x08000a3b 0x2a  0x0   ---- .debug_addr             PROGBITS   compressed
+0x00001960 0x90  0x08001960 0x90  0x0   ---- .rela.debug_addr        RELA       info
+0x00000a65 0x22  0x08000a65 0x22  0x0   ---- .comment                PROGBITS   merge,strings
+0x00000a87 0x0   0x08000a87 0x0   0x0   ---- .note.GNU-stack         PROGBITS   
+0x00000a88 0x90  0x08000a88 0x90  0x0   -r-- .eh_frame               PROGBITS   alloc
+0x000019f0 0x48  0x080019f0 0x48  0x0   ---- .rela.eh_frame          RELA       info
+0x00000b18 0x113 0x08000b18 0x113 0x0   ---- .debug_line             PROGBITS   compressed
+0x00001a38 0x120 0x08001a38 0x120 0x0   ---- .rela.debug_line        RELA       info
+0x00000c2b 0xb9  0x08000c2b 0xb9  0x0   ---- .debug_line_str         PROGBITS   merge,strings,compressed
+0x00001b58 0x6   0x08001b58 0x6   0x0   ---- .llvm_addrsig           0x6fff4c03 exclude
+0x00000ce8 0x2a0 0x08000ce8 0x2a0 0x0   ---- .symtab                 SYMTAB     
     1      DW_TAG_compile_unit       [has children] (0x0)
     DW_AT_producer                 DW_FORM_strx1
     DW_AT_language                 DW_FORM_data2
```

File: librz/core/cbin.c (hunk 2 above)
Comment (b1llow) [reply librz/core/cbin.c:639]: Because I found that the sections of DWARF are interdependent, and if you want to read a certain section, you often have to read several other sections at the same time, so I deleted this control option.

**Comment by b1llow** [comment]
> Also, seems it affected calculation of offsets for sections:
> 
> ```
> [XX] db/cmd/dwarf Compressed debug sections zlib
> RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'iS
> id
> ' bins/elf/float_ex1/float_ex1_arm_clang.dw.zlib
> -- stdout
> --- expected
> +++ actual
> @@ -1,27 +1,27 @@
>  paddr      size  vaddr      vsize align perm name                    type       flags                    
>  ---------------------------------------------------------------------------------------------------------
>  0x00000000 0x0   0x08000000 0x0   0x0   ----                         NULL       
> -0x00001b7e 0x15d 0x08001b7e 0x15d 0x0   ---- .strtab                 STRTAB     
> +0x00001b5e 0x15d 0x08001b5e 0x15d 0x0   ---- .strtab                 STRTAB     
>  0x00000040 0x26c 0x08000040 0x26c 0x0   -r-x .text                   PROGBITS   alloc,execute
> -0x00000fa8 0x168 0x08000fa8 0x168 0x0   ---- .rela.text              RELA       info
> +0x00000f88 0x168 0x08000f88 0x168 0x0   ---- .rela.text              RELA       info
>  0x000002ac 0x4c  0x080002ac 0x4c  0x0   -r-- .rodata.str1.1          PROGBITS   alloc,merge,strings
>  0x000002f8 0x100 0x080002f8 0x100 0x0   ---- .debug_abbrev           PROGBITS   compressed
>  0x000003f8 0x461 0x080003f8 0x461 0x0   ---- .debug_info             PROGBITS   compressed
> -0x00001110 0x60  0x0[800](https://github.com/rizinorg/rizin/actions/runs/6155570684/job/16702682039?pr=3848#step:12:801)1110 0x60  0x0   ---- .rela.debug_info        RELA       info
> -0x00000860 0x29  0x08000860 0x29  0x0   ---- .debug_str_offsets      PROGBITS   compressed
> -0x00001170 0x810 0x08001170 0x810 0x0   ---- .rela.debug_str_offsets RELA       info
> -0x00000890 0x1b9 0x08000890 0x1b9 0x0   ---- .debug_str              PROGBITS   merge,strings,compressed
> -0x00000a50 0x2a  0x08000a50 0x2a  0x0   ---- .debug_addr             PROGBITS   compressed
> -0x00001980 0x90  0x08001980 0x90  0x0   ---- .rela.debug_addr        RELA       info
> -0x00000a7a 0x22  0x08000a7a 0x22  0x0   ---- .comment                PROGBITS   merge,strings
> -0x00000a9c 0x0   0x08000a9c 0x0   0x0   ---- .note.GNU-stack         PROGBITS   
> -0x00000aa0 0x90  0x08000aa0 0x90  0x0   -r-- .eh_frame               PROGBITS   alloc
> -0x00001a10 0x48  0x08001a10 0x48  0x0   ---- .rela.eh_frame          RELA       info
> -0x00000b30 0x113 0x08000b30 0x113 0x0   ---- .debug_line             PROGBITS   compressed
> -0x00001a58 0x120 0x08001a58 0x120 0x0   ---- .rela.debug_line        RELA       info
> -0x00000c48 0xb9  0x08000c48 0xb9  0x0   ---- .debug_line_str         PROGBITS   merge,strings,compressed
> -0x00001b78 0x6   0x08001b78 0x6   0x0   ---- .llvm_addrsig           0x6fff4c03 exclude
> -0x00000d08 0x2a0 0x08000d08 0x2a0 0x0   ---- .symtab                 SYMTAB     
> +0x000010f0 0x60  0x080010f0 0x60  0x0   ---- .rela.debug_info        RELA       info
> +0x00000859 0x29  0x08000859 0x29  0x0   ---- .debug_str_offsets      PROGBITS   compressed
> +0x00001150 0x810 0x08001150 0x810 0x0   ---- .rela.debug_str_offsets RELA       info
> +0x00000882 0x1b9 0x08000882 0x1b9 0x0   ---- .debug_str              PROGBITS   merge,strings,compressed
> +0x00000a3b 0x2a  0x08000a3b 0x2a  0x0   ---- .debug_addr             PROGBITS   compressed
> +0x00001960 0x90  0x08001960 0x90  0x0   ---- .rela.debug_addr        RELA       info
> +0x00000a65 0x22  0x08000a65 0x22  0x0   ---- .comment                PROGBITS   merge,strings
> +0x00000a87 0x0   0x08000a87 0x0   0x0   ---- .note.GNU-stack         PROGBITS   
> +0x00000a88 0x90  0x08000a88 0x90  0x0   -r-- .eh_frame               PROGBITS   alloc
> +0x000019f0 0x48  0x080019f0 0x48  0x0   ---- .rela.eh_frame          RELA       info
> +0x00000b18 0x113 0x08000b18 0x113 0x0   ---- .debug_line             PROGBITS   compressed
> +0x00001a38 0x120 0x08001a38 0x120 0x0   ---- .rela.debug_line        RELA       info
> +0x00000c2b 0xb9  0x08000c2b 0xb9  0x0   ---- .debug_line_str         PROGBITS   merge,strings,compressed
> +0x00001b58 0x6   0x08001b58 0x6   0x0   ---- .llvm_addrsig           0x6fff4c03 exclude
> +0x00000ce8 0x2a0 0x08000ce8 0x2a0 0x0   ---- .symtab                 SYMTAB     
>      1      DW_TAG_compile_unit       [has children] (0x0)
>      DW_AT_producer                 DW_FORM_strx1
>      DW_AT_language                 DW_FORM_data2
> ```

This seems to be normal behavior, at least on MacOS 13.5.2

```
➤ llvm-readelf -S test/bins/elf/float_ex1/float_ex1_arm_clang.dw.zlib
There are 22 section headers, starting at offset 0x1ce0:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .strtab           STRTAB          0000000000000000 001b7e 00015d 00      0   0  1
  [ 2] .text             PROGBITS        0000000000000000 000040 00026c 00  AX  0   0  4
  [ 3] .rela.text        RELA            0000000000000000 000fa8 000168 18   I 21   2  8
  [ 4] .rodata.str1.1    PROGBITS        0000000000000000 0002ac 00004c 01 AMS  0   0  1
  [ 5] .debug_abbrev     PROGBITS        0000000000000000 0002f8 000100 00   C  0   0  8
  [ 6] .debug_info       PROGBITS        0000000000000000 0003f8 000461 00   C  0   0  8
  [ 7] .rela.debug_info  RELA            0000000000000000 001110 000060 18   I 21   6  8
  [ 8] .debug_str_offsets PROGBITS       0000000000000000 000860 000029 00   C  0   0  8
  [ 9] .rela.debug_str_offsets RELA      0000000000000000 001170 000810 18   I 21   8  8
  [10] .debug_str        PROGBITS        0000000000000000 000890 0001b9 01 MSC  0   0  8
  [11] .debug_addr       PROGBITS        0000000000000000 000a50 00002a 00   C  0   0  8
  [12] .rela.debug_addr  RELA            0000000000000000 001980 000090 18   I 21  11  8
  [13] .comment          PROGBITS        0000000000000000 000a7a 000022 01  MS  0   0  1
  [14] .note.GNU-stack   PROGBITS        0000000000000000 000a9c 000000 00      0   0  1
  [15] .eh_frame         PROGBITS        0000000000000000 000aa0 000090 00   A  0   0  8
  [16] .rela.eh_frame    RELA            0000000000000000 001a10 000048 18   I 21  15  8
  [17] .debug_line       PROGBITS        0000000000000000 000b30 000113 00   C  0   0  8
  [18] .rela.debug_line  RELA            0000000000000000 001a58 000120 18   I 21  17  8
  [19] .debug_line_str   PROGBITS        0000000000000000 000c48 0000b9 01 MSC  0   0  8
  [20] .llvm_addrsig     LLVM_ADDRSIG    0000000000000000 001b78 000006 00   E  0   0  1
  [21] .symtab           SYMTAB          0000000000000000 000d08 0002a0 18      1  21  8
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  R (retain), p (processor specific)
```

File: test/db/abi/compilers/gcc (hunk 3 above)
Comment (b1llow) [reply test/db/abi/compilers/gcc]: Mainly because `debug_ranges` `debug_loc` sections were changed to load by need, and `debug_ranges` was not used, so the dump of `debug_ranges` was missing.

Moreover, these sections need the information in the `debug_info` `CompUnit` to be loaded correctly. In the past I used it the wrong way, and this is fixed in this PR.

Comment (b1llow) [reply test/db/abi/compilers/gcc]: the diff

[diff.txt](https://github.com/rizinorg/rizin/files/12597166/diff.txt)

File: librz/analysis/dwarf_process.c [hunk 5]
```diff
@@ -576,10 +575,20 @@ static char *anonymous_type_name(RzBaseTypeKind k, ut64 offset) {
...
+	}
+	attr = rz_bin_dwarf_die_get_attr(die, DW_AT_specification);
+	RzBinDwarfDie *spec = attr ? ht_up_find(ctx->dw->info->die_by_offset, rz_bin_dwarf_attr_udata(attr), NULL) : NULL;
+	if (spec) {
+		attr = rz_bin_dwarf_die_get_attr(spec, DW_AT_name);
+		if (attr) {
+			return attr_string(attr, ctx);
+		}
+	}
+	return NULL;
```
Comment (wargio) [inline librz/analysis/dwarf_process.c]: i would probably invert this if and avoid nesting (just easier to read)

File: librz/analysis/dwarf_process.c [hunk 6]
```diff
@@ -614,12 +623,12 @@ static RzPVector /*<RzBinDwarfDie *>*/ *die_children(const RzBinDwarfDie *die, R
 static ut64 die_bits_size(const RzBinDwarfDie *die) {
 	RzBinDwarfAttr *attr = rz_bin_dwarf_die_get_attr(die, DW_AT_byte_size);
 	if (attr) {
-		return attr->uconstant * CHAR_BIT;
+		return rz_bin_dwarf_attr_udata(attr) * CHAR_BIT;
```
Comment (wargio) [inline librz/analysis/dwarf_process.c:627]: can this overflow?

Comment (b1llow) [reply librz/analysis/dwarf_process.c:627]: Yes, so what should be the behavior when overflowing?

**Review by XVilka — CHANGES_REQUESTED** [review]
```
gcc -Ilibrz/bin/librz_bin.so.0.7.0.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -I../librz/bin/format -I../subprojects/lz4-1.9.4/lib -Isubprojects/zstd-1.5.5/lib -I../subprojects/zstd-1.5.5/lib -I../subprojects/zstd-1.5.5/lib/common -I../subprojects/zstd-1.5.5/lib/compress -I../subprojects/zstd-1.5.5/lib/decompress -I../subprojects/zstd-1.5.5/lib/dictBuilder -I../subprojects/zstd-1.5.5/lib/legacy -Isubprojects/yxml -I../subprojects/yxml -Ilibrz/util/sdb/src -I../librz/util/sdb/src -Ilibrz/util/sdb -I../librz/util/sdb -I../librz/type/parser -I../subprojects/libmspack/libmspack/mspack -I../subprojects/libmspack/libmspack -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -D_GNU_SOURCE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -DRZ_ASSERT_STDOUT=1 -Wno-cpp -fPIC -DRZ_API_BIN_ONLY=1 -MD -MQ librz/bin/librz_bin.so.0.7.0.p/dwarf_op.c.o -MF librz/bin/librz_bin.so.0.7.0.p/dwarf_op.c.o.d -o librz/bin/librz_bin.so.0.7.0.p/dwarf_op.c.o -c ../librz/bin/dwarf/op.c
../librz/bin/dwarf/op.c: In function ‘Evaluation_evaluate_one_operation’:
../librz/bin/dwarf/op.c:973:41: error: comparison between ‘enum <anonymous>’ and ‘enum <anonymous>’ [-Werror=enum-compare]
  973 |                 if (fb_attr->value.kind == OPERATION_KIND_UNSIGNED_CONSTANT) {
      |                                         ^~
cc1: all warnings being treated as errors
```

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@imbillow one error when in C++ mode:
```
#47 175.9 [ 36%] Building CXX object CMakeFiles/core_ghidra.dir/src/core_ghidra.cpp.o
#47 177.6 In file included from /tmp/***-install/usr/include/librz/rz_bin.h:19,
#47 177.6                  from /tmp/***-install/usr/include/librz/rz_asm.h:10,
#47 177.6                  from /tmp/***-install/usr/include/librz/rz_egg.h:4,
#47 177.6                  from /tmp/***-install/usr/include/librz/rz_core.h:14,
#47 177.6                  from /tmp/rz-ghidra/src/ArchMap.h:10,
#47 177.6                  from /tmp/rz-ghidra/src/core_ghidra.cpp:9:
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h: In function 'char* rz_bin_dwarf_attr_string(const RzBinDwarfAttr*, RzBinDWARF*, long long unsigned int)':
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1777:17: error: 'RzBinDwarfAttr_String' was not declared in this scope
#47 177.6   if (v->kind == RzBinDwarfAttr_String) {
#47 177.6                  ^~~~~~~~~~~~~~~~~~~~~
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1777:17: note: suggested alternative: 'RzBinDwarfAttrSpec'
#47 177.6   if (v->kind == RzBinDwarfAttr_String) {
#47 177.6                  ^~~~~~~~~~~~~~~~~~~~~
#47 177.6                  RzBinDwarfAttrSpec
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1779:24: error: 'RzBinDwarfAttr_StrRef' was not declared in this scope
#47 177.6   } else if (v->kind == RzBinDwarfAttr_StrRef && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1779:24: note: suggested alternative: 'RzBinDwarfAttrSpec'
#47 177.6   } else if (v->kind == RzBinDwarfAttr_StrRef && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~
#47 177.6                         RzBinDwarfAttrSpec
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1781:24: error: 'RzBinDwarfAttr_StrOffsetIndex' was not declared in this scope
#47 177.6   } else if (v->kind == RzBinDwarfAttr_StrOffsetIndex && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1781:24: note: suggested alternative: 'RzBinDwarfStrOffsets'
#47 177.6   } else if (v->kind == RzBinDwarfAttr_StrOffsetIndex && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#47 177.6                         RzBinDwarfStrOffsets
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1783:24: error: 'RzBinDwarfAttr_LineStrRef' was not declared in this scope
#47 177.6   } else if (v->kind == RzBinDwarfAttr_LineStrRef && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1783:24: note: suggested alternative: 'RzBinDwarfLineStr'
#47 177.6   } else if (v->kind == RzBinDwarfAttr_LineStrRef && dw) {
#47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~
#47 177.6                         RzBinDwarfLineStr
#47 177.6 In file included from /tmp/***-install/usr/include/librz/rz_vector.h:5,
#47 177.6                  from /tmp/***-install/usr/include/librz/rz_util/rz_annotated_code.h:7,
#47 177.6                  from /tmp/rz-ghidra/src/CodeXMLParse.h:7,
#47 177.6                  from /tmp/rz-ghidra/src/core_ghidra.cpp:8:
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h: In function 'const RzBinDwarfBlock* rz_bin_dwarf_attr_block(const RzBinDwarfAttr*)':
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1808:2: error: 'RzBinDwarfAttr_Block' was not declared in this scope
#47 177.6   rz_return_val_if_fail(attr && attr->value.kind == RzBinDwarfAttr_Block, NULL);
#47 177.6   ^~~~~~~~~~~~~~~~~~~~~
#47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1808:2: note: suggested alternative: 'RzBinDwarfAttrValue'
#47 ...
```

**Comment by b1llow** [comment]
> @imbillow one error when in C++ mode:
> 
> ```
> #47 175.9 [ 36%] Building CXX object CMakeFiles/core_ghidra.dir/src/core_ghidra.cpp.o
> #47 177.6 In file included from /tmp/***-install/usr/include/librz/rz_bin.h:19,
> #47 177.6                  from /tmp/***-install/usr/include/librz/rz_asm.h:10,
> #47 177.6                  from /tmp/***-install/usr/include/librz/rz_egg.h:4,
> #47 177.6                  from /tmp/***-install/usr/include/librz/rz_core.h:14,
> #47 177.6                  from /tmp/rz-ghidra/src/ArchMap.h:10,
> #47 177.6                  from /tmp/rz-ghidra/src/core_ghidra.cpp:9:
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h: In function 'char* rz_bin_dwarf_attr_string(const RzBinDwarfAttr*, RzBinDWARF*, long long unsigned int)':
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1777:17: error: 'RzBinDwarfAttr_String' was not declared in this scope
> #47 177.6   if (v->kind == RzBinDwarfAttr_String) {
> #47 177.6                  ^~~~~~~~~~~~~~~~~~~~~
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1777:17: note: suggested alternative: 'RzBinDwarfAttrSpec'
> #47 177.6   if (v->kind == RzBinDwarfAttr_String) {
> #47 177.6                  ^~~~~~~~~~~~~~~~~~~~~
> #47 177.6                  RzBinDwarfAttrSpec
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1779:24: error: 'RzBinDwarfAttr_StrRef' was not declared in this scope
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_StrRef && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1779:24: note: suggested alternative: 'RzBinDwarfAttrSpec'
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_StrRef && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~
> #47 177.6                         RzBinDwarfAttrSpec
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1781:24: error: 'RzBinDwarfAttr_StrOffsetIndex' was not declared in this scope
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_StrOffsetIndex && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1781:24: note: suggested alternative: 'RzBinDwarfStrOffsets'
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_StrOffsetIndex && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> #47 177.6                         RzBinDwarfStrOffsets
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1783:24: error: 'RzBinDwarfAttr_LineStrRef' was not declared in this scope
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_LineStrRef && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1783:24: note: suggested alternative: 'RzBinDwarfLineStr'
> #47 177.6   } else if (v->kind == RzBinDwarfAttr_LineStrRef && dw) {
> #47 177.6                         ^~~~~~~~~~~~~~~~~~~~~~~~~
> #47 177.6                         RzBinDwarfLineStr
> #47 177.6 In file included from /tmp/***-install/usr/include/librz/rz_vector.h:5,
> #47 177.6                  from /tmp/***-install/usr/include/librz/rz_util/rz_annotated_code.h:7,
> #47 177.6                  from /tmp/rz-ghidra/src/CodeXMLParse.h:7,
> #47 177.6                  from /tmp/rz-ghidra/src/core_ghidra.cpp:8:
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h: In function 'const RzBinDwarfBlock* rz_bin_dwarf_attr_block(const RzBinDwarfAttr*)':
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1808:2: error: 'RzBinDwarfAttr_Block' was not declared in this scope
> #47 177.6   rz_return_val_if_fail(attr && attr->value.kind == RzBinDwarfAttr_Block, NULL);
> #47 177.6   ^~~~~~~~~~~~~~~~~~~~~
> #47 177.6 /tmp/***-install/usr/include/librz/rz_bin_dwarf.h:1808:2: note: suggested alternative: 'RzBinDwarfAttrValue'
> #47 ...
> ```

Can you try this branch? because I don't know the compilation command you used?

https://github.com/rizinorg/rizin/tree/dev-dwarf-fix

**Comment by XVilka** [comment]
It's from building the Docker image with rz-ghidra. You can try it yourself, otherwise I will try tomorrow

**Comment by b1llow** [comment]
> It's from building the Docker image with rz-ghidra. You can try it yourself, otherwise I will try tomorrow

fixed in https://github.com/rizinorg/rizin/pull/3906

**Comment by b1llow** [comment]
Sorry for the delay.

**Comment by kazarmy** [comment]
Sorry didn't realize there was a fix.

**Comment by XVilka** [comment]
> Sorry for the delay.

Sorry for the delay too, I am travelling last weeks, had no time to check.
