### PR TITLE
TriCore IL: fix `CSUB/CSUBN`

### LINKED ISSUE #4401: Tricore IL: CSUB/CSUBN are not properly implemented
https://github.com/rizinorg/rizin/blob/8fec79ab6114b24f1c69fffbec21059b33516834/librz/arch/isa/tricore/tricore_il.c#L2005-L2012

`cond` is ignored that impacts on result/status flags values and also causes memleaks.

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #4401

### CODE REVIEW

**Comment by p371jah** [comment]
According to ISA condition also affects status flags. I think it would be better to add helper like `f_overflow32` with `condition`.
UPD: I see it is already done as part of `e_cadd`.

File: librz/arch/isa/tricore/tricore_il.c [hunk 1]
```diff
@@ -2006,7 +2006,8 @@ static RzILOpEffect *e_op2_cond(
 	const char *r, RzILOpPure *a, RzILOpPure *b, RzILOpPure *cond,
 	RzILOpPure *(*op)(RzILOpPure *x, RzILOpPure *y)) {
 
-	RzILOpEffect *e = SEQ2(SETL("result", op(a, b)),
+	RzILOpEffect *e = SEQ2(
+		SETL("result", ITE(cond, op(a, b), DUP(a))),
 		SETG(r, VARL("result")));
 	return f_overflow32(e);
```
Comment (p371jah) [inline librz/arch/isa/tricore/tricore_il.c]: Move out part of `e_cadd()` handler to a separate function and use it here

**Review by p371jah — CHANGES_REQUESTED** [review]

**Review by XVilka — APPROVED** [review]

**Review by p371jah — APPROVED** [review]
