### PR TITLE
Fix: UAF caused by parse_type_abstract_declarator_node()

### LINKED ISSUE #1982: `double free or corruption (fasttop)` if analysing unstripped binary
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            |  x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64  commit: 081ebe728f368fb91749b7898dfefba82132ee9f, build: 2021-11-15__07:03:54

### Expected behavior

rizin doesn't crash

### Actual behavior

rizin crashes with: 
```
Cannot find base type "allocator"mation.
Cannot find base type "allocator"
Cannot find base type "_Sp_alloc_shared_tag"
Cannot find base type "_Sp_alloc_shared_tag"
Cannot find base type "allocator"
WARNING: (../librz/type/type.c:790):rz_type_db_get_bitsize: code should not be reached
WARNING: rz_type_is_strictly_atomic: assertion 'type->identifier.name' failed (line 357)
WARNING: rz_type_db_get_base_type: assertion 'typedb && name' failed (line 35)
double free or corruption (fasttop)
Aborted
```

### Steps to reproduce the behavior

```
$ rizin money_watch_non_stripped
[0x004091b0]> aaaaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[Cannot find base type "allocator"mation.
Cannot find base type "allocator"
Cannot find base type "_Sp_alloc_shared_tag"
Cannot find base type "_Sp_alloc_shared_tag"
Cannot find base type "allocator"
WARNING: (../librz/type/type.c:790):rz_type_db_get_bitsize: code should not be reached
WARNING: rz_type_is_strictly_atomic: assertion 'type->identifier.name' failed (line 357)
WARNING: rz_type_db_get_base_type: assertion 'typedb && name' failed (line 35)
double free or corruption (fasttop)
Aborted
```
The stripped binary doesn't make rizin crash

### Additional Logs, screenshots, source code,  configuration dump, ...

GDB Backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7cd28a4 in __GI_abort () at abort.c:79
#2  0x00007ffff7d2ba97 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7e3c7fc "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7d3370c in malloc_printerr (str=str@entry=0x7ffff7e3ec48 "double free or corruption (fasttop)") at malloc.c:5628
#4  0x00007ffff7d34c33 in _int_free (av=0x7ffff7e6fa00 <main_arena>, p=0x221fc70, have_lock=0) at malloc.c:4498
#5  0x00007ffff7d387c8 in __GI___libc_free (mem=<optimized out>) at malloc.c:3309
#6  0x00007ffff6d54278 in rz_analysis_dwarf_integrate_functions (analysis=<optimized out>, flags=0x4503e0, dwarf_sdb=dwarf_sdb@entry=0xf7e580) at ../librz/analysis/dwarf_process.c:1708
#7  0x00007ffff69213d1 in rz_core_analysis_everything (core=core@entry=0x7ffff66bf010, experimental=<optimized out>, dh_orig=dh_orig@entry=0x0) at ../librz/core/canalysis.c:6758
#8  0x00007ffff69e2f32 in cmd_analysis_all (input=0xaff642 "aaaa", core=0x7ffff66bf010) at ../librz/core/cmd/cmd_analysis.c:7478
#9  rz_cmd_analysis (data=0x7ffff66bf010, input=0xaff641 "aaaaa") at ../librz/core/cmd/cmd_analysis.c:8423
#10 0x00007ffff69fd250 in call_cd (args=<optimized out>, cd=0x45f5f0, cmd=<optimized out>) at ../librz/core/cmd/cmd_api.c:753
#11 rz_cmd_call_parsed_args (cmd=0x457010, args=args@entry=0xaff5d0) at ../librz/core/cmd/cmd_api.c:768
#12 0x00007ffff69f3508 in handle_ts_arged_stmt_internal (node_string=0xaff590 "aaaaaa", node=..., state=0x7fffffffd970) at ../librz/core/cmd/cmd.c:3981
#13 handle_ts_arged_stmt (state=0x7fffffffd970, node=...) at ../librz/core/cmd/cmd.c:3929
#14 0x00007ffff698de89 in handle_ts_stmt (state=state@entry=0x7fffffffd970, node=...) at ../librz/core/cmd/cmd.c:5429
#15 0x00007ffff69d0b12 in handle_ts_statements_internal (node_string=0xaff570 "aaaaaa", node=..., state=0x7fffffffd970) at ../librz/core/cmd/cmd.c:5486
#16 handle_ts_statements (state=state@entry=0x7fffffffd970, node=...) at ../librz/core/cmd/cmd.c:5451
#17 0x00007ffff69d0efb in core_cmd_tsrzcmd (core=0x7fffffffd988, cstr=<optimized out>, split_lines=split_lines@entry=false, log=log@entry=true) at ../librz/core/cmd/cmd.c:5594
#18 0x00007ffff69c3d3e in rz_core_cmd (core=core@entry=0x7ffff66bf010, cstr=0xafec10 "aaaaaa", log=log@entry=1) at ../librz/core/cmd/cmd.c:5643
#19 0x00007ffff69513ab in rz_core_prompt_exec (r=r@entry=0x7ffff66bf010) at ../librz/core/core.c:2838
#20 0x00007ffff6951a3e in rz_core_prompt_loop (r=r@entry=0x7ffff66bf010) at ../librz/core/core.c:2689
#21 0x00007ffff7eb15ad in rz_main_rizin (argc=<optimized out>, argv=<optimized out>) at ../librz/main/rizin.c:1370
#22 0x00007ffff7cd3b75 in __libc_start_main (main=0x401100 <main>, argc=2, argv=0x7fffffffdd08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcf8) at ../csu/libc-start.c:332
#23 0x000000000040149e in _start ()
```

[binaries.zip](https://github.com/rizinorg/rizin/files/7538605/binaries.zip)

### PR DESCRIPTION
**Pull request by PeiweiHu**
Fix https://github.com/rizinorg/rizin/issues/1982

Signed-off-by: Peiwei Hu <jlu.hpw@foxmail.com>

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

File: librz/type/parser/types_parser.c [hunk 1]
```diff
@@ -1350,13 +1350,15 @@ int parse_type_abstract_declarator_node(CParserState *state, TSNode node, const
 				parser_error(state, "ERROR: Abstract pointer declarator AST should contain at least one node!\n");
 				node_malformed_error(state, node, text, "pointer declarator");
 				free(type);
+				(*tpair)->type = type = NULL;
```
Comment (XVilka) [inline librz/type/parser/types_parser.c]: No need to set `type`, just `(*tpair)->type` is enough. Same for the second case.

**Review by XVilka — CHANGES_REQUESTED** [review]

**Review by XVilka — APPROVED** [review]
