### PR TITLE
Fix type name parsing in `tc` and `tcd`

### LINKED ISSUE #1607: types not correctly autocompleted
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33 x86_64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64
commit: 7b13e5a69d5d0cac04a0d08e4704cd48686fc7ae, build: 2021-09-06__18:54:15

### Expected behavior
`struct s` should be mentioned instead, so that when you do `tc "struct s"` that works.

### Actual behavior
`s` is mentioned in the possible autocompletions, but if you do `tc s` it does not work (it does not even give you a message that `s` does not exist).

### Steps to reproduce the behavior
```
$ rizin
> e cfg.oldshell.autocompletion=false
> td "struct s{}"
> tc <TAB>
```

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Changes the logic in many `t` commands, `tc` and `tcd` in particular to accept just the type name without the `struct` or `union` keyword required.

**Test plan**

```
e cfg.oldshell.autocompletion=false
td "struct blablafoo {};"
tc bla<TAB>
tcd bla<TAB>
tsc bla<TAB> # should show "blablafoo"
tuc bla<TAB> # should show nothing
```

**Closing issues**

Fixes #1607

### CODE REVIEW

File: librz/core/cmd_type.c [hunk 1]
```diff
@@ -318,7 +327,7 @@ RZ_IPI RzCmdStatus rz_type_cc_del_all_handler(RzCore *core, int argc, const char
 RZ_IPI RzCmdStatus rz_type_list_c_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
 		if (!print_type_c(core, argv[1], true)) {
-			printf("Wrong type syntax");
+			eprintf("Type \"%s\" not found\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: `RZ_LOG_ERROR`?

File: librz/core/cmd_type.c [hunk 2]
```diff
@@ -330,7 +339,7 @@ RZ_IPI RzCmdStatus rz_type_list_c_handler(RzCore *core, int argc, const char **a
 RZ_IPI RzCmdStatus rz_type_list_c_nl_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
 		if (!print_type_c(core, argv[1], false)) {
-			eprintf("Wrong type syntax");
+			eprintf("Type \"%s\" not found\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR?

File: librz/core/cmd_type.c [hunk 3]
```diff
@@ -346,15 +355,18 @@ RZ_IPI RzCmdStatus rz_type_define_handler(RzCore *core, int argc, const char **a
...
+	if (argc > 1) {
+		if (argc > 2) {
+			// TODO: Reconsider the `te <enum_name> <member_value>` syntax change
+			return types_enum_member_find(core, argv[1], argv[2]);
 		} else {
 			PJ *pj = (mode == RZ_OUTPUT_MODE_JSON) ? pj_new() : NULL;
-			rz_core_types_enum_print(core, enum_name, mode, pj);
+			RzBaseType *btype = rz_type_db_get_enum(core->analysis->typedb, argv[1]);
+			if (!btype) {
+				eprintf("Cannot find \"%s\" enum type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR

File: librz/core/cmd_type.c [hunk 4]
```diff
@@ -384,7 +396,12 @@ RZ_IPI RzCmdStatus rz_type_enum_bitfield_handler(RzCore *core, int argc, const c
 
 RZ_IPI RzCmdStatus rz_type_enum_c_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
-		rz_core_types_enum_print_c(core->analysis->typedb, argv[1], true);
+		RzBaseType *btype = rz_type_db_get_enum(core->analysis->typedb, argv[1]);
+		if (!btype) {
+			eprintf("Cannot find \"%s\" enum type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR

File: librz/core/cmd_type.c [hunk 5]
```diff
@@ -393,7 +410,12 @@ RZ_IPI RzCmdStatus rz_type_enum_c_handler(RzCore *core, int argc, const char **a
 
 RZ_IPI RzCmdStatus rz_type_enum_c_nl_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
-		rz_core_types_enum_print_c(core->analysis->typedb, argv[1], false);
+		RzBaseType *btype = rz_type_db_get_enum(core->analysis->typedb, argv[1]);
+		if (!btype) {
+			eprintf("Cannot find \"%s\" enum type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR

File: librz/core/cmd_type.c [hunk 6]
```diff
@@ -550,13 +572,17 @@ RZ_IPI RzCmdStatus rz_type_print_hexstring_handler(RzCore *core, int argc, const
...
+	if (argc > 1) {
 		if (mode == RZ_OUTPUT_MODE_STANDARD) {
-			rz_core_types_show_format(core, typename, mode);
+			rz_core_types_show_format(core, argv[1], mode);
 		} else {
 			PJ *pj = (mode == RZ_OUTPUT_MODE_JSON) ? pj_new() : NULL;
-			rz_core_types_struct_print(core, typename, mode, pj);
+			RzBaseType *btype = rz_type_db_get_struct(core->analysis->typedb, argv[1]);
+			if (!btype) {
+				eprintf("Cannot find \"%s\" struct type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR

File: librz/core/cmd_type.c [hunk 7]
```diff
@@ -574,7 +600,12 @@ RZ_IPI RzCmdStatus rz_type_list_structure_handler(RzCore *core, int argc, const
 
 RZ_IPI RzCmdStatus rz_type_structure_c_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
-		rz_core_types_struct_print_c(core->analysis->typedb, argv[1], true);
+		RzBaseType *btype = rz_type_db_get_struct(core->analysis->typedb, argv[1]);
+		if (!btype) {
+			eprintf("Cannot find \"%s\" struct type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: RZ_LOG_ERROR

File: librz/core/cmd_type.c [hunk 8]
```diff
@@ -583,18 +614,27 @@ RZ_IPI RzCmdStatus rz_type_structure_c_handler(RzCore *core, int argc, const cha
 
 RZ_IPI RzCmdStatus rz_type_structure_c_nl_handler(RzCore *core, int argc, const char **argv) {
 	if (argc > 1) {
-		rz_core_types_struct_print_c(core->analysis->typedb, argv[1], false);
+		RzBaseType *btype = rz_type_db_get_struct(core->analysis->typedb, argv[1]);
+		if (!btype) {
+			eprintf("Cannot find \"%s\" struct type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: guess what... RZ_LOG_ERROR :D

File: librz/core/cmd_type.c [hunk 9]
```diff
@@ -583,18 +614,27 @@ RZ_IPI RzCmdStatus rz_type_structure_c_handler(RzCore *core, int argc, const cha
...
 
 RZ_IPI RzCmdStatus rz_type_list_typedef_handler(RzCore *core, int argc, const char **argv, RzOutputMode mode) {
-	const char *typename = argc > 1 ? argv[1] : NULL;
-	if (typename) {
+	if (argc > 1) {
 		PJ *pj = (mode == RZ_OUTPUT_MODE_JSON) ? pj_new() : NULL;
-		rz_core_types_typedef_print(core, typename, mode, pj);
+		RzBaseType *btype = rz_type_db_get_typedef(core->analysis->typedb, argv[1]);
+		if (!btype) {
+			eprintf("Cannot find \"%s\" typedef type\n", argv[1]);
```
Comment (ret2libc) [inline librz/core/cmd_type.c]: xxxxx

Comment (ret2libc) [reply librz/core/cmd_type.c]: everywhere pls

**Review by ret2libc — CHANGES_REQUESTED** [review]
Looks good apart from those things.

File: test/db/cmd/cmd_tc [hunk 10]
```diff
@@ -323,8 +323,8 @@ NAME=tc4 iOS14 arm64e
 FILE=bins/mach0/objc-employee-ios14-arm64e
 CMDS=<<EOF
 .ic*
-tc "struct Employee"
-tc "struct NSString"
+tc Employee
+tc NSString
```
Comment (wargio) [inline test/db/cmd/cmd_tc:327]: i am not sure that these are actually structs.

Comment (XVilka) [reply test/db/cmd/cmd_tc:327]: They are probably classes but for now, are treated as structures.

File: test/db/cmd/types [hunk 11]
```diff
@@ -351,6 +351,7 @@ EXPECT_ERR=<<EOF
 Cannot find base type "xoo"
 Cannot find 'xoo' type
 Cannot find base type "xoo"
+ERROR: Cannot find "xoo" union type
```
Comment (ret2libc) [inline test/db/cmd/types:354]: Why one says "ERROR:" and the others don't?

Comment (XVilka) [reply test/db/cmd/types:354]: Because other parts are in the other C files. Should I change all of them in this PR? It's out of the scope of this PR IMHO,

Comment (ret2libc) [reply test/db/cmd/types:354]: Ok I thought they were coming directly from the commands. Don't like this inconsistency though :D Maybe it was better with eprintf...

\me runs away :D

**Review by ret2libc — APPROVED** [review]
