### PR TITLE
Remove usage of rz_bin_is_big_endian

### LINKED ISSUE #2756: PPC big-endian VLE incorrectly disassemble
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10
| File format of the file you reverse (mandatory)      | Firmware baremetal
| Architecture/bits of the file (mandatory)            | PPC, Big-endian, VLE
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0 @ windows-x86-64 commit: 7158b6192549322e51779ca74c9ec96b977124ec, build: Thu 06/23/2022__21:55:47.16

### Expected behavior
Should be (IDA Pro)
```python
ROM:00000000 00 80                                         se_mflr   r0
ROM:00000002 18 21 06 F0                                   e_stwu    r1, -0x10(r1)
ROM:00000006 D3 F1                                         se_stw    r31, 0xC(r1)
ROM:00000008 D5 01                                         se_stw    r0, 0x14(r1)
ROM:0000000A 2A 04                                         se_cmpi   r4, 0
ROM:0000000C 71 60 00 00                                   e_li      r11, 0
ROM:00000010 7A 12 02 02                                   e_beq     0x212
ROM:00000014 19 44 84 FF                                   e_addi    r10, r4, -1
ROM:00000018 7D 4A 14 70                                   e_srwi    r10, r10, 2
ROM:0000001C 18 EA 80 02                                   e_addi    r7, r10, 2
ROM:00000020 0D 76                                         se_cmpl   r6, r7
ROM:00000022 E0 04                                         se_bge    loc_2A
ROM:00000024 48 13                                         se_li     r3, 1
```

### Actual behavior
Always instructions are 32 bits length

```python
            ;-- pc:
            0x00000000      invalid
            0x00000004      invalid
┌ fcn.00000008 ();
│           0x00000008      stfsu f8, 0x2a04(r1)
│           0x0000000c      andi. r0, r11, 0
│           0x00000010      rldicl r18, r16, 0x20, 8
└           0x00000014      invalid
            0x00000018      invalid
            0x0000001c      invalid
            0x00000020      twi   0xb, r22, 0xe004
        ┌─< 0x00000024      b     0x137824
        │   0x00000028      invalid
        │   0x0000002c      lbz   r0, 0x18e5(r1)
        │   0x00000030      lwz   r0, 0x481f(r4)
        │   0x00000034      invalid
        │   0x00000038      invalid
        │   0x0000003c      invalid
        │   0x00000040      invalid
       ┌──< 0x00000044      b     0x8671c4
```

### Steps to reproduce the behavior

Source file [ppc-big-endian-vle.zip](https://github.com/rizinorg/rizin/files/9010298/ppc-big-endian-vle.zip)

```python
r2=rzpipe.open(r"./ppc-big-endian-vle.bin")
r2.cmd("e asm.arch=ppc")
r2.cmd("e cfg.bigendian=true")
r2.cmd("e asm.bits=16")
r2.cmd("s 0")
r2.cmd("aaa")
v=r2.cmd("pD")
print(v)
```

### Additional Logs, screenshots, source code,  configuration dump, ...
[ppc-big-endian-vle.zip](https://github.com/rizinorg/rizin/files/9010298/ppc-big-endian-vle.zip)

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Remove usage of `rz_bin_is_big_endian` which changes the endianness set  by the user

Fix #2756

### CODE REVIEW

**Review by wargio — COMMENTED** [review]
Missing a test, i will add it later

**Review by ret2libc — CHANGES_REQUESTED** [review]
I think you can completely kill that function (grep for it, it is supposed to be deprecated). Also, `rz_bin_object_is_big_endian` is used in few other places, but I do wonder whether we should just use cfg.bigendian there as well. WDYT?

**Comment by wargio** [comment]
> in few other places, but I do wonder whether we should just use cfg.bigendian the

i feel like the whole big_endian bool should be set only by the callback that sets cfg.bigendian

**Review by XVilka — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Please fix conflicts and after that it can be merged.

**Comment by ret2libc** [comment]
Are you going to fix the `rz_bin_object_is_big_endian` calls in cmeta.c and cmd_meta.c as well?

**Comment by wargio** [comment]
yup

**Review by XVilka — APPROVED** [review]

File: librz/bin/bobj.c [hunk 1]
```diff
@@ -869,14 +869,6 @@ RZ_API RZ_BORROW RzBinString *rz_bin_object_get_string_at(RZ_NONNULL RzBinObject
 	return ht_up_find(obj->strings->phys, address, NULL);
 }
 
-/**
- * \brief Return true if the binary object \p obj is big endian.
- */
-RZ_API bool rz_bin_object_is_big_endian(RzBinObject *obj) {
```
Comment (ret2libc) [inline librz/bin/bobj.c]: I think this can be kept even if it's not currently used... I imagine it should be used when you want to show information of the binary (probably there are places that access info->big_endian directly instead of using this)

Comment (wargio) [reply librz/bin/bobj.c]: added back

**Review by ret2libc — APPROVED** [review]
