### PR TITLE
Add NetBSD debug tests and fix errors

### LINKED ISSUE #3274: Debugging on NetBSD 9.3 x86_64 starts from 0x000000 address
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | NetBSD 9.3 amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 1b4385e22

### Expected behavior

Jump to the entry automatically

### Actual behavior

```
$ rizin -d test/elf/netbsd-hello-x64
[0x000000]>
[0x000000]> pi 4
invalid
invalid
invalid
invalid
```

Nevertheless, if you go to the `main`, it shows the right code
```
[0x000000]> pi 4 @ main
push rbp
mov rbp, rsp
mov edi, str.Hello_World
call sym.imp.puts
```
Moreover, `dc` command always goes to the infinite loop for some reason, with and without `db` set.

See:
- `librz/debug/p/native/bsd/`
- `librz/debug/p/debug_native.c`

### PR DESCRIPTION
**Pull request by well-mannered-goat**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

- Added netbsd x86_64 register profile so that the registers are assigned correct values and hence the `core->offset`, this would show the correct address in the rizin prompt instead of 0x000 for netbsd in debugger mode.
- Fixed `native_wait` function in netbsd.c to use the correct reason instead of assigning RZ_DEBUG_REASON_TRAP and correctly show prompt if process is exited.
- The netbsd attach function just ignored if the ptrace failed (which it would because the debugee is attached from fork and trace), so instead added proper error handling.
- added some netbsd tests, used the binary files that xvilka had pushed in rizin-testbins earlier.

**Test plan**

rz-test test/db/archos/netbsd-x64
CI is green

**Closing issues**

closed #3274 and partially #3072

### CODE REVIEW

File: librz/debug/p/native/netbsd.c [hunk 1]
```diff
@@ -40,11 +40,33 @@ static bool rz_debug_native_step(RzDebug *dbg) {
 	return true;
 }
 
+int match_pid(const void *pid_o, const void *th_o, void *user) {
+	int pid = *(int *)pid_o;
```
Comment (notxvilka) [inline librz/debug/p/native/netbsd.c:45]: Usually this is a bad idea, but because it's only for runtime, then it's probably fine.

File: librz/debug/p/native/netbsd.c [hunk 2]
```diff
@@ -40,11 +40,33 @@ static bool rz_debug_native_step(RzDebug *dbg) {
...
+	RzDebugPid *th = (RzDebugPid *)th_o;
+	return (pid == th->pid) ? 0 : 1;
+}
+
+static RZ_OWN RzList /*<RzDebugPid *>*/ *get_pid_thread_list(RZ_NONNULL RzDebug *dbg, int main_pid) {
+	rz_return_val_if_fail(dbg, NULL);
+	RzList *list = rz_list_new();
+	if (list) {
```
Comment (notxvilka) [inline librz/debug/p/native/netbsd.c]: It's probably better to invert the condition, to do early exit.

File: librz/debug/p/native/netbsd.c [hunk 3]
```diff
@@ -40,11 +40,33 @@ static bool rz_debug_native_step(RzDebug *dbg) {
...
-	if (ret != -1) {
-		eprintf("Trying to attach to %d\n", pid);
-		perror("ptrace (PT_ATTACH)");
+	if (!dbg->threads) {
+		dbg->threads = get_pid_thread_list(dbg, pid);
+	} else {
+		if (!rz_list_find(dbg->threads, &pid, &match_pid, NULL)) {
+			int ret = ptrace(PTRACE_ATTACH, pid, 0, 0);
+			if (ret == -1) {
+				eprintf("Trying to attach to %d\n", pid);
```
Comment (notxvilka) [inline librz/debug/p/native/netbsd.c]: Maybe substitute it with `RZ_LOG_ERROR` too?

**Review by notxvilka — CHANGES_REQUESTED** [review]
Great job, please also add a test for 1) breakpoints 2) step over

It also applies to other platforms - other *BSD, and PPC, ARM64, SystemZ

**Comment by notxvilka** [comment]
Ignore the comment about breakpoints - I see they are part of one test

File: librz/debug/p/native/bsd/bsd_debug.c [hunk 4]
```diff
@@ -675,6 +696,51 @@ RzList *bsd_thread_list(RzDebug *dbg, int pid, RzList *list) {
 		rz_list_append(list, pid_info);
 	}
 
+	free(kp);
+	return list;
+#elif __NetBSD__
```
Comment (Rot127) [inline librz/debug/p/native/bsd/bsd_debug.c]: Please move this block into a static function. It gets confusing with the `#ifdef`

File: librz/debug/p/native/netbsd.c (hunk 1 above)
Comment (Rot127) [reply librz/debug/p/native/netbsd.c:45]: Can the `pid_o` value be received from a remote host with different endianess?
Because then we might get an issues here.

File: librz/debug/p/native/netbsd.c [hunk 5]
```diff
@@ -40,11 +40,33 @@ static bool rz_debug_native_step(RzDebug *dbg) {
...
+	return list;
+}
+
 static int rz_debug_native_attach(RzDebug *dbg, int pid) {
-	int ret = ptrace(PTRACE_ATTACH, pid, 0, 0);
-	if (ret != -1) {
-		eprintf("Trying to attach to %d\n", pid);
-		perror("ptrace (PT_ATTACH)");
+	if (!dbg->threads) {
+		dbg->threads = get_pid_thread_list(dbg, pid);
```
Comment (Rot127) [inline librz/debug/p/native/netbsd.c:64]: Add the return here and save the `else` block please.

File: librz/debug/p/native/netbsd.c [hunk 6]
```diff
@@ -101,17 +120,16 @@ static RzDebugReasonType rz_debug_native_wait(RzDebug *dbg, int pid) {
 	/* we don't know what to do yet, let's try harder to figure it out. */
 	if (reason == RZ_DEBUG_REASON_UNKNOWN) {
 		if (WIFEXITED(status)) {
-			eprintf("child exited with status %d\n", WEXITSTATUS(status));
+			if (dbg->pid == pid) {
+				eprintf("(%d) Process exited with status=0x%x\n", pid, WEXITSTATUS(status));
```
Comment (Rot127) [inline librz/debug/p/native/netbsd.c]: `RZ_LOG_ERROR`

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: librz/debug/p/native/netbsd.c (hunk 1 above)
Comment (notxvilka) [reply librz/debug/p/native/netbsd.c:45]: Not in the native one, it's not a remote debugger plugin

File: librz/debug/p/native/netbsd.c (hunk 6 above)
Comment (well-mannered-goat) [reply librz/debug/p/native/netbsd.c]: Wouldnt it be wrong to log an error when the process exits? Sorry if i am getting it wrong

**Comment by well-mannered-goat** [comment]
Have tweaked some tests to check how they are working, will fix rz-test accordingly

File: librz/debug/p/native/netbsd.c [hunk 7]
```diff
@@ -101,17 +122,16 @@ static RzDebugReasonType rz_debug_native_wait(RzDebug *dbg, int pid) {
...
```
Comment (wargio) [inline librz/debug/p/native/netbsd.c]: RZ_LOG_WARN

File: librz/debug/p/native/netbsd.c [hunk 8]
```diff
@@ -101,17 +122,16 @@ static RzDebugReasonType rz_debug_native_wait(RzDebug *dbg, int pid) {
...
+			} else {
+				eprintf("(%d) Thread exited with status=0x%x\n", pid, WEXITSTATUS(status));
```
Comment (wargio) [inline librz/debug/p/native/netbsd.c]: RZ_LOG_WARN

File: test/db/archos/netbsd-x64/dbg [hunk 9]
```diff
@@ -0,0 +1,109 @@
...
+dc
+EOF
+EXPECT=<<EOF
+push rbp
+mov rbp, rsp
+mov edi, str.Hello_World
+call sym.imp.puts
+mov eax, 0x00
+Hello World
+Bye
```
Comment (notxvilka) [inline test/db/archos/netbsd-x64/dbg]:
```
[XX] 273 ms   db/archos/netbsd-x64/dbg dcu + read
RZ_NOPLUGINS=1 /home/build/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -d -qc 'dcu main
pi 5
dc
' bins/rizin-testbins/elf/netbsd-hello-x64
-- stdout
--- expected
+++ actual
@@ -4,4 +4,3 @@
 call sym.imp.puts
 mov eax, 0x00
 Hello World
-Bye

-- stderr
Process with PID 6740 started...
hit breakpoint at: 0x40096a
(6740) Process exited with status=0x0

==> Process finished
```

File: librz/debug/p/native/bsd/bsd_debug.c [hunk 10]
```diff
@@ -677,8 +675,86 @@ RzList *bsd_thread_list(RzDebug *dbg, int pid, RzList *list) {
...
+	int i = 0;
+
+	if (sysctl(mib, 6, NULL, &len, NULL, 0) == -1) {
+		rz_list_free(list);
+		return NULL;
+	}
+
+	len += sizeof(*kp) + len / 10;
+	kp = malloc(len);
+	if (!kp) {
```
Comment (wargio) [inline librz/debug/p/native/bsd/bsd_debug.c:715]: maybe ensure that len cannot be 0?

File: librz/debug/p/native/bsd/bsd_debug.c [hunk 11]
```diff
@@ -677,8 +675,86 @@ RzList *bsd_thread_list(RzDebug *dbg, int pid, RzList *list) {
...
+		return NULL;
+	}
+
+	max = len / sizeof(*kp);
+
+	for (i = 0; i < max; i++) {
+		RzDebugPid *pid_info;
+		int pid_stat;
+
+		pid_stat = get_rz_status(kp[i].p_stat);
```
Comment (wargio) [inline librz/debug/p/native/bsd/bsd_debug.c]:
```suggestion
		int pid_stat = get_rz_status(kp[i].p_stat);
```

File: librz/debug/p/native/bsd/bsd_debug.c [hunk 12]
```diff
@@ -677,8 +675,86 @@ RzList *bsd_thread_list(RzDebug *dbg, int pid, RzList *list) {
...
+	if (sysctl(mib, 6, kp, &len, NULL, 0) == -1) {
+		free(kp);
+		rz_list_free(list);
+		return NULL;
+	}
+
+	max = len / sizeof(*kp);
+
+	for (i = 0; i < max; i++) {
+		RzDebugPid *pid_info;
```
Comment (wargio) [inline librz/debug/p/native/bsd/bsd_debug.c]: define this directly where it is used `RzDebugPid *pid_info = rz_debug_pid_new`

File: librz/debug/p/native/netbsd.c (hunk 6 above)
Comment (wargio) [reply librz/debug/p/native/netbsd.c]: use WARN.

**Review by wargio — APPROVED** [review]
LGTM

File: librz/debug/p/native/netbsd.c [hunk 13]
```diff
@@ -1,6 +1,7 @@
 // SPDX-FileCopyrightText: 2009-2019 pancake <pancake@nopcode.org>
 // SPDX-License-Identifier: LGPL-3.0-only
 
+#include "rz_util/rz_log.h"
```
Comment (Rot127) [inline librz/debug/p/native/netbsd.c]:
```suggestion
#include <rz_util/rz_log.h>
```

**Review by Rot127 — APPROVED** [review]
