### PR TITLE
Remove the automatically appended n_instr while setting commands in p…

### LINKED ISSUE #3829: Panel Empty
Hi,
I am experiencing some issues with rizin. 
I am on fedora 37, using this (self compiled) rizin version:
```
rizin 0.7.0 @ linux-x86-64
commit: a5780a3855c5673274856baa7b6bcf3be1777892
```
I was playing around with using command line tools instead of ghidra. When trying some toy examples (megabeets example, 32-bit ELF binary) I wanted to try a decompiler (rz-ghidra). When calling `pdg` from the normal cli, the current function gets decompiled successfully, however when using the visual panel mode, and changing the command of one panel to `pdg` this does not work. It also, however, does not work with commands such as `pdf` 

### Expected behavior
Panel should display output of the command

### Actual behavior
Panel is completely empty, like with commands which do not have any output

### Steps to reproduce the behavior
Open a binary, navigate to main function (`s main`), open visual panel mode (`v`), change mode of panel to `pdf` or `pdg`

### PR DESCRIPTION
**Pull request by PeiweiHu**
…anel mode

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The panel is empty because the command `pdf` does not support the <n_instr> parameter which is appended automatically. 

**Test plan**

...

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/3829

### CODE REVIEW

File: librz/core/tui/panels.c [hunk 1]
```diff
@@ -38,6 +38,11 @@
 #define PANEL_CMD_HEXDUMP       "xc"
 #define PANEL_CMD_CONSOLE       "$console"
 
+static const char *panel_command_opt[] = {
```
Comment (XVilka) [inline librz/core/tui/panels.c]: We usually store such lists in `librz/core/tui/modes.c`. Since there are plans to use the common code between various visual and panels mode in the future, it would make a better sense, IMHO: https://github.com/rizinorg/rizin/issues/384

**Review by XVilka — CHANGES_REQUESTED** [review]

File: librz/core/tui/panels.c (hunk 1 above)
Comment (PeiweiHu) [reply librz/core/tui/panels.c]: Ok, I will fix it.

**Review by XVilka — APPROVED** [review]
