### PR TITLE
librz/debug/p/native: fix xnu_get_pid implementation in xnu_debug

### LINKED ISSUE #3396: macOS 13.2 ARM64 debug list processes - endless "getcmdargs(): argument length mismatch" error messages
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 13.2 ARM64
| File format of the file you reverse (mandatory)      | =
| Architecture/bits of the file (mandatory)            | =
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/0e8828c54e0773e41bbbb5fff110c8cc07cadb09
### Expected behavior

No warnings

### Actual behavior

```
[0x00000000]> dpl
getcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatchgetcmdargs(): argument length mismatch - 661 ppid:0 uid:503 s /System/Library/PrivateFrameworks/SoftwareUpdate.framework/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager
 ```
### Steps to reproduce the behavior

```
rizin =
[0x0000000]> dpl
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [x] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

Previously there was a random -30. I've rewritten most of the code to:
- get the argmax size (through sysctl) instead of assuming 4096
- removed `psname` and instead just replace the \0 in the `procargs`, `rz_debug_pid_new` will already duplicate the string.
- fix the -30 check

**Test plan**

On MacOS `dpl` was returning a lot of errors before. This is now gone. 

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3396

### CODE REVIEW

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 1]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
-		return NULL;
+		RZ_LOG_WARN("sysctl(): unspecified sysctl error - %i\n", errno);
+		goto err;
+	}
+	// KERN_PROCARGS2 returns a flat byte buffer with this layout:
+	// |---------------|
+	// | argc          |
+	// |---------------|
+	// | exec_path     |
+	// |    \0 sep     |
```
Comment (notxvilka) [inline librz/debug/p/native/xnu/xnu_debug.c]: I don't understand this diagram, what this line means?

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 2]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
-			} else {
-				psname[psnamelen] = ' ';
-				memcpy(psname + psnamelen + 1, curr_arg, alen + 1);
-			}
-			psnamelen += alen;
-			// printf("arg[%i]: %s\n", iter_args, curr_arg);
-			/* Fetch next argument */
-			curr_arg = iter_args;
+		if (*iter_args == '\0') {
+			*iter_args = ' ';
```
Comment (ret2libc) [inline librz/debug/p/native/xnu/xnu_debug.c:1005]: Need to count as arg only if the previous char wasn't a null as well.

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 3]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
+	RzDebugPid *rpid = NULL;
+	int nargs, mib[3], uid;
+	const char *end_args;
+
 	uid = uidFromPid(pid);
 
-	/* Allocate space for the arguments. */
-	procargs = (char *)malloc(argmax);
+	// Allocate space for the arguments.
+	procargs = RZ_NEWS(char, argmax);
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c]:
```suggestion
	procargs = RZ_NEWS0(char, argmax);
```

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 4]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
-	/*
-	 * Make a sysctl() call to get the raw argument space of the process.
-	 */
+	// Make a sysctl() call to get the raw argument space of the process.
 	mib[0] = CTL_KERN;
 	mib[1] = KERN_PROCARGS2;
 	mib[2] = pid;
 
 	size = argmax;
 	procargs[0] = 0;
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c]: remove this as we initialize the whole buffer to 0

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 5]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
-			return NULL;
+	if (sysctl(mib, RZ_ARRAY_SIZE(mib), procargs, &size, NULL, 0) == -1) {
+		if (errno == EINVAL) {
+			// Some processes do not allow KERN_PROCARGS2, just skip them
+			goto err;
 		}
-		eprintf("sysctl(): unspecified sysctl error - %i\n", errno);
-		free(procargs);
-		return NULL;
+		RZ_LOG_WARN("sysctl(): unspecified sysctl error - %i\n", errno);
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c]:
```suggestion
		RZ_LOG_WARN("sysctl(): unspecified sysctl error - %d\n", errno);
```

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 6]
```diff
@@ -924,91 +936,88 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
+	// | exec_path     |
+	// |    \0 sep     |
+	// | argvs, \0 sep |
+	// |---------------|
+
+	if (size < sizeof(nargs)) {
+		goto err;
+	}
+	procargs[size] = 0;
+	memcpy(&nargs, procargs, sizeof(nargs));
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c:981]: use the functions from rz_endian

File: librz/debug/p/native/xnu/xnu_debug.c (hunk 3 above)
Comment (ret2libc) [reply librz/debug/p/native/xnu/xnu_debug.c]: why this? we don't need it (fully) initialised.

File: librz/debug/p/native/xnu/xnu_debug.c (hunk 6 above)
Comment (ret2libc) [reply librz/debug/p/native/xnu/xnu_debug.c:981]: Which function should I use? Also, I didn't because this is native debugger, so whatever the machine I'm running on should be good.

File: librz/debug/p/native/xnu/xnu_debug.c (hunk 3 above)
Comment (wargio) [reply librz/debug/p/native/xnu/xnu_debug.c]: it's not a memory intensive task, just memzero it.

File: librz/debug/p/native/xnu/xnu_debug.c (hunk 6 above)
Comment (wargio) [reply librz/debug/p/native/xnu/xnu_debug.c:981]: that is true, but this function also needs to work for ppc and x86. i'm not sure how is that value written in the memory by the OS. if is done by a memcpy, then it should be ok by memcpy it back, but if is not, then we should read by the correct endianness. also `int` size depends by the platform, so it is difficult to say which one to use. a good guess is 32 bit.

Comment (ret2libc) [reply librz/debug/p/native/xnu/xnu_debug.c:981]: I'm not sure which function I should use, I think memcpy is fine in these cases because you want the host behaviour.

`rz_read_le32` does:
```c
#if RZ_HOST_IS_LITTLE_ENDIAN
	ut32 val = 0;
	memcpy(&val, src, sizeof(val));
	return val;
#else
```
and `rz_read_be32` does:
```c
#if RZ_HOST_IS_BIG_ENDIAN
	ut32 val = 0;
	memcpy(&val, src, sizeof(val));
	return val;
#else
```

I can probably improve the code to use int32_t instead of relying on `int`, but I'm not sure about having `nargs = (int)rz_read_ble32(procargs, RZ_SYS_ENDIAN == RZ_SYS_ENDIAN_BIG);` which would just translate to a memcpy no matter what.

WDYT?

Comment (wargio) [reply librz/debug/p/native/xnu/xnu_debug.c:981]: that is true. ok. just define int as st32

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 7]
```diff
@@ -841,6 +841,18 @@ static uid_t uidFromPid(pid_t pid) {
 	return uid;
 }
 
+static size_t xnu_get_argmax_cached(void) {
+	static size_t argmax = 0;
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c:846]: Add a comment that this variable should be moved into a context once possible.

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 8]
```diff
@@ -841,6 +841,18 @@ static uid_t uidFromPid(pid_t pid) {
...
+	if (argmax == 0) {
+		size_t argmax_size = sizeof(argmax);
+		int mib[2] = { CTL_KERN, KERN_ARGMAX };
+		if (sysctl(mib, RZ_ARRAY_SIZE(mib), &argmax, &argmax_size, NULL, 0) == -1 || argmax == 0) {
+			argmax = 4096;
+		}
+	}
+	return argmax;
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c]: invert the if and early return.

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 9]
```diff
@@ -924,91 +936,82 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
...
 	uid = uidFromPid(pid);
 
-	/* Allocate space for the arguments. */
-	procargs = (char *)malloc(argmax);
+	// Allocate space for the arguments.
+	procargs = RZ_NEWS0(char, argmax);
 	if (!procargs) {
-		eprintf("getcmdargs(): insufficient memory for procargs %d\n",
+		RZ_LOG_WARN("getcmdargs(): insufficient memory for procargs %d\n",
 			(int)(size_t)argmax);
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c]:
```suggestion
		RZ_LOG_WARN("getcmdargs(): insufficient memory for procargs %" PFMTSZu "n", argmax);
```

File: librz/debug/p/native/xnu/xnu_debug.c (hunk 7 above)
Comment (wargio) [reply librz/debug/p/native/xnu/xnu_debug.c:846]: also how do i reset this if i detach from a debug session and re-attach to a different one?

Comment (ret2libc) [reply librz/debug/p/native/xnu/xnu_debug.c:846]: Even if you reattach to a different process, the argmax is set by the host OS and it won't change. It's independent of the process being debugged.

Comment (wargio) [reply librz/debug/p/native/xnu/xnu_debug.c:846]: ok, maybe add a comment regarding this.

**Review by wargio — APPROVED** [review]
LGTM

**Comment by wargio** [comment]
```
[XX] 00h00m00s260ms db/archos/darwin-arm64/dbg dpa issue
RZ_COLOR=0 RZ_UTF8=0 RZ_NOPLUGINS=1 /private/var/folders/w7/mbsys_rs56s030vd1q140jpr0000_p/T/woodpecker-local-2085845032/workspace/prefix/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc '!sh -c "./bins/mach0/sleep-macos-arm64 100 >/dev/null 2>&1 &"
dpa $(!pgrep sleep-macos-arm64)
pi 3 @ pc
!pkill sleep-macos-arm64
' =
-- stdout
--- expected
+++ actual
@@ -1,3 +1,0 @@
-b.lo
-pacibsp
-stp fp, lr, [sp, -0x10]!

-- stderr
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_drx/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_drx/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_drx/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_drx/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
ERROR: rz_xnu_thread_get_gpr/thread_get_state: (os/kern) invalid argument
```

**Comment by ret2libc** [comment]
Probably some transient error..!?

**Review by notxvilka — APPROVED** [review]
