### PR TITLE
add and fix arm32 relocations

### LINKED ISSUE #5131: ARM: Missing relocation types - common
To see the warning, open the file `libr/bin/p/bin_elf.inc` and remove `ADD(32, GOT, "ARM REG RELOC"); break;` and add these lines instead:
```c
default:
     RZ_LOG_WARN("unimplemented ELF/ARM reloc type %d\n", rel->type);
     break;
```

- 19 - [librpc.so_rel_19.zip](https://github.com/user-attachments/files/20038325/librpc.so_rel_19.zip)
- 43, 44: [wifi_3_0.ko_rel_43_44.zip](https://github.com/user-attachments/files/20038324/wifi_3_0.ko_rel_43_44.zip)

See `librz/bin/p/bin_elf.inc`

### PR DESCRIPTION
**Pull request by well-mannered-goat**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Added handling for some arm relocations
According to this: https://github.com/ARM-software/abi-aa/blob/main/aaelf32/aaelf32.rst#relocation-codes-table
Since some relocations need GOT table entry for that symbol for calculations and I found out that relocation patching is missing for majority relocations so I would be adding that too.

**Test plan**

...

**Closing issues**

closes #5131

### CODE REVIEW

**Comment by well-mannered-goat** [comment]
ignore the comments for now
Some relocation patching is still left especially the ones which have group masking, still trying to understand how those work.

**Review by wargio — CHANGES_REQUESTED** [review]
add tests please.

File: librz/bin/format/elf/elf_relocs_patching.c [hunk 1]
```diff
@@ -865,6 +922,461 @@ static void patch_reloc_arm(RZ_INOUT RzBuffer *buf_patched, const ut64 patch_add
 				((val >> 1) & 0x07ff), // imm11
 			big_endian);
 		break;
+	// Arm and Data instructions
+	//  case R_ARM_PC24: //Deprecated
+	//  case R_ARM_PLT32: //Deprecated
```
Comment (Rot127) [inline librz/bin/format/elf/elf_relocs_patching.c]: Even if deprecated please implement them if not too much work and you have time. People might throw ancient binaries on Rizin.

File: librz/bin/format/elf/elf_relocs_patching.c [hunk 2]
```diff
@@ -865,6 +922,461 @@ static void patch_reloc_arm(RZ_INOUT RzBuffer *buf_patched, const ut64 patch_add
...
+			(((val >> 12) & 0xF) << 16) | // imm4
+			(val & 0xFFF); // imm12
+		rz_write_ble32(buf, keep, big_endian);
+		break;
+	case R_ARM_MOVT_BREL:
+		val = (fs->S + fs->A) >> 16;
+		keep = rz_read_ble32(buf, big_endian);
+		keep = (keep & 0xFFF0F000) |
+			(((val >> 12) & 0xF) << 16) | // imm4
+			(val & 0xFFF); // imm12
```
Comment (Rot127) [inline librz/bin/format/elf/elf_relocs_patching.c]: You can use `patch_val_over_mask_32` from above, if I am not mistaken.

Comment (Rot127) [reply librz/bin/format/elf/elf_relocs_patching.c]: Also for the other places.

File: librz/bin/format/elf/glibc_elf.h [hunk 3]
```diff
@@ -3029,132 +3029,138 @@ enum {
...
-#define R_ARM_THM_GOT_BREL12    131 /* GOT entry relative to GOT origin, 12 bit (Thumb32 LDR).  */
-#define R_ARM_IRELATIVE         160
-#define R_ARM_RXPC25            249
-#define R_ARM_RSBREL32          250
-#define R_ARM_THM_RPC22         251
-#define R_ARM_RREL32            252
-#define R_ARM_RABS22            253
-#define R_ARM_RPC24             254
-#define R_ARM_RBASE             255
+#define R_ARM_NONE               0 /* No reloc */
```
Comment (Rot127) [inline librz/bin/format/elf/glibc_elf.h:3032]: For reference it would be nice if you could link the source of the information.

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: librz/bin/format/elf/elf_relocs_patching.c (hunk 2 above)
Comment (notxvilka) [reply librz/bin/format/elf/elf_relocs_patching.c]: @well-mannered-goat don't forget about this one

**Review by notxvilka — CHANGES_REQUESTED** [review]
LGTM once the feedback is addressed. Good job!

File: librz/bin/format/elf/elf_relocs_patching.c (hunk 2 above)
Comment (well-mannered-goat) [reply librz/bin/format/elf/elf_relocs_patching.c]: Hey, I looked into it. Actually I cannot apply these for thumb relocations since two halfwords need to separately be handled. Also at the end of switch block the `buf` is written. Using this I would need to apply separate writing mechanism for arm and thumb relocations. Also these are mainly linker based relocations so most of the time rizin patching is not required, I didn't realise it earler :sweat_smile: . So imo I dont think it is necessary but I can refactor if you think about it. @notxvilka

Comment (notxvilka) [reply librz/bin/format/elf/elf_relocs_patching.c]: Then remove it and open a new issue about handling such cases. It's better to do it in another PR, imho (it would require some refactoring beyond just this file, I think).

File: librz/bin/format/elf/elf_relocs_conversion.c [hunk 4]
```diff
@@ -139,6 +139,19 @@ static RzBinReloc *reloc_convert_ifunc(ELFOBJ *bin, RzBinElfReloc *rel, RzBinRel
...
 }
 
+// Custom function for arm specific relocations
+static RzBinReloc *reloc_convert_add_t(ELFOBJ *bin, RzBinElfReloc *rel, RzBinRelocType type, bool T, const char *print_name) {
+	RzBinReloc *r = reloc_convert_new(bin, rel);
+	if (!r) {
+		return NULL;
+	}
+
+	r->addend = (r->addend | T);
```
Comment (Rot127) [inline librz/bin/format/elf/elf_relocs_conversion.c]: Is `bool` guaranteed to be `0b1` or `0b0` in `stdbool`?

File: librz/bin/format/elf/elf_relocs_patching.c [hunk 5]
```diff
@@ -865,6 +922,462 @@ static void patch_reloc_arm(RZ_INOUT RzBuffer *buf_patched, const ut64 patch_add
...
+		keephw1 = (keephw1 & 0xFBF0) |
+			((val & 0xF000) >> 12) | // imm4
+			((val & 0x0800) >> 1); // i
+		keephw2 = (keephw2 & 0x8F00) |
+			((val & 0x0700) << 4) | // imm3
+			((val & 0x00FF)); // imm8
+		rz_write_ble16(&buf[0], keephw1, big_endian);
+		rz_write_ble16(&buf[2], keephw2, big_endian);
+		break;
+	case R_ARM_THM_JUMP19: ///
```
Comment (Rot127) [inline librz/bin/format/elf/elf_relocs_patching.c]:
```suggestion
	case R_ARM_THM_JUMP19:
```

File: librz/bin/format/elf/elf_relocs_conversion.c [hunk 6]
```diff
@@ -274,36 +295,44 @@ static RzBinReloc *reloc_convert_amd64(ELFOBJ *bin, RzBinElfReloc *rel, ut64 GOT
 static RzBinReloc *reloc_convert_arm(ELFOBJ *bin, RzBinElfReloc *rel, ut64 GOT) {
 	ut64 B = bin->baddr;
 	ut64 P = rel->vaddr;
+	ut64 Pa = P & 0xfffffffc;
+	bool T = 0;
+	RzBinElfSymbol *symbol = Elf_(rz_bin_elf_get_symbol)(bin, rel->sym);
+	if (symbol && strcmp(symbol->type, RZ_BIN_TYPE_FUNC_STR) == 0) {
```
Comment (Rot127) [inline librz/bin/format/elf/elf_relocs_conversion.c]:
```suggestion
	if (symbol && RZ_STR_EQ(symbol->type, RZ_BIN_TYPE_FUNC_STR)) {
```

**Review by Rot127 — CHANGES_REQUESTED** [review]

**Comment by well-mannered-goat** [comment]
Tried adding same patching helper function for 16 bits thumb relocations as well but it would not really work because the bit spread is a bit complex and need to fetch out bits for 2 halfwords from the same value.

**Review by wargio — APPROVED** [review]
LGTM, i just see many changes and fewer tests, but is ok for me.

File: test/db/formats/elf/elf-relarm [hunk 7]
```diff
@@ -229,3 +229,108 @@ ldr x0, [x0, 0x8c8]
...
+            ;-- foo:
+            0x08000040      blx   foo                                  ; RELOC 24 foo @ 0x08000034
+EOF
+RUN
+
+NAME=arm alu group relocations
+FILE=bins/elf/arm-reloc-alu-group.o
+CMDS=<<EOF
+ir
+s 0x08000038
```
Comment (notxvilka) [inline test/db/formats/elf/elf-relarm]: You could just use `pd 2 @ 0x8000038` instead

File: test/db/formats/elf/elf-relarm [hunk 8]
```diff
@@ -229,3 +229,108 @@ ldr x0, [x0, 0x8c8]
...
+            0x08000038      .dword 0x00000090                          ; RELOC 32 foo ; [02] -rw- section size 4 named .data
+EOF
+RUN
+
+NAME=arm call/jump relocations
+FILE=bins/elf/arm-reloc-call.o
+CMDS=<<EOF
+ir
+s 0x08000038
+pd 1
```
Comment (notxvilka) [inline test/db/formats/elf/elf-relarm]: Same here, use `@` modifier

File: test/db/formats/elf/elf-relarm [hunk 9]
```diff
@@ -229,3 +229,108 @@ ldr x0, [x0, 0x8c8]
 bl reloc.target.fputs
 EOF
 RUN
+
+NAME=arm R_ARM_PREL31 relocation
+FILE=bins/elf/arm-reloc-prel31.o
+CMDS=<<EOF
+ir~R_ARM_PREL31?
+s 0x08000038
```
Comment (notxvilka) [inline test/db/formats/elf/elf-relarm]: And here

**Review by notxvilka — APPROVED** [review]
LGTM with a small nitpick

**Review by notxvilka — APPROVED** [review]
