### PR TITLE
Fixed a buffer overflow in gdbr_parse_processes_xml

### LINKED ISSUE #5882: Segmentation fault when listing remote processes
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x84_64
| File format of the file you reverse (mandatory)      | ELF, PIE
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.9.0 @ linux-x86-64 commit: 0a8fe351630a17211e6cc359d532a4c9cf745cf1

### Expected behavior
After connecting to a remote GDB server, running `dp` should either show a running processes or an error if unable.

### Actual behavior
rizin just crashes due to a segmentation fault:
```
[0x00000000]> dp
Segmentation fault (core dumped)
```

### Steps to reproduce the behavior
- Run a GDB server using `gdbserver --multi :4444`
- Connect rizin to the GDB server: `rizin -d gdb://localhost:4444`
- Run `dp`

### Additional Logs, screenshots, source code,  configuration dump, ...

Please let me know if additional information is required. I can try to get a backtrace from the core dump.

### PR DESCRIPTION
**Pull request by suleif0**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [X] I've documented every `RZ_API` function and struct this PR changes.
- [X] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

This fixes #5882, The issue was that the cmdline buffer size was too small for some of the data that gdbserver sends with the `--multi` flag. The fix was to simply increase the buffer size of cmdline.

**Test plan**

- Start a gdb server: `gdbserver --multi :4444`
- Connect rizin to the GDB server: `rizin -d gdb://localhost:4444`
- list the processes: `dp`

Additionally I made a test for this in test/db/archos/linux-x64/dbg_gdbserver

**Closing issues**

closes #5882

### CODE REVIEW

File: test/db/archos/linux-x64/dbg_gdbserver [hunk 1]
```diff
@@ -13,3 +13,16 @@ EXPECT=<<EOF
...
+NAME=gdbserver dp
+FILE=bins/elf/analysis/pie
+CMDS=<<EOF
+!scripts/gdbserver.py --port 12346 --multi --binary bins/elf/analysis/pie
+oodf gdb://127.0.0.1:12346
+dp 
+EOF
+REGEXP_FILTER_OUT=(^([^\r\n]*))
+EXPECT=<<EOF
+ - 1 ppid:0 uid:0 S /usr/lib/systemd/systemd
```
Comment (notxvilka) [inline test/db/archos/linux-x64/dbg_gdbserver]: It might be different between systems:
```
[XX] 00h00m00s340ms db/archos/linux-x64/dbg_gdbserver gdbserver dp
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc '!scripts/gdbserver.py --port 12346 --multi --binary bins/elf/analysis/pie
oodf gdb://127.0.0.1:12346
dp 
' bins/elf/analysis/pie
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
- - 1 ppid:0 uid:0 S /usr/lib/systemd/systemd
+ - 1 ppid:0 uid:0 S /sbin/init

-- stderr
Traceback (most recent call last):
  File "/home/runner/work/rizin/rizin/test/scripts/gdbserver.py", line 71, in <module>
    main()
  File "/home/runner/work/rizin/rizin/test/scripts/gdbserver.py", line 58, in main
    for output in execute(cmd):
  File "/home/runner/work/rizin/rizin/test/scripts/gdbserver.py", line 22, in execute
    with subprocess.Popen(
         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gdbserver'
Could not resolve address '127.0.0.1' or failed to connect
gdb.io.open: Cannot connect to host.
ERROR: Cannot open file 'gdb://127.0.0.1:12346'
```

**Review by notxvilka — CHANGES_REQUESTED** [review]

File: test/db/archos/linux-x64/dbg_gdbserver (hunk 1 above)
Comment (suleif0) [reply test/db/archos/linux-x64/dbg_gdbserver]: Okay, I'll try matching against `- 1 ppid:0 uid:0`.

**Comment by suleif0** [comment]
@notxvilka  Can you take a look again?

**Review by wargio — APPROVED** [review]

File: subprojects/rzgdb/src/gdbclient/xml.c [hunk 2]
```diff
@@ -408,7 +408,6 @@ static int gdbr_parse_processes_xml(libgdbr_t *g, char *xml_data, ut64 len, int
 
 		column += sizeof("<column name=\"command\">") - 1;
 		column_data_len = column_end - column;
-
 		memcpy(cmdline, column, column_data_len);
```
Comment (wargio) [inline subprojects/rzgdb/src/gdbclient/xml.c]:
```suggestion
		memcpy(cmdline, column, RZ_MIN(column_data_len, sizeof(cmdline)));
```

**Review by notxvilka — APPROVED** [review]
