### PR TITLE
Fix NULL dereference in rz_io_resize()

### LINKED ISSUE #4476: [Segfault] rizin > visual panels mode > insert mode > typing r
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint 21.1 x64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.8.0 @ linux-x86-64 commit: 73d85d270a81c8c42c1b8e601d167ce2ad93157f

### Expected behavior
Working `V` mode

### Actual behavior
Segfault

### Steps to reproduce the behavior
- Run `rizin -c 'Virus'`
- Type <kbd>r</kbd> to reproduce

### Additional Info
The segfault happens **reproducibly**.

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes #4476

### CODE REVIEW

File: librz/io/io.c [hunk 1]
```diff
@@ -422,27 +422,26 @@ RZ_API char *rz_io_system(RzIO *io, const char *cmd) {
...
-			rz_list_free(maps);
-			return false;
-		}
-		rz_list_foreach (maps, iter, current_map) {
-			// we just resize map of the same size of its fd
-			if (current_map->itv.size == fd_size) {
-				rz_io_map_resize(io, current_map->id, newsize);
-			}
-		}
+RZ_API bool rz_io_resize(RZ_NONNULL RzIO *io, ut64 newsize) {
```
Comment (XVilka) [inline librz/io/io.c:425]: Note that in that case all callers should check for NULL before this function called. Since those asserts are omitted from the release builds. If the bug did happen in the first place, that means there's a call passing NULL somewhere. Apart from that LGTM.

**Review by XVilka — APPROVED** [review]

File: librz/io/io.c (hunk 1 above)
Comment (p371jah) [reply librz/io/io.c:425]: In release build we have `checks_level = 1`:
https://github.com/rizinorg/rizin/blob/4594027f8b5ad7828941e59dce9fb023220bbabe/meson.build#L315-L319

In that case `rz_return_val_if_fail(expr, val)` works as a simple `if (!expr) return val;` 
https://github.com/rizinorg/rizin/blob/4594027f8b5ad7828941e59dce9fb023220bbabe/librz/include/rz_util/rz_assert.h#L108-L114

Comment (XVilka) [reply librz/io/io.c:425]: Nice, didn't realize that. LGTM then.

Comment (p371jah) [reply librz/io/io.c:425]: And the bug is caused by accessing to `io->desc` which is `NULL` since `rizin` is launched with no input file

File: librz/io/io.c [hunk 2]
```diff
@@ -422,27 +422,26 @@ RZ_API char *rz_io_system(RzIO *io, const char *cmd) {
...
+	rz_return_val_if_fail(io && io->desc, false);
+
+	RzList *maps = rz_io_map_get_for_fd(io, io->desc->fd);
+	RzIOMap *current_map;
+	RzListIter *iter;
+	ut64 fd_size = rz_io_fd_size(io, io->desc->fd);
+	bool ret = rz_io_desc_resize(io->desc, newsize);
+	if (!ret) {
```
Comment (wargio) [inline librz/io/io.c]: maybe merge these two lines since ret is never used.

**Review by wargio — APPROVED** [review]
LGTM, just a small comment but not really mandatory
