### PR TITLE
Fix NPD in rz_core_analysis_esil_emulate_bb()

### LINKED ISSUE #1365: `aeb` without `aaa` triggers a segmentfault
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 5.10.35 x86-64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | ELF 64-bit
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.1 @ linux-x86-64 release

### Expected behavior
skip or report an error

### Actual behavior
segmentfault and exit

### Steps to reproduce the behavior
1. rizin /usr/bin/ls
2. `aei`, `aeim`, `aeip`
3. `aeb` to trigger this bug

### Additional Logs, screenshots, source code,  configuration dump,
1. run `aeb` after `aa`/`aaa`/`aaaa` will prevent this segment fault
2. backtrace
```sh
─────────────────────────────────────────[ STACK ]──────────────────────────────────────────
00:0000│ rsp  0x7fffffffd1f0 —▸ 0x55555564d352 ◂— 0x41000000002929 /* '))' */
01:0008│      0x7fffffffd1f8 ◂— 0x5b20 /* ' [' */
02:0010│      0x7fffffffd200 ◂— 0x100
03:0018│      0x7fffffffd208 ◂— 0x1
04:0020│      0x7fffffffd210 —▸ 0x555555808f63 ◂— 0x0
05:0028│      0x7fffffffd218 ◂— 0x68f4eba1857c3700
06:0030│      0x7fffffffd220 —▸ 0x555555808f60 ◂— 0x626561 /* 'aeb' */
07:0038│      0x7fffffffd228 ◂— 0x2
───────────────────────────────────────[ BACKTRACE ]────────────────────────────────────────
 ► f 0     7ffff6d66ad0
   f 1     7ffff6d6f977
   f 2     7ffff6db2ee5 rz_cmd_call_parsed_args+629
   f 3     7ffff6da9a0e
   f 4     7ffff6da15aa
   f 5     7ffff6da9171
   f 6     7ffff6da959c
   f 7     7ffff6da9f06 rz_core_cmd+326
   f 8     7ffff6dc484c rz_core_prompt_exec+28
   f 9     7ffff6dc4fa9 rz_core_prompt_loop+25
   f 10     7ffff7e83bec rz_main_rizin+4316

```

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes #1365

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
do you have a test for this? like a bin that does crash rizin?

**Comment by Heersin** [comment]
Well, when I search the "aeb" in rizin there is no comments or help message about it. Should we remove it ? Or add a test for this  command ?

**Comment by XVilka** [comment]
I think it might be useful since we have also `aes` to emulate instruction and `aef` to emulate function. Please add a test, maybe also a help message.

File: librz/core/cil.c [hunk 1]
```diff
@@ -367,7 +367,9 @@ RZ_IPI void rz_core_analysis_esil_emulate(RzCore *core, ut64 addr, ut64 until_ad
 
 RZ_IPI void rz_core_analysis_esil_emulate_bb(RzCore *core) {
 	RzAnalysisBlock *bb = rz_analysis_find_most_relevant_block_in(core->analysis, core->offset);
-	rz_core_analysis_esil_emulate(core, bb->addr, UT64_MAX, bb->ninstr);
+	if (bb) {
+		rz_core_analysis_esil_emulate(core, bb->addr, UT64_MAX, bb->ninstr);
+	}
```
Comment (ret2libc) [inline librz/core/cil.c]: I would do the opposite and check `if (!bb) { ... print something + return error ... }` otherwise if i try to emulate a basicblock and see no output, as a user, i have no idea if things went well or not and why.

File: librz/core/cil.c [hunk 2]
```diff
@@ -367,6 +367,10 @@ RZ_IPI void rz_core_analysis_esil_emulate(RzCore *core, ut64 addr, ut64 until_ad
 
 RZ_IPI void rz_core_analysis_esil_emulate_bb(RzCore *core) {
 	RzAnalysisBlock *bb = rz_analysis_find_most_relevant_block_in(core->analysis, core->offset);
+	if (!bb) {
+		eprintf("Cannot find basic block for 0x%08" PFMT64x "\n", core->offset);
```
Comment (wargio) [inline librz/core/cil.c]: use RZ_LOG
```suggestion
		RZ_LOG_ERROR("Cannot find basic block for 0x%08" PFMT64x "\n", core->offset);
```

**Review by wargio — CHANGES_REQUESTED** [review]

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
