### PR TITLE
Fix `rz-find` ignoring `RZ_LOGLEVEL`.

### LINKED ISSUE #5211: `rz-find <dir>` ignores `RZ_LOGLEVEL=5` environment variable
Just try:
```
RZ_LOGLEVEL=5 rz-find -s bla rizin-testbins/elf/
```
It will still continue print endless WARNINGs of the missing relocations, et cetera.

### PR DESCRIPTION
**Pull request by answarck**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

This commit fixes `rz-find` ignoring `RZ_LOGLEVEL` environment variable, So it restores proper log supression.

**Test plan**

This can be tested by setting `RZ_LOGLEVEL` environment variable to value ranging from 1-5, and the output will be according to the log level.

**Closing issues**

closes #5211

### CODE REVIEW

File: librz/main/rz-find.c [hunk 1]
```diff
@@ -515,6 +515,15 @@ RZ_API int rz_main_rz_find(int argc, const char **argv) {
 	int c;
 	const char *file = NULL;
 
+	char *log_level = rz_sys_getenv("RZ_LOGLEVEL");
+	if (log_level) {
```
Comment (wargio) [inline librz/main/rz-find.c]: Use `RZ_STR_ISNOTEMPTY`

File: librz/main/rz-find.c [hunk 2]
```diff
@@ -515,6 +515,15 @@ RZ_API int rz_main_rz_find(int argc, const char **argv) {
...
+		int n = atoi(log_level);
+		if (n >= 0 && n <= 5) {
+			rz_log_set_level((RzLogLevel)n);
+		}
+		free(log_level);
```
Comment (wargio) [inline librz/main/rz-find.c:524]: move this out of the if when you change the if clause to use `RZ_STR_ISNOTEMPTY`

File: librz/main/rz-find.c [hunk 3]
```diff
@@ -515,6 +517,16 @@ RZ_API int rz_main_rz_find(int argc, const char **argv) {
 	int c;
 	const char *file = NULL;
 
+	int n = RZ_LOGLVL_ERROR;
```
Comment (wargio) [inline librz/main/rz-find.c]:
```suggestion
	int n = RZ_DEFAULT_LOGLVL;
```

**Review by wargio — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]

File: librz/main/rz-find.c [hunk 4]
```diff
@@ -515,6 +517,16 @@ RZ_API int rz_main_rz_find(int argc, const char **argv) {
 	int c;
 	const char *file = NULL;
 
+	int n = RZ_DEFAULT_LOGLVL;
+	char *log_level = rz_sys_getenv("RZ_LOGLEVEL");
+	if (RZ_STR_ISNOTEMPTY(log_level)) {
+		n = atoi(log_level);
+		free(log_level);
+	}
+	if (n >= 0 && n <= 5) {
```
Comment (Rot127) [inline librz/main/rz-find.c]:
```suggestion
	if (n >= 0 && n < RZ_LOGLVL_SIZE) {
```

**Review by Rot127 — CHANGES_REQUESTED** [review]

**Review by Rot127 — APPROVED** [review]

**Comment by answarck** [comment]
Is this codecov test failing due to no test case?

**Comment by wargio** [comment]
it's fine.

**Comment by answarck** [comment]
So what to do now?

**Comment by notxvilka** [comment]
@answarck do you want to try tackling this issue? https://github.com/rizinorg/rizin/issues/5189 Since you already worked on `rz-find`.

**Comment by answarck** [comment]
> @answarck do you want to try tackling this issue? https://github.com/rizinorg/rizin/issues/5189 Since you already worked on `rz-find`.

Absolutely, I would like to.
