### PR TITLE
Macos coredump

### LINKED ISSUE #3054: Core file generation doesn't work on macOS 12.6 ARM64
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 12.6 ARM64 (M1)
| File format of the file you reverse (mandatory)      | MachO
| Architecture/bits of the file (mandatory)            | ARMv8 64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 @ darwin-arm-64
commit: 7c0bd7cd036d6500bb2ef29adf3d50f0529786a8

### Expected behavior

```
rizin -d $(which rz-ax)
[0x1045d4560]> dg
WARNING: core: Writing to file 'core.93555'
[0x1045d4560]>
```
Core file should be written and be loadable in Rizin afterwards

### Actual behavior
```
rizin -d $(which rz-ax)
[0x1045d4560]> dg
WARNING: core: Writing to file 'core.93555'
^C
```
Even <Ctrl-C> doesn't work, only `kill -9 <rizin pid>`

Generate core file successfully, which can be loaded 

It's implemented in "native" debugger plugin, see these places:
- `librz/debug/p/debug_native.c` in `rz_debug_gcore()` function
- `librz/debug/p/native/xnu/xnu_debug.c` in `xnu_generate_corefile()` function

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [x] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

- some `size_t` converted to `int` and viceversa
- missed handling of arm64
- number of segment counts was wrong 

**Test plan**

Expected output:
```
$ ./build-xnu/binrz/rizin/rizin -d $(which rz-ax)
[0x102e6c9c0]> dg
WARNING: core: Writing to file 'core.98610'
Writing section from 0x102d20000 to 0x102d24000 (16384)
Writing section from 0x102d24000 to 0x102d28000 (16384)
Writing section from 0x102d28000 to 0x102d2c000 (16384)
Writing section from 0x102e68000 to 0x102f10000 (688128)
Writing section from 0x102f10000 to 0x102f14000 (16384)
Writing section from 0x102f14000 to 0x102f1c000 (32768)
Writing section from 0x102f1c000 to 0x102f20000 (16384)
Writing section from 0x102f20000 to 0x102f24000 (16384)
Writing section from 0x102f24000 to 0x102f48000 (147456)
Writing section from 0x102f48000 to 0x102fa8000 (393216)
Writing section from 0x1690e0000 to 0x16c8e4000 (58736640)
Writing section from 0x16c8e4000 to 0x16d0e0000 (8372224)
Writing section from 0x180000000 to 0x300000000 (6442450944)
Writing section from 0xfc0000000 to 0x1000000000 (1073741824)
Writing section from 0x1000000000 to 0x7000000000 (412316860416)
[DEBUG] tc location: 0x458
[DEBUG] 1/1
[0x102e6c9c0]>
```

```
$ ./build-xnu/binrz/rizin/rizin core.98610
[0x102d20000]> oml
 1 fd: 3 +0x00000000 0x102d20000 * 0x102d23fff r-x fmap.
 2 fd: 3 +0x00000000 0x102d24000 - 0x102d27fff r-- fmap.
 3 fd: 3 +0x00000000 0x102d28000 - 0x102d2bfff r-- fmap.
 4 fd: 3 +0x00000000 0x102e68000 - 0x102f0ffff r-x fmap.
 5 fd: 3 +0x00000000 0x102f10000 - 0x102f13fff r-- fmap.
 6 fd: 3 +0x00000000 0x102f14000 - 0x102f1bfff r-- fmap.
 7 fd: 3 +0x00000000 0x102f1c000 - 0x102f1ffff r-- fmap.
 8 fd: 3 +0x00000000 0x102f20000 - 0x102f23fff r-- fmap.
 9 fd: 3 +0x00000000 0x102f24000 - 0x102f47fff r-- fmap.
10 fd: 3 +0x00000000 0x102f48000 - 0x102fa7fff r-- fmap.
11 fd: 3 +0x00000000 0x16c8e4000 - 0x16d0dffff r-- fmap.
```

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3054

### CODE REVIEW

File: librz/debug/p/native/xnu/xnu_debug.c [hunk 1]
```diff
@@ -869,7 +868,7 @@ bool xnu_generate_corefile(RzDebug *dbg, RzBuffer *dest) {
 	size_t mach_header_sz;
 	size_t segment_command_sz;
 	size_t padding_sz;
-	int hoffset;
+	size_t hoffset;
```
Comment (wargio) [inline librz/debug/p/native/xnu/xnu_debug.c:871]: is there an actual reason to use `int` ?

**Review by wargio — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]
