### PR TITLE
Legacy Mac OS X Compatibility (Fix #4352)

### LINKED ISSUE #4352: Build failures on several macOS versions: `analysis_xtensa.c: error: too many arguments provided to function-like macro invocation`
`rizin` build fails on a few older macOS versions at the moment. There are two issues:

1. On macOS 10.12 and below this fails, at least with Clang (cannot test with GCC right now):
```
FAILED: librz/analysis/librz_analysis.0.7.dylib.p/p_analysis_xtensa.c.o 
/usr/bin/clang -Ilibrz/analysis/librz_analysis.0.7.dylib.p -I. -I../rizin-v0.7.2 -Ilibrz -I../rizin-v0.7.2/librz -Ilibrz/include -I../rizin-v0.7.2/librz/include -I../rizin-v0.7.2/librz/analysis/arch/gb -Ilibrz/util/sdb/src -I../rizin-v0.7.2/librz/util/sdb/src -I../rizin-v0.7.2/librz/asm/arch/include -I../rizin-v0.7.2/librz/asm/arch -I../rizin-v0.7.2/librz/asm/arch/h8300 -I../rizin-v0.7.2/librz/asm/arch/hexagon -I../rizin-v0.7.2/librz/asm/arch/msp430 -I../rizin-v0.7.2/librz/asm/arch/rsp -I../rizin-v0.7.2/librz/asm/arch/mcore -I../rizin-v0.7.2/librz/asm/arch/v850 -I../rizin-v0.7.2/librz/asm/arch/propeller -I../rizin-v0.7.2/librz/asm/arch/ebc -I../rizin-v0.7.2/librz/asm/arch/cr16 -I../rizin-v0.7.2/librz/asm/arch/8051 -I../rizin-v0.7.2/librz/asm/arch/v810 -I../rizin-v0.7.2/librz/asm/arch/or1k -I../rizin-v0.7.2/librz/asm/arch/tricore -I../rizin-v0.7.2/librz/bin/format -I../rizin-v0.7.2/librz/type/parser -I/opt/local/include/capstone -I/opt/local/libexec/openssl3/include -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -g -DRZ_PLUGIN_INCORE=1 -DUSE_SYS_CAPSTONE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -pipe -Os -arch x86_64 -MD -MQ librz/analysis/librz_analysis.0.7.dylib.p/p_analysis_xtensa.c.o -MF librz/analysis/librz_analysis.0.7.dylib.p/p_analysis_xtensa.c.o.d -o librz/analysis/librz_analysis.0.7.dylib.p/p_analysis_xtensa.c.o -c ../rizin-v0.7.2/librz/analysis/p/analysis_xtensa.c
../rizin-v0.7.2/librz/analysis/p/analysis_xtensa.c:24:45: error: too many arguments provided to function-like macro invocation
        memcpy(ctx->length_table, (int[16]){ 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 8, 8 }, sizeof(ctx->length_table));
                                                   ^
/usr/include/secure/_string.h:64:9: note: macro 'memcpy' defined here
#define memcpy(dest, src, len)                                  \
        ^
../rizin-v0.7.2/librz/analysis/p/analysis_xtensa.c:24:2: note: parentheses are required around macro argument containing braced initializer list
        memcpy(ctx->length_table, (int[16]){ 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 8, 8 }, sizeof(ctx->length_table));
        ^
                                  (                                                          )
1 error generated.
```
Log: https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/263721/steps/install-port/logs/stdio

2. On 10.6 and below this fails (this is an SDK-related issue, not compiler-related):
```
FAILED: librz/io/librz_io.0.7.dylib.p/p_io_debug.c.o 
/opt/local/bin/clang-mp-11 -Ilibrz/io/librz_io.0.7.dylib.p -I. -I../rizin-v0.7.2 -Ilibrz -I../rizin-v0.7.2/librz -Ilibrz/include -I../rizin-v0.7.2/librz/include -I../rizin-v0.7.2/subprojects/rzgdb/include -I../rizin-v0.7.2/subprojects/rzgdb/include/gdbclient -I../rizin-v0.7.2/subprojects/rzgdb/include/gdbserver -Isubprojects/rzwinkd -I../rizin-v0.7.2/subprojects/rzwinkd -Isubprojects/rzar -I../rizin-v0.7.2/subprojects/rzar -Ilibrz/util/sdb/src -I../rizin-v0.7.2/librz/util/sdb/src -I../rizin-v0.7.2/subprojects/rzqnx/include -I/opt/local/libexec/openssl3/include -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -g -DRZ_PLUGIN_INCORE=1 -DUSE_SYS_CAPSTONE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -pipe -Os -arch x86_64 -MD -MQ librz/io/librz_io.0.7.dylib.p/p_io_debug.c.o -MF librz/io/librz_io.0.7.dylib.p/p_io_debug.c.o.d -o librz/io/librz_io.0.7.dylib.p/p_io_debug.c.o -c ../rizin-v0.7.2/librz/io/p/io_debug.c
../rizin-v0.7.2/librz/io/p/io_debug.c:302:2: warning: implicit declaration of function 'posix_spawn_file_actions_addinherit_np' is invalid in C99 [-Wimplicit-function-declaration]
        posix_spawn_file_actions_addinherit_np(&fileActions, STDIN_FILENO);
        ^
../rizin-v0.7.2/librz/io/p/io_debug.c:306:14: error: use of undeclared identifier 'POSIX_SPAWN_CLOEXEC_DEFAULT'
        ps_flags |= POSIX_SPAWN_CLOEXEC_DEFAULT;
                    ^
1 warning and 1 error generated.
```
Log: https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/192137/steps/install-port/logs/stdio

P. S. `POSIX_SPAWN_CLOEXEC_DEFAULT` has been added in 10.7, but apparently is safe to use from 10.8 up. See: https://github.com/python/cpython/issues/109154

Could these be addressed?

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The relevant flag we want to use with posix_spawn is POSIX_SPAWN_CLOEXEC_DEFAULT, for which checking for `__POWERPC__` made no sense. This caused build failures on Mac OS X 10.6 and potential kernel panics on 10.7.

**Test plan**

Try to build on various Mac OS X versions: 
- [x] 10.5 ppc
- [x] 10.5 x86
- [x] 10.6 x86
- [x] 10.7 x86
- [x] 10.8 x86

**Closing Issues**

Fix #4352

### CODE REVIEW

**Review by wargio — APPROVED** [review]

File: librz/debug/p/native/xnu/xnu_excthreads.c [hunk 1]
```diff
@@ -47,7 +47,7 @@ RZ_IPI bool xnu_modify_trace_bit(RzDebug *dbg, xnu_thread_t *th, int enable) {
 #elif __POWERPC__ // ppc processor
 // XXX poor support at this stage i don't care so much. Once intel and arm done it could be done
```
Comment (XVilka) [inline librz/debug/p/native/xnu/xnu_excthreads.c]: Could you please remove this comment while you are on it?

File: librz/io/p/io_debug.c [hunk 2]
```diff
@@ -267,7 +224,24 @@ static RzRunProfile *_get_run_profile(RzIO *io, int bits, char **argv) {
 	return rp;
 }
 
-#if __APPLE__ && !__POWERPC__
+#if USE_POSIX_SPAWN
+
+static void handle_posix_error(int err) {
+	switch (err) {
+	case 0:
+		// eprintf ("Success\n");
```
Comment (wargio) [inline librz/io/p/io_debug.c]: remove this

Comment (XVilka) [inline librz/io/p/io_debug.c]: Remove this as well?

File: librz/io/p/io_debug.c [hunk 3]
```diff
@@ -340,15 +313,42 @@ static int fork_and_ptraceme_for_mac(RzIO *io, int bits, const char *cmd) {
...
+
 typedef struct fork_child_data_t {
 	RzIO *io;
 	int bits;
 	const char *cmd;
 } fork_child_data;
 
+#if __APPLE__ || __BSD__
+static void inferior_abort_handler(int pid) {
+	eprintf("Inferior received signal SIGABRT. Executing BKPT.\n");
```
Comment (XVilka) [inline librz/io/p/io_debug.c:327]: `RZ_LOG_ERROR()`?

**Review by XVilka — CHANGES_REQUESTED** [review]
LGTM with a few nitpicks.

File: librz/debug/p/native/xnu/xnu_excthreads.c (hunk 1 above)
Comment (thestr4ng3r) [reply librz/debug/p/native/xnu/xnu_excthreads.c]: I rephrased it

File: librz/io/p/io_debug.c (hunk 3 above)
Comment (thestr4ng3r) [reply librz/io/p/io_debug.c:327]: If I understand it right, this is not an error, so it should be `RZ_LOG_INFO()`, but that is not printed by default (though I think it should, but that is another story), so I would keep it as eprintf until info is printed.

Comment (wargio) [reply librz/io/p/io_debug.c:327]: use WARN then.

Comment (thestr4ng3r) [reply librz/io/p/io_debug.c:327]: It is not a warning either, it is just informative that the debugee got a SIGABRT.

**Review by XVilka — APPROVED** [review]
