### PR TITLE
fix DWARF parsing leaks 

### LINKED ISSUE #4754: DWARF parsing leaks
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ....
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PPC64
| `rizin -v` full output, **not truncated** (mandatory)  | dev (7637377a45a3950e2ace3df9e32e0699306d000d)

### Expected behavior

Acceptable amounts of leaks or none.

### Actual behavior

Quite a lot of leaks (~600) when opening a PPC binary.

### Steps to reproduce the behavior

```
meson --buildtype=debug -Db_sanitize=address,undefined build
ninja -C build
export UBSAN_OPTIONS="halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1"
export ASAN_OPTIONS="detect_odr_violation=0:halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1:detect_odr_violation=0"
export LSAN_OPTIONS="print_summary=1:print_stacktrace=1"
./build/binrz/rizin/rizin -q test/bins/elf/ppc64_sudoku_dwarf 
```

### Additional Logs, screenshots, source code,  configuration dump, ...

[leaks.txt](https://github.com/user-attachments/files/17979684/leaks.txt)

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #4754

### CODE REVIEW

File: librz/arch/dwarf_process.c [hunk 1]
```diff
@@ -1696,12 +1696,14 @@ static bool variable_from_die(
...
 	RzAnalysisDwarfVariable v = { 0 };
+	bool res = false;
 	if (!function_var_parse(ctx, NULL, NULL, &v, die, NULL)) {
-		variable_fini(&v);
-		return false;
+		goto beach;
 	}
-
-	return try_create_var_global(ctx, die, &v);
+	res = try_create_var_global(ctx, die, &v);
```
Comment (XVilka) [inline librz/arch/dwarf_process.c:1703]: Please note, that one of the `variable_fini()` was removed in 07a7b0d431420d9a921eeb7951271fdb332dc4f8
Sadly, I don't have that file to test on.

**Review by Rot127 — APPROVED** [review]

File: librz/arch/dwarf_process.c (hunk 1 above)
Comment (b1llow) [reply librz/arch/dwarf_process.c:1703]: I don't know how to reproduce it, but so far it looks like the memory leak is caused here, let's see what wargio has to say about it

**Comment by XVilka** [comment]
@wargio take a look please, when you have time

**Review by wargio — APPROVED** [review]
