### PR TITLE
Fix missing win 32 eip

### LINKED ISSUE #2699: RIP register not tracked on 32bit binary on Windows x64
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 32
| `rizin -v` full output, **not truncated** (mandatory)  | 0.4.0 @ windows-x86-64 commit: 6498ee6760d37f6abb11784aa550aecd2e03100b, build: Wed 06/08/2022__15:43:46.93

### Expected behavior
`rip` flag is at the right address and it moves whenever you step in visual mode.

### Actual behavior
image
RIP = 0x7ffd07544d4c, but no `rip` flag at that address.

### Steps to reproduce the behavior
Run `rizin -d <binary>`, go in visual mode. There is no `rip` register flag at the current offset and if you press `s`(for stepping one instruction) you can see the value of the register being updated but the rip flag does not move in the visual disassembly.

### Additional context
The file is 32bit. There is no rip/eip register in `fs registers ; fl`.

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Fix register flag address not updating after `dc`
* Always add `PC` register flag
* Fix `PC` highlighting when debugging 32-bit binaries in x64 Windows

**Test plan**

Tests pass

**Closing issues**

Fixes #2699

### CODE REVIEW

**Comment by XVilka** [comment]
One Linux test broken:
```
[XX] db/archos/linux-x64/dbg_dmh use of dmh, then any command which use grep and index
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc 'db @ sym.main
dc
dmh > /dev/null
aa > /dev/null
pdf @ sym.main~:1
' bins/elf/simple_malloc_x86_64
-- stdout
--- expected
+++ actual
@@ -1,2 +1,2 @@
-/ int main (int argc, char **argv, char **envp);
+            ;-- rax:
 p=3
-- stderr
Process with PID 7783 started...
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
hit breakpoint at: 0x55d2b1c0070a
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)
```

File: librz/core/creg.c [hunk 1]
```diff
@@ -67,10 +67,11 @@ RZ_IPI RzList /*<RzRegItem>*/ *rz_core_reg_flags_candidates(RzCore *core, RzReg
 	if (!ret) {
 		return NULL;
 	}
+	RzRegItem *pc = rz_reg_get_by_role(reg, RZ_REG_NAME_PC);
 	RzListIter *iter;
 	RzRegItem *item;
 	rz_list_foreach (l, iter, item) {
-		if (size != 0 && size != item->size) {
+		if (size != 0 && size != item->size && item != pc) {
```
Comment (ret2libc) [inline librz/core/creg.c:74]: i don't understand this.. why don't we push `PC` flag?

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Doesn't affect the Linux and macOS behavior compared with the current `dev` - I think it's safe to merge.

**Review by ret2libc — APPROVED** [review]
