### PR TITLE
Reduce registers shown in the output of `dr` and `Vpp` when analysing an ARM64 executable

### LINKED ISSUE #1716: Do not print too much registers in `Vpp` mode
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | ARMv8 64 (AARCH64)
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64
commit: 09d5b01b67c640c1fafde9b3434ade342a225b32, build: 2021-09-18__12:22:59

### Expected behavior

Do not print those special registers probably, to avoid cluttering,

### Actual behavior

image

It also prints the same content with `dr`. I am not sure if they should be kept in `dr` output as well, probably better to keep them, but certainly not in the visual mode.

### Steps to reproduce the behavior
- `qemu-aarch64 -g 12345 mra `
- `rizin -a arm -b 64 -d gdb://localhost:12345`
- `ds; Vpp`

### Additional Logs, screenshots, source code,  configuration dump, ...

See https://github.com/rizinorg/cutter/issues/2687

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible) (TODO in a new PR)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Avoids printing system registers when analyzing registers in an ARM64 executable. Does not completely remove other registers as well (will implement that soon), but prunes majority of unnecessary registers.

**Test plan**

Refactor existing tests according to the API changes, and write new ones once the API implementation is complete.

**Closing issues**

Closes #1716.

### CODE REVIEW

File: librz/reg/reg.c [hunk 1]
```diff
@@ -7,7 +7,7 @@
 RZ_LIB_VERSION(rz_reg);
 
 static const char *types[RZ_REG_TYPE_LAST + 1] = {
-	"gpr", "drx", "fpu", "mmx", "xmm", "ymm", "flg", "seg", NULL
+	"gpr", "drx", "fpu", "mmx", "xmm", "ymm", "flg", "seg", "sys", "pauth", NULL
```
Comment (XVilka) [inline librz/reg/reg.c]: Instead of `pauth` here, I suggest more generic `"sec"`. `pauth` is too ARM and implementation specific.

File: shlr/gdb/src/gdbclient/xml.c [hunk 2]
```diff
@@ -772,6 +773,11 @@ static RzList *_extract_regs(char *regstr, RzList *flags, char *pc_alias) {
 				// -- Aarch64
 			} else if ((tmp1 = strstr(regstr, "sve")) != NULL && tmp1 < feature_end) {
 				typegroup = "ymm";
+			} else if ((tmp1 = strstr(regstr, "pauth")) != NULL && tmp1 < feature_end) {
+				typegroup = "pauth";
```
Comment (XVilka) [inline shlr/gdb/src/gdbclient/xml.c]: `"sec"` then too.

**Review by XVilka — CHANGES_REQUESTED** [review]

**Comment by DMaroo** [comment]
Should I add any tests for this?

File: shlr/gdb/src/gdbclient/xml.c [hunk 3]
```diff
@@ -772,6 +773,11 @@ static RzList *_extract_regs(char *regstr, RzList *flags, char *pc_alias) {
 				// -- Aarch64
 			} else if ((tmp1 = strstr(regstr, "sve")) != NULL && tmp1 < feature_end) {
 				typegroup = "ymm";
+			} else if ((tmp1 = strstr(regstr, "sec")) != NULL && tmp1 < feature_end) {
```
Comment (XVilka) [inline shlr/gdb/src/gdbclient/xml.c]: Shouldn't be `pauth` here, in the the detection?

**Comment by XVilka** [comment]
You could add a dump of GDB response and add a new unit test for this. That would be a good start.
Maybe a `gdbr_parse_target_xml()`, not sure.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
I get the following warning, not important probably, just for the information:
```
[i] ℤ rizin -a arm -b 64 -d gdb://localhost:12345                                                                                                                                                                                 13:55:36 
WARNING: rz_file_exists: assertion '!RZ_STR_ISEMPTY(str)' failed (line 172)
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGBCR'
= attach 1 984639
```

**Comment by DMaroo** [comment]
Yes. I also encountered these warnings. Looks like a register is being re-parsed. I'll have a look and fix it if possible without breaking other stuff.

**Review by yossizap — APPROVED** [review]
