### PR TITLE
Fix: add meta size in code count

### LINKED ISSUE #5050: Incorrect Analysis Coverage
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 64-bit LSB pie executable, x86-64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.8.0 @ linux-x86-64
| |commit: 719637af39a844348597fdde147fdac698be0851

### Expected behavior

Coverage should have been <= code size

### Actual behavior

coverage is > code size making analysis inconsistent 

### Steps to reproduce the behavior
- Compile literally any C++ program, could be just a `main` function with `return 0` or use [this](https://github.com/rizinorg/rizin-testbins/blob/master/elf/demangle-test-cpp) binary from [rizin-testbins](https://github.com/rizinorg/rizin-testbins)
- Run this  `rizin -AA /path/to/compiled_binary`
- type aai 
- check the coverage and code size

### Additional Logs, screenshots, source code,  configuration dump, ...

Image

### PR DESCRIPTION
**Pull request by PremadeS**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).

**Detailed description**

Handles the **Inconsistent Analysis Coverage** issue

**Fixed Problem:**

The **code size** calculation in `rz_core_analysis_code_count()` was incorrect because it did not count `meta size`. This made **analysis coverage** inconsistent in cases where `meta size` is larger than size of **executable sections**.

**How This Fix Solves the Problem:**

Adds `meta size` to `code count` in `rz_core_analysis_code_count()` so the **percentage covered** does not go beyond **100%** 

**Changes Implemented:**
- Modified `rz_core_analysis_code_count()` in `librz/core/canalysis.c` to include `meta size` in the **code size** calculation
- Added a **test** in `test/unit/test_analysis_coverage.c` to verify that the **fix** correctly calculates **analysis coverage**.
- Added `analysis coverage` entry in `test/unit/meson.build` to run the **test**
- Added `cmd_coverage` in `test/db/cmd` to verify the output of `aai` command

**Before:**
before

**After:**
after

**Note:**
- This **PR** does not modify the functionality or behavior of any `RZ_API` function or struct.  
- The only change is adding a `meta size` to a `code size` in `rz_core_analysis_code_count()`
- So no changes required in **API documentation**.  
...

**Test plan**

1. **Verify the Fix Works:**  
   - Run the `test_analysis_coverage.c` test using:  
     ```sh
     meson test -C build analysis_coverage
     ```
   - Ensure the test **passes** with the changes applied.  

2. **Verify the Issue Before the Fix:**  
   - Revert the changes made to `rz_core_analysis_code_count()` in `librz/core/canalysis.c`.  
   - Run the test again using:  
     ```sh
     meson test -C build analysis_coverage
     ```
   - The test should **fail**, confirming that the **issue** existed before this **fix**.
...

**Closing issues**

closes #5050 
...

### CODE REVIEW

**Comment by wargio** [comment]
add also a command test, since probably we don't have any, with one of the binaries that you were able to reproduce this issue

**Review by wargio — APPROVED** [review]

File: test/unit/test_analysis_coverage.c [hunk 1]
```diff
@@ -0,0 +1,43 @@
+#include <rz_analysis.h>
```
Comment (wargio) [inline test/unit/test_analysis_coverage.c:3]: Please add the following header:

```
// SPDX-FileCopyrightText: 2025 username <email>
// SPDX-License-Identifier: LGPL-3.0-only
```

Comment (PremadeS) [reply test/unit/test_analysis_coverage.c:3]: Done

File: test/unit/test_analysis_coverage.c [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+	bool written = rz_io_write_at(r->io, 0x10, codes, sizeof(codes));
+	mu_assert("Failed to write instructions to memory", written);
+
+	bool meta_set = rz_meta_set(r->analysis, RZ_META_TYPE_DATA, 0x10, 0x60, "some random data");
+	mu_assert("Failed to set metadata", meta_set);
+
+	rz_core_analysis_all(r);
+
+	long long int code = rz_core_analysis_code_count(r);
+	printf("\n\n%lld\n\n", code);
```
Comment (Rot127) [inline test/unit/test_analysis_coverage.c]: This is debug and test code, so it is fine here. But for the future:
All format strings should use the `PFMT...` macros for compatibility. So in this case it would be: `""\n\n" PFMT64d "\n\n"`.

File: librz/core/canalysis.c [hunk 3]
```diff
@@ -5604,6 +5604,7 @@ RZ_API st64 rz_core_analysis_coverage_count(RZ_NONNULL RzCore *core) {
 RZ_API st64 rz_core_analysis_code_count(RZ_NONNULL RzCore *core) {
 	rz_return_val_if_fail(core, ST64_MAX);
 	st64 code = 0;
+	code += (st64)rz_meta_get_size(core->analysis, RZ_META_TYPE_DATA);
```
Comment (Rot127) [inline librz/core/canalysis.c]: Anyone has an idea why `code` has to be a signed type? @wargio Maybe it should be changed to unsigned, while @PremadeS is at it? Invalid value would `UT64_MAX`

**Review by Rot127 — APPROVED** [review]
Looks good to me.

File: librz/core/canalysis.c (hunk 3 above)
Comment (wargio) [reply librz/core/canalysis.c]: i was wondering the same. it could be just `size_t`

File: test/unit/test_analysis_coverage.c (hunk 2 above)
Comment (wargio) [reply test/unit/test_analysis_coverage.c]: ah, i missed this. yeah remove this if is debug code.

File: librz/core/canalysis.c (hunk 3 above)
Comment (Rot127) [reply librz/core/canalysis.c]: @PremadeS Would you mind addressing this? You can also add it to the doxygen of the function, what it returns in case of failure (maximum of `size_t`, but forgot what the macro is for this).

File: test/unit/test_analysis_coverage.c (hunk 2 above)
Comment (PremadeS) [reply test/unit/test_analysis_coverage.c]: I forgot to remove the `printf()` before making the pull request. That statement should not be there in the first place.

File: librz/core/canalysis.c (hunk 3 above)
Comment (PremadeS) [reply librz/core/canalysis.c]: You're right, I'll change it to `size_t`, I was also wondering, the `cov` variable in `rz_core_analysis_coverage_count()` that calculates the `analysis coverage` is also `signed` should that be made unsigned aswell?

Comment (Rot127) [reply librz/core/canalysis.c]: Yes

File: test/unit/test_analysis_coverage.c (hunk 2 above)
Comment (PremadeS) [reply test/unit/test_analysis_coverage.c]: Done

File: librz/core/canalysis.c (hunk 3 above)
Comment (PremadeS) [reply librz/core/canalysis.c]: Done

**Review by Rot127 — APPROVED** [review]
Thanks!

**Review by wargio — APPROVED** [review]
