### PR TITLE
librz/core: fix dpa command

### LINKED ISSUE #3397: macOS 13.2 ARM64 - attach process doesn't get an access to memory/code
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 13.2 ARM64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/0e8828c54e0773e41bbbb5fff110c8cc07cadb09

### Expected behavior

Show instructions and stack once attached

### Actual behavior

```
rizin =
 -- The more 'a' you add after 'aa' the more analysis steps are executed.
[0x00000000]> dpa 59547
[0x188158320]> pd 1
            0x188158320      ffffffff       invalid
[0x188158320]> pd 5
            0x188158320      ffffffff       invalid
            0x188158324      ffffffff       invalid
            0x188158328      ffffffff       invalid
            0x18815832c      ffffffff       invalid
            0x188158330      ffffffff       invalid
[0x188158320]> px 10
- offset -    0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x188158320  ffff ffff ffff ffff ffff                 ..........
[0x188158320]> dr
x0 = 0x0000000000000004
x1 = 0x0000000000000000
x2 = 0x0000000000000000
x3 = 0x0000000000000000
x4 = 0x0000000000000000
x5 = 0x000000016b2052fc
x6 = 0x000000000000000c
x7 = 0x0000000000000001
x8 = 0x0000000000000000
x9 = 0x00000001e37265c0
x10 = 0x0000000000000002
x11 = 0x00000000fffffffd
x12 = 0x0000010000000000
x13 = 0x0000000000000000
x14 = 0x0000000000000000
x15 = 0x0000000000000000
x16 = 0x000000000000018a
x17 = 0x00000001e857f6c0
x18 = 0x0000000000000000
x19 = 0x0000000000000000
x20 = 0x0000000000000000
x21 = 0x000000016b205300
x22 = 0x0000000000000001
x23 = 0x000000016b2052fc
x24 = 0x0000600003446370
x25 = 0x0000000000000000
x26 = 0x0000000000000001
x27 = 0x000060000196ea88
x28 = 0x000060000196ea80
x29 = 0x000000016b2052e0
wzr = 0x00000000
zr = 0x0000000000000000
fp = 0x000000016b2052e0
lr = 0x000000018816b820
sp = 0x000000016b205270
pc = 0x0000000188158320
pstate = 0x00000001a0001000
nf = 0x0
```

### Steps to reproduce the behavior

1. Open `rizin /bin/ls` instance
2. Start another `rizin` instance and attach to the first:
```
rizin =
[0x000000]> dpa <1st rizin pid>
[0x000000]> pd 10
[0x000000]> px 100
...
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [x] I've documented every `RZ_API` function and struct this PR changes.
- [x] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [x] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [x] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**
Since `rz_core_setup_debugger` (used when you do `rizin -d dbg://<pid>`) was working well, this PR reuses that function for `dpa` but prepares the right RzCoreFile before calling it.

**Test plan**
See the issue

**Closing issues**
Closes https://github.com/rizinorg/rizin/issues/3397

### CODE REVIEW

File: librz/core/cio.c [hunk 1]
```diff
@@ -21,7 +21,18 @@ RZ_API int rz_core_setup_debugger(RzCore *r, const char *debugbackend, bool atta
...
+		if (pid > 0) {
+			rz_debug_attach(r->dbg, pid);
+		} else {
+			if (r->file && r->io) {
+				rz_debug_attach(r->dbg, rz_io_fd_get_pid(r->io, r->file->fd));
+			}
+		}
+		rz_debug_select(r->dbg, r->dbg->pid, r->dbg->tid);
+		rz_config_set_i(r->config, "dbg.swstep", (r->dbg->cur && !r->dbg->cur->canstep));
+		rz_io_system(r->io, rz_strf(buf, "pid %d", r->dbg->pid));
```
Comment (wargio) [inline librz/core/cio.c]: since this was just moved out from `rz_core_debug_attach` and now `rz_core_debug_attach` is never called, i don't see how this can fix the issue.

**Review by wargio — CHANGES_REQUESTED** [review]

File: librz/core/cio.c (hunk 1 above)
Comment (ret2libc) [reply librz/core/cio.c]: The fix is not here. Setup_debugger was already working (it's called when you do Rizin -d pid). dpa instead was broken and the reason was that there was no IO mapping (which is now setup in the rz_core_attach_debug function, called by the dpa cmd handler).

Comment (wargio) [reply librz/core/cio.c]: then move this into a static function.

**Review by wargio — APPROVED** [review]

File: librz/core/cdebug.c [hunk 2]
```diff
@@ -822,6 +843,37 @@ RZ_API bool rz_core_debug_process_close(RzCore *core) {
...
+RZ_API bool rz_core_debug_process_detach(RzCore *core) {
+	rz_return_val_if_fail(core && core->dbg, false);
+	RzDebug *dbg = core->dbg;
+	// Stop trace session
+	if (dbg->session) {
+		rz_debug_session_free(dbg->session);
+		dbg->session = NULL;
+	}
+	// Detach debugee and all child processes
+	if (dbg->cur && dbg->cur->pids && dbg->pid != -1) {
```
Comment (wargio) [inline librz/core/cdebug.c:862]: early return.

File: librz/core/cdebug.c [hunk 3]
```diff
@@ -293,18 +293,42 @@ RZ_API void rz_core_debug_bp_add_noreturn_func(RzCore *core) {
...
+		if (!cfile) {
+			RZ_LOG_ERROR("Failed to open file for pid %d\n", pid);
+			return;
 		}
+		// Create an IO map covering the full address space so memory
+		// reads/writes are routed through this debug descriptor.
+		RzIODesc *iod = core->io ? rz_io_desc_get(core->io, cfile->fd) : NULL;
+		rz_io_map_new(core->io, iod->fd, iod->perm, 0LL, 0LL, rz_io_desc_size(iod));
+	} else {
+		RZ_LOG_WARN("No pid provided and not attached to any file descriptor, IO mapping will not be set up\n");
```
Comment (wargio) [inline librz/core/cdebug.c]:
```suggestion
		RZ_LOG_WARN("core: No pid provided and not attached to any file descriptor, IO mapping will not be set up\n");
```

File: librz/core/cdebug.c [hunk 4]
```diff
@@ -293,18 +293,42 @@ RZ_API void rz_core_debug_bp_add_noreturn_func(RzCore *core) {
...
+	pid = pid > 0 ? pid : fd_pid;
 	if (pid > 0) {
-		rz_debug_attach(core->dbg, pid);
-	} else {
-		if (core->file && core->io) {
-			rz_debug_attach(core->dbg, rz_io_fd_get_pid(core->io, core->file->fd));
+		rz_strf(uri, "dbg://%d", pid);
+		RzCoreFile *cfile = rz_core_file_open(core, uri, RZ_PERM_RW, 0);
+		if (!cfile) {
+			RZ_LOG_ERROR("Failed to open file for pid %d\n", pid);
```
Comment (wargio) [inline librz/core/cdebug.c]:
```suggestion
			RZ_LOG_ERROR("core: Failed to open file for pid %d\n", pid);
```

Comment (wargio) [reply librz/core/cdebug.c]: i'm not sure if `pid` is just `int` also on windows.

File: librz/core/cdebug.c (hunk 3 above)
Comment (ret2libc) [reply librz/core/cdebug.c]: why are we adding `core:` to messages going to the users? Are they really going to understand it?

File: librz/core/cdebug.c (hunk 2 above)
Comment (ret2libc) [reply librz/core/cdebug.c:862]: I'm not sure it's needed in this case. I have to execute:
```
	rz_core_debug_clear_register_flags(core);
	return true;
```
anyway at the end and the `if` is not that big. I'd have to duplicate this code otherwise or use a `goto` and I don't see that big of a reason in this case.

File: librz/core/cdebug.c (hunk 4 above)
Comment (ret2libc) [reply librz/core/cdebug.c]: All existing functions use `int pid` so I guess it is.

File: librz/core/cdebug.c (hunk 3 above)
Comment (wargio) [reply librz/core/cdebug.c]: it's more for us to understand who is throwing the error when a user opens an issue

**Review by notxvilka — APPROVED** [review]

File: librz/core/cdebug.c [hunk 5]
```diff
@@ -820,6 +844,37 @@ RZ_API bool rz_core_debug_process_close(RzCore *core) {
...
+		if (list) {
+			rz_list_foreach (list, iter, p) {
+				rz_debug_detach(dbg, p->pid);
+			}
+		} else {
+			rz_debug_detach(dbg, dbg->pid);
+		}
+	}
+	// Remove the target's registers from the flag list
+	rz_core_debug_clear_register_flags(core);
```
Comment (Rot127) [inline librz/core/cdebug.c:876]: Does `list` leaks here?

File: librz/core/cdebug.c [hunk 6]
```diff
@@ -293,18 +293,42 @@ RZ_API void rz_core_debug_bp_add_noreturn_func(RzCore *core) {
...
+	rz_debug_use(core->dbg, NULL);
+
+	pid = pid > 0 ? pid : fd_pid;
 	if (pid > 0) {
-		rz_debug_attach(core->dbg, pid);
-	} else {
-		if (core->file && core->io) {
-			rz_debug_attach(core->dbg, rz_io_fd_get_pid(core->io, core->file->fd));
+		rz_strf(uri, "dbg://%d", pid);
+		RzCoreFile *cfile = rz_core_file_open(core, uri, RZ_PERM_RW, 0);
```
Comment (Rot127) [inline librz/core/cdebug.c:318]:
```suggestion
		RzCoreFile *cfile = rz_core_file_open(core, uri, RZ_PERM_R, 0);
```
Or not?

**Review by Rot127 — APPROVED** [review]
Please check those two comments. Othwerwise lgtm

File: librz/core/cdebug.c (hunk 6 above)
Comment (ret2libc) [reply librz/core/cdebug.c:318]: I think you want RW so you can write memory while debugging. Right?

Comment (Rot127) [reply librz/core/cdebug.c:318]: I just checked casually. I assumed if the core file is opened with RW, it will also allow to change the content of it.

But I don't know much about the debug code tbh.

**Review by notxvilka — APPROVED** [review]
