### PR TITLE
Fix vv mode theme refresh

### LINKED ISSUE #5045: `:eco <theme>` does not refresh function body in `Vv` mode in Linux terminals
Run `aaa` then go into `Vv` mode, then go into some function body, then change to a different color theme using `eco <theme>`, observe that function roster theme has changed, while the function body disassembly didn't. Only moving to another function changes colors in the function disassembly.

Happens only on Linux (any terminal) but not on macOS (iTerm2)

### PR DESCRIPTION
**Pull request by Ayushd785**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md) to this repository.
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#code-style).
- [ ] I've documented every `RZ_API` function and struct this PR changes.
- [ ] I've added tests that prove my changes are effective (required for changes to `RZ_API`).
- [ ] I've updated the [Rizin book](https://github.com/rizinorg/book) with the relevant information (if needed).
- [x] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else. ( Used AI just to study the issue, the code is written by my own)

**Detailed description**

This PR fixes issue #5045 where changing the color theme using `:eco <theme>` in Vv mode on Linux terminals would update the function roster theme but not the function body disassembly theme until navigating to another function.

The function body disassembly output is cached in `view->output` to avoid redundant analysis when scrolling. The cache is only invalidated when `output_mode` or `output_addr` changes, but not when the theme changes. When `:eco <theme>` is executed, the palette colors update via `rz_cons_pal_update_event()`, but the cached output still contains ANSI color codes from the old theme.

**Test plan**

***Screen Recording***

After the fix, changing the theme using eco <theme> now immediately updates both the function roster and the function disassembly view.

https://github.com/user-attachments/assets/b187d6dd-9e8f-45f8-a7a9-52bab51c9cfc

**Closing issues**

closes #5045

### CODE REVIEW

**Review by notxvilka — CHANGES_REQUESTED** [review]
Please remove unrelated ROP changes from the PR

**Comment by Ayushd785** [comment]
> Please remove unrelated ROP changes from the PR

Sorry about that. I accidentally committed changes from the previous branch

**Review by notxvilka — APPROVED** [review]

File: librz/core/tui/vmenus.c [hunk 1]
```diff
@@ -259,6 +259,16 @@ static void rz_core_visual_analysis_refresh_column(RzCore *core, int colpos) {
 	if (view->printMode == 1) { // px $r
 		addr += view->delta * 16;
 	}
+	const char *current_theme = rz_core_theme_get(core);
+	if (view->curtheme && current_theme && strcmp(view->curtheme, current_theme)) {
```
Comment (b1llow) [inline librz/core/tui/vmenus.c]: I suggest using RZ_STR_EQ/RZ_STR_NE?

File: librz/core/tui/vmenus.c [hunk 2]
```diff
@@ -259,6 +259,16 @@ static void rz_core_visual_analysis_refresh_column(RzCore *core, int colpos) {
...
+		RZ_FREE(view->output);
+		view->output_mode = -1;
+		view->output_addr = -1;
+	}
+	if (!view->curtheme || !current_theme || (view->curtheme && current_theme && strcmp(view->curtheme, current_theme))) {
```
Comment (b1llow) [inline librz/core/tui/vmenus.c]: RZ_STR_EQ/RZ_STR_NE?

File: librz/core/tui/vmenus.c (hunk 1 above)
Comment (Ayushd785) [reply librz/core/tui/vmenus.c]: Okay i'll replace `strcmp` with `RZ_STR_NE`, it does better NULL handling

**Review by b1llow — APPROVED** [review]
