### PR TITLE
Fix function argument by DWARF

### LINKED ISSUE #3470: Function argument and return types should be inferred from DWARF
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | FreeRTOS ARMv7 (Cortex-M
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARMv7
| `rizin -v` full output, **not truncated** (mandatory)  |  https://github.com/rizinorg/rizin/commit/7670834a9cb74aa9c0f34f44cc5a3c19fffe29d8

### Actual behavior

Screenshot 2023-04-19 at 15 39 02

Note, that it loaded the `void VListInsertEnd( List_t * const pxList, ListItem_t * const pxNewListItem )` from the DWARF, but didn't apply the types of arguments to the function signature.

This function is common in FreeRTOS and should be presented in any ARM target: https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/aa987a3443b60894bc64714135bca44831406886/list.c#L98

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #3470

...

### CODE REVIEW

File: librz/analysis/dwarf_process.c [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // SPDX-FileCopyrightText: 2012-2020 houndthe <cgkajm@gmail.com>
 // SPDX-License-Identifier: LGPL-3.0-only
 
+#include "rz_util/rz_strbuf.h"
```
Comment (XVilka) [inline librz/analysis/dwarf_process.c]: I think strbuf is the part of `rz_util.h`

File: librz/analysis/var.c [hunk 2]
```diff
@@ -151,6 +165,28 @@ RZ_API RZ_BORROW RzAnalysisVar *rz_analysis_function_set_var(RzAnalysisFunction
 	return var;
 }
 
+RZ_API RZ_BORROW RzAnalysisVar *rz_analysis_function_add_var(RzAnalysisFunction *fcn, RZ_OWN RzAnalysisVar *var,
```
Comment (XVilka) [inline librz/analysis/var.c:177]: Please add Doxygen for new APIs added

File: librz/include/rz_analysis.h [hunk 3]
```diff
@@ -686,6 +686,12 @@ static inline void rz_analysis_var_storage_init_stack(RzAnalysisVarStorage *stor
 	stor->stack_off = stack_off;
 }
 
+typedef enum rz_analysis_var_kind_t {
```
Comment (XVilka) [inline librz/include/rz_analysis.h:693]: Please add doxygen

File: librz/include/rz_analysis.h [hunk 4]
```diff
@@ -686,6 +686,12 @@ static inline void rz_analysis_var_storage_init_stack(RzAnalysisVarStorage *stor
...
+	RZ_ANALYSIS_VAR_KIND_INVALID = 0,
+	RZ_ANALYSIS_VAR_KIND_FORMAL_PARAMETER,
+	RZ_ANALYSIS_VAR_KIND_VARIABLE,
+	RZ_ANALYSIS_VAR_KIND_UNSPECIFIED_PARAMETERS,
+} RzAnalysisVarKind;
 /**
```
Comment (XVilka) [inline librz/include/rz_analysis.h:700]: Missing empty line

**Review by XVilka — CHANGES_REQUESTED** [review]
Nice changes. I don't like how we use SDB to store this kind of information - it hinders the performance, but it's definitely out of the scope of this PR. But as you work on debug information during your GSoC anyway, we might think how to handle this better in the future. If you have any suggestions - lets discuss it in Mattermost, etc.

Could you please add also the new test based on the files I referenced in the issue? It will be useful also at a later stage, for RzIL, float, and Tricore things.

**Comment by XVilka** [comment]
See also:
```
Run python3 rz-bindgen/src/lint.py \
Mismatched function annotation for rz_analysis_function_add_var at <rizin/librz/include/rz_analysis.h:1645:33> : RZ_NONNULL (was RZ_OWN at <rizin/librz/analysis/var.c:168:33>
Mismatched function annotation for rz_analysis_function_add_var at <rizin/librz/include/rz_analysis.h:1645:33> : RZ_OWN (was None at <rizin/librz/analysis/var.c:16[8](https://github.com/rizinorg/rizin/actions/runs/5085717600/jobs/9139465266?pr=3530#step:6:9):33>
```

File: librz/analysis/var.c [hunk 5]
```diff
@@ -104,6 +105,36 @@ RZ_API void rz_analysis_var_resolve_overlaps(RzAnalysisVar *var) {
...
 }
 
+static inline RzAnalysisVar *fcn_var_get_or_new(RzAnalysisFunction *fcn,
+	const char *name, RzAnalysisVarStorage *stor, const RzType *typ) {
+	if (!(fcn && stor && RZ_STR_ISNOTEMPTY(name))) {
+		return NULL;
+	}
+	RzAnalysisVar *existing = rz_analysis_function_get_var_byname(fcn, name);
+	if (existing && !storage_equals(&existing->storage, stor)) {
+		// var name already exists at a different kind+delta
```
Comment (XVilka) [inline librz/analysis/var.c:114]: I think we could print warning here or something?

File: test/db/analysis/vars [hunk 6]
```diff
@@ -543,22 +543,24 @@ EOF
...
 |           0x0000113d      mov   rbp, rsp
 |           0x00001140      sub   rsp, 0x10
-|           0x00001144      mov   dword [lightbulb], 1
-|           0x0000114b      mov   dword [sun], 2
-|           0x00001152      mov   dword [last], 3
-|           0x00001159      mov   dword [chance], 4
+|           0x00001144      mov   dword [last], 1
+|           0x0000114b      mov   dword [chance], 2
+|           0x00001152      mov   dword [var_10h], 3
+|           0x00001159      mov   dword [var_ch], 4
```
Comment (wargio) [inline test/db/analysis/vars]: this looks like wrong.
@thestr4ng3r

File: librz/analysis/dwarf_process.c (hunk 1 above)
Comment (ret2libc) [reply librz/analysis/dwarf_process.c]: also, use `<rz_util/rz_strbuf.h>`

File: librz/analysis/dwarf_process.c [hunk 7]
```diff
@@ -1137,7 +1146,6 @@ static VariableLocation *parse_dwarf_location(Context *ctx, const RzBinDwarfAttr
 			// TODO: The following is only an educated guess. There is actually more involved in calculating the
 			//       CFA correctly.
 			kind = LOCATION_CFA;
-			offset += ctx->analysis->bits / 8; // guessed return address size
```
Comment (ret2libc) [inline librz/analysis/dwarf_process.c:1140]: was this just plain wrong?

File: test/db/analysis/vars [hunk 8]
```diff
@@ -590,19 +592,21 @@ EOF
...
+|           ; var int64_t var_8h @ stack - 0x8
+|           ; var int64_t var_4h @ stack - 0x4
 |           0x00001137      sub   rsp, 0x10
 |           0x0000113b      mov   dword [rsp], 1
-|           0x00001142      mov   dword [sun], 2
-|           0x0000114a      mov   dword [last], 3
-|           0x00001152      mov   dword [chance], 4
+|           0x00001142      mov   dword [chance], 2
+|           0x0000114a      mov   dword [var_8h], 3
+|           0x00001152      mov   dword [var_4h], 4
```
Comment (ret2libc) [inline test/db/analysis/vars]: this is still wrong according to IDA:
```
public varfunc
varfunc proc near

lightbulb= dword ptr -10h
sun= dword ptr -0Ch
last= dword ptr -8
chance= dword ptr -4

; __unwind {
sub     rsp, 10h
mov     [rsp+10h+lightbulb], 1
mov     [rsp+10h+sun], 2
mov     [rsp+10h+last], 3
mov     [rsp+10h+chance], 4
mov     eax, 0
call    leaffunc
mov     eax, [rsp+10h+chance]
mov     [rsp+10h+sun], eax
mov     eax, [rsp+10h+lightbulb]
add     rsp, 10h
retn
; } // starts at 1137
varfunc endp
```

maybe we should at least mark this as BROKEN

File: test/db/analysis/vars (hunk 6 above)
Comment (ret2libc) [reply test/db/analysis/vars]: yes it is, see other comment.

File: librz/analysis/var.c [hunk 9]
```diff
@@ -104,6 +105,36 @@ RZ_API void rz_analysis_var_resolve_overlaps(RzAnalysisVar *var) {
...
+		o->fcn = fcn;
+		rz_vector_init(&o->accesses, sizeof(RzAnalysisVarAccess), NULL, NULL);
+		rz_vector_init(&o->constraints, sizeof(RzTypeConstraint), NULL, NULL);
+	} else {
+		free(o->name);
+		if (o->type != typ) {
+			// only free if not assigning the own type to itself
+			rz_type_free(o->type);
+			o->type = NULL;
+		}
```
Comment (ret2libc) [inline librz/analysis/var.c]: I'm not sure I understand why you are cleaning these things. Could you explain?
Also, if you are freeing the `name` maybe it's better to set it to NULL.

File: librz/analysis/dwarf_process.c (hunk 7 above)
Comment (XVilka) [reply librz/analysis/dwarf_process.c:1140]: I think so, it assumed too much.

File: librz/analysis/var.c (hunk 9 above)
Comment (XVilka) [reply librz/analysis/var.c]: I think this part of the code was just moved from another place

File: librz/analysis/dwarf_process.c (hunk 7 above)
Comment (b1llow) [reply librz/analysis/dwarf_process.c:1140]: yes

File: librz/analysis/var.c (hunk 9 above)
Comment (b1llow) [reply librz/analysis/var.c]: Yes, it's just move from `rz_analysis_function_set_var`

File: test/db/analysis/vars (hunk 8 above)
Comment (b1llow) [reply test/db/analysis/vars]: `llvm-objdump --disassemble`:
```
0000000000001137 <varfunc>:
    1137: 48 83 ec 10                  	subq	$16, %rsp
    113b: c7 04 24 01 00 00 00         	movl	$1, (%rsp)
    1142: c7 44 24 04 02 00 00 00      	movl	$2, 4(%rsp)
    114a: c7 44 24 08 03 00 00 00      	movl	$3, 8(%rsp)
    1152: c7 44 24 0c 04 00 00 00      	movl	$4, 12(%rsp)
    115a: b8 00 00 00 00               	movl	$0, %eax
    115f: e8 d1 ff ff ff               	callq	0x1135 <leaffunc>
    1164: 8b 44 24 0c                  	movl	12(%rsp), %eax
    1168: 89 44 24 04                  	movl	%eax, 4(%rsp)
    116c: 8b 04 24                     	movl	(%rsp), %eax
    116f: 48 83 c4 10                  	addq	$16, %rsp
    1173: c3                           	retq
```

`llvm-dwarfdump --debug-frame`:
```
0000009c 00000014 00000070 FDE cie=00000030 pc=00001137...00001174
  Format:       DWARF32
  DW_CFA_advance_loc: 4
  DW_CFA_def_cfa_offset: +24
  DW_CFA_advance_loc: 56
  DW_CFA_def_cfa_offset: +8
  DW_CFA_nop:

  0x1137: CFA=RSP+8: RIP=[CFA-8]
  0x113b: CFA=RSP+24: RIP=[CFA-8]
  0x1173: CFA=RSP+8: RIP=[CFA-8]
```

`llvm-dwarfdump`:

```
0x000000d1:   DW_TAG_subprogram
                DW_AT_external	(true)
                DW_AT_name	("varfunc")
                DW_AT_decl_file	("/home/florian/re/vars/main.c")
                DW_AT_decl_line	(8)
                DW_AT_decl_column	(0x05)
                DW_AT_type	(0x00000058 "int")
                DW_AT_low_pc	(0x0000000000001137)
                DW_AT_high_pc	(0x0000000000001174)
                DW_AT_frame_base	(DW_OP_call_frame_cfa)
                DW_AT_call_all_tail_calls	(true)
                DW_AT_sibling	(0x0000012a)

0x000000f3:     DW_TAG_variable
                  DW_AT_name	("lightbulb")
                  DW_AT_decl_file	("/home/florian/re/vars/main.c")
                  DW_AT_decl_line	(10)
                  DW_AT_decl_column	(6)
                  DW_AT_type	(0x00000058 "int")
                  DW_AT_location	(DW_OP_fbreg -24)

0x00000100:     DW_TAG_variable
                  DW_AT_name	("sun")
                  DW_AT_decl_file	("/home/florian/re/vars/main.c")
                  DW_AT_decl_line	(11)
                  DW_AT_decl_column	(0x06)
                  DW_AT_type	(0x00000058 "int")
                  DW_AT_location	(DW_OP_fbreg -20)

0x0000010f:     DW_TAG_variable
                  DW_AT_name	("last")
                  DW_AT_decl_file	("/home/florian/re/vars/main.c")
                  DW_AT_decl_line	(12)
                  DW_AT_decl_column	(6)
                  DW_AT_type	(0x00000058 "int")
                  DW_AT_location	(DW_OP_fbreg -16)

0x0000011c:     DW_TAG_variable
                  DW_AT_name	("chance")
                  DW_AT_decl_file	("/home/florian/re/vars/main.c")
                  DW_AT_decl_line	(13)
                  DW_AT_decl_column	(6)
                  DW_AT_type	(0x00000058 "int")
                  DW_AT_location	(DW_OP_fbreg -12)
```

Comment (b1llow) [reply test/db/analysis/vars]: In the current version of Rizin, it appears that the information from `.eh_frame` and `.debug_frame` is not being used to correct the position of variables.

---

Moreover, the positions of these variables should be `CFA+=offset`.

```
lightbulb @ stack - 0x18 -> lightbulb @ CFA - 0x18
0x113b: CFA=RSP+24: RIP=[CFA-8]
lightbulb @ CFA - 0x18 -> lightbulb @ RSP+24-0x18 -> lightbulb @ RSP
```

So, by using the `frame` information in DWARF, we can accurately obtain the address of variables with location kind `DW_OP_fbreg` or `DW_OP_call_frame_cfa`.

Comment (b1llow) [reply test/db/analysis/vars]: `0x113b: CFA=RSP+24: RIP=[CFA-8]`: From this information, I can infer that the value of CFA (Canonical Frame Address) has an offset of +24 (0x18).

~~However, in the disassembly line `1137: 48 83 ec 10 subq $16, %rsp`, we only subtracted 16 from RSP. I still don't know how the value of 24 is calculated.~~

from chatgpt:

> The discrepancy between the offset value in the CFA calculation and the subtraction in the disassembly can be explained by the fact that the CFA value is typically established based on the function prologue and the specific compiler optimizations or stack frame layout being used.
> 
> In the given disassembly line, `subq $16, %rsp`, we can see that 16 bytes are subtracted from the RSP register. This instruction typically reserves space on the stack for local variables or function parameters.
> 
> The additional offset of 8 bytes in the CFA calculation (`RIP=[CFA-8]`) may be due to other factors such as the storage of the return address or the size of certain data structures in the stack frame.
> 
> To accurately determine how the value of 24 is calculated in this context, a deeper analysis of the surrounding code and the specific compiler settings would be required.

Comment (b1llow) [reply test/db/analysis/vars]: I have an idea. Perhaps we can introduce a new `RZ_ANALYSIS_VAR_STORAGE_CFA`, to represent the storage of variables.

During the disassembly of a function (`pdf`), we can output the following content:

```
/ dbg.varfunc ();
|           ; var int lightbulb @ CFA - 0x18
|           ; var int sun @ CFA - 0x14
|           ; var int last @ CFA - 0x10
|           ; var int chance @ CFA - 0xc
            ; CFA=RSP+8: RIP=[CFA-8]
|           0x00001137      sub   rsp, 0x10
            ; CFA=RSP+0x18: RIP=[CFA-8]
|           0x0000113b      mov   dword [lightbulb], 1
|           0x00001142      mov   dword [sun], 2
|           0x0000114a      mov   dword [last], 3
|           0x00001152      mov   dword [chance], 4
...
```

Comment (XVilka) [reply test/db/analysis/vars]: @imbillow maybe these could be helpful?

- https://www.polarsignals.com/blog/posts/2022/11/29/dwarf-based-stack-walking-using-ebpf/
- https://dl.acm.org/doi/pdf/10.1145/3360572
- https://stackoverflow.com/questions/7534420/gas-explanation-of-cfi-def-cfa-offset
- https://www.imperialviolet.org/2017/01/18/cfi.html
- https://maskray.me/blog/2020-11-08-stack-unwinding

If it doesn't help, gathering more data from real-world binaries is a good idea (by doing your way by just printing these offsets for now and merging this PR); then we can deal with this later once we better understand it. @thestr4ng3r, what do you think about this, since you are the one who migrated variables to the frame pointer?

**Comment by wargio** [comment]
@imbillow https://github.com/rizinorg/rizin-testbins/pull/113

**Comment by wargio** [comment]
the current output of rizin for that bin is in sync with what IDA outputs.

**Comment by wargio** [comment]
This is the output from your branch (**which is wrong**)
image
This is the output from dev (*which is correct*)
image

**Comment by wargio** [comment]
you can use my example `bins/elf/vars_args/example.x64` (git pull bins first)

**Review by wargio — CHANGES_REQUESTED** [review]
^

**Comment by b1llow** [comment]
@wargio 

Yes, that's because this line of code applied some offset to `CFA+offset` to convert it to `stack+offset` (which was removed in my branch).

However, this is inaccurate and actually incorrect conversion on ARM and TriCore architectures.

`offset += ctx->analysis->bits / 8; // guessed return address size`

**Comment by wargio** [comment]
> `offset += ctx->analysis->bits / 8; // guessed return address size`

that can be recovered by using `archinfo` from `RzAnalysis`
```c
ut32 alignment = rz_analysis_archinfo(analysis, RZ_ANALYSIS_ARCHINFO_DATA_ALIGN);
offset += alignment; 
```

**Comment by b1llow** [comment]
> > `offset += ctx->analysis->bits / 8; // guessed return address size`
> 
> that can be recovered by using `archinfo` from `RzAnalysis`
> 
> ```c
> ut32 alignment = rz_analysis_archinfo(analysis, RZ_ANALYSIS_ARCHINFO_DATA_ALIGN);
> offset += alignment; 
> ```

But at least on x86 architecture, it hasn't been implemented.

```
static int archinfo(RzAnalysis *a, RzAnalysisInfoType query) {
	switch (query) {
	case RZ_ANALYSIS_ARCHINFO_MIN_OP_SIZE:
		return 1;
	case RZ_ANALYSIS_ARCHINFO_MAX_OP_SIZE:
		return 16;
	case RZ_ANALYSIS_ARCHINFO_TEXT_ALIGN:
		/* fall-thru */
	case RZ_ANALYSIS_ARCHINFO_DATA_ALIGN:
		return 0;
	case RZ_ANALYSIS_ARCHINFO_CAN_USE_POINTERS:
		return true;
	default:
		return -1;
	}
}
```

**Comment by b1llow** [comment]
The DWARF parse of elf generated by the hightec compiler seems to have problems, because there is enough information in DWARF.

```
 <1><202>: Abbrev Number: 10 (DW_TAG_subprogram)
    <203>   DW_AT_external    : 1	
    <204>   DW_AT_name        : fn1	
    <208>   DW_AT_decl_file   : 1	
    <209>   DW_AT_decl_line   : 15	
    <20a>   DW_AT_prototyped  : 1	
    <20b>   DW_AT_type        : <0x25e>	
    <20f>   DW_AT_low_pc      : 0x8000041c	
    <213>   DW_AT_high_pc     : 0x800004ac	
    <217>   DW_AT_frame_base  : 1 byte block: 9c 	(DW_OP_call_frame_cfa)
    <219>   Unknown AT value: 2116: 1	
    <21a>   DW_AT_sibling     : <0x25e>	
 <2><21e>: Abbrev Number: 11 (DW_TAG_formal_parameter)
    <21f>   DW_AT_name        : a	
    <221>   DW_AT_decl_file   : 1	
    <222>   DW_AT_decl_line   : 15	
    <223>   DW_AT_type        : <0x149>	
    <227>   DW_AT_location    : 2 byte block: 8e 7c 	(DW_OP_breg30: -4)
 <2><22a>: Abbrev Number: 11 (DW_TAG_formal_parameter)
    <22b>   DW_AT_name        : g	
    <22d>   DW_AT_decl_file   : 1	
    <22e>   DW_AT_decl_line   : 15	
    <22f>   DW_AT_type        : <0x19b>	
    <233>   DW_AT_location    : 2 byte block: 8e 78 	(DW_OP_breg30: -8)
 <2><236>: Abbrev Number: 11 (DW_TAG_formal_parameter)
    <237>   DW_AT_name        : q	
    <239>   DW_AT_decl_file   : 1	
    <23a>   DW_AT_decl_line   : 15	
    <23b>   DW_AT_type        : <0x267>	
    <23f>   DW_AT_location    : 2 byte block: 8e 70 	(DW_OP_breg30: -16)
 <2><242>: Abbrev Number: 11 (DW_TAG_formal_parameter)
    <243>   DW_AT_name        : gg	
    <246>   DW_AT_decl_file   : 1	
    <247>   DW_AT_decl_line   : 15	
    <248>   DW_AT_type        : <0x271>	
    <24c>   DW_AT_location    : 2 byte block: 8e 6c 	(DW_OP_breg30: -20)
 <2><24f>: Abbrev Number: 11 (DW_TAG_formal_parameter)
    <250>   DW_AT_name        : out	
    <254>   DW_AT_decl_file   : 1	
    <255>   DW_AT_decl_line   : 15	
    <256>   DW_AT_type        : <0x277>	
    <25a>   DW_AT_location    : 2 byte block: 8e 68 	(DW_OP_breg30: -24)
```

**Comment by XVilka** [comment]
@imbillow I have two thoughts about this:
- Hightec compiler based on the very [old GCC (4.9)](https://gcc.gnu.org/gcc-4.9/changes.html), the DWARF standard or implementation could be incomplete, we should think how to deal with this as well, since we are RE tool
- The fix for Tricore could be postponed if too troublesome - we can focus on x86, ARM, etc here. Once your new disasm and RzIL for Tricore are merged we could return to this issue. Then we should make a test and mark it as broken, plus open a new issue to track and not forget.

Also, we could add non-Hightec Tricore tests, e.g. made by the newer gcc/binutils from https://github.com/bkoppelmann/package_940 and postpone making Hightec one work to a later stage.

Alternatively, you could check our DWARF parser at `librz/bin/dwarf.c` and find out what's wrong with parsing Hightec binary.

**Comment by XVilka** [comment]
Have you checked also the function "get_dwarf_reg_name()"? It seems to support only x86 and PPC for now?

**Comment by b1llow** [comment]
> Have you checked also the function "get_dwarf_reg_name()"? It seems to support only x86 and PPC for now?

I'll check it out after a while.

**Review by XVilka — APPROVED** [review]
Already a big improvement. We can figure more about CFI and CFA as we progress more with debug information and other architectures.

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
I created a new issue to track that missing CFA/CFI thing: https://github.com/rizinorg/rizin/issues/3539
