### PR TITLE
Rz-test: assign the expected successful and failed test

### LINKED ISSUE #2029: Allow to set expected value of tests to fail in `rz-test`
On some targets, like Alpine Static or Debian old a few tests fail, e.g. debugging ones and there is no intention to ever fix them.
For now we ignore all test results on those, which might lead to huge regressions in the future. Also for some ongoing ports like System-Z where only some tests pass, but it would be nice to avoid further breakage.

I suggest to add two options:
- `--expect-pass=X` to fail/pass (`rz-test` return code) depending on the number of tests passed
- `--expect-fail=X` to fail/pass (`rz-test` return code) depending on the number of tests failed.

### PR DESCRIPTION
**Pull request by PeiweiHu**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**
closes https://github.com/rizinorg/rizin/issues/2029

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

File: binrz/rz-test/rz-test.c [hunk 1]
```diff
@@ -292,6 +296,21 @@ int rz_test_main(int argc, const char **argv) {
 		case 'e':
 			rz_pvector_push(except_dir, strdup(opt.arg));
 			break;
+		case 's':
+			// rz_num_math returns 0 for both '0' and invalid str
+			expect_succ = rz_num_math(NULL, opt.arg);
+			if (!rz_str_isnumber(opt.arg) || expect_succ < 0) {
```
Comment (ret2libc) [inline binrz/rz-test/rz-test.c]: rz_num_is_valid_input

File: binrz/rz-test/rz-test.c [hunk 2]
```diff
@@ -292,6 +296,21 @@ int rz_test_main(int argc, const char **argv) {
...
+				RZ_LOG_ERROR("Number of expected successful tests is invalid\n");
+				goto beach;
+			}
+			break;
+		case 'x':
+			expect_fail = rz_num_math(NULL, opt.arg);
+			if (!rz_str_isnumber(opt.arg) || expect_fail < 0) {
```
Comment (ret2libc) [inline binrz/rz-test/rz-test.c]: rz_num_is_valid_input

**Review by ret2libc — CHANGES_REQUESTED** [review]

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]
