### PR TITLE
Fix tricore sub jumps #3664

### LINKED ISSUE #3664: Tricore - do not add `#` character before flag name in jump/call instructions
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | *
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Tricore
| `rizin -v` full output, **not truncated** (mandatory)  |https://github.com/rizinorg/rizin/commit/aa2c54f1286fdae90f4af5562fcd3dde3ff85f31

### Expected behavior
```
 j     dbg._Mbtowcx
call  dbg.fwrite
```

### Actual behavior
```
> pdf @ dbg._Mbtowc
        ╎   ; CALL XREF from dbg._Printf @ 0x80000d02
        ╎   ;-- _Mbtowc:
╭ int dbg._Mbtowc(wchar_t *pwc, const char *s, size_t nin, mbstate_t *pst);
│       ╎   ; arg size_t nin @ d4
│       ╎   ; arg wchar_t *pwc @ a4
│       ╎   ; arg const char *s @ a5
│       ╎   ; arg mbstate_t *pst @ a6
│       ╎   0x80003084      910000fd       movh.a a15, #0xd000         ; xmbtowc.c:150 ; int _Mbtowc(wchar_t *pwc, const char *s, size_t nin, mbstate_t *pst);
│       ╎   0x80003088      99ff08d0       ld.a  a15, [a15]#0x348
│       ╎   0x8000308c      404e           mov.aa a14, a4              ; arg5
│       ╎   0x8000308e      405d           mov.aa a13, a5              ; arg6
│       ╎   0x80003090      024f           mov   d15, d4
│       ╎   0x80003092      406c           mov.aa a12, a6              ; arg7
│       ╎   0x80003094      bcf4           jz.a  a15, #0x8000309c      ; xmbtowc.c:151
│       ╎   0x80003096      0000           nop
│       ╎   0x80003098      2d0f0000       calli a15
│       ╎   0x8000309c      9100007d       movh.a a7, #0xd000
│       ╎   0x800030a0      40e4           mov.aa a4, a14
│       ╎   0x800030a2      40d5           mov.aa a5, a13
│       ╎   0x800030a4      02f4           mov   d4, d15
│       ╎   0x800030a6      40c6           mov.aa a6, a12
│       ╎   0x800030a8      d9770cd0       lea   a7, [a7]#0x34c
╰       ╰─< 0x800030ac      1dff36ff       j     #dbg._Mbtowcx

[0x0000000]> > pdf @ dbg.prout
            ;-- prout:
╭ void *dbg.prout(void *str, const char *buf, size_t n);
│           ; arg void *str @ a15
│           ; arg size_t n @ d4
│           ; arg const char *buf @ a5
│           0x80000c04      404f           mov.aa a15, a4              ; printf.c:5 ; arg5 ; void *prout(void *str, const char *buf, size_t n);
│           0x80000c06      024f           mov   d15, d4
│           0x80000c08      4054           mov.aa a4, a5               ; printf.c:6 ; arg6
│           0x80000c0a      02f5           mov   d5, d15
│           0x80000c0c      8214           mov   d4, #1
│           0x80000c0e      40f5           mov.aa a5, a15
│           0x80000c10      6d003e08       call  #dbg.fwrite           ; size_t fwrite(const void *ptr, size_t size, size_t nitems, FILE *stream)
│           0x80000c14      0bf20021       eq    d2, d2, d15
│           0x80000c18      80ff           mov.d d15, a15              ; printf.c:7
│           0x80000c1a      2bf250f2       seln  d15, d2, d2, d15
│           0x80000c1e      60f2           mov.a a2, d15
╰           0x80000c20      0090           ret
```

### Steps to reproduce the behavior
- `rizin -A test/bins/elf/float_ex1/float_ex1_hightec`
- `pdf @ dbg._Mbtowc`
- `pdf @ dbg.prout`

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #3664

### CODE REVIEW

File: test/db/analysis/tricore [hunk 1]
```diff
@@ -686,10 +706,9 @@ EXPECT=<<EOF
 .---------------------------------------------------------.   .---------------.
 |  0x800004f6                                             |   |  0x800004f2   |
 | mov d4, #0x14                                           |   | mov d15, #0   |
-| ; dbg.malloc                                            |   | j #0x8000054c |
-| ; void *malloc(size_t size)                             |   `---------------'
-| call #0x80000afc                                        |       v
-| mov.aa a15, a2                                          |       |
+| ; void *malloc(size_t size)                             |   | j #0x8000054c |
```
Comment (XVilka) [inline test/db/analysis/tricore]: What about also not showing `#` in case of jumps to the address?

**Review by XVilka — CHANGES_REQUESTED** [review]
@Rot127 take a look at this one please, since you changed parsing of the instructions mnemonics back in time (token-based parser).

File: test/db/analysis/tricore (hunk 1 above)
Comment (b1llow) [reply test/db/analysis/tricore]: It's a bit of a hassle.

If we simply remove all "#" from the opstr of all `JMP`, `CALL`, and `UJMP` instructions, it seems to affect other instructions.

I was trying to work at the Operands level, but realized that our replacement for disassemble also works at the string level.

File: librz/core/disasm.c [hunk 2]
```diff
@@ -4854,32 +4842,37 @@ static void ds_print_as_string(RzDisasmState *ds) {
 
 static char *_find_next_number(char *op) {
 	char *p = op;
-	if (p) {
-		while (*p) {
-			// look for start of next separator or ANSI sequence
-			while (*p && !IS_SEPARATOR(*p) && *p != 0x1b) {
+	if (!p)
```
Comment (XVilka) [inline librz/core/disasm.c]: Please use `{}` here.

**Review by XVilka — CHANGES_REQUESTED** [review]

**Review by wargio — APPROVED** [review]

**Comment by Rot127** [comment]
This is the right, but deprecated way to do it.
What I would actually recommend is:

- Implement a `get_token_patterns()` and `compile_token_patterns` functions like here https://github.com/rizinorg/rizin/blob/d497840b07204f4039a73493937ec0722abbd7a1/librz/asm/p/asm_hexagon.c#L22-L128
  - Patterns first in the vector are matched first as well. So `pattern order = priority`
- (if you find time, it would be very nice, if you move the `compile_token_pattern()` function to `asm.c` where the other tokenize code is).
- Compile the token patterns when the tricore module is initialized: https://github.com/rizinorg/rizin/blob/d497840b07204f4039a73493937ec0722abbd7a1/librz/asm/p/asm_hexagon.c#L175-L176
- Now, whenever bytes have been disassembled, you can call `rz_asm_tokenize_asm_regex` on it to parse it into tokens. https://github.com/rizinorg/rizin/blob/d497840b07204f4039a73493937ec0722abbd7a1/librz/asm/arch/hexagon/hexagon_arch.c#L856
- Now you can iterate over the tokens and remove the `#` from the number tokens (if necessary).

File: test/db/analysis/tricore (hunk 1 above)
Comment (XVilka) [reply test/db/analysis/tricore]: Operating on the tokens level should help solve this too, see @Rot127's comment.

File: librz/core/disasm.c [hunk 3]
```diff
@@ -885,9 +885,29 @@ static void __replaceImports(RzDisasmState *ds) {
 	}
 }
 
+static void ds_opstr_try_colorize(RzDisasmState *ds, bool print_color) {
```
Comment (XVilka) [inline librz/core/disasm.c:890]: If you decide to port Tricore to tokens, please keep this function extraction change - it's still useful.

**Comment by Rot127** [comment]
@imbillow https://github.com/Rot127/rizin/blob/asm_token_docs/doc/asm_strings.md

`compile_token_pattern` has been moved as well in https://github.com/rizinorg/rizin/pull/3711

**Comment by b1llow** [comment]
@Rot127 Why don't we use bnf to describe the language?

**Comment by Rot127** [comment]
I can't recall that we came up with the idea a year ago. Back then I implemented it out of necessity that the Hexagon syntax was very hard to read, but also had other thinks to focus on.

So reasons are:
- (I think) We didn't thought about it (although regex was not the most optimal choice) cc @thestr4ng3r any comments?
- Would need an additional parser (maybe a bit over-engineered for primarily coloring strings).
- Would have taken way longer.

But we can of cause discuss it, if you see a big advantage in it.

**Comment by XVilka** [comment]
Yes, in general even complicated assembly languages are still very simple. BNF grammar would be overengineering for relatively simple syntax, IMHO. Regexes are notoriously fast, and code is already in Rizin, so the choice was somewhat obvious. I suggest to stick to it, at least until we meet unsurmountable issues with it.

File: librz/asm/p/asm_tricore_cs.c [hunk 4]
```diff
@@ -46,6 +46,81 @@ static int disassemble(RzAsm *a, RzAsmOp *op, const ut8 *buf, int len) {
...
+}
+
+static bool init(void **user) {
+	State *state = get_state();
+	rz_return_val_if_fail(state, false);
+
+	*user = state; // user = RzAsm.plugin_data
+
+	state->token_patterns = get_token_patterns();
+	compile_token_patterns(state->token_patterns);
```
Comment (Rot127) [inline librz/asm/p/asm_tricore_cs.c]: You can use `rz_asm_compile_token_patterns` if you rebase onto `dev`. It is already meged.

File: librz/asm/p/asm_tricore_cs.c [hunk 5]
```diff
@@ -46,6 +46,81 @@ static int disassemble(RzAsm *a, RzAsmOp *op, const ut8 *buf, int len) {
...
+
+	state = RZ_NEW0(State);
+	if (!state) {
+		RZ_LOG_FATAL("Could not allocate memory for HexState!");
+	}
+	return state;
+}
+
+static bool init(void **user) {
+	State *state = get_state();
```
Comment (Rot127) [inline librz/asm/p/asm_tricore_cs.c]: The state is not necessary (if you do not intend to use it for other purposes). Since the token vector is already static, it will return the same.
(In the Hexagon plugin it is needed for other stuff as well, that is why it is used there).

File: librz/asm/p/asm_tricore_cs.c (hunk 4 above)
Comment (Rot127) [reply librz/asm/p/asm_tricore_cs.c]: Alternatively you can skip this step as well. The patterns get also compiled in `rz_asm_tokenize_asm_regex` if it wasn't done before.

Comment (b1llow) [reply librz/asm/p/asm_tricore_cs.c]: @Rot127 You seem to be reviewing outdated code. Maybe there's something wrong with github's cache.

**Review by XVilka — APPROVED** [review]
Tested on various Tricore files - works fine.
