### PR TITLE
core: fix output of pC commands

### LINKED ISSUE #3318: Fix `pCd` missing instructions problems
image

The problem is that the second columns starts at 0x100003a64, but the first one ends with 0x100003a5c. So there is an instruction (0x100003a60) that is not displayed.

However... this is not strictly a problem with your conversion, so if you want go ahead but let's create an issue for this at least.

_Originally posted by @ret2libc in https://github.com/rizinorg/rizin/issues/3213#issuecomment-1399918455_

See `librz/core/cmd/cmd_print.c`

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

See https://github.com/rizinorg/rizin/issues/3318 for the issue. The problem is that when there are flags in the printed output, the commands used by `pC` (like `px`, `pdq`, etc.) may output more than the expected number of rows. The fix is to count the number of lines returned by the command and the number of lines we actually print and then make sure the next column starts in the right place to address the missing printed line.

**Test plan**

see tests.

**Closing issues**

Close https://github.com/rizinorg/rizin/issues/3318 and https://github.com/rizinorg/rizin/pull/3438 .

### CODE REVIEW

File: librz/core/cmd/cmd_print.c [hunk 1]
```diff
@@ -5414,46 +5414,50 @@ RZ_IPI RzCmdStatus rz_print_columns_disassembly_handler(RzCore *core, int argc,
...
-	bool asm_minicols = rz_config_get_i(core->config, "asm.minicols");
-	char *o_ao = strdup(rz_config_get(core->config, "asm.offset"));
-	char *o_ab = strdup(rz_config_get(core->config, "asm.bytes"));
-	if (asm_minicols) {
+	int rows = user_rows > 0 ? user_rows : h - 2;
+
+	RzConfigHold *ch = rz_config_hold_new(core->config);
+	rz_config_hold_i(ch, "asm.offset", "asm.bytes", NULL);
+	if (rz_config_get_i(core->config, "asm.minicols")) {
 		rz_config_set(core->config, "asm.offset", "false");
```
Comment (XVilka) [inline librz/core/cmd/cmd_print.c]: rz_config_set_b()

File: librz/core/cmd/cmd_print.c [hunk 2]
```diff
@@ -5414,46 +5414,50 @@ RZ_IPI RzCmdStatus rz_print_columns_disassembly_handler(RzCore *core, int argc,
...
 	rz_config_set(core->config, "asm.bytes", "false");
+
 	RzConsCanvas *c = rz_cons_canvas_new(w, rows);
 	ut64 osek = core->offset;
+	int pos_i = 0;
 	c->color = rz_config_get_i(core->config, "scr.color");
-	rz_core_block_size(core, rows * 32);
 	for (i = 0; i < columns; i++) {
 		(void)rz_cons_canvas_gotoxy(c, i * (w / columns), 0);
-		// TODO: Use the API directly
```
Comment (XVilka) [inline librz/core/cmd/cmd_print.c:5437]: Don't remove this TODO

**Review by XVilka — CHANGES_REQUESTED** [review]

**Review by XVilka — APPROVED** [review]

File: librz/core/cmd/cmd_print.c [hunk 3]
```diff
@@ -5548,38 +5555,50 @@
...
 		char *dis = rz_core_cmd_str(core, cmd);
 		if (dis) {
+			RzList *dis_lines = rz_str_split_duplist_n(dis, "\n", 0, false);
+			ut32 n_lines = rz_list_length(dis_lines);
+			rz_list_free(dis_lines);
+
+			// If the output contains more lines than expected, do not move
+			// forward the whole chunk as some data will be hidden.
+			if (n_lines > canvas_rows) {
+				tsek -= (n_lines - canvas_rows - 1) * hex_cols;
```
[the remark this answers is not in the document]
Comment (XVilka) [reply librz/core/cmd/cmd_print.c]: @ret2libc check this warning

**Comment by XVilka** [comment]
@ret2libc please fix this PR or postpone to 0.7.0

**Review by XVilka — APPROVED** [review]
