### PR TITLE
Fix #1032 - Wrong use of wcstombs

### LINKED ISSUE #1032: Wrong use of `sz = wcstombs(NULL, buf, len);` in `librz/util/str.c`
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33 x86_64 
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/41192158ecf168eb18e831d225cdfb02829a40b9

### Expected behavior

No warnings

### Actual behavior

```
../librz/util/str.c: In function ‘rz_str_wc_to_mb_l’:
../librz/util/str.c:3519:7: warning: argument 1 is null but the corresponding size argument 3 range is [1, 2147483647] [-Wnonnull]
 3519 |  sz = wcstombs(NULL, buf, len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../librz/include/rz_types.h:250,
                 from ../librz/util/str.c:4:
/usr/include/stdlib.h:937:15: note: in a call to function ‘wcstombs’ declared with attribute ‘write_only (1, 3)’
  937 | extern size_t wcstombs (char *__restrict __s,
      |               ^~~~~~~~
```

This call was introduced in https://github.com/rizinorg/rizin/commit/527ff71d4184a07d724f9a7c3a464a3b228ea408

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Tries to fix:
```
../librz/util/str.c: In function ‘rz_str_wc_to_mb_l’:
../librz/util/str.c:3519:7: warning: argument 1 is null but the corresponding size argument 3 range is [1, 2147483647] [-Wnonnull]
 3519 |  sz = wcstombs(NULL, buf, len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../librz/include/rz_types.h:250,
                 from ../librz/util/str.c:4:
/usr/include/stdlib.h:937:15: note: in a call to function ‘wcstombs’ declared with attribute ‘write_only (1, 3)’
  937 | extern size_t wcstombs (char *__restrict __s,
      |               ^~~~~~~~

```

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

File: librz/util/str.c [hunk 1]
```diff
@@ -3510,30 +3510,31 @@ RZ_API wchar_t *rz_str_mb_to_wc_l(const char *buf, int len) {
...
 	size_t sz;
+	mbstate_t mbs;
+	const wchar_t *tmp = buf;
 
 	if (!buf || len <= 0) {
 		return NULL;
 	}
-	sz = wcstombs(NULL, buf, len);
+	mbrlen(NULL, 0, &mbs);
+	sz = wcsrtombs(NULL, &tmp, 0, &mbs);
```
Comment (karliss) [inline librz/util/str.c]: I don't think that's a correct use of mbrlen. From what I understood by reading docs mbrlen requires an initialized mbstate_t structure. Also what's the point of using `wcsrtombs` instead of wcstombs if you are not using the restartability feature?

Comment (wargio) [reply librz/util/str.c]: `A call to the function with a null pointer as pmb resets the shift state (and ignores parameter max).`
http://www.cplusplus.com/reference/cwchar/mbrlen/

Comment (wargio) [reply librz/util/str.c]: `wcsrtombs` allows to pass a null pointer to get the size (like snprintf). The issue is that you can't use `wcstombs` with null ptr.

Comment (karliss) [reply librz/util/str.c]: cplusplus.com is only place suggesting such use of mbrlen.  Cppreference and microsoft documentation doesn't mention such behavior and suggest to zero initialize the mbstate_t structure instead.

Why do you think wcstombs can't be used with null ptr for such use case? From what I understood GCC warning was because it was used with `dst=NULL` and `len > 0` at the same time not because using NULL in general.

Comment (karliss) [reply librz/util/str.c]: On the other hand we might want to use wcsrtombs in both calls, because nonrestartable version internally uses a global mbstate_t variable making it not thread safe.

Comment (wargio) [reply librz/util/str.c]: i actually tried to think about this. i wasn't sure because the references are mixed; but the behavior of wcsrtombs is standardized.
therefore i do not know. i can close this and let somebody else fix this.

**Comment by ret2libc** [comment]
For better reference, I added the error msg in the PR description.

File: librz/util/str.c (hunk 1 above)
Comment (wargio) [reply librz/util/str.c]: @karliss after reading more, i decided to go your way.

**Review by XVilka — APPROVED** [review]
LGTM as is, though we might want thread safety too.

**Review by karliss — APPROVED** [review]
